# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-04 18:16:40
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.animation import FuncAnimation
from scipy.integrate import solve_ivp

# Gravitational constant
G = 6.674e-11

# Masses (kg) - using solar mass scale
M1 = 1.989e30  # Mass 1 (solar mass)
M2 = 1.989e30  # Mass 2 (solar mass)
M3 = 1.989e30  # Mass 3 (solar mass)

# Initial positions (m) - figure-8 like configuration scaled up
AU = 1.496e11  # Astronomical unit

# Use a known stable figure-8 solution (scaled)
# Positions in AU, velocities in AU/year
# Convert to SI units

year = 3.156e7  # seconds in a year

# Figure-8 three-body solution initial conditions
# (Chenciner & Montgomery, 2000)
# These are in normalized units where G=1, M=1, scale=1

# Scale factors
L = AU  # length scale
T = year  # time scale
M = M1  # mass scale

# Recompute G in normalized units
G_norm = G * M * T ** 2 / L ** 3

print(f"Gravitational constant (normalized): {G_norm:.4f}")
print("Setting up 3-body problem simulation...")

# Use a simpler but visually interesting configuration
# Three bodies in a plane with some 3D perturbation

# Initial positions (in AU converted to meters)
r1_0 = np.array([-0.5, 0.0, 0.1]) * AU
r2_0 = np.array([0.5, 0.0, -0.1]) * AU
r3_0 = np.array([0.0, 0.866, 0.0]) * AU

# Initial velocities (m/s)
# Approximate circular orbit velocity
v_circ = np.sqrt(G * M1 / AU) * 0.8

v1_0 = np.array([0.0, v_circ, v_circ * 0.3])
v2_0 = np.array([0.0, -v_circ, -v_circ * 0.3])
v3_0 = np.array([-v_circ * 0.5, 0.0, 0.0])

# Adjust velocities so center of mass is stationary
total_momentum = M1 * v1_0 + M2 * v2_0 + M3 * v3_0
v1_0 -= total_momentum / (3 * M1)
v2_0 -= total_momentum / (3 * M2)
v3_0 -= total_momentum / (3 * M3)


def three_body_equations(t, state):
    """Equations of motion for the three-body problem."""
    # Unpack state vector
    r1 = state[0:3]
    r2 = state[3:6]
    r3 = state[6:9]
    v1 = state[9:12]
    v2 = state[12:15]
    v3 = state[15:18]

    # Distance vectors
    r12 = r2 - r1
    r13 = r3 - r1
    r23 = r3 - r2

    # Distances
    d12 = np.linalg.norm(r12)
    d13 = np.linalg.norm(r13)
    d23 = np.linalg.norm(r23)

    # Softening parameter to avoid singularities
    eps = 0.01 * AU
    d12 = max(d12, eps)
    d13 = max(d13, eps)
    d23 = max(d23, eps)

    # Accelerations
    a1 = G * M2 * r12 / d12 ** 3 + G * M3 * r13 / d13 ** 3
    a2 = G * M1 * (-r12) / d12 ** 3 + G * M3 * r23 / d23 ** 3
    a3 = G * M1 * (-r13) / d13 ** 3 + G * M2 * (-r23) / d23 ** 3

    return np.concatenate([v1, v2, v3, a1, a2, a3])


# Initial state vector
state0 = np.concatenate([r1_0, r2_0, r3_0, v1_0, v2_0, v3_0])

# Time span (simulate for 5 years)
t_span = (0, 5 * year)
t_eval = np.linspace(0, 5 * year, 3000)

print("Solving differential equations...")
print("This may take a moment...")

# Solve the ODE
solution = solve_ivp(
    three_body_equations,
    t_span,
    state0,
    t_eval=t_eval,
    method='RK45',
    rtol=1e-9,
    atol=1e-9,
    max_step=year / 1000
)

print(f"Solution status: {'Success' if solution.success else 'Failed'}")
print(f"Number of time steps: {len(solution.t)}")

# Extract positions (convert to AU for plotting)
x1 = solution.y[0] / AU
y1 = solution.y[1] / AU
z1 = solution.y[2] / AU

x2 = solution.y[3] / AU
y2 = solution.y[4] / AU
z2 = solution.y[5] / AU

x3 = solution.y[6] / AU
y3 = solution.y[7] / AU
z3 = solution.y[8] / AU

print(f"Body 1 position range: x=[{x1.min():.2f}, {x1.max():.2f}] AU")
print(f"Body 2 position range: x=[{x2.min():.2f}, {x2.max():.2f}] AU")
print(f"Body 3 position range: x=[{x3.min():.2f}, {x3.max():.2f}] AU")

# ============================================================
# ANIMATION
# ============================================================
print("\nCreating 3D animation...")

fig = plt.figure(figsize=(12, 9))
ax = fig.add_subplot(111, projection='3d')

# Color scheme
colors = ['#FF4444', '#44AAFF', '#44FF88']
trail_colors = ['#FF000066', '#0066FF66', '#00FF6666']

# Determine axis limits
all_x = np.concatenate([x1, x2, x3])
all_y = np.concatenate([y1, y2, y3])
all_z = np.concatenate([z1, z2, z3])

margin = 0.2
x_lim = [all_x.min() - margin, all_x.max() + margin]
y_lim = [all_y.min() - margin, all_y.max() + margin]
z_lim = [all_z.min() - margin, all_z.max() + margin]

# Trail length
trail_length = 200

# Initialize plot elements
trail1, = ax.plot([], [], [], '-', color=colors[0], alpha=0.4, linewidth=1.5, label='Body 1')
trail2, = ax.plot([], [], [], '-', color=colors[1], alpha=0.4, linewidth=1.5, label='Body 2')
trail3, = ax.plot([], [], [], '-', color=colors[2], alpha=0.4, linewidth=1.5, label='Body 3')

point1, = ax.plot([], [], [], 'o', color=colors[0], markersize=12, markeredgecolor='white', markeredgewidth=1)
point2, = ax.plot([], [], [], 'o', color=colors[1], markersize=12, markeredgecolor='white', markeredgewidth=1)
point3, = ax.plot([], [], [], 'o', color=colors[2], markersize=12, markeredgecolor='white', markeredgewidth=1)

# Center of mass trail
xcm = (M1 * solution.y[0] + M2 * solution.y[3] + M3 * solution.y[6]) / (M1 + M2 + M3) / AU
ycm = (M1 * solution.y[1] + M2 * solution.y[4] + M3 * solution.y[7]) / (M1 + M2 + M3) / AU
zcm = (M1 * solution.y[2] + M2 * solution.y[5] + M3 * solution.y[8]) / (M1 + M2 + M3) / AU

cm_point, = ax.plot([], [], [], '*', color='yellow', markersize=8, label='Center of Mass')

# Time text
time_text = ax.text2D(0.02, 0.95, '', transform=ax.transAxes, color='white', fontsize=11)


def setup_axes():
    ax.set_xlim(x_lim)
    ax.set_ylim(y_lim)
    ax.set_zlim(z_lim)
    ax.set_xlabel('X (AU)', color='white', labelpad=10)
    ax.set_ylabel('Y (AU)', color='white', labelpad=10)
    ax.set_zlabel('Z (AU)', color='white', labelpad=10)
    ax.set_title('3-Body Problem Simulation', color='white', fontsize=14, pad=20)
    ax.tick_params(colors='white')
    ax.xaxis.pane.fill = False
    ax.yaxis.pane.fill = False
    ax.zaxis.pane.fill = False
    ax.xaxis.pane.set_edgecolor('gray')
    ax.yaxis.pane.set_edgecolor('gray')
    ax.zaxis.pane.set_edgecolor('gray')
    ax.grid(True, alpha=0.3)
    ax.legend(loc='upper right', facecolor='black', edgecolor='gray', labelcolor='white')


setup_axes()

# Dark background
fig.patch.set_facecolor('#0a0a1a')
ax.set_facecolor('#0a0a1a')


def init():
    trail1.set_data([], [])
    trail1.set_3d_properties([])
    trail2.set_data([], [])
    trail2.set_3d_properties([])
    trail3.set_data([], [])
    trail3.set_3d_properties([])
    point1.set_data([], [])
    point1.set_3d_properties([])
    point2.set_data([], [])
    point2.set_3d_properties([])
    point3.set_data([], [])
    point3.set_3d_properties([])
    cm_point.set_data([], [])
    cm_point.set_3d_properties([])
    time_text.set_text('')
    return trail1, trail2, trail3, point1, point2, point3, cm_point, time_text


# Animation step (skip frames for speed)
step = 5
n_frames = len(solution.t) // step


def animate(frame):
    i = frame * step
    i = min(i, len(solution.t) - 1)

    # Trail indices
    start = max(0, i - trail_length)

    # Update trails
    trail1.set_data(x1[start:i + 1], y1[start:i + 1])
    trail1.set_3d_properties(z1[start:i + 1])

    trail2.set_data(x2[start:i + 1], y2[start:i + 1])
    trail2.set_3d_properties(z2[start:i + 1])

    trail3.set_data(x3[start:i + 1], y3[start:i + 1])
    trail3.set_3d_properties(z3[start:i + 1])

    # Update body positions
    point1.set_data([x1[i]], [y1[i]])
    point1.set_3d_properties([z1[i]])

    point2.set_data([x2[i]], [y2[i]])
    point2.set_3d_properties([z2[i]])

    point3.set_data([x3[i]], [y3[i]])
    point3.set_3d_properties([z3[i]])

    # Center of mass
    cm_point.set_data([xcm[i]], [ycm[i]])
    cm_point.set_3d_properties([zcm[i]])

    # Time display
    t_years = solution.t[i] / year
    time_text.set_text(f'Time: {t_years:.2f} years')

    # Slowly rotate the view
    ax.view_init(elev=20 + 10 * np.sin(frame * 0.02), azim=frame * 0.3)

    return trail1, trail2, trail3, point1, point2, point3, cm_point, time_text


print(f"Animating {n_frames} frames...")

anim = FuncAnimation(
    fig,
    animate,
    frames=n_frames,
    init_func=init,
    interval=20,
    blit=False
)

plt.tight_layout()
print("\n3-Body Problem Simulation Ready!")
print("=" * 50)
print("Three equal-mass bodies interacting gravitationally")
print("Simulation duration: 5 years")
print("Close the window to exit.")
print("=" * 50)

plt.show()