# Generated by: qwen3-coder:30b (Ollama)
# Date: 2026-03-02 20:07:01
# AutoCoder System - Automated Code Generation

import pygame
import math
import datetime

# Initialize pygame
pygame.init()

# Set up the display
WIDTH, HEIGHT = 400, 400
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Analogue Clock")

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
GRAY = (200, 200, 200)

# Clock parameters
center = (WIDTH // 2, HEIGHT // 2)
clock_radius = 180

# Font for numbers
font = pygame.font.SysFont('Arial', 24)

# Main loop
running = True
clock = pygame.time.Clock()

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # Get current time
    now = datetime.datetime.now()
    hour = now.hour % 12
    minute = now.minute
    second = now.second

    # Calculate angles for hands
    # Second hand (shortest)
    second_angle = math.radians(second * 6 - 90)  # 6 degrees per second
    second_x = center[0] + 150 * math.cos(second_angle)
    second_y = center[1] + 150 * math.sin(second_angle)

    # Minute hand
    minute_angle = math.radians(minute * 6 - 90)  # 6 degrees per minute
    minute_x = center[0] + 120 * math.cos(minute_angle)
    minute_y = center[1] + 120 * math.sin(minute_angle)

    # Hour hand
    hour_angle = math.radians((hour * 30 + minute * 0.5) - 90)  # 30 degrees per hour, 0.5 per minute
    hour_x = center[0] + 80 * math.cos(hour_angle)
    hour_y = center[1] + 80 * math.sin(hour_angle)

    # Draw clock face
    screen.fill(WHITE)

    # Draw outer circle
    pygame.draw.circle(screen, BLACK, center, clock_radius, 3)

    # Draw hour markers
    for i in range(12):
        angle = math.radians(i * 30 - 90)
        marker_x1 = center[0] + (clock_radius - 10) * math.cos(angle)
        marker_y1 = center[1] + (clock_radius - 10) * math.sin(angle)
        marker_x2 = center[0] + clock_radius * math.cos(angle)
        marker_y2 = center[1] + clock_radius * math.sin(angle)
        pygame.draw.line(screen, BLACK, (marker_x1, marker_y1), (marker_x2, marker_y2), 3)

        # Draw numbers
        number_x = center[0] + (clock_radius - 30) * math.cos(angle)
        number_y = center[1] + (clock_radius - 30) * math.sin(angle)
        number_text = font.render(str(i if i != 0 else 12), True, BLACK)
        screen.blit(number_text, (number_x - number_text.get_width() // 2, number_y - number_text.get_height() // 2))

    # Draw hour hand
    pygame.draw.line(screen, BLACK, center, (hour_x, hour_y), 6)

    # Draw minute hand
    pygame.draw.line(screen, BLACK, center, (minute_x, minute_y), 4)

    # Draw second hand
    pygame.draw.line(screen, RED, center, (second_x, second_y), 2)

    # Draw center dot
    pygame.draw.circle(screen, BLACK, center, 8)

    # Update display
    pygame.display.flip()

    # Control frame rate
    clock.tick(30)

pygame.quit()