import control as ctrl
# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-04 15:08:50
# AutoCoder System - Automated Code Generation

import pygame
import numpy as np
import sys
from pygame import gfxdraw

# Initialize pygame
pygame.init()

# Screen dimensions
SCREEN_W = 1400
SCREEN_H = 800
screen = pygame.display.set_mode((SCREEN_W, SCREEN_H))
pygame.display.set_caption("S-Plane Pole Mover with Bode Plot & Step Response")

# Colors
BG_COLOR = (15, 15, 25)
GRID_COLOR = (40, 40, 60)
AXIS_COLOR = (100, 100, 140)
POLE_COLOR = (255, 80, 80)
POLE_DRAG_COLOR = (255, 180, 80)
TEXT_COLOR = (200, 200, 220)
BODE_MAG_COLOR = (80, 200, 255)
BODE_PHASE_COLOR = (80, 255, 150)
STEP_COLOR = (255, 200, 80)
PANEL_BG = (20, 20, 35)
HIGHLIGHT_COLOR = (60, 60, 90)

# Layout panels
SPLANE_RECT = pygame.Rect(10, 10, 480, 480)
BODE_MAG_RECT = pygame.Rect(510, 10, 430, 230)
BODE_PHASE_RECT = pygame.Rect(510, 250, 430, 230)
STEP_RECT = pygame.Rect(960, 10, 430, 470)
INFO_RECT = pygame.Rect(10, 500, 480, 290)

font_small = pygame.font.SysFont("monospace", 13)
font_med = pygame.font.SysFont("monospace", 15, bold=True)
font_large = pygame.font.SysFont("monospace", 17, bold=True)

# S-plane coordinate system
# Map s-plane coords to pixel coords within SPLANE_RECT
# Real axis: -6 to 1, Imag axis: -4 to 4
S_REAL_MIN, S_REAL_MAX = -6.0, 1.0
S_IMAG_MIN, S_IMAG_MAX = -4.0, 4.0


def s_to_pixel(sigma, omega, rect):
    """Convert s-plane coordinates to pixel coordinates."""
    px = rect.x + (sigma - S_REAL_MIN) / (S_REAL_MAX - S_REAL_MIN) * rect.width
    py = rect.y + (1.0 - (omega - S_IMAG_MIN) / (S_IMAG_MAX - S_IMAG_MIN)) * rect.height
    return int(px), int(py)


def pixel_to_s(px, py, rect):
    """Convert pixel coordinates to s-plane coordinates."""
    sigma = S_REAL_MIN + (px - rect.x) / rect.width * (S_REAL_MAX - S_REAL_MIN)
    omega = S_IMAG_MIN + (1.0 - (py - rect.y) / rect.height) * (S_IMAG_MAX - S_IMAG_MIN)
    return sigma, omega


def compute_transfer_function(sigma, omega_n):
    """
    Poles at sigma +/- j*omega_n
    H(s) = omega_n^2 + sigma^2 / ((s - p1)(s - p2))
    = K / (s^2 - 2*sigma*s + (sigma^2 + omega_n^2))
    where K = sigma^2 + omega_n^2 (DC gain = 1)
    """
    # Denominator coefficients: s^2 + a1*s + a0
    a1 = -2.0 * sigma  # coefficient of s
    a0 = sigma ** 2 + omega_n ** 2  # constant term
    K = a0  # so DC gain = 1
    return K, a1, a0


def compute_bode(sigma, omega_n, num_points=300):
    """Compute Bode magnitude and phase."""
    K, a1, a0 = compute_transfer_function(sigma, omega_n)

    # Frequency range
    w_min = 0.01
    w_max = 100.0
    w = np.logspace(np.log10(w_min), np.log10(w_max), num_points)

    # H(jw) = K / ((jw)^2 + a1*(jw) + a0)
    # = K / (-w^2 + j*a1*w + a0)
    # = K / ((a0 - w^2) + j*a1*w)

    real_part = a0 - w ** 2
    imag_part = a1 * w

    denom_mag_sq = real_part ** 2 + imag_part ** 2
    denom_mag_sq = np.maximum(denom_mag_sq, 1e-30)

    mag = np.abs(K) / np.sqrt(denom_mag_sq)
    mag_db = 20.0 * np.log10(np.maximum(mag, 1e-15))

    phase_rad = np.arctan2(-imag_part, real_part)  # angle of denominator negated
    phase_deg = np.degrees(phase_rad)

    return w, mag_db, phase_deg


def compute_step_response(sigma, omega_n, t_max=10.0, num_points=500):
    """Compute step response using inverse Laplace / time domain formula."""
    K, a1, a0 = compute_transfer_function(sigma, omega_n)
    t = np.linspace(0, t_max, num_points)

    # Poles: p = sigma +/- j*omega_n
    # Step response of H(s)/s
    # H(s) = K / (s^2 + a1*s + a0)
    # Y(s) = H(s)/s = K / (s*(s^2 + a1*s + a0))

    # Partial fractions: Y(s) = A/s + (Bs + C)/(s^2 + a1*s + a0)
    # A = K/a0 (DC gain)
    # At s=0: A*a0 = K => A = K/a0 = 1 (since K=a0)

    A = K / a0  # = 1.0

    # Remaining: Y(s) - A/s = (K - A*(s^2 + a1*s + a0)) / (s*(s^2 + a1*s + a0))
    # = (-A*s^2 - A*a1*s) / (s*(s^2 + a1*s + a0))
    # = (-A*s - A*a1) / (s^2 + a1*s + a0)
    # = -(A*s + A*a1) / (s^2 + a1*s + a0)

    # So y(t) = A*u(t) + inverse_laplace[-(A*s + A*a1)/(s^2 + a1*s + a0)]

    # s^2 + a1*s + a0 = (s - sigma)^2 + omega_n^2
    # where sigma = -a1/2, omega_d = omega_n (imaginary part)

    sigma_p = -a1 / 2.0  # = sigma (the real part of poles)
    omega_d = omega_n  # damped natural frequency

    if abs(omega_d) < 1e-6:
        # Repeated real poles
        y = A * (1.0 - np.exp(sigma_p * t) * (1.0 - sigma_p * t))
    else:
        # Complex poles
        # inverse_laplace[-(A*s + A*a1)/(s^2 + a1*s + a0)]
        # = -A * e^(sigma_p*t) * [cos(omega_d*t) + (a1 + 2*sigma_p)/omega_d * sin(omega_d*t)/2... ]
        # Let's use: -(A*s + A*a1) = -A*(s + a1)
        # = -A*((s - sigma_p) + (a1 + sigma_p))
        # = -A*((s - sigma_p) + sigma_p)  since a1 = -2*sigma_p => a1 + sigma_p = -sigma_p
        # Wait: a1 = -2*sigma_p, so a1 + sigma_p = -sigma_p

        # inverse_laplace[-A*(s-sigma_p)/((s-sigma_p)^2+omega_d^2)] = -A*e^(sigma_p*t)*cos(omega_d*t)
        # inverse_laplace[-A*sigma_p/((s-sigma_p)^2+omega_d^2)] = -A*sigma_p/omega_d * e^(sigma_p*t)*sin(omega_d*t)

        cos_term = -A * np.exp(sigma_p * t) * np.cos(omega_d * t)
        sin_term = -A * (sigma_p / omega_d) * np.exp(sigma_p * t) * np.sin(omega_d * t)

        y = A + cos_term + sin_term

    return t, y


def draw_panel(surface, rect, title):
    """Draw a panel with background and title."""
    pygame.draw.rect(surface, PANEL_BG, rect, border_radius=8)
    pygame.draw.rect(surface, HIGHLIGHT_COLOR, rect, 1, border_radius=8)
    title_surf = font_large.render(title, True, TEXT_COLOR)
    surface.blit(title_surf, (rect.x + 8, rect.y + 5))


def draw_splane(surface, rect, sigma, omega_n, dragging):
    """Draw the S-plane with poles."""
    draw_panel(surface, rect, "S-Plane")

    # Clip drawing to rect
    clip_rect = pygame.Rect(rect.x, rect.y + 25, rect.width, rect.height - 25)

    # Draw grid
    for real_val in np.arange(np.ceil(S_REAL_MIN), np.floor(S_REAL_MAX) + 1, 1):
        px, _ = s_to_pixel(real_val, 0, rect)
        pygame.draw.line(surface, GRID_COLOR, (px, rect.y + 25), (px, rect.bottom), 1)
        if real_val != 0:
            lbl = font_small.render(f"{int(real_val)}", True, AXIS_COLOR)
            surface.blit(lbl, (px - 8, rect.bottom - 18))

    for imag_val in np.arange(np.ceil(S_IMAG_MIN), np.floor(S_IMAG_MAX) + 1, 1):
        _, py = s_to_pixel(0, imag_val, rect)
        pygame.draw.line(surface, GRID_COLOR, (rect.x, py), (rect.right, py), 1)
        if imag_val != 0:
            lbl = font_small.render(f"{int(imag_val)}j", True, AXIS_COLOR)
            surface.blit(lbl, (rect.x + 2, py - 8))

    # Draw axes
    px0, _ = s_to_pixel(0, 0, rect)
    _, py0 = s_to_pixel(0, 0, rect)
    pygame.draw.line(surface, AXIS_COLOR, (rect.x, py0), (rect.right, py0), 2)
    pygame.draw.line(surface, AXIS_COLOR, (px0, rect.y + 25), (px0, rect.bottom), 2)

    # Stability region shading (left half plane)
    stable_surf = pygame.Surface((px0 - rect.x, rect.height - 25), pygame.SRCALPHA)
    stable_surf.fill((0, 100, 0, 20))
    surface.blit(stable_surf, (rect.x, rect.y + 25))

    # Unstable region
    unstable_surf = pygame.Surface((rect.right - px0, rect.height - 25), pygame.SRCALPHA)
    unstable_surf.fill((100, 0, 0, 20))
    surface.blit(unstable_surf, (px0, rect.y + 25))

    # Draw poles
    pole_color = POLE_DRAG_COLOR if dragging else POLE_COLOR

    # Upper pole: sigma + j*omega_n
    px1, py1 = s_to_pixel(sigma, omega_n, rect)
    # Lower pole: sigma - j*omega_n
    px2, py2 = s_to_pixel(sigma, -omega_n, rect)

    # Draw X marks for poles
    for px, py in [(px1, py1), (px2, py2)]:
        if rect.x <= px <= rect.right and rect.y <= py <= rect.bottom:
            size = 10
            pygame.draw.line(surface, pole_color, (px - size, py - size), (px + size, py + size), 3)
            pygame.draw.line(surface, pole_color, (px + size, py - size), (px - size, py + size), 3)
            # Glow effect
            glow_surf = pygame.Surface((size * 4, size * 4), pygame.SRCALPHA)
            pygame.draw.circle(glow_surf, (*pole_color[:3], 60), (size * 2, size * 2), size * 2)
            surface.blit(glow_surf, (px - size * 2, py - size * 2))

    # Draw dashed line connecting poles
    if rect.x <= px1 <= rect.right and rect.x <= px2 <= rect.right:
        for i in range(0, abs(py2 - py1), 8):
            y_start = min(py1, py2) + i
            y_end = min(y_start + 4, max(py1, py2))
            pygame.draw.line(surface, (*pole_color[:3], 100), (px1, y_start), (px1, y_end), 1)

    # Labels
    lbl_real = font_small.render("Real (σ)", True, AXIS_COLOR)
    lbl_imag = font_small.render("Imag (jω)", True, AXIS_COLOR)
    surface.blit(lbl_real, (rect.right - 70, py0 + 5))
    surface.blit(lbl_imag, (px0 + 5, rect.y + 28))

    # Stable/Unstable labels
    stable_lbl = font_small.render("STABLE", True, (0, 150, 0))
    unstable_lbl = font_small.render("UNSTABLE", True, (150, 0, 0))
    surface.blit(stable_lbl, (rect.x + 10, rect.y + 30))
    surface.blit(unstable_lbl, (px0 + 10, rect.y + 30))


def draw_bode_mag(surface, rect, w, mag_db):
    """Draw Bode magnitude plot."""
    draw_panel(surface, rect, "Bode Plot - Magnitude")

    plot_rect = pygame.Rect(rect.x + 50, rect.y + 25, rect.width - 60, rect.height - 35)
    pygame.draw.rect(surface, (10, 10, 20), plot_rect)

    # Magnitude range
    mag_min, mag_max = -60, 40

    # Draw grid lines
    for db_val in range(-60, 50, 20):
        py = plot_rect.y + (1.0 - (db_val - mag_min) / (mag_max - mag_min)) * plot_rect.height
        if plot_rect.y <= py <= plot_rect.bottom:
            pygame.draw.line(surface, GRID_COLOR, (plot_rect.x, int(py)), (plot_rect.right, int(py)), 1)
            lbl = font_small.render(f"{db_val}", True, AXIS_COLOR)
            surface.blit(lbl, (rect.x + 2, int(py) - 7))

    # 0 dB line
    py0 = plot_rect.y + (1.0 - (0 - mag_min) / (mag_max - mag_min)) * plot_rect.height
    pygame.draw.line(surface, (80, 80, 120), (plot_rect.x, int(py0)), (plot_rect.right, int(py0)), 1)

    # Frequency grid (log scale)
    for decade in [0.01, 0.1, 1, 10, 100]:
        px = plot_rect.x + (np.log10(decade) - np.log10(0.01)) / (np.log10(100) - np.log10(0.01)) * plot_rect.width
        if plot_rect.x <= px <= plot_rect.right:
            pygame.draw.line(surface, GRID_COLOR, (int(px), plot_rect.y), (int(px), plot_rect.bottom), 1)
            lbl = font_small.render(f"{decade}", True, AXIS_COLOR)
            surface.blit(lbl, (int(px) - 10, plot_rect.bottom + 2))

    # Plot magnitude
    points = []
    for i, (wi, mdb) in enumerate(zip(w, mag_db)):
        px = plot_rect.x + (np.log10(wi) - np.log10(0.01)) / (np.log10(100) - np.log10(0.01)) * plot_rect.width
        py = plot_rect.y + (1.0 - (mdb - mag_min) / (mag_max - mag_min)) * plot_rect.height
        py = max(plot_rect.y, min(plot_rect.bottom, py))
        points.append((int(px), int(py)))

    if len(points) > 1:
        pygame.draw.lines(surface, BODE_MAG_COLOR, False, points, 2)

    # Y-axis label
    lbl = font_small.render("dB", True, AXIS_COLOR)
    surface.blit(lbl, (rect.x + 2, rect.y + 25))


def draw_bode_phase(surface, rect, w, phase_deg):
    """Draw Bode phase plot."""
    draw_panel(surface, rect, "Bode Plot - Phase")

    plot_rect = pygame.Rect(rect.x + 50, rect.y + 25, rect.width - 60, rect.height - 35)
    pygame.draw.rect(surface, (10, 10, 20), plot_rect)

    # Phase range
    phase_min, phase_max = -200, 20

    # Draw grid lines
    for ph_val in range(-200, 30, 45):
        py = plot_rect.y + (1.0 - (ph_val - phase_min) / (phase_max - phase_min)) * plot_rect.height
        if plot_rect.y <= py <= plot_rect.bottom:
            pygame.draw.line(surface, GRID_COLOR, (plot_rect.x, int(py)), (plot_rect.right, int(py)), 1)
            lbl = font_small.render(f"{ph_val}°", True, AXIS_COLOR)
            surface.blit(lbl, (rect.x + 2, int(py) - 7))

    # Frequency grid
    for decade in [0.01, 0.1, 1, 10, 100]:
        px = plot_rect.x + (np.log10(decade) - np.log10(0.01)) / (np.log10(100) - np.log10(0.01)) * plot_rect.width
        if plot_rect.x <= px <= plot_rect.right:
            pygame.draw.line(surface, GRID_COLOR, (int(px), plot_rect.y), (int(px), plot_rect.bottom), 1)
            lbl = font_small.render(f"{decade}", True, AXIS_COLOR)
            surface.blit(lbl, (int(px) - 10, plot_rect.bottom + 2))

    # Plot phase
    points = []
    for i, (wi, ph) in enumerate(zip(w, phase_deg)):
        px = plot_rect.x + (np.log10(wi) - np.log10(0.01)) / (np.log10(100) - np.log10(0.01)) * plot_rect.width
        py = plot_rect.y + (1.0 - (ph - phase_min) / (phase_max - phase_min)) * plot_rect.height
        py = max(plot_rect.y, min(plot_rect.bottom, py))
        points.append((int(px), int(py)))

    if len(points) > 1:
        pygame.draw.lines(surface, BODE_PHASE_COLOR, False, points, 2)

    # X-axis label
    lbl = font_small.render("ω (rad/s)", True, AXIS_COLOR)
    surface.blit(lbl, (plot_rect.right - 60, plot_rect.bottom + 2))


def draw_step_response(surface, rect, t, y):
    """Draw step response."""
    draw_panel(surface, rect, "Step Response")

    plot_rect = pygame.Rect(rect.x + 45, rect.y + 25, rect.width - 55, rect.height - 45)
    pygame.draw.rect(surface, (10, 10, 20), plot_rect)

    # Y range
    y_min = min(-0.2, np.min(y) - 0.1) if len(y) > 0 else -0.2
    y_max = max(2.0, np.max(y) + 0.1) if len(y) > 0 else 2.0
    y_range = y_max - y_min

    # Grid
    for y_val in np.arange(0, y_max + 0.5, 0.5):
        py = plot_rect.y + (1.0 - (y_val - y_min) / y_range) * plot_rect.height
        if plot_rect.y <= py <= plot_rect.bottom:
            pygame.draw.line(surface, GRID_COLOR, (plot_rect.x, int(py)), (plot_rect.right, int(py)), 1)
            lbl = font_small.render(f"{y_val:.1f}", True, AXIS_COLOR)
            surface.blit(lbl, (rect.x + 2, int(py) - 7))

    # Reference line at y=1
    py1 = plot_rect.y + (1.0 - (1.0 - y_min) / y_range) * plot_rect.height
    if plot_rect.y <= py1 <= plot_rect.bottom:
        pygame.draw.line(surface, (80, 80, 120), (plot_rect.x, int(py1)), (plot_rect.right, int(py1)), 1)

    # Time grid
    t_max = t[-1] if len(t) > 0 else 10.0
    for t_val in np.arange(0, t_max + 1, 2):
        px = plot_rect.x + (t_val / t_max) * plot_rect.width
        if plot_rect.x <= px <= plot_rect.right:
            pygame.draw.line(surface, GRID_COLOR, (int(px), plot_rect.y), (int(px), plot_rect.bottom), 1)
            lbl = font_small.render(f"{t_val:.0f}", True, AXIS_COLOR)
            surface.blit(lbl, (int(px) - 8, plot_rect.bottom + 2))

    # Plot step response
    points = []
    for ti, yi in zip(t, y):
        px = plot_rect.x + (ti / t_max) * plot_rect.width
        py = plot_rect.y + (1.0 - (yi - y_min) / y_range) * plot_rect.height
        py = max(plot_rect.y, min(plot_rect.bottom, py))
        points.append((int(px), int(py)))

    if len(points) > 1:
        pygame.draw.lines(surface, STEP_COLOR, False, points, 2)

    # Labels
    lbl_x = font_small.render("Time (s)", True, AXIS_COLOR)
    lbl_y = font_small.render("y(t)", True, AXIS_COLOR)
    surface.blit(lbl_x, (plot_rect.right - 50, plot_rect.bottom + 2))
    surface.blit(lbl_y, (rect.x + 2, rect.y + 25))


def draw_info(surface, rect, sigma, omega_n):
    """Draw system information panel."""
    draw_panel(surface, rect, "System Information")

    K, a1, a0 = compute_transfer_function(sigma, omega_n)

    # Compute system parameters
    wn = np.sqrt(sigma ** 2 + omega_n ** 2)  # natural frequency
    if wn > 1e-6:
        zeta = -sigma / wn  # damping ratio
    else:
        zeta = 0.0

    # Stability
    stable = sigma < 0
    stable_str = "STABLE ✓" if stable else "UNSTABLE ✗"
    stable_color = (0, 200, 0) if stable else (200, 0, 0)

    lines = [
        f"Poles: {sigma:.3f} ± {omega_n:.3f}j",
        f"",
        f"Transfer Function:",
        f"  H(s) = {K:.3f}",
        f"         ─────────────────────",
        f"         s² + {a1:.3f}s + {a0:.3f}",
        f"",
        f"Natural Freq (ωn): {wn:.3f} rad/s",
        f"Damping Ratio (ζ): {zeta:.3f}",
        f"Damped Freq (ωd):  {abs(omega_n):.3f} rad/s",
        f"",
        f"Status: {stable_str}",
        f"",
        f"Controls:",
        f"  Drag poles to move",
        f"  Poles move as conjugate pair",
    ]

    y_offset = rect.y + 28
    for i, line in enumerate(lines):
        color = stable_color if "Status" in line else TEXT_COLOR
        if "Status" in line:
            surf = font_med.render(line, True, color)
        else:
            surf = font_small.render(line, True, color)
        surface.blit(surf, (rect.x + 10, y_offset))
        y_offset += 16


def main():
    print("Starting S-Plane Pole Mover with Bode Plot & Step Response")
    print("Drag the poles (X marks) in the S-plane to see real-time updates!")

    clock = pygame.time.Clock()

    # Initial pole position: sigma=-1, omega_n=2 (underdamped)
    sigma = -1.0
    omega_n = 2.0

    dragging = False

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_r:
                    # Reset to default
                    sigma = -1.0
                    omega_n = 2.0
                    print(f"Reset poles to sigma={sigma}, omega_n={omega_n}")

            elif event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 1:
                    mx, my = event.pos
                    # Check if clicking near either pole
                    px1, py1 = s_to_pixel(sigma, omega_n, SPLANE_RECT)
                    px2, py2 = s_to_pixel(sigma, -omega_n, SPLANE_RECT)

                    dist1 = np.sqrt((mx - px1) ** 2 + (my - py1) ** 2)
                    dist2 = np.sqrt((mx - px2) ** 2 + (my - py2) ** 2)

                    if dist1 < 20 or dist2 < 20:
                        dragging = True

            elif event.type == pygame.MOUSEBUTTONUP:
                if event.button == 1:
                    dragging = False

            elif event.type == pygame.MOUSEMOTION:
                if dragging:
                    mx, my = event.pos
                    # Convert mouse position to s-plane coordinates
                    new_sigma, new_omega = pixel_to_s(mx, my, SPLANE_RECT)

                    # Clamp to valid range
                    new_sigma = max(S_REAL_MIN + 0.1, min(S_REAL_MAX - 0.1, new_sigma))
                    new_omega = max(0.01, min(S_IMAG_MAX - 0.1, abs(new_omega)))

                    sigma = new_sigma
                    omega_n = new_omega

        # Compute data
        try:
            w, mag_db, phase_deg = compute_bode(sigma, omega_n)
            t, y = compute_step_response(sigma, omega_n)
        except Exception as e:
            print(f"Computation error: {e}")
            w = np.logspace(-2, 2, 300)
            mag_db = np.zeros(300)
            phase_deg = np.zeros(300)
            t = np.linspace(0, 10, 500)
            y = np.zeros(500)

        # Draw everything
        screen.fill(BG_COLOR)

        draw_splane(screen, SPLANE_RECT, sigma, omega_n, dragging)
        draw_bode_mag(screen, BODE_MAG_RECT, w, mag_db)
        draw_bode_phase(screen, BODE_PHASE_RECT, w, phase_deg)
        draw_step_response(screen, STEP_RECT, t, y)
        draw_info(screen, INFO_RECT, sigma, omega_n)

        # Title bar info
        title_surf = font_med.render(
            f"σ={sigma:.2f}  ωd={omega_n:.2f}  |  Press R to reset, ESC to quit",
            True, (150, 150, 180)
        )
        screen.blit(title_surf, (510, 500))

        pygame.display.flip()
        clock.tick(60)

    pygame.quit()
    print("Application closed.")
    sys.exit()


if __name__ == "__main__":
    main()