# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-13 15:46:30
# AutoCoder System - Automated Code Generation

import control as ctrl
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# Second order system transfer function:
# H(s) = wn^2 / (s^2 + 2*zeta*wn*s + wn^2)
# In frequency domain (s = j*omega):
# H(jw) = wn^2 / ((jw)^2 + 2*zeta*wn*(jw) + wn^2)
# Normalized: H(ju) = 1 / (1 - u^2 + 2*j*zeta*u)  where u = w/wn

print("Generating Bode plot of second order system with different damping factors...")

# Damping ratios to plot
damping_factors = [0.1, 0.2, 0.3, 0.5, 0.707, 1.0, 2.0]

# Normalized frequency range (omega / omega_n)
u = np.logspace(-2, 2, 2000)  # u = w/wn from 0.01 to 100

# Colors for different damping factors
colors = ['#e74c3c', '#e67e22', '#f1c40f', '#2ecc71', '#3498db', '#9b59b6', '#1abc9c']

# Create figure with two subplots
fig = plt.figure(figsize=(12, 9))
fig.patch.set_facecolor('#1a1a2e')

gs = gridspec.GridSpec(2, 1, hspace=0.4)
ax_mag = fig.add_subplot(gs[0])
ax_phase = fig.add_subplot(gs[1])

# Style axes
for ax in [ax_mag, ax_phase]:
    ax.set_facecolor('#16213e')
    ax.tick_params(colors='white', labelsize=10)
    ax.xaxis.label.set_color('white')
    ax.yaxis.label.set_color('white')
    ax.title.set_color('white')
    for spine in ax.spines.values():
        spine.set_edgecolor('#444466')
    ax.grid(True, which='both', linestyle='--', linewidth=0.5, color='#334466', alpha=0.7)

# Plot magnitude and phase for each damping factor
for zeta, color in zip(damping_factors, colors):
    # Transfer function H(ju) = 1 / (1 - u^2 + 2j*zeta*u)
    H = 1.0 / ((1 - u ** 2) + 2j * zeta * u)

    # Magnitude in dB
    magnitude_dB = 20 * np.log10(np.abs(H))

    # Phase in degrees
    phase_deg = np.degrees(np.angle(H))

    label = f'zeta = {zeta}'

    ax_mag.semilogx(u, magnitude_dB, color=color, linewidth=2.0, label=label)
    ax_phase.semilogx(u, phase_deg, color=color, linewidth=2.0, label=label)

# Add vertical line at natural frequency (u = 1)
ax_mag.axvline(x=1.0, color='white', linestyle=':', linewidth=1.0, alpha=0.5)
ax_phase.axvline(x=1.0, color='white', linestyle=':', linewidth=1.0, alpha=0.5)

# Add horizontal reference lines
ax_mag.axhline(y=0, color='white', linestyle='--', linewidth=0.8, alpha=0.4)
ax_mag.axhline(y=-3, color='yellow', linestyle=':', linewidth=0.8, alpha=0.4)
ax_phase.axhline(y=-90, color='white', linestyle='--', linewidth=0.8, alpha=0.4)
ax_phase.axhline(y=-180, color='white', linestyle='--', linewidth=0.8, alpha=0.4)

# Annotate natural frequency
ax_mag.annotate('wn', xy=(1.0, ax_mag.get_ylim()[0] if ax_mag.get_ylim()[0] > -60 else -60),
                xytext=(1.2, -55), color='white', fontsize=9, alpha=0.7)

# Magnitude plot formatting
ax_mag.set_title('Bode Plot - Second Order System: H(s) = wn^2 / (s^2 + 2*zeta*wn*s + wn^2)',
                 fontsize=12, color='white', pad=12)
ax_mag.set_ylabel('Magnitude (dB)', fontsize=11)
ax_mag.set_xlim([u[0], u[-1]])
ax_mag.set_ylim([-60, 30])
ax_mag.set_yticks(range(-60, 35, 10))
ax_mag.legend(loc='lower left', fontsize=9, facecolor='#1a1a2e',
              edgecolor='#444466', labelcolor='white', ncol=2)

# Phase plot formatting
ax_phase.set_xlabel('Normalized Frequency  w / wn', fontsize=11)
ax_phase.set_ylabel('Phase (degrees)', fontsize=11)
ax_phase.set_xlim([u[0], u[-1]])
ax_phase.set_ylim([-195, 15])
ax_phase.set_yticks([0, -30, -60, -90, -120, -150, -180])
ax_phase.legend(loc='lower left', fontsize=9, facecolor='#1a1a2e',
                edgecolor='#444466', labelcolor='white', ncol=2)

# Add text annotations for phase reference lines
ax_phase.text(u[-1] * 0.6, -87, '-90 deg', color='white', fontsize=8, alpha=0.6)
ax_phase.text(u[-1] * 0.6, -177, '-180 deg', color='white', fontsize=8, alpha=0.6)

# Add annotation box explaining key observations
textstr = (
    'Key Observations:\n'
    '- zeta < 0.707: resonance peak in magnitude\n'
    '- zeta = 0.707: maximally flat (Butterworth)\n'
    '- zeta >= 1.0: overdamped, no peak\n'
    '- Phase shifts from 0 to -180 deg'
)
props = dict(boxstyle='round', facecolor='#0f3460', alpha=0.8, edgecolor='#3498db')
ax_mag.text(0.012, 27, textstr, fontsize=8, color='white',
            verticalalignment='top', bbox=props)

plt.suptitle('Second Order System Bode Plot', fontsize=14, color='white',
             fontweight='bold', y=0.98)

plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.savefig('bode_plot_second_order.png', dpi=150, bbox_inches='tight',
            facecolor='#1a1a2e')
print("Bode plot saved as 'bode_plot_second_order.png'")
plt.show()
print("Done.")