# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-24 15:50:38
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.widgets import Slider
from scipy import signal

# ── initial parameters ──────────────────────────────────────────────────────
INIT_ORDER      = 4
INIT_CUTOFF     = 0.3          # normalised (0‥1)
INIT_ATTEN      = 40           # dB
FS              = 1000         # Hz
NFFT            = 2048
T_WINDOW        = 0.05         # seconds of signal shown
N_ANIM          = int(T_WINDOW * FS)

# ── build composite test signal ──────────────────────────────────────────────
np.random.seed(42)
t_full = np.linspace(0, 1, FS, endpoint=False)
raw_signal = (np.sin(2 * np.pi * 50  * t_full) +
              0.6 * np.sin(2 * np.pi * 200 * t_full) +
              0.4 * np.sin(2 * np.pi * 400 * t_full) +
              0.3 * np.random.randn(FS))

print("Signal generated: length =", len(raw_signal))

# ── figure layout ────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(14, 9))
fig.patch.set_facecolor('#1a1a2e')

ax_freq  = fig.add_axes([0.07, 0.55, 0.57, 0.36])   # frequency response
ax_sig   = fig.add_axes([0.07, 0.13, 0.57, 0.33])   # time-domain signal
ax_pole  = fig.add_axes([0.70, 0.30, 0.27, 0.55])   # pole-zero plot

for ax in (ax_freq, ax_sig, ax_pole):
    ax.set_facecolor('#0f0f23')
    for spine in ax.spines.values():
        spine.set_edgecolor('#444466')

# ── slider axes ─────────────────────────────────────────────────────────────
ax_s_order  = fig.add_axes([0.07, 0.07, 0.25, 0.03])
ax_s_cutoff = fig.add_axes([0.07, 0.03, 0.25, 0.03])
ax_s_atten  = fig.add_axes([0.38, 0.07, 0.25, 0.03])

slider_kw = dict(color='#3a3a6e', track_color='#1a1a3e')
s_order  = Slider(ax_s_order,  'Order',    1,    10,   valinit=INIT_ORDER,  valstep=1,  **slider_kw)
s_cutoff = Slider(ax_s_cutoff, 'Cutoff',   0.05, 0.95, valinit=INIT_CUTOFF,             **slider_kw)
s_atten  = Slider(ax_s_atten,  'Atten dB', 10,   80,   valinit=INIT_ATTEN,  valstep=1,  **slider_kw)

for sl in (s_order, s_cutoff, s_atten):
    sl.label.set_color('white')
    sl.valtext.set_color('#aaffaa')

# ── helper: build filter ──────────────────────────────────────────────────────
def make_filter(order, cutoff):
    b, a = signal.butter(int(order), float(cutoff), btype='low', analog=False)
    return b, a

def freq_response(b, a):
    w, h = signal.freqz(b, a, worN=NFFT)
    freq_hz = w / np.pi * (FS / 2)
    mag_db  = 20 * np.log10(np.abs(h) + 1e-12)
    phase   = np.unwrap(np.angle(h)) * 180 / np.pi
    return freq_hz, mag_db, phase

# ── initial filter ────────────────────────────────────────────────────────────
b0, a0 = make_filter(INIT_ORDER, INIT_CUTOFF)
freq_hz, mag_db, phase = freq_response(b0, a0)
filtered_full = signal.lfilter(b0, a0, raw_signal)
print("Initial filter computed. Poles/zeros calculated.")

# ── frequency response plot ───────────────────────────────────────────────────
ax_freq.set_title('Butterworth Low-Pass Frequency Response', color='white', pad=6)
ax_freq.set_xlabel('Frequency (Hz)', color='#aaaacc')
ax_freq.set_ylabel('Magnitude (dB)', color='#aaaacc')
ax_freq.tick_params(colors='#aaaacc')
ax_freq.set_xlim(0, FS / 2)
ax_freq.set_ylim(-100, 5)
ax_freq.grid(True, color='#333355', linewidth=0.5)

line_mag,  = ax_freq.plot(freq_hz, mag_db,  color='#00e5ff', lw=1.8, label='Magnitude')
ax_freq2   = ax_freq.twinx()
ax_freq2.set_facecolor('#0f0f23')
ax_freq2.set_ylabel('Phase (deg)', color='#ff9966')
ax_freq2.tick_params(colors='#ff9966')
line_phase, = ax_freq2.plot(freq_hz, phase, color='#ff9966', lw=1.2, alpha=0.7, label='Phase')
cutoff_line = ax_freq.axvline(INIT_CUTOFF * FS / 2, color='#ff4444', lw=1.5,
                               linestyle='--', label='Cutoff')
ax_freq.legend(loc='lower left', facecolor='#1a1a2e', labelcolor='white', fontsize=8)
ax_freq2.set_ylim(-1000, 100)

# ── time-domain plot ──────────────────────────────────────────────────────────
t_win = np.arange(N_ANIM) / FS
ax_sig.set_title('Real-Time Signal Filtering', color='white', pad=6)
ax_sig.set_xlabel('Time (s)', color='#aaaacc')
ax_sig.set_ylabel('Amplitude', color='#aaaacc')
ax_sig.tick_params(colors='#aaaacc')
ax_sig.set_xlim(0, T_WINDOW)
ax_sig.set_ylim(-3.5, 3.5)
ax_sig.grid(True, color='#333355', linewidth=0.5)

line_raw,  = ax_sig.plot(t_win, raw_signal[:N_ANIM],    color='#888899', lw=1,
                          alpha=0.6, label='Raw')
line_filt, = ax_sig.plot(t_win, filtered_full[:N_ANIM], color='#00ff88', lw=2,
                          label='Filtered')
ax_sig.legend(loc='upper right', facecolor='#1a1a2e', labelcolor='white', fontsize=8)

info_text = ax_sig.text(0.02, 0.92, '', transform=ax_sig.transAxes,
                         color='#ffdd88', fontsize=8, va='top')

# ── pole-zero plot ────────────────────────────────────────────────────────────
ax_pole.set_title('Pole-Zero Map', color='white', pad=6)
ax_pole.set_xlabel('Real', color='#aaaacc')
ax_pole.set_ylabel('Imaginary', color='#aaaacc')
ax_pole.tick_params(colors='#aaaacc')
ax_pole.set_aspect('equal')
ax_pole.grid(True, color='#333355', linewidth=0.5)
unit_circle = plt.Circle((0, 0), 1, fill=False, color='#555577', lw=1.2, linestyle='--')
ax_pole.add_patch(unit_circle)
ax_pole.axhline(0, color='#444466', lw=0.8)
ax_pole.axvline(0, color='#444466', lw=0.8)

zeros_plot, = ax_pole.plot([], [], 'o', color='#00e5ff', ms=8, label='Zeros', zorder=5)
poles_plot, = ax_pole.plot([], [], 'x', color='#ff4444', ms=10, mew=2.5,
                            label='Poles', zorder=5)
ax_pole.legend(loc='upper left', facecolor='#1a1a2e', labelcolor='white', fontsize=8)

def update_pole_zero(b, a):
    z, p, _ = signal.tf2zpk(b, a)
    zeros_plot.set_data(z.real, z.imag)
    poles_plot.set_data(p.real, p.imag)
    margin = 0.3
    all_pts = np.concatenate([z, p, [1+0j, -1+0j, 1j, -1j]])
    lim = max(np.abs(all_pts).max() + margin, 1.4)
    ax_pole.set_xlim(-lim, lim)
    ax_pole.set_ylim(-lim, lim)

update_pole_zero(b0, a0)
print("Pole-zero plot initialized.")

# ── suptitle ──────────────────────────────────────────────────────────────────
fig.suptitle('Interactive Butterworth Filter Simulation', color='white',
             fontsize=14, fontweight='bold', y=0.98)

# ── animation state ───────────────────────────────────────────────────────────
state = {
    'b': b0, 'a': a0,
    'filtered': filtered_full,
    'frame': 0,
    'dirty': False,
}

# ── slider callbacks ──────────────────────────────────────────────────────────
def recompute(_=None):
    order  = int(s_order.val)
    cutoff = float(s_cutoff.val)
    try:
        b, a = make_filter(order, cutoff)
        fh, md, ph = freq_response(b, a)
        line_mag.set_data(fh, md)
        line_phase.set_data(fh, ph)
        ax_freq2.set_ylim(ph.min() - 50, ph.max() + 50)
        cutoff_line.set_xdata([cutoff * FS / 2, cutoff * FS / 2])
        state['b'] = b
        state['a'] = a
        state['filtered'] = signal.lfilter(b, a, raw_signal)
        update_pole_zero(b, a)
        state['dirty'] = True
        print(f"Filter updated: order={order}, cutoff={cutoff:.3f} ({cutoff*FS/2:.1f} Hz)")
    except Exception as e:
        print(f"Filter error: {e}")

s_order.on_changed(recompute)
s_cutoff.on_changed(recompute)
s_atten.on_changed(recompute)

# ── animation ─────────────────────────────────────────────────────────────────
STEP = 4   # samples to advance each frame
max_start = len(raw_signal) - N_ANIM

def animate(frame):
    idx = state['frame']
    end = idx + N_ANIM
    if end > len(raw_signal):
        state['frame'] = 0
        idx = 0
        end = N_ANIM

    raw_chunk  = raw_signal[idx:end]
    filt_chunk = state['filtered'][idx:end]

    line_raw.set_ydata(raw_chunk)
    line_filt.set_ydata(filt_chunk)

    order  = int(s_order.val)
    cutoff = float(s_cutoff.val)
    info_text.set_text(
        f'Order: {order}   Cutoff: {cutoff*FS/2:.1f} Hz   '
        f'Atten: {int(s_atten.val)} dB'
    )

    state['frame'] = (idx + STEP) % max(max_start, 1)
    return line_raw, line_filt, info_text

ani = animation.FuncAnimation(fig, animate, interval=30, blit=False, cache_frame_data=False)

print("Animation started. Displaying interactive filter simulation...")
plt.show()
