# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-04 11:06:05
# AutoCoder System - Automated Code Generation

import tkinter as tk
from tkinter import ttk, messagebox, simpledialog
import calendar
from datetime import datetime, date
import json
import os

# ─── Color Palette ───────────────────────────────────────────────────────────
BG_MAIN       = "#1e1e2e"
BG_HEADER     = "#313244"
BG_CARD       = "#45475a"
BG_TODAY      = "#89b4fa"
BG_WEEKEND    = "#2a2a3e"
BG_APPT       = "#a6e3a1"
FG_MAIN       = "#cdd6f4"
FG_HEADER     = "#89dceb"
FG_TODAY      = "#1e1e2e"
FG_MUTED      = "#6c7086"
ACCENT        = "#cba6f7"
ACCENT2       = "#f38ba8"
BTN_BG        = "#585b70"
BTN_HOVER     = "#7f849c"

APPOINTMENTS_FILE = "appointments.json"

# ─── Data Layer ───────────────────────────────────────────────────────────────
def load_appointments():
    if os.path.exists(APPOINTMENTS_FILE):
        with open(APPOINTMENTS_FILE, "r") as f:
            return json.load(f)
    return {}

def save_appointments(data):
    with open(APPOINTMENTS_FILE, "w") as f:
        json.dump(data, f, indent=2)

# ─── Main App ─────────────────────────────────────────────────────────────────
class CalendarApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("✨ Aesthetic Calendar")
        self.configure(bg=BG_MAIN)
        self.resizable(True, True)
        self.geometry("900x700")

        self.appointments = load_appointments()
        self.today = date.today()
        self.current_year  = self.today.year
        self.current_month = self.today.month
        self.selected_date = None

        self._build_ui()
        self._draw_calendar()
        print(f"[Calendar] Launched – today is {self.today}")

    # ── UI skeleton ──────────────────────────────────────────────────────────
    def _build_ui(self):
        # ── Top header ──
        header = tk.Frame(self, bg=BG_HEADER, pady=12)
        header.pack(fill="x")

        tk.Button(header, text="◀", command=self._prev_month,
                  bg=BTN_BG, fg=FG_MAIN, relief="flat",
                  font=("Segoe UI", 14, "bold"), padx=10,
                  activebackground=BTN_HOVER, cursor="hand2"
                  ).pack(side="left", padx=(20, 5))

        self.month_label = tk.Label(header, text="", bg=BG_HEADER,
                                    fg=FG_HEADER,
                                    font=("Segoe UI", 22, "bold"))
        self.month_label.pack(side="left", expand=True)

        tk.Button(header, text="▶", command=self._next_month,
                  bg=BTN_BG, fg=FG_MAIN, relief="flat",
                  font=("Segoe UI", 14, "bold"), padx=10,
                  activebackground=BTN_HOVER, cursor="hand2"
                  ).pack(side="right", padx=(5, 20))

        tk.Button(header, text="Today", command=self._go_today,
                  bg=ACCENT, fg=BG_MAIN, relief="flat",
                  font=("Segoe UI", 11, "bold"), padx=12, pady=4,
                  activebackground=BTN_HOVER, cursor="hand2"
                  ).pack(side="right", padx=5)

        # ── Day-of-week row ──
        dow_frame = tk.Frame(self, bg=BG_MAIN)
        dow_frame.pack(fill="x", padx=10, pady=(8, 0))
        days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        for i, d in enumerate(days):
            color = ACCENT2 if i >= 5 else FG_MUTED
            tk.Label(dow_frame, text=d, bg=BG_MAIN, fg=color,
                     font=("Segoe UI", 11, "bold"),
                     width=10).grid(row=0, column=i, padx=2)

        # ── Calendar grid ──
        self.grid_frame = tk.Frame(self, bg=BG_MAIN)
        self.grid_frame.pack(fill="both", expand=True, padx=10, pady=6)

        # ── Appointment panel ──
        self.appt_frame = tk.Frame(self, bg=BG_HEADER, pady=10)
        self.appt_frame.pack(fill="x", side="bottom")

        self.appt_title = tk.Label(self.appt_frame,
                                   text="Select a day to view appointments",
                                   bg=BG_HEADER, fg=FG_HEADER,
                                   font=("Segoe UI", 13, "bold"))
        self.appt_title.pack()

        self.appt_list = tk.Frame(self.appt_frame, bg=BG_HEADER)
        self.appt_list.pack(fill="x", padx=20, pady=4)

        self.add_btn = tk.Button(self.appt_frame, text="＋ Add Appointment",
                                 command=self._add_appointment,
                                 bg=ACCENT, fg=BG_MAIN, relief="flat",
                                 font=("Segoe UI", 11, "bold"),
                                 padx=14, pady=5, cursor="hand2",
                                 activebackground=BTN_HOVER)
        self.add_btn.pack(pady=(4, 2))
        self.add_btn.pack_forget()   # hidden until a date is selected

    # ── Calendar drawing ─────────────────────────────────────────────────────
    def _draw_calendar(self):
        for w in self.grid_frame.winfo_children():
            w.destroy()

        self.month_label.config(
            text=f"{calendar.month_name[self.current_month]}  {self.current_year}")

        cal = calendar.monthcalendar(self.current_year, self.current_month)

        for row_i, week in enumerate(cal):
            self.grid_frame.rowconfigure(row_i, weight=1)
            for col_i, day in enumerate(week):
                self.grid_frame.columnconfigure(col_i, weight=1)

                cell = tk.Frame(self.grid_frame, relief="flat",
                                bd=0, padx=2, pady=2)
                cell.grid(row=row_i, column=col_i,
                          sticky="nsew", padx=3, pady=3)

                if day == 0:
                    cell.configure(bg=BG_MAIN)
                    continue

                # Determine colours
                is_today   = (day == self.today.day and
                              self.current_month == self.today.month and
                              self.current_year  == self.today.year)
                is_weekend = col_i >= 5
                is_sel     = (self.selected_date ==
                              date(self.current_year, self.current_month, day))

                if is_today:
                    bg = BG_TODAY; fg = FG_TODAY
                elif is_sel:
                    bg = ACCENT;   fg = BG_MAIN
                elif is_weekend:
                    bg = BG_WEEKEND; fg = ACCENT2
                else:
                    bg = BG_CARD;  fg = FG_MAIN

                cell.configure(bg=bg)

                # Day number
                lbl = tk.Label(cell, text=str(day), bg=bg, fg=fg,
                               font=("Segoe UI", 12, "bold"),
                               anchor="nw", padx=6, pady=4)
                lbl.pack(fill="both", expand=True)

                # Appointment dots
                key = str(date(self.current_year, self.current_month, day))
                if key in self.appointments and self.appointments[key]:
                    dot_frame = tk.Frame(cell, bg=bg)
                    dot_frame.pack(fill="x", padx=4, pady=(0, 4))
                    for appt in self.appointments[key][:3]:
                        short = appt[:18] + "…" if len(appt) > 18 else appt
                        tk.Label(dot_frame, text=f"• {short}",
                                 bg=bg, fg=BG_APPT,
                                 font=("Segoe UI", 8),
                                 anchor="w").pack(fill="x")

                # Click binding
                d = day
                for widget in (cell, lbl):
                    widget.bind("<Button-1>",
                                lambda e, dd=d: self._select_day(dd))
                    widget.bind("<Enter>",
                                lambda e, f=cell, b=bg: f.configure(
                                    bg=BTN_HOVER if b not in (BG_TODAY, ACCENT)
                                    else b))
                    widget.bind("<Leave>",
                                lambda e, f=cell, b=bg: f.configure(bg=b))

    # ── Navigation ───────────────────────────────────────────────────────────
    def _prev_month(self):
        if self.current_month == 1:
            self.current_month = 12
            self.current_year -= 1
        else:
            self.current_month -= 1
        self._draw_calendar()

    def _next_month(self):
        if self.current_month == 12:
            self.current_month = 1
            self.current_year += 1
        else:
            self.current_month += 1
        self._draw_calendar()

    def _go_today(self):
        self.current_year  = self.today.year
        self.current_month = self.today.month
        self.selected_date = self.today
        self._draw_calendar()
        self._refresh_appt_panel()

    # ── Day selection ────────────────────────────────────────────────────────
    def _select_day(self, day):
        self.selected_date = date(self.current_year, self.current_month, day)
        print(f"[Calendar] Selected {self.selected_date}")
        self._draw_calendar()
        self._refresh_appt_panel()

    # ── Appointment panel ────────────────────────────────────────────────────
    def _refresh_appt_panel(self):
        for w in self.appt_list.winfo_children():
            w.destroy()

        if not self.selected_date:
            return

        key = str(self.selected_date)
        self.appt_title.config(
            text=f"📅  {self.selected_date.strftime('%A, %B %d %Y')}")
        self.add_btn.pack(pady=(4, 2))

        appts = self.appointments.get(key, [])
        if not appts:
            tk.Label(self.appt_list, text="No appointments – add one!",
                     bg=BG_HEADER, fg=FG_MUTED,
                     font=("Segoe UI", 10, "italic")).pack()
        else:
            for i, appt in enumerate(appts):
                row = tk.Frame(self.appt_list, bg=BG_HEADER)
                row.pack(fill="x", pady=2)
                tk.Label(row, text=f"🗓  {appt}", bg=BG_HEADER,
                         fg=BG_APPT, font=("Segoe UI", 10),
                         anchor="w").pack(side="left", padx=6)
                idx = i
                tk.Button(row, text="✕", bg=ACCENT2, fg=BG_MAIN,
                          relief="flat", font=("Segoe UI", 9, "bold"),
                          padx=4, cursor="hand2",
                          command=lambda k=key, ii=idx: self._delete_appt(k, ii)
                          ).pack(side="right", padx=4)

    def _add_appointment(self):
        if not self.selected_date:
            return
        appt = simpledialog.askstring(
            "New Appointment",
            f"Enter appointment for {self.selected_date.strftime('%B %d, %Y')}:",
            parent=self)
        if appt and appt.strip():
            key = str(self.selected_date)
            self.appointments.setdefault(key, []).append(appt.strip())
            save_appointments(self.appointments)
            print(f"[Calendar] Added appointment on {key}: {appt.strip()}")
            self._draw_calendar()
            self._refresh_appt_panel()

    def _delete_appt(self, key, idx):
        if messagebox.askyesno("Delete", "Remove this appointment?"):
            del self.appointments[key][idx]
            if not self.appointments[key]:
                del self.appointments[key]
            save_appointments(self.appointments)
            print(f"[Calendar] Deleted appointment #{idx} on {key}")
            self._draw_calendar()
            self._refresh_appt_panel()


# ─── Entry point ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("[Calendar] Starting aesthetic calendar app…")
    app = CalendarApp()
    app.mainloop()
    print("[Calendar] App closed.")
