# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-07 12:53:21
# AutoCoder System - Automated Code Generation

import pygame
import numpy as np
import sys
import math
import random

# Initialize pygame
pygame.init()
pygame.mixer.init(frequency=44100, size=-16, channels=2, buffer=512)

# Screen setup
WIDTH, HEIGHT = 1200, 800
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("First Contact - Close Encounters Musical Experience")

clock = pygame.time.Clock()
FPS = 60

# Colors
BLACK = (0, 0, 5)
STAR_COLOR = (200, 210, 255)
GOLDEN_YELLOW = (255, 215, 0)
DEEP_PURPLE = (80, 0, 160)
ELECTRIC_ORANGE = (255, 100, 0)
COBALT_BLUE = (0, 80, 220)
BRILLIANT_WHITE = (240, 245, 255)
SCANNER_GREEN = (0, 255, 100)
MIST_BLUE = (100, 150, 220)
AMBER = (255, 180, 50)

# Note colors for the 5 columns
NOTE_COLORS = [GOLDEN_YELLOW, DEEP_PURPLE, ELECTRIC_ORANGE, COBALT_BLUE, BRILLIANT_WHITE]
NOTE_NAMES = ["Re", "Mi", "Do", "Do", "Sol"]

# Five-note motif frequencies (Re Mi Do Do-low Sol)
# D5, E5, C5, C4, G4
NOTE_FREQS = [587.33, 659.25, 523.25, 261.63, 392.00]
NOTE_DURATIONS = [0.6, 0.6, 0.6, 0.8, 1.2]  # seconds


def generate_tone(frequency, duration, sample_rate=44100, volume=0.6):
    """Generate a sine wave tone as pygame sound."""
    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
    # Add harmonics for richer sound
    wave = (np.sin(2 * np.pi * frequency * t) * 0.6 +
            np.sin(2 * np.pi * frequency * 2 * t) * 0.2 +
            np.sin(2 * np.pi * frequency * 3 * t) * 0.1)
    # Envelope: attack, sustain, release
    attack = int(0.05 * sample_rate)
    release = int(0.15 * sample_rate)
    envelope = np.ones(len(t))
    if attack > 0:
        envelope[:attack] = np.linspace(0, 1, attack)
    if release > 0 and release < len(t):
        envelope[-release:] = np.linspace(1, 0, release)
    wave = wave * envelope * volume
    # Convert to int16 stereo
    wave_int = (wave * 32767).astype(np.int16)
    stereo = np.column_stack([wave_int, wave_int])
    return pygame.sndarray.make_sound(stereo)


# Pre-generate sounds
print("Generating tones...")
sounds = []
for i, (freq, dur) in enumerate(zip(NOTE_FREQS, NOTE_DURATIONS)):
    s = generate_tone(freq, dur)
    sounds.append(s)
    print(f"  Note {NOTE_NAMES[i]}: {freq:.2f} Hz, {dur}s")


# Stars
class Star:
    def __init__(self):
        self.reset()
        self.y = random.randint(0, HEIGHT)

    def reset(self):
        self.x = random.randint(0, WIDTH)
        self.y = random.randint(0, HEIGHT * 0.85)
        self.base_brightness = random.randint(80, 200)
        self.brightness = self.base_brightness
        self.size = random.choice([1, 1, 1, 2])
        self.pulse_speed = random.uniform(0.01, 0.04)
        self.pulse_phase = random.uniform(0, math.pi * 2)
        self.vx = random.uniform(-0.05, 0.05)
        self.vy = random.uniform(-0.02, 0.02)
        self.scatter_vx = 0
        self.scatter_vy = 0
        self.scatter_decay = 0.95

    def update(self, time):
        # Pulse
        pulse = math.sin(time * self.pulse_speed * 60 + self.pulse_phase)
        self.brightness = int(self.base_brightness + pulse * 30)
        self.brightness = max(40, min(255, self.brightness))
        # Drift
        self.x += self.vx + self.scatter_vx
        self.y += self.vy + self.scatter_vy
        self.scatter_vx *= self.scatter_decay
        self.scatter_vy *= self.scatter_decay
        # Wrap
        if self.x < 0: self.x = WIDTH
        if self.x > WIDTH: self.x = 0
        if self.y < 0: self.y = HEIGHT * 0.85
        if self.y > HEIGHT * 0.85: self.y = 0

    def scatter(self, cx, cy, strength=3):
        dx = self.x - cx
        dy = self.y - cy
        dist = math.sqrt(dx * dx + dy * dy) + 1
        if dist < 300:
            force = strength * (300 - dist) / 300
            self.scatter_vx += (dx / dist) * force
            self.scatter_vy += (dy / dist) * force

    def draw(self, surface):
        c = self.brightness
        color = (min(255, int(c * 0.85)), min(255, int(c * 0.9)), min(255, c))
        if self.size == 1:
            surface.set_at((int(self.x), int(self.y)), color)
        else:
            pygame.draw.circle(surface, color, (int(self.x), int(self.y)), self.size)


# Light column
class LightColumn:
    def __init__(self, index, x, color):
        self.index = index
        self.x = x
        self.color = color
        self.height = 0
        self.target_height = 0
        self.max_height = HEIGHT * 0.75
        self.width = 60
        self.active = False
        self.bloom = 0
        self.shockwave_radius = 0
        self.shockwave_active = False
        self.shockwave_alpha = 0

    def activate(self):
        self.active = True
        self.target_height = self.max_height
        self.bloom = 1.0
        self.shockwave_radius = 0
        self.shockwave_active = True
        self.shockwave_alpha = 255

    def update(self):
        if self.active:
            self.height += (self.target_height - self.height) * 0.15
            self.bloom *= 0.97
        else:
            self.height *= 0.92
            self.bloom *= 0.95
            self.target_height = 0

        if self.shockwave_active:
            self.shockwave_radius += 8
            self.shockwave_alpha = max(0, self.shockwave_alpha - 5)
            if self.shockwave_alpha <= 0:
                self.shockwave_active = False
                self.shockwave_radius = 0

    def draw(self, surface):
        if self.height < 2:
            return
        h = int(self.height)
        col_x = int(self.x - self.width // 2)
        col_y = HEIGHT - h

        # Draw column with gradient
        for layer in range(3):
            alpha_factor = 1.0 - layer * 0.25
            w = self.width - layer * 15
            if w <= 0:
                continue
            lx = int(self.x - w // 2)
            r = min(255, int(self.color[0] * alpha_factor))
            g = min(255, int(self.color[1] * alpha_factor))
            b = min(255, int(self.color[2] * alpha_factor))

            col_surf = pygame.Surface((w, h), pygame.SRCALPHA)
            for py in range(h):
                # Gradient from bottom (bright) to top (dim)
                t = py / max(h, 1)
                brightness = (1 - t * 0.6) * alpha_factor
                cr = min(255, int(r * brightness + 50 * brightness))
                cg = min(255, int(g * brightness + 50 * brightness))
                cb = min(255, int(b * brightness + 50 * brightness))
                ca = int(180 * brightness * alpha_factor)
                pygame.draw.line(col_surf, (cr, cg, cb, ca), (0, py), (w, py))
            surface.blit(col_surf, (lx, col_y))

        # Bloom at top
        if self.bloom > 0.05:
            bloom_size = int(80 * self.bloom + 20)
            bloom_surf = pygame.Surface((bloom_size * 2, bloom_size * 2), pygame.SRCALPHA)
            for r_step in range(bloom_size, 0, -5):
                alpha = int(80 * self.bloom * (1 - r_step / bloom_size))
                cr = min(255, self.color[0] + 50)
                cg = min(255, self.color[1] + 50)
                cb = min(255, self.color[2] + 50)
                pygame.draw.circle(bloom_surf, (cr, cg, cb, alpha),
                                   (bloom_size, bloom_size), r_step)
            surface.blit(bloom_surf, (int(self.x) - bloom_size, col_y - bloom_size),
                         special_flags=pygame.BLEND_ADD)

        # Shockwave
        if self.shockwave_active and self.shockwave_radius > 0:
            sw_surf = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
            alpha = int(self.shockwave_alpha * 0.6)
            pygame.draw.circle(sw_surf, (self.color[0], self.color[1], self.color[2], alpha),
                               (int(self.x), HEIGHT - 10), int(self.shockwave_radius), 3)
            surface.blit(sw_surf, (0, 0))


# Geometric alien symbol
class AlienSymbol:
    SHAPES = ['fibonacci', 'triangle', 'hexagon', 'spiral_square', 'diamond']

    def __init__(self):
        self.reset()

    def reset(self):
        side = random.choice(['left', 'right', 'top'])
        if side == 'left':
            self.x = -50
            self.y = random.randint(50, HEIGHT - 200)
            self.vx = random.uniform(0.3, 0.8)
            self.vy = random.uniform(-0.2, 0.2)
        elif side == 'right':
            self.x = WIDTH + 50
            self.y = random.randint(50, HEIGHT - 200)
            self.vx = random.uniform(-0.8, -0.3)
            self.vy = random.uniform(-0.2, 0.2)
        else:
            self.x = random.randint(100, WIDTH - 100)
            self.y = -50
            self.vx = random.uniform(-0.2, 0.2)
            self.vy = random.uniform(0.3, 0.7)
        self.angle = random.uniform(0, math.pi * 2)
        self.rot_speed = random.uniform(-0.01, 0.01)
        self.size = random.randint(20, 45)
        self.alpha = 0
        self.fade_in = True
        self.max_alpha = random.randint(60, 130)
        self.shape = random.choice(self.SHAPES)
        self.color = random.choice([
            (100, 255, 150), (150, 200, 255), (200, 150, 255),
            (255, 200, 100), (100, 220, 220)
        ])
        self.active = True

    def update(self):
        self.x += self.vx
        self.y += self.vy
        self.angle += self.rot_speed

        if self.fade_in:
            self.alpha = min(self.max_alpha, self.alpha + 1)
            if self.alpha >= self.max_alpha:
                self.fade_in = False
        else:
            self.alpha = max(0, self.alpha - 0.3)

        # Check if off screen
        if (self.x < -100 or self.x > WIDTH + 100 or
                self.y < -100 or self.y > HEIGHT + 100 or
                (not self.fade_in and self.alpha <= 0)):
            self.active = False

    def get_polygon_points(self, cx, cy, n, size, angle_offset=0):
        points = []
        for i in range(n):
            a = angle_offset + i * (2 * math.pi / n)
            px = cx + size * math.cos(a)
            py = cy + size * math.sin(a)
            points.append((px, py))
        return points

    def draw(self, surface):
        if self.alpha <= 0:
            return
        sym_surf = pygame.Surface((self.size * 4, self.size * 4), pygame.SRCALPHA)
        cx = self.size * 2
        cy = self.size * 2
        alpha = int(self.alpha)
        color_a = (self.color[0], self.color[1], self.color[2], alpha)

        if self.shape == 'triangle':
            pts = self.get_polygon_points(cx, cy, 3, self.size, self.angle)
            if len(pts) >= 3:
                pygame.draw.polygon(sym_surf, color_a, pts, 2)
                inner = self.get_polygon_points(cx, cy, 3, self.size * 0.5, self.angle + math.pi)
                pygame.draw.polygon(sym_surf, color_a, inner, 1)

        elif self.shape == 'hexagon':
            pts = self.get_polygon_points(cx, cy, 6, self.size, self.angle)
            pygame.draw.polygon(sym_surf, color_a, pts, 2)
            inner = self.get_polygon_points(cx, cy, 6, self.size * 0.5, self.angle + math.pi / 6)
            pygame.draw.polygon(sym_surf, color_a, inner, 1)

        elif self.shape == 'fibonacci':
            # Nested rectangles rotated
            for i in range(4):
                s = self.size * (1 - i * 0.2)
                pts = [
                    (cx + s * math.cos(self.angle + i * 0.3),
                     cy + s * math.sin(self.angle + i * 0.3)),
                    (cx + s * math.cos(self.angle + i * 0.3 + math.pi / 2),
                     cy + s * math.sin(self.angle + i * 0.3 + math.pi / 2)),
                    (cx + s * math.cos(self.angle + i * 0.3 + math.pi),
                     cy + s * math.sin(self.angle + i * 0.3 + math.pi)),
                    (cx + s * math.cos(self.angle + i * 0.3 + 3 * math.pi / 2),
                     cy + s * math.sin(self.angle + i * 0.3 + 3 * math.pi / 2)),
                ]
                a_fade = max(0, alpha - i * 20)
                pygame.draw.polygon(sym_surf, (self.color[0], self.color[1], self.color[2], a_fade), pts, 1)

        elif self.shape == 'spiral_square':
            pts = self.get_polygon_points(cx, cy, 4, self.size, self.angle)
            pygame.draw.polygon(sym_surf, color_a, pts, 2)
            pts2 = self.get_polygon_points(cx, cy, 4, self.size * 0.6, self.angle + math.pi / 4)
            pygame.draw.polygon(sym_surf, color_a, pts2, 1)
            # Connect corners
            for i in range(4):
                pygame.draw.line(sym_surf, (self.color[0], self.color[1], self.color[2], alpha // 2),
                                 (int(pts[i][0]), int(pts[i][1])),
                                 (int(pts2[i][0]), int(pts2[i][1])), 1)

        elif self.shape == 'diamond':
            pts = self.get_polygon_points(cx, cy, 4, self.size, self.angle)
            pygame.draw.polygon(sym_surf, color_a, pts, 2)
            # Cross lines
            pygame.draw.line(sym_surf, color_a,
                             (int(pts[0][0]), int(pts[0][1])),
                             (int(pts[2][0]), int(pts[2][1])), 1)
            pygame.draw.line(sym_surf, color_a,
                             (int(pts[1][0]), int(pts[1][1])),
                             (int(pts[3][0]), int(pts[3][1])), 1)

        surface.blit(sym_surf, (int(self.x) - self.size * 2, int(self.y) - self.size * 2),
                     special_flags=pygame.BLEND_ADD)


# Mist particle
class MistParticle:
    def __init__(self):
        self.reset()
        self.x = random.randint(0, WIDTH)

    def reset(self):
        self.x = random.choice([-50, WIDTH + 50])
        self.y = HEIGHT - random.randint(20, 80)
        self.w = random.randint(150, 350)
        self.h = random.randint(20, 50)
        self.vx = random.uniform(0.2, 0.6) * (1 if self.x < 0 else -1)
        self.alpha = random.randint(15, 45)
        self.color = random.choice([
            (100, 150, 220), (150, 180, 240), (180, 200, 255)
        ])

    def update(self):
        self.x += self.vx
        if self.x > WIDTH + 200 or self.x < -200:
            self.reset()

    def draw(self, surface):
        mist_surf = pygame.Surface((self.w, self.h), pygame.SRCALPHA)
        for i in range(self.h):
            t = i / self.h
            a = int(self.alpha * math.sin(t * math.pi))
            pygame.draw.line(mist_surf, (self.color[0], self.color[1], self.color[2], a),
                             (0, i), (self.w, i))
        surface.blit(mist_surf, (int(self.x - self.w // 2), int(self.y)))


# Scanner beam
class ScannerBeam:
    def __init__(self):
        self.x = 0
        self.speed = 1.5
        self.width = 3
        self.alpha = 120
        self.y = HEIGHT - 100
        self.beam_height = 30

    def update(self):
        self.x += self.speed
        if self.x > WIDTH + 50:
            self.x = -50

    def draw(self, surface):
        beam_surf = pygame.Surface((self.width + 20, self.beam_height), pygame.SRCALPHA)
        for i in range(self.beam_height):
            t = i / self.beam_height
            a = int(self.alpha * math.sin(t * math.pi))
            pygame.draw.line(beam_surf, (0, 255, 100, a), (0, i), (self.width + 20, i))
        surface.blit(beam_surf, (int(self.x) - 10, self.y - self.beam_height))
        # Glow dot
        glow_surf = pygame.Surface((40, 40), pygame.SRCALPHA)
        pygame.draw.circle(glow_surf, (0, 255, 100, 60), (20, 20), 20)
        pygame.draw.circle(glow_surf, (0, 255, 100, 120), (20, 20), 8)
        surface.blit(glow_surf, (int(self.x) - 20, self.y - 20), special_flags=pygame.BLEND_ADD)


# Button
class CentralButton:
    def __init__(self):
        self.x = WIDTH // 2
        self.y = HEIGHT // 2 + 50
        self.radius = 60
        self.glow = 0
        self.glow_dir = 1
        self.pressed = False
        self.pulse_time = 0

    def update(self, time):
        self.pulse_time = time
        self.glow += 0.02 * self.glow_dir
        if self.glow > 1: self.glow_dir = -1
        if self.glow < 0: self.glow_dir = 1

    def is_clicked(self, pos):
        dx = pos[0] - self.x
        dy = pos[1] - self.y
        return math.sqrt(dx * dx + dy * dy) < self.radius

    def draw(self, surface):
        pulse = 0.5 + 0.5 * math.sin(self.pulse_time * 2)

        # Outer glow rings
        for r in range(5, 0, -1):
            glow_r = self.radius + r * 12 + pulse * 8
            alpha = int(30 * (1 - r / 5) * (0.5 + 0.5 * pulse))
            glow_surf = pygame.Surface((int(glow_r * 2 + 4), int(glow_r * 2 + 4)), pygame.SRCALPHA)
            pygame.draw.circle(glow_surf, (255, 200, 80, alpha),
                               (int(glow_r + 2), int(glow_r + 2)), int(glow_r))
            surface.blit(glow_surf, (int(self.x - glow_r - 2), int(self.y - glow_r - 2)),
                         special_flags=pygame.BLEND_ADD)

        # Main button
        btn_surf = pygame.Surface((self.radius * 2 + 4, self.radius * 2 + 4), pygame.SRCALPHA)
        # Gradient fill
        for r in range(self.radius, 0, -2):
            t = r / self.radius
            cr = int(255 * (1 - t * 0.3))
            cg = int(180 * (1 - t * 0.4) + 20 * pulse)
            cb = int(50 * (1 - t * 0.5))
            ca = int(200 + 55 * (1 - t))
            pygame.draw.circle(btn_surf, (cr, cg, cb, ca),
                               (self.radius + 2, self.radius + 2), r)
        surface.blit(btn_surf, (self.x - self.radius - 2, self.y - self.radius - 2))

        # Rim
        pygame.draw.circle(surface, (255, 230, 150), (self.x, self.y), self.radius, 3)
        pygame.draw.circle(surface, (255, 255, 200), (self.x, self.y), self.radius - 5, 1)

        # Center light
        center_surf = pygame.Surface((30, 30), pygame.SRCALPHA)
        pygame.draw.circle(center_surf, (255, 255, 220, int(180 + 75 * pulse)), (15, 15), 12)
        surface.blit(center_surf, (self.x - 15, self.y - 15), special_flags=pygame.BLEND_ADD)

        # Label
        font = pygame.font.SysFont('Arial', 14, bold=True)
        label = font.render("PLAY", True, (255, 240, 180))
        surface.blit(label, (self.x - label.get_width() // 2, self.y + self.radius + 10))


# Initialize objects
print("Initializing scene objects...")
stars = [Star() for _ in range(200)]
columns = []
col_spacing = WIDTH // 6
for i in range(5):
    cx = col_spacing + i * col_spacing
    columns.append(LightColumn(i, cx, NOTE_COLORS[i]))

alien_symbols = [AlienSymbol() for _ in range(8)]
mist_particles = [MistParticle() for _ in range(12)]
scanner = ScannerBeam()
button = CentralButton()

# Sequence state
playing = False
current_note = -1
note_timer = 0
note_index = 0
sequence_complete = False
sequence_delay = 0

# Title font
title_font = pygame.font.SysFont('Arial', 36, bold=True)
subtitle_font = pygame.font.SysFont('Arial', 18)
note_font = pygame.font.SysFont('Arial', 16, bold=True)


def play_note(idx):
    """Play a note and activate its column."""
    global current_note
    current_note = idx
    sounds[idx].play()
    columns[idx].activate()
    # Scatter nearby stars
    for star in stars:
        star.scatter(columns[idx].x, HEIGHT - 50, strength=4)
    print(f"  Playing note {idx + 1}/5: {NOTE_NAMES[idx]} ({NOTE_FREQS[idx]:.1f} Hz)")


# Background surface for stars (pre-render once, update each frame)
bg_surf = pygame.Surface((WIDTH, HEIGHT))
bg_surf.fill(BLACK)

time_elapsed = 0
running = True

print("Starting 'First Contact' experience...")
print("Click the central button to play the five-note motif!")

while running:
    dt = clock.tick(FPS) / 1000.0
    time_elapsed += dt

    # Events
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False
            elif event.key == pygame.K_SPACE and not playing:
                playing = True
                note_index = 0
                note_timer = 0
                sequence_complete = False
                print("\nStarting five-note sequence...")
                play_note(0)
                note_timer = NOTE_DURATIONS[0]
        elif event.type == pygame.MOUSEBUTTONDOWN:
            if event.button == 1 and not playing:
                if button.is_clicked(event.pos):
                    playing = True
                    note_index = 0
                    note_timer = 0
                    sequence_complete = False
                    print("\nStarting five-note sequence...")
                    play_note(0)
                    note_timer = NOTE_DURATIONS[0]

    # Update sequence
    if playing:
        note_timer -= dt
        if note_timer <= 0:
            # Deactivate current column
            if current_note >= 0:
                columns[current_note].active = False
            note_index += 1
            if note_index < 5:
                play_note(note_index)
                note_timer = NOTE_DURATIONS[note_index]
            else:
                playing = False
                current_note = -1
                sequence_complete = True
                sequence_delay = 3.0
                print("Sequence complete!")

    if sequence_complete:
        sequence_delay -= dt
        if sequence_delay <= 0:
            sequence_complete = False

    # Update objects
    for star in stars:
        star.update(time_elapsed)
    for col in columns:
        col.update()
    scanner.update()
    button.update(time_elapsed)

    # Update alien symbols
    for sym in alien_symbols:
        sym.update()
        if not sym.active:
            sym.reset()

    # Occasionally spawn new symbols
    if random.random() < 0.005:
        alien_symbols.append(AlienSymbol())
        if len(alien_symbols) > 15:
            alien_symbols.pop(0)

    for mist in mist_particles:
        mist.update()

    # Draw
    screen.fill(BLACK)

    # Draw stars
    for star in stars:
        star.draw(screen)

    # Draw mist
    for mist in mist_particles:
        mist.draw(screen)

    # Draw scanner
    scanner.draw(screen)

    # Horizon line
    horizon_y = HEIGHT - 90
    pygame.draw.line(screen, (20, 40, 60), (0, horizon_y), (WIDTH, horizon_y), 1)
    # Ground glow
    ground_surf = pygame.Surface((WIDTH, 90), pygame.SRCALPHA)
    for i in range(90):
        t = i / 90
        a = int(40 * (1 - t))
        pygame.draw.line(ground_surf, (20, 50, 80, a), (0, i), (WIDTH, i))
    screen.blit(ground_surf, (0, horizon_y))

    # Draw alien symbols
    for sym in alien_symbols:
        sym.draw(screen)

    # Draw columns
    for col in columns:
        col.draw(screen)

    # Draw column labels
    for i, col in enumerate(columns):
        if col.height > 10:
            label = note_font.render(NOTE_NAMES[i], True, NOTE_COLORS[i])
            screen.blit(label, (int(col.x) - label.get_width() // 2, HEIGHT - 85))

    # Draw button (only when not playing)
    if not playing:
        button.draw(screen)

    # Title
    title_surf = title_font.render("FIRST CONTACT", True, (200, 180, 120))
    # Add subtle glow
    glow_title = title_font.render("FIRST CONTACT", True, (100, 80, 40))
    screen.blit(glow_title, (WIDTH // 2 - title_surf.get_width() // 2 + 2, 32))
    screen.blit(title_surf, (WIDTH // 2 - title_surf.get_width() // 2, 30))

    subtitle_text = "The Five-Note Motif from Close Encounters of the Third Kind"
    sub_surf = subtitle_font.render(subtitle_text, True, (120, 110, 80))
    screen.blit(sub_surf, (WIDTH // 2 - sub_surf.get_width() // 2, 75))

    # Instructions
    if not playing:
        inst_font = pygame.font.SysFont('Arial', 15)
        inst = inst_font.render("Click the button or press SPACE to begin | ESC to quit", True, (80, 80, 100))
        screen.blit(inst, (WIDTH // 2 - inst.get_width() // 2, HEIGHT - 30))

    # Playing indicator
    if playing and current_note >= 0:
        note_display = note_font.render(
            f"Note {current_note + 1}/5: {NOTE_NAMES[current_note]}  ({NOTE_FREQS[current_note]:.0f} Hz)",
            True, NOTE_COLORS[current_note]
        )
        screen.blit(note_display, (WIDTH // 2 - note_display.get_width() // 2, HEIGHT - 30))

    # Sequence complete message
    if sequence_complete:
        complete_font = pygame.font.SysFont('Arial', 28, bold=True)
        msg = complete_font.render("They are here...", True, (180, 220, 255))
        alpha_val = min(255, int(255 * (sequence_delay / 3.0 if sequence_delay < 1.5 else 1.0)))
        msg.set_alpha(alpha_val)
        screen.blit(msg, (WIDTH // 2 - msg.get_width() // 2, HEIGHT // 2 - 20))

    pygame.display.flip()

pygame.quit()
sys.exit()