# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-22 22:44:17
# AutoCoder System - Automated Code Generation

import pygame
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

print("Starting Rotating Cube animation...")

# Define cube vertices
vertices = np.array([
    [-1, -1, -1],
    [ 1, -1, -1],
    [ 1,  1, -1],
    [-1,  1, -1],
    [-1, -1,  1],
    [ 1, -1,  1],
    [ 1,  1,  1],
    [-1,  1,  1],
], dtype=float)

# Define the 6 faces of the cube (indices into vertices)
faces = [
    [0, 1, 2, 3],  # bottom
    [4, 5, 6, 7],  # top
    [0, 1, 5, 4],  # front
    [2, 3, 7, 6],  # back
    [0, 3, 7, 4],  # left
    [1, 2, 6, 5],  # right
]

# Aesthetic face colors
face_colors = [
    '#FF6B6B',  # coral red
    '#4ECDC4',  # teal
    '#45B7D1',  # sky blue
    '#96CEB4',  # sage green
    '#FFEAA7',  # soft yellow
    '#DDA0DD',  # plum
]

def rotation_matrix(ax, ay, az):
    """Combined rotation matrix for x, y, z angles."""
    Rx = np.array([
        [1, 0, 0],
        [0, np.cos(ax), -np.sin(ax)],
        [0, np.sin(ax),  np.cos(ax)],
    ])
    Ry = np.array([
        [ np.cos(ay), 0, np.sin(ay)],
        [0, 1, 0],
        [-np.sin(ay), 0, np.cos(ay)],
    ])
    Rz = np.array([
        [np.cos(az), -np.sin(az), 0],
        [np.sin(az),  np.cos(az), 0],
        [0, 0, 1],
    ])
    return Rz @ Ry @ Rx

fig = plt.figure(figsize=(7, 7), facecolor='#1a1a2e')
ax = fig.add_subplot(111, projection='3d')
ax.set_facecolor('#1a1a2e')
fig.patch.set_facecolor('#1a1a2e')

# Remove axis panes and grid for clean look
ax.xaxis.pane.fill = False
ax.yaxis.pane.fill = False
ax.zaxis.pane.fill = False
ax.xaxis.pane.set_edgecolor('none')
ax.yaxis.pane.set_edgecolor('none')
ax.zaxis.pane.set_edgecolor('none')
ax.grid(False)
ax.set_axis_off()

ax.set_xlim([-2, 2])
ax.set_ylim([-2, 2])
ax.set_zlim([-2, 2])

plt.suptitle("Rotating Cube", y=0.98, color='white', fontsize=16, fontweight='bold', fontfamily='monospace')

poly_collection = None

def init():
    return []

def update(frame):
    global poly_collection
    if poly_collection is not None:
        try:
            poly_collection.remove()
        except Exception:
            pass

    angle_x = frame * 0.03
    angle_y = frame * 0.05
    angle_z = frame * 0.02

    R = rotation_matrix(angle_x, angle_y, angle_z)
    rotated = (R @ vertices.T).T

    face_verts = [[rotated[i] for i in face] for face in faces]

    # Compute face normals for shading
    alphas = []
    for face in faces:
        v0 = rotated[face[0]]
        v1 = rotated[face[1]]
        v2 = rotated[face[2]]
        normal = np.cross(v1 - v0, v2 - v0)
        norm_len = np.linalg.norm(normal)
        if norm_len > 1e-9:
            normal = normal / norm_len
        light = np.array([0.5, 0.5, 1.0])
        light = light / np.linalg.norm(light)
        shade = np.dot(normal, light)
        alphas.append(0.55 + 0.4 * max(shade, 0))

    # Apply per-face shading with color
    colored_faces = []
    for i, color in enumerate(face_colors):
        r, g, b = plt.matplotlib.colors.to_rgb(color)
        shade = alphas[i]
        colored_faces.append((r * shade, g * shade, b * shade, 0.85))

    poly_collection = Poly3DCollection(
        face_verts,
        facecolors=colored_faces,
        edgecolors='white',
        linewidths=0.8,
    )

    ax.add_collection3d(poly_collection)

    return [poly_collection]

print("Setting up FuncAnimation...")

ani = animation.FuncAnimation(
    fig,
    update,
    frames=360,
    init_func=init,
    interval=30,
    blit=False,
)

plt.tight_layout()
print("Displaying animation window. Close the window to exit.")
plt.show()
print("Animation complete.")
