# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-10 22:15:22
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
import numpy as np

fig = plt.figure(figsize=(18, 22), facecolor='#0d1117')
ax = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
ax.axis('off')
ax.set_facecolor('#0d1117')

# Title
ax.text(0.5, 0.965, r'$\mathbf{Common\ Fourier\ Transform\ Pairs}$',
        ha='center', va='center', fontsize=22, color='#e6edf3',
        fontweight='bold', transform=ax.transAxes)

ax.text(0.5, 0.945,
        r'$\hat{f}(\omega) = \int_{-\infty}^{\infty} f(t)\, e^{-i\omega t}\, dt$',
        ha='center', va='center', fontsize=15, color='#79c0ff',
        transform=ax.transAxes)

# ── helper ──────────────────────────────────────────────────────────────────
def draw_table(ax, title, col_headers, rows, y_top, col_widths,
               header_color='#1f6feb', row_colors=('#161b22', '#0d1117'),
               title_color='#f0883e'):

    x_start = 0.03
    row_h   = 0.032
    hdr_h   = 0.034
    title_h = 0.030

    # Section title bar
    rect = FancyBboxPatch((x_start, y_top - title_h),
                          0.94, title_h,
                          boxstyle="round,pad=0.003",
                          facecolor='#21262d', edgecolor=title_color,
                          linewidth=1.5, transform=ax.transAxes, zorder=2)
    ax.add_patch(rect)
    ax.text(x_start + 0.01, y_top - title_h / 2, title,
            ha='left', va='center', fontsize=13,
            color=title_color, fontweight='bold', transform=ax.transAxes, zorder=3)

    y_cur = y_top - title_h

    # Column header row
    x_cur = x_start
    rect = FancyBboxPatch((x_start, y_cur - hdr_h),
                          0.94, hdr_h,
                          boxstyle="round,pad=0.002",
                          facecolor=header_color, edgecolor='#30363d',
                          linewidth=0.8, transform=ax.transAxes, zorder=2)
    ax.add_patch(rect)
    for i, (hdr, w) in enumerate(zip(col_headers, col_widths)):
        ax.text(x_cur + w / 2, y_cur - hdr_h / 2, hdr,
                ha='center', va='center', fontsize=11,
                color='white', fontweight='bold',
                transform=ax.transAxes, zorder=3)
        x_cur += w
    y_cur -= hdr_h

    # Data rows
    for r_idx, row in enumerate(rows):
        bg = row_colors[r_idx % 2]
        rect = FancyBboxPatch((x_start, y_cur - row_h),
                              0.94, row_h,
                              boxstyle="round,pad=0.001",
                              facecolor=bg, edgecolor='#21262d',
                              linewidth=0.5, transform=ax.transAxes, zorder=2)
        ax.add_patch(rect)
        x_cur = x_start
        for cell, w in zip(row, col_widths):
            ax.text(x_cur + w / 2, y_cur - row_h / 2, cell,
                    ha='center', va='center', fontsize=10.5,
                    color='#e6edf3', transform=ax.transAxes, zorder=3)
            x_cur += w
        y_cur -= row_h

    return y_cur  # bottom of this table

# ── Table 1 : Basic Functions ────────────────────────────────────────────────
basic_rows = [
    (r'$\delta(t)$',                    r'$1$'),
    (r'$1$',                            r'$2\pi\,\delta(\omega)$'),
    (r'$e^{i\omega_0 t}$',              r'$2\pi\,\delta(\omega - \omega_0)$'),
    (r'$\cos(\omega_0 t)$',             r'$\pi[\delta(\omega-\omega_0)+\delta(\omega+\omega_0)]$'),
    (r'$\sin(\omega_0 t)$',             r'$-i\pi[\delta(\omega-\omega_0)-\delta(\omega+\omega_0)]$'),
]

y = 0.920
col_w = [0.47, 0.47]
y = draw_table(ax, 'Basic Functions',
               [r'$f(t)$', r'$\hat{f}(\omega)$'],
               basic_rows, y, col_w,
               title_color='#f0883e')

y -= 0.012

# ── Table 2 : Exponential & Gaussian ────────────────────────────────────────
exp_rows = [
    (r'$e^{-at}u(t),\quad a>0$',   r'$\dfrac{1}{a + i\omega}$'),
    (r'$e^{-a|t|},\quad a>0$',     r'$\dfrac{2a}{a^2+\omega^2}$'),
    (r'$e^{-at^2},\quad a>0$',     r'$\sqrt{\dfrac{\pi}{a}}\,e^{-\omega^2/4a}$'),
]

y = draw_table(ax, 'Exponential & Gaussian',
               [r'$f(t)$', r'$\hat{f}(\omega)$'],
               exp_rows, y, col_w,
               title_color='#79c0ff')

# Gaussian note
y -= 0.005
ax.text(0.5, y - 0.013,
        r'$\star$ The Gaussian is self-dual: it is its own Fourier transform',
        ha='center', va='center', fontsize=9.5, color='#8b949e',
        style='italic', transform=ax.transAxes, zorder=3)
y -= 0.030

# ── Table 3 : Step & Rectangle ───────────────────────────────────────────────
step_rows = [
    (r'$u(t)$  (unit step)',
     r'$\pi\,\delta(\omega) + \dfrac{1}{i\omega}$'),
    (r'$\mathrm{rect}(t/\tau)$',
     r'$\tau\,\mathrm{sinc}\!\left(\dfrac{\omega\tau}{2\pi}\right)$'),
    (r'$\mathrm{sinc}(Wt)$',
     r'$\dfrac{1}{W}\,\mathrm{rect}\!\left(\dfrac{\omega}{2\pi W}\right)$'),
]

y = draw_table(ax, 'Step & Rectangle Functions',
               [r'$f(t)$', r'$\hat{f}(\omega)$'],
               step_rows, y, col_w,
               title_color='#56d364')

y -= 0.018

# ── Table 4 : Properties (3 columns) ────────────────────────────────────────
prop_rows = [
    ('Linearity',          r'$af(t)+bg(t)$',          r'$a\hat{f}+b\hat{g}$'),
    ('Time shift',         r'$f(t-t_0)$',             r'$e^{-i\omega t_0}\hat{f}(\omega)$'),
    ('Frequency shift',    r'$e^{i\omega_0 t}f(t)$',  r'$\hat{f}(\omega-\omega_0)$'),
    ('Scaling',            r'$f(at)$',                r'$\frac{1}{|a|}\hat{f}\!\left(\frac{\omega}{a}\right)$'),
    ('Differentiation',    r'$f^{\prime}(t)$',        r'$i\omega\,\hat{f}(\omega)$'),
    ('Convolution',        r'$f * g$',                r'$\hat{f}\cdot\hat{g}$'),
    ("Parseval's theorem", r'$\int|f|^2\,dt$',        r'$\frac{1}{2\pi}\int|\hat{f}|^2\,d\omega$'),
]

col_w3 = [0.28, 0.33, 0.33]
y = draw_table(ax, 'Useful Properties',
               ['Property', r'$f(t)$  (time domain)', r'$\hat{f}(\omega)$  (frequency domain)'],
               prop_rows, y, col_w3,
               title_color='#d2a8ff')

y -= 0.018

# ── Footer note ──────────────────────────────────────────────────────────────
ax.text(0.5, y - 0.010,
        r'Tip: conventions vary — some texts use $e^{-2\pi i\xi t}$ '
        r'or a symmetric $\frac{1}{\sqrt{2\pi}}$ factor.',
        ha='center', va='center', fontsize=9.5, color='#8b949e',
        style='italic', transform=ax.transAxes, zorder=3)

plt.subplots_adjust(left=0, right=1, top=1, bottom=0)
plt.savefig('fourier_transforms.png', dpi=150, bbox_inches='tight',
            facecolor='#0d1117')
print("Saved fourier_transforms.png")
plt.show()
print("Done.")