# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-13 08:04:22
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyArrowPatch

# ── parameters ────────────────────────────────────────────────────────────────
L        = np.pi          # half-period
x        = np.linspace(-L, L, 2000)
N_terms  = [1, 3, 5, 9, 19]   # number of harmonics to include
colors   = ['#e74c3c', '#e67e22', '#f1c40f', '#2ecc71', '#3498db']

# ── true square wave ──────────────────────────────────────────────────────────
def square_wave(x):
    return np.where(np.sin(x) >= 0, 1.0, -1.0)

# ── partial Fourier sum for square wave ───────────────────────────────────────
def fourier_square(x, N):
    """Sum of first N odd harmonics: (4/pi) * sum_{k=0}^{N-1} sin((2k+1)x)/(2k+1)"""
    result = np.zeros_like(x, dtype=float)
    for k in range(N):
        n = 2*k + 1
        result += np.sin(n * x) / n
    return (4 / np.pi) * result

# ── individual sine components (first few) ────────────────────────────────────
def sine_component(x, k):
    n = 2*k + 1
    return (4 / np.pi) * np.sin(n * x) / n

# ══════════════════════════════════════════════════════════════════════════════
# FIGURE 1 — Convergence of Fourier Series
# ══════════════════════════════════════════════════════════════════════════════
fig1, axes = plt.subplots(len(N_terms), 1, figsize=(12, 14), sharex=True)
fig1.patch.set_facecolor('#0d1117')

sq = square_wave(x)

for ax, N, col in zip(axes, N_terms, colors):
    ax.set_facecolor('#161b22')
    approx = fourier_square(x, N)
    ax.plot(x, sq,     color='#ffffff', lw=1.2, alpha=0.35, ls='--', label=r'$f(x)$ exact')
    ax.plot(x, approx, color=col,       lw=2.0,
            label=r'$N=' + str(N) + r'$ term' + ('' if N == 1 else 's'))
    ax.set_ylim(-1.6, 1.6)
    ax.set_yticks([-1, 0, 1])
    ax.tick_params(colors='#aaaaaa', labelsize=9)
    for spine in ax.spines.values():
        spine.set_edgecolor('#333333')
    ax.legend(loc='upper right', fontsize=9,
              facecolor='#0d1117', edgecolor='#444444', labelcolor='white')
    ax.axhline(0, color='#444444', lw=0.8)
    ax.set_ylabel(r'$f(x)$', color='#aaaaaa', fontsize=9)

axes[-1].set_xlabel(r'$x$', color='#cccccc', fontsize=12)
axes[-1].set_xticks([-np.pi, -np.pi/2, 0, np.pi/2, np.pi])
axes[-1].set_xticklabels([r'$-\pi$', r'$-\pi/2$', r'$0$', r'$\pi/2$', r'$\pi$'],
                          color='#cccccc', fontsize=10)

fig1.suptitle(r'Fourier Series Approximation of a Square Wave'
              '\n'
              r'$f(x) = \frac{4}{\pi}\sum_{k=0}^{\infty}'
              r'\frac{\sin\!\left((2k+1)x\right)}{2k+1}$',
              color='white', fontsize=14, y=0.995)

plt.subplots_adjust(left=0.08, right=0.97, top=0.93, bottom=0.06, hspace=0.18)
plt.savefig('fourier_convergence.png', dpi=150, bbox_inches='tight',
            facecolor=fig1.get_facecolor())
print("Figure 1 saved: fourier_convergence.png")

# ══════════════════════════════════════════════════════════════════════════════
# FIGURE 2 — Individual Harmonic Components + Their Sum
# ══════════════════════════════════════════════════════════════════════════════
n_comp = 5   # show first 5 odd harmonics
comp_colors = ['#e74c3c','#e67e22','#f1c40f','#2ecc71','#3498db']

fig2 = plt.figure(figsize=(13, 10))
fig2.patch.set_facecolor('#0d1117')
gs = gridspec.GridSpec(n_comp + 1, 1, hspace=0.08,
                       left=0.09, right=0.97, top=0.93, bottom=0.06)

# individual components
for i in range(n_comp):
    ax = fig2.add_subplot(gs[i])
    ax.set_facecolor('#161b22')
    comp = sine_component(x, i)
    n    = 2*i + 1
    ax.plot(x, comp, color=comp_colors[i], lw=1.8)
    ax.fill_between(x, comp, alpha=0.18, color=comp_colors[i])
    ax.set_ylim(-1.4, 1.4)
    ax.set_yticks([])
    ax.set_xticks([])
    for spine in ax.spines.values():
        spine.set_edgecolor('#333333')
    ax.axhline(0, color='#444444', lw=0.7)
    lbl = (r'$\frac{4}{\pi}\cdot\frac{\sin(' + str(n) + r'x)}{' + str(n) + r'}$')
    ax.text(0.01, 0.72, lbl, transform=ax.transAxes,
            color=comp_colors[i], fontsize=10, va='top')

# sum panel
ax_sum = fig2.add_subplot(gs[n_comp])
ax_sum.set_facecolor('#161b22')
ax_sum.plot(x, square_wave(x), color='white', lw=1.2, alpha=0.4,
            ls='--', label=r'$f(x)$ exact')
ax_sum.plot(x, fourier_square(x, n_comp), color='#9b59b6', lw=2.2,
            label=r'Sum of first $' + str(n_comp) + r'$ odd harmonics')
ax_sum.set_ylim(-1.6, 1.6)
ax_sum.set_yticks([-1, 0, 1])
ax_sum.tick_params(colors='#aaaaaa', labelsize=9)
ax_sum.set_xticks([-np.pi, -np.pi/2, 0, np.pi/2, np.pi])
ax_sum.set_xticklabels([r'$-\pi$', r'$-\pi/2$', r'$0$', r'$\pi/2$', r'$\pi$'],
                        color='#cccccc', fontsize=10)
ax_sum.axhline(0, color='#444444', lw=0.8)
for spine in ax_sum.spines.values():
    spine.set_edgecolor('#333333')
ax_sum.legend(loc='upper right', fontsize=9,
              facecolor='#0d1117', edgecolor='#444444', labelcolor='white')
ax_sum.set_xlabel(r'$x$', color='#cccccc', fontsize=12)

fig2.suptitle(r'Harmonic Decomposition of the Square Wave',
              color='white', fontsize=14)

plt.savefig('fourier_harmonics.png', dpi=150, bbox_inches='tight',
            facecolor=fig2.get_facecolor())
print("Figure 2 saved: fourier_harmonics.png")

# ══════════════════════════════════════════════════════════════════════════════
# FIGURE 3 — Frequency (Amplitude) Spectrum
# ══════════════════════════════════════════════════════════════════════════════
fig3, ax3 = plt.subplots(figsize=(11, 5))
fig3.patch.set_facecolor('#0d1117')
ax3.set_facecolor('#161b22')

max_harm = 25
harmonics = np.arange(1, max_harm + 1, 2)          # odd harmonics only
amplitudes = 4 / (np.pi * harmonics)

bars = ax3.bar(harmonics, amplitudes, width=0.6,
               color=[plt.cm.plasma(a / amplitudes.max()) for a in amplitudes],
               edgecolor='#333333', linewidth=0.6)

# label each bar
for h, a in zip(harmonics, amplitudes):
    ax3.text(h, a + 0.005, r'$\frac{4}{' + str(h) + r'\pi}$',
             ha='center', va='bottom', color='#cccccc', fontsize=7)

ax3.set_xlabel(r'Harmonic number $n$  (odd only)', color='#cccccc', fontsize=12)
ax3.set_ylabel(r'Amplitude $\frac{4}{n\pi}$',      color='#cccccc', fontsize=12)
ax3.set_title(r'Frequency Spectrum of the Square Wave'
              '\n'
              r'$b_n = \frac{4}{n\pi}$ for odd $n$,  $b_n = 0$ for even $n$',
              color='white', fontsize=13)
ax3.tick_params(colors='#aaaaaa')
ax3.set_xticks(harmonics)
ax3.set_xticklabels([str(h) for h in harmonics], color='#cccccc', fontsize=9)
for spine in ax3.spines.values():
    spine.set_edgecolor('#444444')
ax3.set_xlim(0, max_harm + 1)
ax3.set_ylim(0, amplitudes.max() * 1.25)

plt.subplots_adjust(left=0.09, right=0.97, top=0.88, bottom=0.12)
plt.savefig('fourier_spectrum.png', dpi=150, bbox_inches='tight',
            facecolor=fig3.get_facecolor())
print("Figure 3 saved: fourier_spectrum.png")

# ══════════════════════════════════════════════════════════════════════════════
# FIGURE 4 — Gibbs Phenomenon close-up
# ══════════════════════════════════════════════════════════════════════════════
fig4, (ax4a, ax4b) = plt.subplots(1, 2, figsize=(13, 5))
fig4.patch.set_facecolor('#0d1117')

x_zoom = np.linspace(0, np.pi * 0.35, 3000)

for ax, N_list, title in [
    (ax4a, [5, 15, 51],   r'Convergence near discontinuity'),
    (ax4b, [51, 101, 201], r'Gibbs overshoot  $\approx 9\%$  persists'),
]:
    ax.set_facecolor('#161b22')
    ax.axhline(1.0,  color='white', lw=1.0, alpha=0.4, ls='--')
    ax.axhline(1.09, color='#e74c3c', lw=0.8, alpha=0.6, ls=':')
    cols_g = ['#3498db', '#2ecc71', '#e74c3c']
    for N_g, cg in zip(N_list, cols_g):
        ax.plot(x_zoom, fourier_square(x_zoom, N_g), color=cg, lw=1.6,
                label=r'$N=' + str(2*N_g - 1) + r'$')
    ax.set_ylim(0.7, 1.25)
    ax.set_xlim(0, x_zoom[-1])
    ax.set_xlabel(r'$x$', color='#cccccc', fontsize=11)
    ax.set_ylabel(r'$f_N(x)$', color='#cccccc', fontsize=11)
    ax.set_title(title, color='white', fontsize=11)
    ax.tick_params(colors='#aaaaaa')
    for spine in ax.spines.values():
        spine.set_edgecolor('#444444')
    ax.legend(fontsize=9, facecolor='#0d1117',
              edgecolor='#444444', labelcolor='white')
    ax.text(0.55, 0.92, r'$\approx 9\%$ overshoot',
            transform=ax.transAxes, color='#e74c3c', fontsize=9)

fig4.suptitle(r'Gibbs Phenomenon — overshoot near the discontinuity',
              color='white', fontsize=13)
plt.subplots_adjust(left=0.07, right=0.97, top=0.88, bottom=0.12, wspace=0.28)
plt.savefig('fourier_gibbs.png', dpi=150, bbox_inches='tight',
            facecolor=fig4.get_facecolor())
print("Figure 4 saved: fourier_gibbs.png")

# ── show all figures ──────────────────────────────────────────────────────────
plt.show()
print("\nAll four Fourier-series illustrations displayed successfully.")