# Generated: 2026-04-04 08:37:26
# ============================================================

# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-04-04 08:36:04
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyArrowPatch
from matplotlib.gridspec import GridSpec

# Physical constants (SI unless noted)
k_B   = 1.380649e-23      # J/K
eV    = 1.602176634e-19   # J per eV
keV   = 1e3 * eV
MeV   = 1e6 * eV
hbar  = 1.054571817e-34   # J s
m_p   = 1.67262192e-27    # kg
eps0  = 8.854187817e-12   # F/m
e_ch  = 1.602176634e-19   # C

# D-T specific
m_D   = 2.014 * m_p
m_T   = 3.016 * m_p
mu    = (m_D * m_T) / (m_D + m_T)
Z1, Z2 = 1, 1

# D-T fusion energy release: 17.6 MeV per reaction
E_fusion = 17.6 * MeV

# Gamow tunnelling exponent
def gamow_factor(E_J):
    b = np.pi * Z1 * Z2 * e_ch**2 * np.sqrt(2 * mu) / (hbar * np.sqrt(eV))
    E_eV = E_J / eV
    return np.exp(-b / np.sqrt(E_eV))

# Bosch-Hale parameterisation of D-T reactivity in cm^3/s
def DT_reactivity_cm3s(T_keV):
    T = np.asarray(T_keV, dtype=float)
    BG    = 34.3827
    mrc2  = 1124656.0
    C1    =  1.17302e-9
    C2    =  1.51361e-2
    C3    =  7.51886e-2
    C4    =  4.60643e-3
    C5    =  1.35000e-2
    C6    = -1.06750e-4
    C7    =  1.36600e-5

    theta = T / (1.0 - T * (C2 + T * (C4 + T * C6)) /
                         (1.0 + T * (C3 + T * (C5 + T * C7))))
    xi    = (BG**2 / (4.0 * theta))**(1.0/3.0)
    sv    = C1 * theta * np.sqrt(xi / (mrc2 * T**3)) * np.exp(-3.0 * xi)
    return sv

# Q factor (energy gain)
def Q_factor(T_keV, n_tau=1e20):
    T  = np.asarray(T_keV, dtype=float)
    sv = DT_reactivity_cm3s(T) * 1e-6
    T_J = T * keV
    Q   = (n_tau * sv * E_fusion) / (4.0 * k_B * T_J)
    return Q

# Tunnelling probability vs energy in keV
def tunnelling_prob(E_keV):
    E_J = np.asarray(E_keV, dtype=float) * keV
    return gamow_factor(E_J)

# Approximate D-T cross section in barns
def DT_cross_section_barn(E_keV):
    E = np.asarray(E_keV, dtype=float)
    S0 = 6.27e4
    S  = S0 / (1.0 + ((E - 64.0)/40.0)**2)
    BG  = 34.3827
    eta2pi = np.pi * BG / np.sqrt(E)
    sigma  = (S / E) * np.exp(-eta2pi)
    return sigma

# Temperature and energy arrays
T_arr   = np.linspace(1, 100, 500)
T_arr2  = np.linspace(1, 200, 800)
E_arr   = np.linspace(1, 300, 600)

sv_arr  = DT_reactivity_cm3s(T_arr)
Q_arr   = Q_factor(T_arr2, n_tau=1e20)
Q_arr2  = Q_factor(T_arr2, n_tau=3e20)
cs_arr  = DT_cross_section_barn(E_arr)
tun_arr = tunnelling_prob(E_arr)

# Figure layout
fig = plt.figure(figsize=(16, 13))
gs  = GridSpec(2, 2, figure=fig, hspace=0.42, wspace=0.35)

ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[0, 1])
ax3 = fig.add_subplot(gs[1, 0])
ax4 = fig.add_subplot(gs[1, 1])

fig.suptitle("D-T Nuclear Fusion Simulation - Plasma Physics", fontsize=15, fontweight='bold', y=0.98)

# Plot 1: Reaction rate <sigma*v> vs Temperature
ax1.semilogy(T_arr, sv_arr, color='orangered', lw=2.5, label=r'$\langle\sigma v\rangle$ D-T')
ax1.axvline(10, color='gold', ls='--', lw=1.5, label='Sun core (~10 keV)')
ax1.axvline(64, color='cyan', ls='--', lw=1.5, label='D-T peak (~64 keV)')
ax1.axhline(3e-16, color='gray', ls=':', lw=1.2, label=r'Ignition threshold ~$3\times10^{-16}$')
ax1.fill_between(T_arr, 3e-16, sv_arr,
                 where=(sv_arr >= 3e-16), alpha=0.18, color='lime', label='Ignition region')
ax1.set_xlabel('Plasma Temperature (keV)', fontsize=11)
ax1.set_ylabel(r'$\langle\sigma v\rangle$ (cm$^3$ s$^{-1}$)', fontsize=11)
ax1.set_title('Maxwellian-Averaged Reactivity vs Temperature', fontsize=11, fontweight='bold')
ax1.legend(fontsize=8, loc='lower right')
ax1.set_xlim(1, 100)
ax1.set_ylim(1e-22, 1e-14)
ax1.grid(True, which='both', alpha=0.3)
ax1.annotate('D-T peak\n~64 keV', xy=(64, 4e-16), xytext=(72, 2e-17),
             fontsize=8, color='cyan',
             arrowprops=dict(arrowstyle='->', color='cyan', lw=1.2))

# Plot 2: Q factor vs Temperature
ax2.semilogy(T_arr2, Q_arr,  color='dodgerblue', lw=2.5, label=r'$n\tau_E = 10^{20}$ m$^{-3}$s')
ax2.semilogy(T_arr2, Q_arr2, color='mediumorchid', lw=2.5, ls='--',
             label=r'$n\tau_E = 3\times10^{20}$ m$^{-3}$s')
ax2.axhline(1.0, color='lime', ls='-', lw=2, label='Q = 1 (breakeven)')
ax2.axhline(10.0, color='gold', ls='--', lw=1.8, label='Q = 10 (ignition goal)')
ax2.fill_between(T_arr2, 1, Q_arr2,
                 where=(Q_arr2 >= 1.0), alpha=0.12, color='lime')
ax2.set_xlabel('Plasma Temperature (keV)', fontsize=11)
ax2.set_ylabel('Energy Gain Q', fontsize=11)
ax2.set_title('Energy Gain Q vs Temperature\n(Lawson Criterion)', fontsize=11, fontweight='bold')
ax2.legend(fontsize=8, loc='upper right')
ax2.set_xlim(1, 200)
ax2.set_ylim(1e-3, 1e3)
ax2.grid(True, which='both', alpha=0.3)
idx_ig = np.where((Q_arr >= 1.0))[0]
if len(idx_ig):
    T_ig = T_arr2[idx_ig[0]]
    ax2.axvline(T_ig, color='lime', ls=':', lw=1.2)
    ax2.annotate(f'Breakeven\n~{T_ig:.0f} keV', xy=(T_ig, 1.0),
                 xytext=(T_ig + 10, 0.15), fontsize=8, color='lime',
                 arrowprops=dict(arrowstyle='->', color='lime', lw=1.0))

# Plot 3: D-T Fusion Cross Section vs Energy
ax3_r = ax3.twinx()
ax3.plot(E_arr, cs_arr, color='tomato', lw=2.5, label='Cross section (barn)')
ax3_r.plot(E_arr, tun_arr, color='cornflowerblue', lw=2, ls='--', label='Tunnelling prob.')
ax3.axvline(64, color='gold', ls='--', lw=1.5, label='Peak ~64 keV')
ax3.fill_between(E_arr, 0, cs_arr,
                 where=((E_arr >= 40) & (E_arr <= 100)), alpha=0.18, color='tomato')
ax3.set_xlabel('Centre-of-Mass Energy (keV)', fontsize=11)
ax3.set_ylabel('Cross Section (barn)', fontsize=11, color='tomato')
ax3_r.set_ylabel('Tunnelling Probability', fontsize=11, color='cornflowerblue')
ax3.set_title('D-T Fusion Cross Section &\nCoulomb Tunnelling Probability', fontsize=11, fontweight='bold')
ax3.set_xlim(1, 300)
ax3.set_ylim(0)
ax3_r.set_ylim(0, 1)
ax3.tick_params(axis='y', labelcolor='tomato')
ax3_r.tick_params(axis='y', labelcolor='cornflowerblue')
lines1, labs1 = ax3.get_legend_handles_labels()
lines2, labs2 = ax3_r.get_legend_handles_labels()
ax3.legend(lines1 + lines2, labs1 + labs2, fontsize=8, loc='upper right')
ax3.grid(True, alpha=0.3)
ax3.annotate('Resonance peak\n~64 keV', xy=(64, cs_arr[np.argmin(np.abs(E_arr-64))]),
             xytext=(110, 4.5), fontsize=8, color='gold',
             arrowprops=dict(arrowstyle='->', color='gold', lw=1.2))

# Plot 4: Coulomb Barrier & Tunnelling schematic
ax4.set_xlim(-5, 5)
ax4.set_ylim(-1.5, 12)
ax4.set_xlabel('Internuclear Separation (fm)', fontsize=11)
ax4.set_ylabel('Potential Energy (MeV)', fontsize=11)
ax4.set_title('Coulomb Barrier & Quantum Tunnelling\n(D-T Reaction Schematic)', fontsize=11, fontweight='bold')

r_nuc = 1.0
r_pos = np.linspace(r_nuc, 5, 300)
r_neg = np.linspace(-5, -r_nuc, 300)
V_coulomb     = 1.44 / r_pos
V_coulomb_neg = 1.44 / np.abs(r_neg)

r_well_r = np.linspace(r_nuc, 1.5, 50)
r_well_l = np.linspace(-1.5, -r_nuc, 50)
V_well   = -1.0 * np.ones(50)

ax4.plot(r_pos, V_coulomb, color='orangered', lw=2.5, label='Coulomb barrier')
ax4.plot(r_neg, V_coulomb_neg, color='orangered', lw=2.5)
ax4.plot(r_well_r, V_well, color='steelblue', lw=2.5, label='Nuclear potential well')
ax4.plot(r_well_l, V_well, color='steelblue', lw=2.5)
ax4.plot([r_nuc, r_nuc], [-1, V_coulomb[0]], color='steelblue', lw=2.5)
ax4.plot([-r_nuc, -r_nuc], [-1, V_coulomb_neg[0]], color='steelblue', lw=2.5)
ax4.plot([1.5, 1.5], [-1, 0], color='steelblue', lw=2.5)
ax4.plot([-1.5, -1.5], [-1, 0], color='steelblue', lw=2.5)

E_thermal_MeV = 0.01
ax4.axhline(E_thermal_MeV, color='gold', ls='--', lw=1.8, label='Thermal energy ~10 keV')

E_gamow_MeV = 0.064
ax4.axhline(E_gamow_MeV, color='lime', ls=':', lw=1.8, label='Gamow peak ~64 keV')

ax4.annotate('', xy=(r_nuc + 0.05, E_thermal_MeV),
             xytext=(2.5, E_thermal_MeV),
             arrowprops=dict(arrowstyle='->', color='gold', lw=2.0,
                             connectionstyle='arc3,rad=0.0'))
ax4.text(1.6, E_thermal_MeV + 0.15, 'Quantum\ntunnelling', fontsize=8, color='gold')

ax4.text(0, -1.25, 'He-4 + n\n(17.6 MeV)', fontsize=8, color='cyan',
         ha='center', va='bottom',
         bbox=dict(boxstyle='round,pad=0.3', facecolor='navy', alpha=0.7, edgecolor='cyan'))

V_barrier = V_coulomb[0]
ax4.annotate(f'Barrier top\n~{V_barrier:.1f} MeV', xy=(r_nuc, V_barrier),
             xytext=(2.2, V_barrier + 1.5), fontsize=8, color='orangered',
             arrowprops=dict(arrowstyle='->', color='orangered', lw=1.2))

ax4.legend(fontsize=8, loc='upper right')
ax4.grid(True, alpha=0.3)
ax4.set_facecolor('#0d0d1a')
ax4.spines['bottom'].set_color('gray')
ax4.spines['left'].set_color('gray')

plt.tight_layout()
plt.savefig('dt_fusion_simulation.png', dpi=150, bbox_inches='tight',
            facecolor='#111111', edgecolor='none')
plt.show()
print("D-T Fusion simulation complete. Plot saved as 'dt_fusion_simulation.png'.")