# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-13 16:05:13
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyArrowPatch

# ── colour palette ──────────────────────────────────────────────────────────
BG      = '#0d1117'
PANEL   = '#161b22'
ACCENT1 = '#58a6ff'   # blue
ACCENT2 = '#f78166'   # red-orange
ACCENT3 = '#3fb950'   # green
ACCENT4 = '#d2a8ff'   # purple
GOLD    = '#e3b341'
WHITE   = '#e6edf3'
GREY    = '#8b949e'

plt.rcParams.update({
    'figure.facecolor': BG,
    'axes.facecolor':   PANEL,
    'text.color':       WHITE,
    'axes.labelcolor':  WHITE,
    'xtick.color':      GREY,
    'ytick.color':      GREY,
    'axes.edgecolor':   GREY,
    'grid.color':       '#21262d',
    'grid.linewidth':   0.6,
    'font.family':      'DejaVu Sans',
})

fig = plt.figure(figsize=(18, 14))
fig.patch.set_facecolor(BG)

gs = gridspec.GridSpec(3, 3, figure=fig,
                       hspace=0.55, wspace=0.40,
                       left=0.06, right=0.97,
                       top=0.93, bottom=0.05)

# ════════════════════════════════════════════════════════════════════════════
# TITLE
# ════════════════════════════════════════════════════════════════════════════
fig.text(0.5, 0.965, r'$\mathbf{The\ Hamiltonian\ —\ Mathematics\ Illustrated}$',
         ha='center', va='top', fontsize=22, color=GOLD, fontweight='bold')
fig.text(0.5, 0.945,
         r'$H = T + V \quad|\quad \hat{H}|\psi\rangle = E|\psi\rangle \quad|\quad '
         r'i\hbar\,\frac{\partial}{\partial t}|\psi\rangle = \hat{H}|\psi\rangle$',
         ha='center', va='top', fontsize=13, color=ACCENT1)

# ════════════════════════════════════════════════════════════════════════════
# 1. PARTICLE IN A BOX — wave-functions
# ════════════════════════════════════════════════════════════════════════════
ax1 = fig.add_subplot(gs[0, 0])
L = 1.0
x = np.linspace(0, L, 500)
colors_pib = [ACCENT1, ACCENT2, ACCENT3, GOLD]
for n, c in zip(range(1, 5), colors_pib):
    psi = np.sqrt(2/L) * np.sin(n * np.pi * x / L)
    En  = n**2 * np.pi**2          # in units ℏ²/2mL²
    ax1.plot(x, psi + En*0.012, color=c, lw=1.8,
             label=r'$n=%d,\;E_%d$' % (n, n))

ax1.axvline(0, color=WHITE, lw=2)
ax1.axvline(L, color=WHITE, lw=2)
ax1.set_title(r'$\psi_n(x)=\sqrt{\frac{2}{L}}\sin\!\left(\frac{n\pi x}{L}\right)$',
              fontsize=10, color=WHITE, pad=6)
ax1.set_xlabel(r'$x/L$', fontsize=9)
ax1.set_ylabel(r'$\psi_n + \mathrm{offset}$', fontsize=9)
ax1.legend(fontsize=7, loc='upper right',
           facecolor=PANEL, edgecolor=GREY, labelcolor=WHITE)
ax1.set_xlim(-0.05, 1.05)
ax1.grid(True)
ax1.set_facecolor(PANEL)

# ════════════════════════════════════════════════════════════════════════════
# 2. PARTICLE IN A BOX — energy levels
# ════════════════════════════════════════════════════════════════════════════
ax2 = fig.add_subplot(gs[0, 1])
ns   = np.arange(1, 7)
E_n  = ns**2          # E_n ∝ n²  (units E_1)
for n, E, c in zip(ns, E_n, [ACCENT1,ACCENT2,ACCENT3,GOLD,ACCENT4,'#ff7b72']):
    ax2.hlines(E, 0.2, 0.8, colors=c, lw=2.5)
    ax2.text(0.85, E, r'$n=%d$' % n, va='center', fontsize=8, color=c)
    ax2.text(0.05, E, r'$%d E_1$' % E, va='center', fontsize=7, color=c)

ax2.set_xlim(0, 1.1)
ax2.set_ylim(0, 40)
ax2.set_title(r'$E_n = \frac{n^2\pi^2\hbar^2}{2mL^2}$', fontsize=10, color=WHITE, pad=6)
ax2.set_ylabel(r'$E_n / E_1$', fontsize=9)
ax2.set_xticks([])
ax2.grid(True, axis='y')
ax2.set_facecolor(PANEL)

# ════════════════════════════════════════════════════════════════════════════
# 3. QUANTUM HARMONIC OSCILLATOR — potential + levels
# ════════════════════════════════════════════════════════════════════════════
ax3 = fig.add_subplot(gs[0, 2])
x_qho = np.linspace(-4, 4, 600)
V_qho = 0.5 * x_qho**2          # ½mω²x² with m=ω=1
ax3.plot(x_qho, V_qho, color=ACCENT1, lw=2, label=r'$V=\frac{1}{2}m\omega^2 x^2$')

for n in range(6):
    E = n + 0.5                  # E_n = ℏω(n+½)
    x_cl = np.sqrt(2*E)          # classical turning points
    x_lev = np.linspace(-x_cl, x_cl, 300)
    # wave-function (Hermite-based approximation via numpy)
    from numpy.polynomial.hermite import hermval
    coeffs = [0]*n + [1]
    psi_raw = hermval(x_lev, coeffs) * np.exp(-x_lev**2/2)
    norm = np.sqrt(np.trapz(psi_raw**2, x_lev))
    if norm > 0:
        psi_norm = psi_raw / norm * 0.6
    else:
        psi_norm = psi_raw
    c = [ACCENT1,ACCENT2,ACCENT3,GOLD,ACCENT4,'#ff7b72'][n]
    ax3.hlines(E, -x_cl, x_cl, colors=c, lw=1.5, alpha=0.6)
    ax3.plot(x_lev, psi_norm + E, color=c, lw=1.2)
    ax3.text(3.5, E, r'$n\!=\!%d$' % n, va='center', fontsize=7, color=c)

ax3.set_xlim(-4.5, 4.5)
ax3.set_ylim(-0.2, 6.5)
ax3.set_title(r'$\hat{H}=-\frac{\hbar^2}{2m}\frac{d^2}{dx^2}+\frac{1}{2}m\omega^2 x^2$',
              fontsize=9, color=WHITE, pad=6)
ax3.set_xlabel(r'$x$', fontsize=9)
ax3.set_ylabel(r'$E\;[\hbar\omega]$', fontsize=9)
ax3.legend(fontsize=7, facecolor=PANEL, edgecolor=GREY, labelcolor=WHITE)
ax3.grid(True)
ax3.set_facecolor(PANEL)

# ════════════════════════════════════════════════════════════════════════════
# 4. CLASSICAL PHASE SPACE — Hamiltonian trajectories (H = p²/2m + ½kx²)
# ════════════════════════════════════════════════════════════════════════════
ax4 = fig.add_subplot(gs[1, 0])
theta = np.linspace(0, 2*np.pi, 400)
energies = [0.5, 1.0, 2.0, 3.5, 5.5]
cmap_e = [ACCENT1, ACCENT2, ACCENT3, GOLD, ACCENT4]
for E, c in zip(energies, cmap_e):
    x_ph = np.sqrt(2*E) * np.cos(theta)
    p_ph = np.sqrt(2*E) * np.sin(theta)
    ax4.plot(x_ph, p_ph, color=c, lw=1.8, label=r'$H=%.1f$' % E)

ax4.set_title(r'$H = \frac{p^2}{2m} + \frac{1}{2}kx^2$' + '\n' +
              r'$\mathrm{Phase\ Space\ Trajectories}$',
              fontsize=9, color=WHITE, pad=6)
ax4.set_xlabel(r'$x$', fontsize=9)
ax4.set_ylabel(r'$p$', fontsize=9)
ax4.legend(fontsize=6.5, facecolor=PANEL, edgecolor=GREY, labelcolor=WHITE,
           loc='upper right')
ax4.set_aspect('equal')
ax4.grid(True)
ax4.set_facecolor(PANEL)

# ════════════════════════════════════════════════════════════════════════════
# 5. TIME EVOLUTION — |ψ(t)|² for superposition of two eigenstates
# ════════════════════════════════════════════════════════════════════════════
ax5 = fig.add_subplot(gs[1, 1])
x_te = np.linspace(0, 1, 300)
t_vals = np.linspace(0, 2*np.pi, 200)
# |ψ⟩ = (|1⟩ + |2⟩)/√2
E1, E2 = 1.0, 4.0          # ∝ n²
prob_xt = np.zeros((len(t_vals), len(x_te)))
for i, t in enumerate(t_vals):
    psi1 = np.sqrt(2) * np.sin(1*np.pi*x_te) * np.exp(-1j*E1*t)
    psi2 = np.sqrt(2) * np.sin(2*np.pi*x_te) * np.exp(-1j*E2*t)
    psi  = (psi1 + psi2) / np.sqrt(2)
    prob_xt[i] = np.abs(psi)**2

im = ax5.imshow(prob_xt, aspect='auto', origin='lower',
                extent=[0, 1, 0, 2*np.pi],
                cmap='plasma', interpolation='bilinear')
plt.colorbar(im, ax=ax5, label=r'$|\psi|^2$', fraction=0.046, pad=0.04)
ax5.set_title(r'$|\psi(x,t)|^2,\;\psi=\frac{|\psi_1\rangle+|\psi_2\rangle}{\sqrt{2}}$',
              fontsize=9, color=WHITE, pad=6)
ax5.set_xlabel(r'$x/L$', fontsize=9)
ax5.set_ylabel(r'$t$', fontsize=9)
ax5.set_facecolor(PANEL)

# ════════════════════════════════════════════════════════════════════════════
# 6. EXPECTATION VALUE ⟨E⟩ and UNCERTAINTY ΔE
# ════════════════════════════════════════════════════════════════════════════
ax6 = fig.add_subplot(gs[1, 2])
ns_arr = np.arange(1, 9)
E_arr  = ns_arr**2          # PIB in units E_1
# Gaussian superposition weights
sigma_g = 2.0
n0      = 3.0
weights = np.exp(-(ns_arr - n0)**2 / (2*sigma_g**2))
weights /= weights.sum()

E_mean = np.sum(weights * E_arr)
E2_mean= np.sum(weights * E_arr**2)
dE     = np.sqrt(E2_mean - E_mean**2)

bars = ax6.bar(ns_arr, weights, color=ACCENT1, alpha=0.8, edgecolor=ACCENT1)
ax6.axvline(E_mean/E_arr[0]**0.5, color=GOLD, lw=2, linestyle='--',
            label=r'$\langle n\rangle \approx %.1f$' % (E_mean**0.5))
ax6.set_title(r'$c_n = e^{-(n-n_0)^2/2\sigma^2}$' + '\n' +
              r'$\langle E\rangle=%.2f E_1,\;\Delta E=%.2f E_1$' % (E_mean, dE),
              fontsize=9, color=WHITE, pad=6)
ax6.set_xlabel(r'$n$', fontsize=9)
ax6.set_ylabel(r'$|c_n|^2$', fontsize=9)
ax6.legend(fontsize=8, facecolor=PANEL, edgecolor=GREY, labelcolor=WHITE)
ax6.grid(True, axis='y')
ax6.set_facecolor(PANEL)

# ════════════════════════════════════════════════════════════════════════════
# 7. SCHRÖDINGER EQUATION — annotated diagram (text panel)
# ════════════════════════════════════════════════════════════════════════════
ax7 = fig.add_subplot(gs[2, :2])
ax7.set_facecolor('#0d1117')
ax7.axis('off')

# Main equation
ax7.text(0.5, 0.82,
         r'$i\hbar\,\frac{\partial}{\partial t}|\psi(t)\rangle = \hat{H}|\psi(t)\rangle$',
         ha='center', va='center', fontsize=18, color=GOLD,
         transform=ax7.transAxes)

# Annotations with arrows — using ax7.annotate
annotations = [
    (0.08, 0.82, r'$i\hbar\frac{\partial}{\partial t}$',
     r'$\mathrm{Time\ derivative}$' + '\n' + r'$\mathrm{(LHS)}$', 0.08, 0.35),
    (0.50, 0.82, r'$\hat{H}$',
     r'$\mathrm{Hamiltonian}$' + '\n' + r'$= \hat{T}+\hat{V}$', 0.50, 0.35),
    (0.72, 0.82, r'$|\psi\rangle$',
     r'$\mathrm{Quantum\ state}$' + '\n' + r'$\mathrm{(ket\ vector)}$', 0.72, 0.35),
]

for (xa, ya, label, desc, xd, yd) in annotations:
    ax7.annotate('', xy=(xd, yd+0.12), xycoords='axes fraction',
                 xytext=(xa, ya-0.08), textcoords='axes fraction',
                 arrowprops=dict(arrowstyle='->', color=GREY, lw=1.2))
    ax7.text(xd, yd, desc, ha='center', va='top', fontsize=8.5,
             color=GREY, transform=ax7.transAxes,
             bbox=dict(boxstyle='round,pad=0.3', facecolor=PANEL,
                       edgecolor=GREY, alpha=0.8))

# Solution note
ax7.text(0.5, 0.10,
         r'$\mathrm{Solution:}\quad |\psi(t)\rangle = e^{-i\hat{H}t/\hbar}|\psi(0)\rangle'
         r'\quad\Rightarrow\quad |\psi_n(t)\rangle = e^{-iE_n t/\hbar}|\psi_n(0)\rangle$',
         ha='center', va='center', fontsize=11, color=ACCENT3,
         transform=ax7.transAxes)

ax7.set_title(r'$\mathrm{Time-Dependent\ Schrodinger\ Equation}$',
              fontsize=11, color=WHITE, pad=4)

# ════════════════════════════════════════════════════════════════════════════
# 8. ENERGY EIGENVALUE SPECTRUM — H atom analogy (E ∝ -1/n²)
# ════════════════════════════════════════════════════════════════════════════
ax8 = fig.add_subplot(gs[2, 2])
ns_H = np.arange(1, 8)
E_H  = -13.6 / ns_H**2      # hydrogen-like in eV

for n, E, c in zip(ns_H, E_H,
                   [ACCENT2,ACCENT1,ACCENT3,GOLD,ACCENT4,'#ff7b72',GREY]):
    ax8.hlines(E, 0.1, 0.9, colors=c, lw=2.2)
    ax8.text(0.92, E, r'$n\!=\!%d$' % n, va='center', fontsize=7.5, color=c)
    ax8.text(0.02, E, r'$%.1f$' % E, va='center', fontsize=6.5, color=c)

# Ionisation limit
ax8.axhline(0, color=WHITE, lw=1, linestyle='--', alpha=0.5)
ax8.text(0.5, 0.3, r'$\mathrm{Ionisation}$', ha='center', fontsize=7,
         color=WHITE, alpha=0.6)

ax8.set_xlim(0, 1.1)
ax8.set_ylim(-15, 1.5)
ax8.set_title(r'$E_n = -\frac{13.6\,\mathrm{eV}}{n^2}$' + '\n' +
              r'$\mathrm{Hydrogen\ Spectrum}$',
              fontsize=9, color=WHITE, pad=6)
ax8.set_ylabel(r'$E\;[\mathrm{eV}]$', fontsize=9)
ax8.set_xticks([])
ax8.grid(True, axis='y')
ax8.set_facecolor(PANEL)

# ── save & show ─────────────────────────────────────────────────────────────
plt.savefig('hamiltonian_mathematics.png', dpi=150, bbox_inches='tight',
            facecolor=BG)
print("Figure saved as 'hamiltonian_mathematics.png'")
plt.show()
print("Done — Hamiltonian mathematics illustrated across 8 panels.")