# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-22 02:07:06
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap

# Compute the integral of sin^2(x)
# integral of sin^2(x) dx = x/2 - sin(2x)/4 + C
x = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
y_original = np.sin(x) ** 2
y_integral = x / 2 - np.sin(2 * x) / 4  # antiderivative (C=0)

# Aesthetic color palette
bg_color = "#0d0d1a"
color1 = "#e040fb"   # purple/magenta
color2 = "#00e5ff"   # cyan
color3 = "#ff6f00"   # amber
grid_color = "#1e1e3a"

fig, axes = plt.subplots(2, 1, figsize=(10, 12), facecolor=bg_color)

# Top panel: sin^2(x)
ax1 = axes[0]
ax1.set_facecolor(bg_color)

ax1.fill_between(x, y_original, alpha=0.25, color=color1)
ax1.plot(x, y_original, color=color1, linewidth=2.5, label=r"$f(x) = \sin^2(x)$")

ax1.axhline(0, color="white", linewidth=0.5, alpha=0.4)
ax1.axvline(0, color="white", linewidth=0.5, alpha=0.4)

ax1.set_title(r"Original Function:  $f(x) = \sin^2(x)$",
              color="white", fontsize=15, fontweight="bold", pad=12)
ax1.set_xlabel(r"$x$", color="white", fontsize=12)
ax1.set_ylabel(r"$\sin^2(x)$", color="white", fontsize=12)

ax1.tick_params(colors="white", labelsize=10)
for spine in ax1.spines.values():
    spine.set_edgecolor(grid_color)

ax1.set_xticks([-2*np.pi, -np.pi, 0, np.pi, 2*np.pi])
ax1.set_xticklabels([r"$-2\pi$", r"$-\pi$", r"$0$", r"$\pi$", r"$2\pi$"],
                    color="white", fontsize=11)
ax1.yaxis.label.set_color("white")
ax1.grid(True, color=grid_color, linewidth=0.8, linestyle="--", alpha=0.7)

legend1 = ax1.legend(facecolor="#1a1a2e", edgecolor=color1,
                     labelcolor="white", fontsize=12, loc="upper right")

# Bottom panel: antiderivative
ax2 = axes[1]
ax2.set_facecolor(bg_color)

ax2.fill_between(x, y_integral, alpha=0.20, color=color2)
ax2.plot(x, y_integral, color=color2, linewidth=2.5,
         label=r"$F(x) = \frac{x}{2} - \frac{\sin(2x)}{4} + C$")

# Overlay sin^2(x) faintly for reference
ax2.plot(x, y_original, color=color1, linewidth=1.0, alpha=0.35,
         linestyle="--", label=r"$\sin^2(x)$ (reference)")

ax2.axhline(0, color="white", linewidth=0.5, alpha=0.4)
ax2.axvline(0, color="white", linewidth=0.5, alpha=0.4)

ax2.set_title(r"Antiderivative:  $F(x) = \int \sin^2(x)\,dx = \frac{x}{2} - \frac{\sin(2x)}{4} + C$",
              color="white", fontsize=14, fontweight="bold", pad=12)
ax2.set_xlabel(r"$x$", color="white", fontsize=12)
ax2.set_ylabel(r"$F(x)$", color="white", fontsize=12)

ax2.tick_params(colors="white", labelsize=10)
for spine in ax2.spines.values():
    spine.set_edgecolor(grid_color)

ax2.set_xticks([-2*np.pi, -np.pi, 0, np.pi, 2*np.pi])
ax2.set_xticklabels([r"$-2\pi$", r"$-\pi$", r"$0$", r"$\pi$", r"$2\pi$"],
                    color="white", fontsize=11)
ax2.yaxis.label.set_color("white")
ax2.grid(True, color=grid_color, linewidth=0.8, linestyle="--", alpha=0.7)

legend2 = ax2.legend(facecolor="#1a1a2e", edgecolor=color2,
                     labelcolor="white", fontsize=11, loc="upper left")

# Main title
plt.suptitle(r"Integration of $\sin^2(x)$", y=0.98,
             color="white", fontsize=18, fontweight="bold",
             fontfamily="DejaVu Sans")

plt.tight_layout()
plt.savefig("integral_sin_squared_poster.png", dpi=150,
            bbox_inches="tight", facecolor=bg_color)
plt.show()

print("Plot saved as 'integral_sin_squared_poster.png'")
print(f"x range: [{x[0]:.4f}, {x[-1]:.4f}]")
print(f"sin^2(x) range: [{y_original.min():.4f}, {y_original.max():.4f}]")
print(f"Antiderivative range: [{y_integral.min():.4f}, {y_integral.max():.4f}]")
print("Rendering complete.")