# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-22 02:28:09
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
from matplotlib import gridspec
from matplotlib.colors import LinearSegmentedColormap
import math

# ── colour palette ──────────────────────────────────────────────────────────
BG      = "#0D0D1A"
GOLD    = "#FFD700"
CYAN    = "#00E5FF"
MAGENTA = "#FF4081"
GREEN   = "#69FF47"
WHITE   = "#F0F0F0"
PURPLE  = "#B388FF"
ORANGE  = "#FF9100"

plt.rcParams.update({
    "text.usetex": False,
    "font.family": "serif",
    "axes.facecolor": BG,
    "figure.facecolor": BG,
    "text.color": WHITE,
    "axes.labelcolor": WHITE,
    "xtick.color": WHITE,
    "ytick.color": WHITE,
    "axes.edgecolor": "#333355",
    "grid.color": "#222244",
    "grid.linestyle": "--",
    "grid.alpha": 0.4,
})

fig = plt.figure(figsize=(22, 28))
fig.patch.set_facecolor(BG)

gs_main = gridspec.GridSpec(
    5, 3,
    figure=fig,
    hspace=0.55,
    wspace=0.38,
)

# ════════════════════════════════════════════════════════════════════════════
# HEADER PANEL
# ════════════════════════════════════════════════════════════════════════════
ax_header = fig.add_subplot(gs_main[0, :])
ax_header.set_xlim(0, 1)
ax_header.set_ylim(0, 1)
ax_header.axis("off")

# gradient-like background rectangle
for gc in np.linspace(0, 1, 200):
    c = plt.cm.cool(gc * 0.5 + 0.1)
    ax_header.axvline(gc, color=c, alpha=0.08, linewidth=3)

fancy = FancyBboxPatch((0.01, 0.05), 0.98, 0.90,
                        boxstyle="round,pad=0.02",
                        linewidth=3, edgecolor=GOLD,
                        facecolor="#11112A", zorder=2)
ax_header.add_patch(fancy)

ax_header.text(0.5, 0.72, "The Joy of",
               ha="center", va="center", fontsize=34,
               color=CYAN, fontweight="bold",
               fontstyle="italic", zorder=3)

ax_header.text(0.5, 0.38, r"$\mathcal{L\!A\!T\!E\!X}$",
               ha="center", va="center", fontsize=72,
               color=GOLD, fontweight="bold", zorder=3)

ax_header.text(0.5, 0.10,
               r"Equations  $|$  Graphs  $|$  Beauty  $|$  Precision",
               ha="center", va="center", fontsize=16,
               color=PURPLE, fontstyle="italic", zorder=3)

# decorative rule lines
for y in [0.88, 0.12]:
    ax_header.plot([0.05, 0.95], [y, y], color=GOLD, lw=1.5,
                   alpha=0.6, zorder=3)

# ════════════════════════════════════════════════════════════════════════════
# ROW 1 – three plots
# ════════════════════════════════════════════════════════════════════════════

# ── 1A  Fourier Series ───────────────────────────────────────────────────
ax1 = fig.add_subplot(gs_main[1, 0])
x = np.linspace(-np.pi, np.pi, 1000)
colors_f = [CYAN, MAGENTA, GREEN, ORANGE, PURPLE]
labels_f = ["n=1", "n=3", "n=5", "n=7", "n=9"]
sq = np.zeros_like(x)
for k, n in enumerate([1, 3, 5, 7, 9]):
    term = (4 / (n * np.pi)) * np.sin(n * x)
    sq += term
    ax1.plot(x, term, color=colors_f[k], lw=1.2,
             alpha=0.7, label=labels_f[k])
ax1.plot(x, sq, color=GOLD, lw=2.5, label="Sum", zorder=5)
ax1.set_title("Fourier Series Approximation", color=GOLD,
               fontsize=12, pad=8)
ax1.set_xlabel(r"$x$")
ax1.set_ylabel(r"$f(x)$")
ax1.legend(fontsize=7, loc="upper right",
           facecolor="#11112A", edgecolor=GOLD, labelcolor=WHITE)
ax1.grid(True)

ax1.text(0.02, 0.05,
         r"$f(x)=\sum_{n\,\mathrm{odd}}\!\frac{4}{n\pi}\sin(nx)$",
         transform=ax1.transAxes, fontsize=9,
         color=CYAN, bbox=dict(facecolor="#11112A", edgecolor=CYAN,
                                boxstyle="round,pad=0.3", alpha=0.8))

# ── 1B  Gaussian / Normal Distribution ──────────────────────────────────
ax2 = fig.add_subplot(gs_main[1, 1])
x_g = np.linspace(-4, 4, 500)
params = [(0, 1, CYAN, r"$\mu=0,\,\sigma=1$"),
          (0, 0.5, MAGENTA, r"$\mu=0,\,\sigma=0.5$"),
          (1, 1.2, GREEN, r"$\mu=1,\,\sigma=1.2$")]
for mu, sig, col, lbl in params:
    y_g = (1 / (sig * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x_g - mu) / sig) ** 2)
    ax2.plot(x_g, y_g, color=col, lw=2, label=lbl)
    ax2.fill_between(x_g, y_g, alpha=0.12, color=col)

ax2.set_title("Gaussian Distributions", color=GOLD, fontsize=12, pad=8)
ax2.set_xlabel(r"$x$")
ax2.set_ylabel(r"$p(x)$")
ax2.legend(fontsize=8, facecolor="#11112A", edgecolor=GOLD, labelcolor=WHITE)
ax2.grid(True)
ax2.text(0.02, 0.88,
         r"$p(x)=\frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}$",
         transform=ax2.transAxes, fontsize=9, color=CYAN,
         bbox=dict(facecolor="#11112A", edgecolor=CYAN,
                   boxstyle="round,pad=0.3", alpha=0.8))

# ── 1C  Polar Rose ───────────────────────────────────────────────────────
ax3 = fig.add_subplot(gs_main[1, 2], projection="polar")
ax3.set_facecolor(BG)
theta = np.linspace(0, 2 * np.pi, 1000)
for k, (n, col) in enumerate([(3, CYAN), (5, MAGENTA), (7, GREEN)]):
    r = np.abs(np.cos(n * theta))
    ax3.plot(theta, r, color=col, lw=1.5, alpha=0.85,
             label=f"n={n}")
ax3.set_title(r"Polar Rose  $r=|\cos(n\theta)|$",
              color=GOLD, fontsize=12, pad=14)
ax3.tick_params(colors=WHITE, labelsize=7)
ax3.grid(color="#333355", linestyle="--", alpha=0.5)
ax3.legend(fontsize=8, loc="lower right",
           facecolor="#11112A", edgecolor=GOLD, labelcolor=WHITE)

# ════════════════════════════════════════════════════════════════════════════
# ROW 2 – three plots
# ════════════════════════════════════════════════════════════════════════════

# ── 2A  3-D Surface (Sinc) ───────────────────────────────────────────────
ax4 = fig.add_subplot(gs_main[2, 0], projection="3d")
ax4.set_facecolor(BG)
X3 = np.linspace(-6, 6, 80)
Y3 = np.linspace(-6, 6, 80)
X3, Y3 = np.meshgrid(X3, Y3)
R3 = np.sqrt(X3**2 + Y3**2) + 1e-9
Z3 = np.sin(R3) / R3
cmap_sinc = LinearSegmentedColormap.from_list(
    "sinc", [BG, PURPLE, CYAN, GOLD])
ax4.plot_surface(X3, Y3, Z3, cmap=cmap_sinc,
                 linewidth=0, antialiased=True, alpha=0.9)
ax4.set_title(r"Sinc Surface  $\frac{\sin r}{r}$",
              color=GOLD, fontsize=11, pad=6)
ax4.set_xlabel("x", color=WHITE, fontsize=8)
ax4.set_ylabel("y", color=WHITE, fontsize=8)
ax4.set_zlabel("z", color=WHITE, fontsize=8)
ax4.tick_params(colors=WHITE, labelsize=6)
ax4.xaxis.pane.fill = False
ax4.yaxis.pane.fill = False
ax4.zaxis.pane.fill = False

# ── 2B  Equations Showcase ───────────────────────────────────────────────
ax5 = fig.add_subplot(gs_main[2, 1])
ax5.set_xlim(0, 1)
ax5.set_ylim(0, 1)
ax5.axis("off")

fancy2 = FancyBboxPatch((0.02, 0.02), 0.96, 0.96,
                         boxstyle="round,pad=0.02",
                         linewidth=2, edgecolor=PURPLE,
                         facecolor="#0A0A1E")
ax5.add_patch(fancy2)

equations = [
    (r"$e^{i\pi}+1=0$",                    0.85, GOLD,    16),
    (r"$\nabla^2\phi = \rho/\varepsilon_0$", 0.70, CYAN,    13),
    (r"$E=mc^2$",                            0.56, MAGENTA, 16),
    (r"$\hat{H}\psi=E\psi$",                 0.42, GREEN,   14),
    (r"$F=G\frac{m_1 m_2}{r^2}$",            0.28, ORANGE,  13),
    (r"$\oint \mathbf{B}\cdot d\mathbf{l}=\mu_0 I$", 0.14, PURPLE, 12),
]
for eq, ypos, col, fs in equations:
    ax5.text(0.5, ypos, eq, ha="center", va="center",
             fontsize=fs, color=col)

ax5.set_title("Iconic Equations", color=GOLD, fontsize=12, pad=8)

# ── 2C  Mandelbrot-like iteration count ─────────────────────────────────
ax6 = fig.add_subplot(gs_main[2, 2])
nx, ny = 300, 300
x_m = np.linspace(-2.5, 1.0, nx)
y_m = np.linspace(-1.25, 1.25, ny)
C = x_m[np.newaxis, :] + 1j * y_m[:, np.newaxis]
Z = np.zeros_like(C)
M = np.zeros(C.shape, dtype=float)
for i in range(60):
    mask = np.abs(Z) <= 2
    Z[mask] = Z[mask] ** 2 + C[mask]
    M[mask] += 1
cmap_m = LinearSegmentedColormap.from_list(
    "mb", [BG, PURPLE, CYAN, GOLD, WHITE])
ax6.imshow(M, extent=[-2.5, 1.0, -1.25, 1.25],
           cmap=cmap_m, origin="lower", aspect="auto")
ax6.set_title("Mandelbrot Set", color=GOLD, fontsize=12, pad=8)
ax6.set_xlabel(r"$\mathrm{Re}(c)$")
ax6.set_ylabel(r"$\mathrm{Im}(c)$")
ax6.text(0.02, 0.05, r"$z_{n+1}=z_n^2+c$",
         transform=ax6.transAxes, fontsize=10, color=GOLD,
         bbox=dict(facecolor="#11112A", edgecolor=GOLD,
                   boxstyle="round,pad=0.3", alpha=0.8))

# ════════════════════════════════════════════════════════════════════════════
# ROW 3 – three plots
# ════════════════════════════════════════════════════════════════════════════

# ── 3A  Lissajous Curves ─────────────────────────────────────────────────
ax7 = fig.add_subplot(gs_main[3, 0])
t_l = np.linspace(0, 2 * np.pi, 2000)
liss_params = [(3, 2, 0,       CYAN),
               (5, 4, np.pi/4, MAGENTA),
               (7, 6, np.pi/6, GREEN)]
for a, b, delta, col in liss_params:
    xl = np.sin(a * t_l + delta)
    yl = np.sin(b * t_l)
    ax7.plot(xl, yl, color=col, lw=1.0, alpha=0.8)
ax7.set_title("Lissajous Curves", color=GOLD, fontsize=12, pad=8)
ax7.set_xlabel(r"$\sin(at+\delta)$")
ax7.set_ylabel(r"$\sin(bt)$")
ax7.grid(True)
ax7.text(0.02, 0.05,
         r"$x=\sin(at+\delta),\;y=\sin(bt)$",
         transform=ax7.transAxes, fontsize=8, color=CYAN,
         bbox=dict(facecolor="#11112A", edgecolor=CYAN,
                   boxstyle="round,pad=0.3", alpha=0.8))

# ── 3B  Taylor Series of exp(x) ─────────────────────────────────────────
ax8 = fig.add_subplot(gs_main[3, 1])
x_t = np.linspace(-3, 3, 500)
ax8.plot(x_t, np.exp(x_t), color=GOLD, lw=3, label=r"$e^x$", zorder=5)
colors_t = [CYAN, MAGENTA, GREEN, ORANGE, PURPLE]
for n, col in zip([1, 2, 3, 4, 5], colors_t):
    approx = sum(x_t**k / math.factorial(k) for k in range(n + 1))
    ax8.plot(x_t, approx, color=col, lw=1.5, linestyle="--",
             label=f"n={n}", alpha=0.85)
ax8.set_ylim(-2, 12)
ax8.set_title(r"Taylor Series of $e^x$", color=GOLD, fontsize=12, pad=8)
ax8.set_xlabel(r"$x$")
ax8.set_ylabel(r"$f(x)$")
ax8.legend(fontsize=7, facecolor="#11112A", edgecolor=GOLD, labelcolor=WHITE)
ax8.grid(True)
ax8.text(0.02, 0.88,
         r"$e^x=\sum_{k=0}^{n}\frac{x^k}{k!}$",
         transform=ax8.transAxes, fontsize=9, color=CYAN,
         bbox=dict(facecolor="#11112A", edgecolor=CYAN,
                   boxstyle="round,pad=0.3", alpha=0.8))

# ── 3C  Spiral / Parametric ─────────────────────────────────────────────
ax9 = fig.add_subplot(gs_main[3, 2])
t_s = np.linspace(0, 6 * np.pi, 3000)
for k, (a, b, col) in enumerate([(1, 0.15, CYAN),
                                   (1, 0.20, MAGENTA),
                                   (1, 0.25, GREEN)]):
    r_s = a * np.exp(b * t_s)
    xs = r_s * np.cos(t_s)
    ys = r_s * np.sin(t_s)
    ax9.plot(xs, ys, color=col, lw=1.2, alpha=0.85,
             label=rf"$b={b}$")
ax9.set_title("Logarithmic Spirals", color=GOLD, fontsize=12, pad=8)
ax9.set_xlabel(r"$x$")
ax9.set_ylabel(r"$y$")
ax9.legend(fontsize=8, facecolor="#11112A", edgecolor=GOLD, labelcolor=WHITE)
ax9.grid(True)
ax9.text(0.02, 0.05,
         r"$r=ae^{b\theta}$",
         transform=ax9.transAxes, fontsize=11, color=GOLD,
         bbox=dict(facecolor="#11112A", edgecolor=GOLD,
                   boxstyle="round,pad=0.3", alpha=0.8))

# ════════════════════════════════════════════════════════════════════════════
# ROW 4 – footer / credits
# ════════════════════════════════════════════════════════════════════════════
ax_foot = fig.add_subplot(gs_main[4, :])
ax_foot.set_xlim(0, 1)
ax_foot.set_ylim(0, 1)
ax_foot.axis("off")

fancy3 = FancyBboxPatch((0.01, 0.05), 0.98, 0.88,
                          boxstyle="round,pad=0.02",
                          linewidth=2, edgecolor=PURPLE,
                          facecolor="#0A0A1E")
ax_foot.add_patch(fancy3)

footer_eqs = [
    r"$\int_{-\infty}^{\infty}e^{-x^2}dx=\sqrt{\pi}$",
    r"$\zeta(s)=\sum_{n=1}^{\infty}\frac{1}{n^s}$",
    r"$\binom{n}{k}=\frac{n!}{k!(n-k)!}$",
    r"$\mathbf{F}=m\ddot{\mathbf{r}}$",
    r"$\Delta x\,\Delta p\geq\frac{\hbar}{2}$",
]
positions = np.linspace(0.10, 0.90, len(footer_eqs))
for eq, xp in zip(footer_eqs, positions):
    ax_foot.text(xp, 0.60, eq, ha="center", va="center",
                 fontsize=11, color=CYAN)

ax_foot.text(0.5, 0.22,
             r"Typeset with  \LaTeX  --  where mathematics meets elegance",
             ha="center", va="center", fontsize=13,
             color=GOLD, fontstyle="italic")

ax_foot.plot([0.05, 0.95], [0.82, 0.82], color=PURPLE, lw=1, alpha=0.6)
ax_foot.plot([0.05, 0.95], [0.10, 0.10], color=PURPLE, lw=1, alpha=0.6)

# ════════════════════════════════════════════════════════════════════════════
# MAIN TITLE
# ════════════════════════════════════════════════════════════════════════════
plt.suptitle("The Joy of LaTeX", y=0.995,
             fontsize=44, fontweight="bold",
             color=GOLD, fontstyle="italic")

plt.tight_layout()
plt.savefig("joy_of_latex_poster.png", dpi=150,
            bbox_inches="tight", facecolor=BG)
plt.show()

print("Poster saved as joy_of_latex_poster.png")
print("All panels rendered successfully:")
print("  - Header panel with LaTeX title")
print("  - Row 1: Fourier Series, Gaussian Distributions, Polar Rose")
print("  - Row 2: Sinc Surface (3D), Iconic Equations, Mandelbrot Set")
print("  - Row 3: Lissajous Curves, Taylor Series, Logarithmic Spirals")
print("  - Footer panel with famous equations")
