# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-10 07:58:08
# AutoCoder System - Automated Code Generation

import pygame
import numpy as np
import sys

# --- Kalman Filter Implementation ---
class KalmanFilter1D:
    def __init__(self, process_noise=1.0, measurement_noise=10.0, initial_estimate=0.0, initial_uncertainty=1.0):
        self.Q = process_noise          # Process noise covariance
        self.R = measurement_noise      # Measurement noise covariance
        self.x = initial_estimate       # State estimate
        self.P = initial_uncertainty    # Estimate uncertainty

    def update(self, measurement):
        # Predict (constant velocity model, F=1, B=0)
        x_pred = self.x
        P_pred = self.P + self.Q

        # Kalman Gain
        K = P_pred / (P_pred + self.R)

        # Update
        self.x = x_pred + K * (measurement - x_pred)
        self.P = (1 - K) * P_pred

        return self.x, K

    def reset(self, initial_estimate=0.0, initial_uncertainty=1.0):
        self.x = initial_estimate
        self.P = initial_uncertainty


# --- Pygame Setup ---
pygame.init()
WIDTH, HEIGHT = 1100, 700
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Interactive Kalman Filter Demo")
clock = pygame.time.Clock()

# Fonts
font_large = pygame.font.SysFont("monospace", 20, bold=True)
font_med   = pygame.font.SysFont("monospace", 16)
font_small = pygame.font.SysFont("monospace", 13)

# Colors
BG_COLOR        = (15, 15, 30)
GRID_COLOR      = (40, 40, 60)
TRUE_COLOR      = (80, 200, 120)    # Green - true signal
MEAS_COLOR      = (220, 80, 80)     # Red - noisy measurement
KALMAN_COLOR    = (80, 160, 255)    # Blue - Kalman estimate
PANEL_COLOR     = (25, 25, 50)
SLIDER_BG       = (60, 60, 90)
SLIDER_FG       = (100, 180, 255)
SLIDER_HANDLE   = (200, 220, 255)
TEXT_COLOR      = (220, 220, 240)
TITLE_COLOR     = (255, 220, 80)
HIGHLIGHT       = (255, 255, 100)

# --- Plot Area ---
PLOT_X, PLOT_Y = 20, 60
PLOT_W, PLOT_H = 720, 500
PLOT_RECT = pygame.Rect(PLOT_X, PLOT_Y, PLOT_W, PLOT_H)

# --- Signal Parameters ---
HISTORY = 300   # number of time steps shown
dt = 0.05

# Sliders: (label, min, max, default, y_pos)
PANEL_X = 760
PANEL_W = 320

slider_defs = [
    {"label": "Process Noise Q",   "min": 0.01, "max": 20.0,  "value": 1.0,  "y": 160},
    {"label": "Meas. Noise R",     "min": 0.1,  "max": 50.0,  "value": 10.0, "y": 230},
    {"label": "Signal Frequency",  "min": 0.1,  "max": 3.0,   "value": 0.5,  "y": 300},
    {"label": "Signal Amplitude",  "min": 1.0,  "max": 100.0, "value": 50.0, "y": 370},
    {"label": "Noise Amplitude",   "min": 1.0,  "max": 80.0,  "value": 20.0, "y": 440},
    {"label": "Speed",             "min": 0.1,  "max": 5.0,   "value": 1.0,  "y": 510},
]

SLIDER_LEFT  = PANEL_X + 10
SLIDER_RIGHT = PANEL_X + PANEL_W - 10
SLIDER_LEN   = SLIDER_RIGHT - SLIDER_LEFT
HANDLE_R     = 9

def val_to_x(s):
    frac = (s["value"] - s["min"]) / (s["max"] - s["min"])
    return int(SLIDER_LEFT + frac * SLIDER_LEN)

def x_to_val(s, mx):
    frac = np.clip((mx - SLIDER_LEFT) / SLIDER_LEN, 0, 1)
    return s["min"] + frac * (s["max"] - s["min"])

dragging = None   # index of slider being dragged

# --- State ---
kf = KalmanFilter1D(process_noise=slider_defs[0]["value"],
                    measurement_noise=slider_defs[1]["value"])

true_history  = []
meas_history  = []
kalman_history = []
gain_history  = []

t = 0.0
paused = False

def get_slider(idx):
    return slider_defs[idx]["value"]

def reset_histories():
    global t, true_history, meas_history, kalman_history, gain_history
    true_history.clear()
    meas_history.clear()
    kalman_history.clear()
    gain_history.clear()
    t = 0.0
    kf.reset()

def draw_grid():
    # Horizontal grid lines
    for i in range(5):
        y = PLOT_Y + int(i * PLOT_H / 4)
        pygame.draw.line(screen, GRID_COLOR, (PLOT_X, y), (PLOT_X + PLOT_W, y), 1)
    # Vertical grid lines
    for i in range(7):
        x = PLOT_X + int(i * PLOT_W / 6)
        pygame.draw.line(screen, GRID_COLOR, (x, PLOT_Y), (x, PLOT_Y + PLOT_H), 1)

def signal_to_screen_y(val, amp):
    """Map signal value to screen y coordinate."""
    center_y = PLOT_Y + PLOT_H // 2
    scale = (PLOT_H * 0.42) / max(amp, 1)
    return int(center_y - val * scale)

def draw_history(history, color, width=2, amp=100):
    if len(history) < 2:
        return
    n = len(history)
    points = []
    for i, v in enumerate(history):
        x = PLOT_X + int(i * PLOT_W / HISTORY)
        y = signal_to_screen_y(v, amp)
        y = np.clip(y, PLOT_Y + 2, PLOT_Y + PLOT_H - 2)
        points.append((x, y))
    if len(points) >= 2:
        pygame.draw.lines(screen, color, False, points, width)

def draw_scatter(history, color, amp=100):
    """Draw measurement dots."""
    n = len(history)
    for i, v in enumerate(history):
        x = PLOT_X + int(i * PLOT_W / HISTORY)
        y = signal_to_screen_y(v, amp)
        y = np.clip(y, PLOT_Y + 2, PLOT_Y + PLOT_H - 2)
        pygame.draw.circle(screen, color, (x, y), 2)

def draw_slider(s, idx):
    y = s["y"]
    # Label
    label_surf = font_small.render(s["label"], True, TEXT_COLOR)
    screen.blit(label_surf, (PANEL_X + 10, y - 20))
    # Value
    val_str = f"{s['value']:.2f}"
    val_surf = font_small.render(val_str, True, HIGHLIGHT)
    screen.blit(val_surf, (PANEL_X + PANEL_W - 55, y - 20))
    # Track
    pygame.draw.rect(screen, SLIDER_BG, (SLIDER_LEFT, y - 4, SLIDER_LEN, 8), border_radius=4)
    # Fill
    hx = val_to_x(s)
    fill_w = hx - SLIDER_LEFT
    if fill_w > 0:
        pygame.draw.rect(screen, SLIDER_FG, (SLIDER_LEFT, y - 4, fill_w, 8), border_radius=4)
    # Handle
    pygame.draw.circle(screen, SLIDER_HANDLE, (hx, y), HANDLE_R)
    pygame.draw.circle(screen, (150, 180, 220), (hx, y), HANDLE_R, 2)

def draw_legend():
    items = [
        (TRUE_COLOR,   "True Signal"),
        (MEAS_COLOR,   "Noisy Measurement"),
        (KALMAN_COLOR, "Kalman Estimate"),
    ]
    lx = PLOT_X + 10
    ly = PLOT_Y + 10
    for color, label in items:
        pygame.draw.line(screen, color, (lx, ly + 7), (lx + 25, ly + 7), 3)
        t_surf = font_small.render(label, True, TEXT_COLOR)
        screen.blit(t_surf, (lx + 30, ly))
        lx += 170

def draw_info_panel(K_gain):
    # Current Kalman Gain
    kg_surf = font_med.render(f"Kalman Gain K = {K_gain:.4f}", True, HIGHLIGHT)
    screen.blit(kg_surf, (PANEL_X + 10, 580))

    # Interpretation
    if K_gain > 0.7:
        interp = "Trusting measurement more"
        ic = MEAS_COLOR
    elif K_gain < 0.3:
        interp = "Trusting model more"
        ic = TRUE_COLOR
    else:
        interp = "Balanced trust"
        ic = KALMAN_COLOR
    i_surf = font_small.render(interp, True, ic)
    screen.blit(i_surf, (PANEL_X + 10, 605))

    # Controls hint
    hints = ["[SPACE] Pause/Resume", "[R] Reset", "[Q] Quit"]
    for i, h in enumerate(hints):
        hs = font_small.render(h, True, (140, 140, 170))
        screen.blit(hs, (PANEL_X + 10, 640 + i * 18))

print("Kalman Filter Interactive Demo starting...")
print("Controls: SPACE=pause, R=reset, Q=quit")
print("Drag sliders to change parameters in real time.")

running = True
last_K = 0.5
speed_accum = 0.0

while running:
    clock.tick(60)

    # --- Events ---
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_q:
                running = False
            elif event.key == pygame.K_SPACE:
                paused = not paused
                print(f"{'Paused' if paused else 'Resumed'}")
            elif event.key == pygame.K_r:
                reset_histories()
                print("Reset!")

        elif event.type == pygame.MOUSEBUTTONDOWN:
            mx, my = event.pos
            for idx, s in enumerate(slider_defs):
                hx = val_to_x(s)
                if abs(mx - hx) <= HANDLE_R + 4 and abs(my - s["y"]) <= HANDLE_R + 4:
                    dragging = idx
                    break

        elif event.type == pygame.MOUSEBUTTONUP:
            dragging = None

        elif event.type == pygame.MOUSEMOTION:
            if dragging is not None:
                mx, my = event.pos
                slider_defs[dragging]["value"] = x_to_val(slider_defs[dragging], mx)
                # Update KF parameters live
                kf.Q = get_slider(0)
                kf.R = get_slider(1)

    # --- Simulation Step ---
    if not paused:
        speed = get_slider(5)
        speed_accum += speed

        steps = int(speed_accum)
        speed_accum -= steps

        for _ in range(max(1, steps)):
            freq  = get_slider(2)
            amp   = get_slider(3)
            noise = get_slider(4)

            # True signal: sine wave
            true_val = amp * np.sin(2 * np.pi * freq * t)

            # Noisy measurement
            meas_val = true_val + np.random.normal(0, noise)

            # Kalman filter update
            kf.Q = get_slider(0)
            kf.R = get_slider(1)
            est, K = kf.update(meas_val)
            last_K = K

            true_history.append(true_val)
            meas_history.append(meas_val)
            kalman_history.append(est)
            gain_history.append(K)

            # Keep history length
            if len(true_history) > HISTORY:
                true_history.pop(0)
                meas_history.pop(0)
                kalman_history.pop(0)
                gain_history.pop(0)

            t += dt

    # --- Drawing ---
    screen.fill(BG_COLOR)

    # Title
    title = font_large.render("Interactive Kalman Filter Demo", True, TITLE_COLOR)
    screen.blit(title, (PLOT_X, 20))

    # Plot border
    pygame.draw.rect(screen, (60, 60, 100), PLOT_RECT, 2, border_radius=4)

    # Grid
    draw_grid()

    # Center line
    cy = PLOT_Y + PLOT_H // 2
    pygame.draw.line(screen, (70, 70, 100), (PLOT_X, cy), (PLOT_X + PLOT_W, cy), 1)

    # Histories
    amp = get_slider(3) + get_slider(4)  # display scale
    draw_scatter(meas_history, (*MEAS_COLOR[:3], 120), amp=amp)
    draw_history(true_history,   TRUE_COLOR,   width=2, amp=amp)
    draw_history(kalman_history, KALMAN_COLOR, width=3, amp=amp)

    # Legend
    draw_legend()

    # Right panel background
    pygame.draw.rect(screen, PANEL_COLOR,
                     (PANEL_X - 5, 50, PANEL_W + 10, HEIGHT - 60), border_radius=6)
    pygame.draw.rect(screen, (60, 60, 100),
                     (PANEL_X - 5, 50, PANEL_W + 10, HEIGHT - 60), 1, border_radius=6)

    # Panel title
    pt = font_large.render("Parameters", True, TITLE_COLOR)
    screen.blit(pt, (PANEL_X + 10, 65))

    # Equations
    eq1 = font_small.render("Predict: x = F*x + B*u", True, (160, 200, 160))
    eq2 = font_small.render("Update:  x = x + K*(z - H*x)", True, (160, 200, 160))
    eq3 = font_small.render("Gain:    K = P/(P + R)", True, (160, 200, 160))
    screen.blit(eq1, (PANEL_X + 10, 95))
    screen.blit(eq2, (PANEL_X + 10, 113))
    screen.blit(eq3, (PANEL_X + 10, 131))

    # Sliders
    for idx, s in enumerate(slider_defs):
        draw_slider(s, idx)

    # Info panel
    draw_info_panel(last_K)

    # Paused overlay
    if paused:
        ps = font_large.render("PAUSED - Press SPACE to resume", True, (255, 200, 50))
        screen.blit(ps, (PLOT_X + 10, PLOT_Y + PLOT_H // 2 - 12))

    pygame.display.flip()

pygame.quit()
print("Demo closed.")
sys.exit()