# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-19 20:03:50
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# ── Simulation parameters ──────────────────────────────────────────────────
np.random.seed(42)
dt      = 0.1    # time step (s)
n_steps = 150    # total frames
t_arr   = np.arange(n_steps) * dt

# True motion: constant acceleration + sinusoidal component
true_pos = 0.5 * 0.3 * t_arr**2 + 2.0 * np.sin(0.5 * t_arr)
true_vel = 0.3 * t_arr           + 2.0 * 0.5 * np.cos(0.5 * t_arr)

# Noise parameters
meas_noise_std = 3.0   # measurement noise std dev (position only)
proc_noise_std = 0.1   # process noise std dev

# Noisy measurements (position only — velocity is never measured)
measurements = true_pos + np.random.normal(0, meas_noise_std, n_steps)

# ── Kalman filter matrices ─────────────────────────────────────────────────
F = np.array([[1, dt],
              [0,  1]])

H = np.array([[1, 0]])

Q = proc_noise_std**2 * np.array([[dt**4/4, dt**3/2],
                                   [dt**3/2, dt**2  ]])

R = np.array([[meas_noise_std**2]])

x_est = np.array([[0.0], [0.0]])
P     = np.eye(2) * 500.0

kf_pos     = np.zeros(n_steps)
kf_vel     = np.zeros(n_steps)
kf_pos_std = np.zeros(n_steps)
kf_vel_std = np.zeros(n_steps)

# ── Pre-run the filter ─────────────────────────────────────────────────────
for k in range(n_steps):
    x_pred = F @ x_est
    P_pred = F @ P @ F.T + Q

    z     = np.array([[measurements[k]]])
    S     = H @ P_pred @ H.T + R
    K     = P_pred @ H.T @ np.linalg.inv(S)
    x_est = x_pred + K @ (z - H @ x_pred)
    P     = (np.eye(2) - K @ H) @ P_pred

    kf_pos[k]     = x_est[0, 0]
    kf_vel[k]     = x_est[1, 0]
    kf_pos_std[k] = np.sqrt(P[0, 0])
    kf_vel_std[k] = np.sqrt(P[1, 1])

print("Kalman filter pre-computation complete.")
print(f"Final position estimate: {kf_pos[-1]:.2f} m  (true: {true_pos[-1]:.2f} m)")
print(f"Final velocity estimate: {kf_vel[-1]:.2f} m/s  (true: {true_vel[-1]:.2f} m/s)")

# ── Figure layout ──────────────────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
fig.patch.set_facecolor('#0f0f1a')
for ax in (ax1, ax2):
    ax.set_facecolor('#12122a')
    ax.tick_params(colors='#ccccdd', labelsize=9)
    for spine in ax.spines.values():
        spine.set_edgecolor('#333355')

fig.suptitle('Kalman Filter - 1D Position & Velocity Estimation',
             color='white', fontsize=14, fontweight='bold', y=0.98)

C_TRUE  = '#00e5ff'
C_MEAS  = '#ff6b6b'
C_KF    = '#69ff47'
C_SHADE = '#69ff47'

# ── Position subplot ───────────────────────────────────────────────────────
ax1.set_ylabel('Position (m)', color='#ccccdd', fontsize=10)
ax1.set_title('Position over Time', color='#aaaacc', fontsize=10, pad=4)
ax1.set_xlim(t_arr[0], t_arr[-1])
ax1.set_ylim(min(true_pos.min(), measurements.min()) - 4,
             max(true_pos.max(), measurements.max()) + 4)
ax1.grid(True, color='#222244', linewidth=0.5, linestyle='--')

line_true_pos, = ax1.plot([], [], color=C_TRUE, lw=2,  label='True position',    zorder=4)
scat_meas,     = ax1.plot([], [], 'o', color=C_MEAS, ms=3, alpha=0.6,
                           label='Noisy measurement', zorder=3)
line_kf_pos,   = ax1.plot([], [], color=C_KF,  lw=2,  label='Kalman estimate',   zorder=5)
# Placeholder for legend entry for uncertainty band
ax1.fill_between([0], [0], [0], color=C_SHADE, alpha=0.15, label='Uncertainty (1 sigma)', zorder=2)
ax1.legend(loc='upper left', facecolor='#1a1a2e', edgecolor='#333355',
           labelcolor='white', fontsize=8)

info_text = ax1.text(0.99, 0.97, '', transform=ax1.transAxes,
                     ha='right', va='top', fontsize=8, color='#ffdd88',
                     family='monospace',
                     bbox=dict(boxstyle='round,pad=0.4', facecolor='#1a1a2e',
                               edgecolor='#333355', alpha=0.85))

# Keep a reference to the fill_between poly for position
pos_fill = [None]
vel_fill = [None]

# ── Velocity subplot ───────────────────────────────────────────────────────
ax2.set_xlabel('Time (s)', color='#ccccdd', fontsize=10)
ax2.set_ylabel('Velocity (m/s)', color='#ccccdd', fontsize=10)
ax2.set_title('Velocity over Time  (never directly measured - inferred by filter)',
              color='#aaaacc', fontsize=10, pad=4)
ax2.set_xlim(t_arr[0], t_arr[-1])
ax2.set_ylim(min(true_vel.min(), kf_vel.min()) - 2,
             max(true_vel.max(), kf_vel.max()) + 2)
ax2.grid(True, color='#222244', linewidth=0.5, linestyle='--')

line_true_vel, = ax2.plot([], [], color=C_TRUE, lw=2, label='True velocity',  zorder=4)
line_kf_vel,   = ax2.plot([], [], color=C_KF,  lw=2, label='Kalman estimate', zorder=5)
ax2.fill_between([0], [0], [0], color=C_SHADE, alpha=0.15, label='Uncertainty (1 sigma)', zorder=2)
ax2.legend(loc='upper left', facecolor='#1a1a2e', edgecolor='#333355',
           labelcolor='white', fontsize=8)

plt.subplots_adjust(left=0.08, right=0.97, top=0.93, bottom=0.08, hspace=0.35)

# ── Animation update ───────────────────────────────────────────────────────
def update(frame):
    k = frame + 1

    t_sl  = t_arr[:k]
    tp_sl = true_pos[:k]
    tv_sl = true_vel[:k]
    m_sl  = measurements[:k]
    kp_sl = kf_pos[:k]
    kv_sl = kf_vel[:k]
    ks_p  = kf_pos_std[:k]
    ks_v  = kf_vel_std[:k]

    line_true_pos.set_data(t_sl, tp_sl)
    scat_meas.set_data(t_sl, m_sl)
    line_kf_pos.set_data(t_sl, kp_sl)

    # Remove old fill_between by removing the PolyCollection from the axes
    if pos_fill[0] is not None:
        try:
            pos_fill[0].remove()
        except Exception:
            pass
    pos_fill[0] = ax1.fill_between(t_sl, kp_sl - ks_p, kp_sl + ks_p,
                                   color=C_SHADE, alpha=0.15, zorder=2)

    line_true_vel.set_data(t_sl, tv_sl)
    line_kf_vel.set_data(t_sl, kv_sl)

    if vel_fill[0] is not None:
        try:
            vel_fill[0].remove()
        except Exception:
            pass
    vel_fill[0] = ax2.fill_between(t_sl, kv_sl - ks_v, kv_sl + ks_v,
                                   color=C_SHADE, alpha=0.15, zorder=2)

    if k > 0:
        info_text.set_text(
            f"t = {t_sl[-1]:.1f} s\n"
            f"Pos error : {abs(kp_sl[-1] - tp_sl[-1]):+.2f} m\n"
            f"Vel error : {abs(kv_sl[-1] - tv_sl[-1]):+.2f} m/s\n"
            f"Pos sigma : {ks_p[-1]:.2f} m\n"
            f"Vel sigma : {ks_v[-1]:.2f} m/s"
        )

    return (line_true_pos, scat_meas, line_kf_pos,
            line_true_vel, line_kf_vel, info_text)

print("Starting animation...")

ani = animation.FuncAnimation(
    fig, update,
    frames=n_steps,
    interval=60,
    blit=False,
    repeat=True
)

plt.show()