# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-08 17:55:54
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pygame
import pygame.gfxdraw
import math
import random
import sys

# Initialize pygame
pygame.init()

# Screen dimensions
WIDTH, HEIGHT = 1400, 850
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Auckland Laptop Market — Live Prices")

clock = pygame.time.Clock()
FPS = 60

# Colors
BG_COLOR = (26, 31, 46)
CYAN = (0, 212, 255)
VIOLET = (108, 59, 255)
WHITE = (255, 255, 255)
GOLD = (255, 215, 0)
CORAL = (255, 99, 99)
AMBER = (255, 191, 0)
ELECTRIC_GREEN = (0, 255, 128)
DARK_PANEL = (18, 22, 35)
FROSTED = (30, 40, 60, 200)

# Auckland Laptop Data (embedded from research)
laptop_data = [
    {"brand": "Apple MacBook Air M2", "model": "MacBook Air 13\"", "price": 2199, "ram": 16, "storage": 512, "retailer": "PB Tech"},
    {"brand": "Apple MacBook Pro M3", "model": "MacBook Pro 14\"", "price": 3299, "ram": 18, "storage": 512, "retailer": "Noel Leeming"},
    {"brand": "Dell XPS 13", "model": "XPS 13 Plus", "price": 2499, "ram": 16, "storage": 512, "retailer": "Harvey Norman"},
    {"brand": "Lenovo ThinkPad X1", "model": "ThinkPad X1 Carbon", "price": 2899, "ram": 16, "storage": 512, "retailer": "PB Tech"},
    {"brand": "HP Spectre x360", "model": "Spectre x360 14\"", "price": 2199, "ram": 16, "storage": 512, "retailer": "Noel Leeming"},
    {"brand": "ASUS ROG Zephyrus", "model": "Zephyrus G14", "price": 2799, "ram": 32, "storage": 1024, "retailer": "PB Tech"},
    {"brand": "Microsoft Surface", "model": "Surface Laptop 5", "price": 1999, "ram": 16, "storage": 256, "retailer": "Harvey Norman"},
    {"brand": "Acer Swift 5", "model": "Swift 5 14\"", "price": 1499, "ram": 16, "storage": 512, "retailer": "PB Tech"},
    {"brand": "Samsung Galaxy Book3", "model": "Galaxy Book3 Pro", "price": 2299, "ram": 16, "storage": 512, "retailer": "Noel Leeming"},
    {"brand": "LG Gram 16", "model": "Gram 16 2024", "price": 2099, "ram": 16, "storage": 512, "retailer": "Harvey Norman"},
    {"brand": "MSI Prestige 14", "model": "Prestige 14 EVO", "price": 1799, "ram": 32, "storage": 1024, "retailer": "PB Tech"},
    {"brand": "Razer Blade 14", "model": "Blade 14 2024", "price": 3499, "ram": 16, "storage": 1024, "retailer": "Noel Leeming"},
]

# Short labels for bars
bar_labels = [
    "MacBook Air", "MacBook Pro", "Dell XPS 13", "ThinkPad X1",
    "HP Spectre", "ASUS ROG", "Surface 5", "Acer Swift",
    "Galaxy Book3", "LG Gram 16", "MSI Prestige", "Razer Blade"
]

# Retailer colors
retailer_colors = {
    "PB Tech": CORAL,
    "Noel Leeming": AMBER,
    "Harvey Norman": ELECTRIC_GREEN,
}

# ─── Font setup ───────────────────────────────────────────────────────────────
try:
    title_font = pygame.font.SysFont("Rajdhani", 32, bold=True)
    label_font = pygame.font.SysFont("Rajdhani", 14)
    tooltip_font = pygame.font.SysFont("Rajdhani", 16)
    price_font = pygame.font.SysFont("Rajdhani", 18, bold=True)
    small_font = pygame.font.SysFont("Rajdhani", 12)
except:
    title_font = pygame.font.SysFont("Arial", 28, bold=True)
    label_font = pygame.font.SysFont("Arial", 12)
    tooltip_font = pygame.font.SysFont("Arial", 14)
    price_font = pygame.font.SysFont("Arial", 16, bold=True)
    small_font = pygame.font.SysFont("Arial", 11)

# ─── Grid surface (circuit board) ─────────────────────────────────────────────
grid_surface = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
GRID_SPACING = 40
for gx in range(0, WIDTH, GRID_SPACING):
    pygame.draw.line(grid_surface, (0, 212, 255, 20), (gx, 0), (gx, HEIGHT), 1)
for gy in range(0, HEIGHT, GRID_SPACING):
    pygame.draw.line(grid_surface, (0, 212, 255, 20), (0, gy), (WIDTH, gy), 1)

# ─── Particles (price tags) ───────────────────────────────────────────────────
class Particle:
    def __init__(self):
        self.reset()

    def reset(self):
        self.x = random.uniform(0, WIDTH * 0.65)
        self.y = random.uniform(0, HEIGHT)
        self.vy = random.uniform(-0.3, -0.8)
        self.vx = random.uniform(-0.2, 0.2)
        self.size = random.randint(6, 14)
        self.alpha = random.randint(20, 50)
        self.angle = random.uniform(0, math.pi * 2)
        self.rot_speed = random.uniform(-0.01, 0.01)

    def update(self):
        self.y += self.vy
        self.x += self.vx
        self.angle += self.rot_speed
        if self.y < -20:
            self.reset()
            self.y = HEIGHT + 10

    def draw(self, surface):
        s = pygame.Surface((self.size * 3, self.size * 2), pygame.SRCALPHA)
        pts = [
            (0, self.size // 2),
            (self.size * 2, self.size // 2),
            (self.size * 2, self.size * 2 - 2),
            (0, self.size * 2 - 2),
        ]
        pygame.draw.polygon(s, (255, 215, 0, self.alpha), pts)
        pygame.draw.polygon(s, (255, 215, 0, self.alpha + 10), pts, 1)
        rotated = pygame.transform.rotate(s, math.degrees(self.angle))
        rx, ry = rotated.get_rect().size
        surface.blit(rotated, (int(self.x - rx // 2), int(self.y - ry // 2)))

particles = [Particle() for _ in range(35)]

# ─── Bar chart state ──────────────────────────────────────────────────────────
BAR_AREA_X = 60
BAR_AREA_Y = 130
BAR_AREA_W = int(WIDTH * 0.60)
BAR_AREA_H = 480

n_bars = len(laptop_data)
bar_padding = 8
bar_w = (BAR_AREA_W - bar_padding * (n_bars + 1)) // n_bars

max_price = max(d["price"] for d in laptop_data)
min_price = min(d["price"] for d in laptop_data)

# Animation state
anim_time = 0.0
bar_heights = [0.0] * n_bars  # 0..1 animated
bar_target = [1.0] * n_bars
ANIM_SPEED = 0.025

# Hover state
hovered_bar = -1
bar_lift = [0.0] * n_bars
bar_glow = [0.0] * n_bars

# Price range slider
slider_min_val = min_price
slider_max_val = max_price
SLIDER_X = BAR_AREA_X
SLIDER_Y = HEIGHT - 55
SLIDER_W = BAR_AREA_W
SLIDER_H = 8
slider_left = 0.0   # 0..1
slider_right = 1.0  # 0..1
dragging_left = False
dragging_right = False

# Title animation
title_chars = list("AUCKLAND LAPTOP MARKET  -  LIVE PRICES")
title_alpha = [0.0] * len(title_chars)
title_delay = [i * 0.04 for i in range(len(title_chars))]

# Cyan bar sweep
sweep_x = -200.0
sweep_done = False

# Scatter sonar
sonar_timers = [random.uniform(0, 3.0) for _ in range(n_bars)]
SONAR_PERIOD = 4.0

# ─── Helper: draw gradient rect ───────────────────────────────────────────────
def draw_gradient_bar(surface, x, y, w, h, color_bottom, color_top, alpha=255):
    if h <= 0:
        return
    bar_surf = pygame.Surface((w, h), pygame.SRCALPHA)
    for row in range(h):
        t = row / max(h - 1, 1)
        r = int(color_bottom[0] * t + color_top[0] * (1 - t))
        g = int(color_bottom[1] * t + color_top[1] * (1 - t))
        b = int(color_bottom[2] * t + color_top[2] * (1 - t))
        pygame.draw.line(bar_surf, (r, g, b, alpha), (0, row), (w, row))
    surface.blit(bar_surf, (x, y))

def draw_glow_rect(surface, x, y, w, h, color, radius=8, alpha=80):
    for i in range(radius, 0, -1):
        a = int(alpha * (1 - i / radius))
        glow_surf = pygame.Surface((w + i * 2, h + i * 2), pygame.SRCALPHA)
        pygame.draw.rect(glow_surf, (*color, a), (0, 0, w + i * 2, h + i * 2), border_radius=4)
        surface.blit(glow_surf, (x - i, y - i))

def draw_rounded_rect(surface, color, rect, radius=8, alpha=255):
    s = pygame.Surface((rect[2], rect[3]), pygame.SRCALPHA)
    pygame.draw.rect(s, (*color[:3], alpha), (0, 0, rect[2], rect[3]), border_radius=radius)
    surface.blit(s, (rect[0], rect[1]))

def lerp(a, b, t):
    return a + (b - a) * t

# ─── Scatter plot area ────────────────────────────────────────────────────────
SCATTER_X = int(WIDTH * 0.66)
SCATTER_Y = 130
SCATTER_W = WIDTH - SCATTER_X - 20
SCATTER_H = 380

def get_scatter_pos(laptop):
    # x = RAM (8..32), y = price
    ram_range = (8, 32)
    price_range = (min_price - 200, max_price + 200)
    nx = (laptop["ram"] - ram_range[0]) / (ram_range[1] - ram_range[0])
    ny = 1.0 - (laptop["price"] - price_range[0]) / (price_range[1] - price_range[0])
    sx = SCATTER_X + 40 + int(nx * (SCATTER_W - 60))
    sy = SCATTER_Y + 20 + int(ny * (SCATTER_H - 40))
    return sx, sy

# ─── Main loop ────────────────────────────────────────────────────────────────
running = True
total_time = 0.0
mouse_pos = (0, 0)
tooltip_alpha = [0.0] * n_bars

print("Auckland Laptop Market Explorer starting...")
print(f"Loaded {len(laptop_data)} laptop entries")
print("Controls: Drag the cyan slider thumbs at the bottom to filter prices")

while running:
    dt = clock.tick(FPS) / 1000.0
    total_time += dt

    # ── Events ────────────────────────────────────────────────────────────────
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False

        if event.type == pygame.MOUSEBUTTONDOWN:
            mx, my = event.pos
            # Check slider thumbs
            left_thumb_x = SLIDER_X + int(slider_left * SLIDER_W)
            right_thumb_x = SLIDER_X + int(slider_right * SLIDER_W)
            if abs(mx - left_thumb_x) < 12 and abs(my - (SLIDER_Y + SLIDER_H // 2)) < 14:
                dragging_left = True
            elif abs(mx - right_thumb_x) < 12 and abs(my - (SLIDER_Y + SLIDER_H // 2)) < 14:
                dragging_right = True

        if event.type == pygame.MOUSEBUTTONUP:
            dragging_left = False
            dragging_right = False

        if event.type == pygame.MOUSEMOTION:
            mouse_pos = event.pos
            mx, my = event.pos
            if dragging_left:
                slider_left = max(0.0, min(slider_right - 0.05,
                                           (mx - SLIDER_X) / SLIDER_W))
            if dragging_right:
                slider_right = min(1.0, max(slider_left + 0.05,
                                            (mx - SLIDER_X) / SLIDER_W))

    # ── Update ────────────────────────────────────────────────────────────────
    # Title chars fade in
    for i in range(len(title_chars)):
        if total_time > title_delay[i]:
            title_alpha[i] = min(255.0, title_alpha[i] + 8.0)

    # Sweep bar
    if not sweep_done:
        sweep_x += 6.0
        if sweep_x > WIDTH + 200:
            sweep_done = True

    # Bar spring animation
    for i in range(n_bars):
        bar_heights[i] = lerp(bar_heights[i], bar_target[i], ANIM_SPEED * 3.5)

    # Hover detection
    hovered_bar = -1
    mx, my = mouse_pos
    price_lo = min_price + slider_left * (max_price - min_price)
    price_hi = min_price + slider_right * (max_price - min_price)

    for i in range(n_bars):
        bx = BAR_AREA_X + bar_padding + i * (bar_w + bar_padding)
        price = laptop_data[i]["price"]
        norm = (price - 0) / (max_price * 1.1)
        bh = int(norm * BAR_AREA_H * bar_heights[i])
        by = BAR_AREA_Y + BAR_AREA_H - bh
        if bx <= mx <= bx + bar_w and by - 10 <= my <= BAR_AREA_Y + BAR_AREA_H:
            hovered_bar = i

    # Animate hover glow/lift
    for i in range(n_bars):
        target_glow = 1.0 if i == hovered_bar else 0.0
        bar_glow[i] = lerp(bar_glow[i], target_glow, 0.12)
        target_lift = 4.0 if i == hovered_bar else 0.0
        bar_lift[i] = lerp(bar_lift[i], target_lift, 0.12)
        target_tooltip = 1.0 if i == hovered_bar else 0.0
        tooltip_alpha[i] = lerp(tooltip_alpha[i], target_tooltip, 0.10)

    # Sonar timers
    for i in range(n_bars):
        sonar_timers[i] += dt
        if sonar_timers[i] > SONAR_PERIOD:
            sonar_timers[i] = 0.0

    # Particles
    for p in particles:
        p.update()

    # ── Draw ──────────────────────────────────────────────────────────────────
    screen.fill(BG_COLOR)

    # Grid
    grid_pulse = 0.5 + 0.5 * math.sin(total_time * 0.5)
    grid_alpha_surf = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
    grid_alpha_surf.blit(grid_surface, (0, 0))
    grid_alpha_surf.set_alpha(int(180 + 40 * grid_pulse))
    screen.blit(grid_alpha_surf, (0, 0))

    # Particles
    for p in particles:
        p.draw(screen)

    # ── Title ─────────────────────────────────────────────────────────────────
    title_text = "AUCKLAND LAPTOP MARKET  -  LIVE PRICES"
    char_x = 60
    char_y = 28
    for i, ch in enumerate(title_text):
        alpha = int(title_alpha[i])
        if alpha > 0:
            surf = title_font.render(ch, True, WHITE)
            surf.set_alpha(alpha)
            screen.blit(surf, (char_x, char_y))
        char_x += title_font.size(ch)[0]

    # Sweep bar under title
    sweep_surf = pygame.Surface((200, 4), pygame.SRCALPHA)
    for px in range(200):
        t = px / 199
        r = int(VIOLET[0] * (1 - t) + CYAN[0] * t)
        g = int(VIOLET[1] * (1 - t) + CYAN[1] * t)
        b = int(VIOLET[2] * (1 - t) + CYAN[2] * t)
        pygame.draw.line(sweep_surf, (r, g, b, 220), (px, 0), (px, 3))
    screen.blit(sweep_surf, (int(sweep_x - 200), 72))

    # Static underline after sweep
    if sweep_done:
        pygame.draw.line(screen, (*CYAN, 180), (60, 72), (BAR_AREA_X + BAR_AREA_W, 72), 3)

    # ── Bar chart background panel ─────────────────────────────────────────────
    draw_rounded_rect(screen, DARK_PANEL,
                      (BAR_AREA_X - 10, BAR_AREA_Y - 20, BAR_AREA_W + 20, BAR_AREA_H + 60),
                      radius=12, alpha=180)
    pygame.draw.rect(screen, (*CYAN, 40),
                     (BAR_AREA_X - 10, BAR_AREA_Y - 20, BAR_AREA_W + 20, BAR_AREA_H + 60),
                     2, border_radius=12)

    # Y-axis labels
    for tick in range(0, 5):
        t = tick / 4
        price_tick = int(max_price * 1.1 * t)
        ty = BAR_AREA_Y + BAR_AREA_H - int(t * BAR_AREA_H)
        pygame.draw.line(screen, (*CYAN, 30), (BAR_AREA_X - 5, ty), (BAR_AREA_X + BAR_AREA_W, ty), 1)
        lbl = small_font.render(f"${price_tick:,}", True, (*CYAN, 150))
        screen.blit(lbl, (BAR_AREA_X - 50, ty - 7))

    # ── Draw bars ─────────────────────────────────────────────────────────────
    price_lo = min_price + slider_left * (max_price - min_price)
    price_hi = min_price + slider_right * (max_price - min_price)

    for i, laptop in enumerate(laptop_data):
        bx = BAR_AREA_X + bar_padding + i * (bar_w + bar_padding)
        price = laptop["price"]
        norm = (price) / (max_price * 1.1)
        bh = int(norm * BAR_AREA_H * bar_heights[i])
        lift = int(bar_lift[i])
        by = BAR_AREA_Y + BAR_AREA_H - bh - lift

        in_range = price_lo <= price <= price_hi
        alpha = 255 if in_range else 50

        if bh > 0:
            # Glow behind bar
            if bar_glow[i] > 0.05:
                glow_alpha = int(bar_glow[i] * 100)
                draw_glow_rect(screen, bx - 3, by - 3, bar_w + 6, bh + 6,
                               WHITE, radius=10, alpha=glow_alpha)

            # Gradient bar
            draw_gradient_bar(screen, bx, by, bar_w, bh,
                               VIOLET, CYAN, alpha=alpha)

            # Bright top edge
            if in_range:
                pygame.draw.line(screen, (*CYAN, 200), (bx, by), (bx + bar_w, by), 2)

        # X label
        lbl_surf = label_font.render(bar_labels[i], True, (*WHITE, alpha))
        lbl_surf = pygame.transform.rotate(lbl_surf, 35)
        screen.blit(lbl_surf, (bx, BAR_AREA_Y + BAR_AREA_H + 5))

    # ── Tooltips ──────────────────────────────────────────────────────────────
    for i, laptop in enumerate(laptop_data):
        if tooltip_alpha[i] < 0.02:
            continue
        bx = BAR_AREA_X + bar_padding + i * (bar_w + bar_padding)
        price = laptop["price"]
        norm = price / (max_price * 1.1)
        bh = int(norm * BAR_AREA_H * bar_heights[i])
        lift = int(bar_lift[i])
        by = BAR_AREA_Y + BAR_AREA_H - bh - lift

        tip_w, tip_h = 180, 72
        tip_x = min(bx - 20, WIDTH - tip_w - 10)
        tip_y = max(by - tip_h - 10, 10)

        ta = int(tooltip_alpha[i] * 220)
        # Frosted glass background
        tip_surf = pygame.Surface((tip_w, tip_h), pygame.SRCALPHA)
        pygame.draw.rect(tip_surf, (20, 30, 50, ta), (0, 0, tip_w, tip_h), border_radius=10)
        pygame.draw.rect(tip_surf, (*CYAN, int(ta * 0.6)), (0, 0, tip_w, tip_h), 1, border_radius=10)
        screen.blit(tip_surf, (tip_x, tip_y))

        # Retailer color dot
        rc = retailer_colors.get(laptop["retailer"], WHITE)
        pygame.draw.circle(screen, rc, (tip_x + 14, tip_y + 16), 5)

        t1 = tooltip_font.render(laptop["brand"][:22], True, WHITE)
        t1.set_alpha(int(tooltip_alpha[i] * 255))
        screen.blit(t1, (tip_x + 24, tip_y + 8))

        t2 = price_font.render(f"NZD ${price:,}", True, CYAN)
        t2.set_alpha(int(tooltip_alpha[i] * 255))
        screen.blit(t2, (tip_x + 10, tip_y + 30))

        t3 = small_font.render(laptop["retailer"], True, rc)
        t3.set_alpha(int(tooltip_alpha[i] * 255))
        screen.blit(t3, (tip_x + 10, tip_y + 52))

    # ── Scatter plot panel ────────────────────────────────────────────────────
    draw_rounded_rect(screen, DARK_PANEL,
                      (SCATTER_X - 10, SCATTER_Y - 20, SCATTER_W + 20, SCATTER_H + 40),
                      radius=12, alpha=180)
    pygame.draw.rect(screen, (*CYAN, 40),
                     (SCATTER_X - 10, SCATTER_Y - 20, SCATTER_W + 20, SCATTER_H + 40),
                     2, border_radius=12)

    # Scatter title
    st = label_font.render("PRICE vs RAM  (scatter)", True, CYAN)
    screen.blit(st, (SCATTER_X + 10, SCATTER_Y - 14))

    # Scatter axes
    pygame.draw.line(screen, (*CYAN, 60),
                     (SCATTER_X + 40, SCATTER_Y + 20),
                     (SCATTER_X + 40, SCATTER_Y + SCATTER_H - 20), 1)
    pygame.draw.line(screen, (*CYAN, 60),
                     (SCATTER_X + 40, SCATTER_Y + SCATTER_H - 20),
                     (SCATTER_X + SCATTER_W - 20, SCATTER_Y + SCATTER_H - 20), 1)

    # Axis labels
    ax_lbl = small_font.render("RAM (GB)", True, (*WHITE, 120))
    screen.blit(ax_lbl, (SCATTER_X + SCATTER_W // 2 - 20, SCATTER_Y + SCATTER_H - 12))
    ay_lbl = pygame.transform.rotate(small_font.render("Price NZD", True, (*WHITE, 120)), 90)
    screen.blit(ay_lbl, (SCATTER_X + 2, SCATTER_Y + SCATTER_H // 2 - 20))

    # RAM tick labels
    for ram_val in [8, 16, 32]:
        nx = (ram_val - 8) / (32 - 8)
        tx = SCATTER_X + 40 + int(nx * (SCATTER_W - 60))
        ty = SCATTER_Y + SCATTER_H - 20
        pygame.draw.line(screen, (*CYAN, 40), (tx, ty - 3), (tx, ty + 3), 1)
        rl = small_font.render(str(ram_val), True, (*WHITE, 100))
        screen.blit(rl, (tx - 6, ty + 5))

    # Draw scatter orbs
    for i, laptop in enumerate(laptop_data):
        sx, sy = get_scatter_pos(laptop)
        rc = retailer_colors.get(laptop["retailer"], WHITE)

        # Sonar ping
        sonar_t = sonar_timers[i] / SONAR_PERIOD
        if sonar_t < 0.5:
            ring_r = int(6 + sonar_t * 30)
            ring_a = int(180 * (1 - sonar_t * 2))
            ring_surf = pygame.Surface((ring_r * 2 + 4, ring_r * 2 + 4), pygame.SRCALPHA)
            pygame.draw.circle(ring_surf, (*rc, ring_a),
                               (ring_r + 2, ring_r + 2), ring_r, 2)
            screen.blit(ring_surf, (sx - ring_r - 2, sy - ring_r - 2))

        # Orb glow
        for gr in range(8, 0, -1):
            ga = int(60 * (1 - gr / 8))
            pygame.gfxdraw.filled_circle(screen, sx, sy, gr + 4, (*rc, ga))

        # Orb core
        pygame.gfxdraw.filled_circle(screen, sx, sy, 6, (*rc, 230))
        pygame.gfxdraw.aacircle(screen, sx, sy, 6, (*rc, 255))

        # Label
        ol = small_font.render(bar_labels[i][:10], True, (*WHITE, 160))
        screen.blit(ol, (sx + 8, sy - 6))

    # Legend
    leg_y = SCATTER_Y + SCATTER_H + 10
    for j, (retailer, color) in enumerate(retailer_colors.items()):
        lx = SCATTER_X + 10 + j * 110
        pygame.draw.circle(screen, color, (lx + 6, leg_y + 7), 5)
        ll = small_font.render(retailer, True, (*WHITE, 180))
        screen.blit(ll, (lx + 14, leg_y))

    # ── Info panel (right side, below scatter) ────────────────────────────────
    info_y = SCATTER_Y + SCATTER_H + 50
    info_panel_h = HEIGHT - info_y - 70
    draw_rounded_rect(screen, DARK_PANEL,
                      (SCATTER_X - 10, info_y - 10, SCATTER_W + 20, info_panel_h),
                      radius=10, alpha=160)
    pygame.draw.rect(screen, (*CYAN, 30),
                     (SCATTER_X - 10, info_y - 10, SCATTER_W + 20, info_panel_h),
                     1, border_radius=10)

    ih = label_font.render("TOP PICKS", True, CYAN)
    screen.blit(ih, (SCATTER_X + 10, info_y))

    sorted_laptops = sorted(laptop_data, key=lambda x: x["price"])
    for k, lap in enumerate(sorted_laptops[:4]):
        iy = info_y + 22 + k * 28
        rc = retailer_colors.get(lap["retailer"], WHITE)
        pygame.draw.circle(screen, rc, (SCATTER_X + 16, iy + 8), 4)
        name_s = small_font.render(bar_labels[laptop_data.index(lap)][:16], True, (*WHITE, 200))
        screen.blit(name_s, (SCATTER_X + 26, iy))
        price_s = small_font.render(f"${lap['price']:,}", True, CYAN)
        screen.blit(price_s, (SCATTER_X + SCATTER_W - 55, iy))

    # ── Price range slider ────────────────────────────────────────────────────
    # Background track
    draw_rounded_rect(screen, DARK_PANEL,
                      (SLIDER_X - 15, SLIDER_Y - 20, SLIDER_W + 30, 50),
                      radius=8, alpha=180)

    # Track
    pygame.draw.rect(screen, (40, 50, 70), (SLIDER_X, SLIDER_Y, SLIDER_W, SLIDER_H), border_radius=4)

    # Active range
    lx = SLIDER_X + int(slider_left * SLIDER_W)
    rx = SLIDER_X + int(slider_right * SLIDER_W)
    active_surf = pygame.Surface((rx - lx, SLIDER_H), pygame.SRCALPHA)
    for px in range(rx - lx):
        t = px / max(rx - lx - 1, 1)
        r = int(VIOLET[0] * (1 - t) + CYAN[0] * t)
        g = int(VIOLET[1] * (1 - t) + CYAN[1] * t)
        b = int(VIOLET[2] * (1 - t) + CYAN[2] * t)
        pygame.draw.line(active_surf, (r, g, b, 220), (px, 0), (px, SLIDER_H - 1))
    screen.blit(active_surf, (lx, SLIDER_Y))

    # Thumb left
    for gr in range(6, 0, -1):
        pygame.gfxdraw.filled_circle(screen, lx, SLIDER_Y + SLIDER_H // 2, gr + 4, (*CYAN, 30))
    pygame.gfxdraw.filled_circle(screen, lx, SLIDER_Y + SLIDER_H // 2, 8, (*CYAN, 230))
    pygame.gfxdraw.aacircle(screen, lx, SLIDER_Y + SLIDER_H // 2, 8, WHITE)

    # Thumb right
    for gr in range(6, 0, -1):
        pygame.gfxdraw.filled_circle(screen, rx, SLIDER_Y + SLIDER_H // 2, gr + 4, (*CYAN, 30))
    pygame.gfxdraw.filled_circle(screen, rx, SLIDER_Y + SLIDER_H // 2, 8, (*CYAN, 230))
    pygame.gfxdraw.aacircle(screen, rx, SLIDER_Y + SLIDER_H // 2, 8, WHITE)

    # Slider labels
    lo_val = int(min_price + slider_left * (max_price - min_price))
    hi_val = int(min_price + slider_right * (max_price - min_price))
    sl_lbl = label_font.render("PRICE FILTER:", True, (*WHITE, 180))
    screen.blit(sl_lbl, (SLIDER_X, SLIDER_Y - 16))
    lo_lbl = price_font.render(f"${lo_val:,}", True, CYAN)
    screen.blit(lo_lbl, (lx - 20, SLIDER_Y + 14))
    hi_lbl = price_font.render(f"${hi_val:,}", True, CYAN)
    screen.blit(hi_lbl, (rx - 20, SLIDER_Y + 14))

    # ── Bottom bar ────────────────────────────────────────────────────────────
    pygame.draw.line(screen, (*CYAN, 60), (0, HEIGHT - 22), (WIDTH, HEIGHT - 22), 1)
    footer = small_font.render(
        "Auckland Laptop Market  |  Data: PB Tech, Noel Leeming, Harvey Norman  |  Prices in NZD  |  ESC to exit",
        True, (*WHITE, 100))
    screen.blit(footer, (20, HEIGHT - 16))

    pygame.display.flip()

pygame.quit()
print("Application closed.")
sys.exit()