# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-21 19:10:01
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.widgets import Slider, Button
import warnings
warnings.filterwarnings('ignore')

# -----------------------------------------------------------------------------
# 1. LORENZ SYSTEM & RUNGE-KUTTA 4 SOLVER
# -----------------------------------------------------------------------------

def lorenz_derivatives(state, sigma=10.0, rho=28.0, beta=8/3):
    """
    Compute time derivatives of the Lorenz system:
        dx/dt = sigma * (y - x)
        dy/dt = x * (rho - z) - y
        dz/dt = x * y - beta * z
    """
    x, y, z = state
    dx = sigma * (y - x)
    dy = x * (rho - z) - y
    dz = x * y - beta * z
    return np.array([dx, dy, dz])


def rk4_step(f, state, dt, **kwargs):
    """
    Advance one step using classical 4th-order Runge-Kutta.
    Achieves O(dt^5) local error -- critical for chaotic systems
    where errors grow exponentially.
    """
    k1 = f(state,              **kwargs)
    k2 = f(state + dt/2 * k1, **kwargs)
    k3 = f(state + dt/2 * k2, **kwargs)
    k4 = f(state + dt    * k3, **kwargs)
    return state + (dt / 6.0) * (k1 + 2*k2 + 2*k3 + k4)


def compute_trajectory(initial_state, dt=0.005, n_steps=20_000,
                        sigma=10.0, rho=28.0, beta=8/3):
    """
    Pre-compute the entire Lorenz trajectory before animating.
    Pre-computation ensures smooth, lag-free playback -- no ODE
    solving happens during the render loop.

    Returns
    -------
    trajectory : np.ndarray, shape (n_steps, 3)
    time_array : np.ndarray, shape (n_steps,)
    """
    trajectory = np.empty((n_steps, 3))
    trajectory[0] = np.asarray(initial_state, dtype=float)

    for i in range(1, n_steps):
        trajectory[i] = rk4_step(
            lorenz_derivatives,
            trajectory[i - 1],
            dt,
            sigma=sigma, rho=rho, beta=beta
        )

    time_array = np.arange(n_steps) * dt
    return trajectory, time_array


# -----------------------------------------------------------------------------
# 2. COLOUR HELPERS
# -----------------------------------------------------------------------------

def make_trail_colors(trail_length, cmap_name='plasma'):
    """
    Build an (trail_length, 4) RGBA array that fades from nearly
    transparent at the tail to fully opaque at the head.
    Alpha ramps 0.05 -> 1.0 so older points appear ghostly.
    """
    cmap   = plt.get_cmap(cmap_name)
    t      = np.linspace(0, 1, trail_length)
    colors = cmap(t)
    colors[:, 3] = np.linspace(0.05, 1.0, trail_length)
    return colors


# -----------------------------------------------------------------------------
# 3. MAIN ANIMATION CLASS
# -----------------------------------------------------------------------------

class LorenzAnimator:
    """
    Interactive 3D Lorenz attractor animator.

    Features
    --------
    * Sliding trail window  - only the most recent `trail_length` points
      are drawn each frame, creating a comet-like effect.
    * Colour-mapped trail   - 'plasma' colormap with fading alpha.
    * Head marker           - bright scatter point marks current position.
    * Speed slider          - adjust animation speed without restarting.
    * Pause / Resume button - freeze for manual rotation.
    * Twin trajectory       - slightly perturbed second orbit demonstrates
      sensitive dependence on initial conditions (chaos).
    * Full mouse rotation   - matplotlib 3D axes support click-drag
      rotation and scroll-wheel zoom natively.
    """

    SIGMA = 10.0
    RHO   = 28.0
    BETA  = 8.0 / 3.0

    def __init__(self,
                 initial_state = (0.1, 0.0, 0.0),
                 dt            = 0.005,
                 n_steps       = 20_000,
                 trail_length  = 600,
                 frame_skip    = 4,
                 show_twin     = True,
                 twin_epsilon  = 1e-5):
        """
        Parameters
        ----------
        initial_state : tuple  - starting (x, y, z)
        dt            : float  - RK4 time step
        n_steps       : int    - total pre-computed steps (~100 s simulation)
        trail_length  : int    - number of past points forming the visible trail
        frame_skip    : int    - steps advanced per animation frame
        show_twin     : bool   - draw a perturbed second trajectory
        twin_epsilon  : float  - perturbation magnitude for twin trajectory
        """
        self.dt           = dt
        self.n_steps      = n_steps
        self.trail_length = trail_length
        self.frame_skip   = frame_skip
        self.show_twin    = show_twin
        self.paused       = False
        self.current_step = trail_length  # start after enough history exists

        print("Computing primary trajectory ...")
        self.traj, self.time = compute_trajectory(
            initial_state, dt, n_steps,
            self.SIGMA, self.RHO, self.BETA
        )
        print(f"Primary trajectory computed: {n_steps} steps.")

        if show_twin:
            perturbed = np.array(initial_state) + twin_epsilon
            print("Computing twin trajectory ...")
            self.traj2, _ = compute_trajectory(
                perturbed, dt, n_steps,
                self.SIGMA, self.RHO, self.BETA
            )
            print(f"Twin trajectory computed: {n_steps} steps.")

        # Pre-build colour arrays (reused every frame -- no allocation in loop)
        self.trail_colors  = make_trail_colors(trail_length, 'plasma')
        self.trail_colors2 = make_trail_colors(trail_length, 'cool')

        self._build_figure()
        self._init_artists()

    # -- Figure / axes setup --------------------------------------------------

    def _build_figure(self):
        """Create the figure, 3D axes, and widget axes."""
        self.fig = plt.figure(figsize=(13, 9), facecolor='#0a0a0a')
        self.fig.suptitle(
            'Lorenz Attractor  |  sigma=10  rho=28  beta=8/3\n'
            'Drag to rotate  -  Scroll to zoom  -  Use controls below',
            color='white', fontsize=12, y=0.97
        )

        # Main 3D axes -- leave room at bottom for widgets
        self.ax = self.fig.add_axes([0.05, 0.15, 0.90, 0.80],
                                    projection='3d')
        self._style_axes()

        # Widget axes
        ax_speed  = self.fig.add_axes([0.15, 0.06, 0.55, 0.025],
                                      facecolor='#222222')
        ax_button = self.fig.add_axes([0.75, 0.04, 0.12, 0.055],
                                      facecolor='#222222')

        self.speed_slider = Slider(
            ax_speed, 'Speed', 1, 20,
            valinit=self.frame_skip, valstep=1,
            color='#ff6b35'
        )
        self.speed_slider.label.set_color('white')
        self.speed_slider.valtext.set_color('white')
        self.speed_slider.on_changed(self._on_speed_change)

        self.pause_btn = Button(ax_button, 'Pause',
                                color='#333333', hovercolor='#555555')
        self.pause_btn.label.set_color('white')
        self.pause_btn.on_clicked(self._on_pause_click)

    def _style_axes(self):
        """Apply dark-theme styling to the 3D axes."""
        ax = self.ax
        ax.set_facecolor('#0a0a0a')
        ax.set_xlabel('X', color='#aaaaaa', labelpad=8)
        ax.set_ylabel('Y', color='#aaaaaa', labelpad=8)
        ax.set_zlabel('Z', color='#aaaaaa', labelpad=8)
        ax.tick_params(colors='#555555', labelsize=7)
        for pane in (ax.xaxis.pane, ax.yaxis.pane, ax.zaxis.pane):
            pane.fill = False
            pane.set_edgecolor('#1a1a1a')
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.grid(True, color='#1a1a1a', linewidth=0.4)
        ax.view_init(elev=25, azim=-60)

    # -- Artist initialisation ------------------------------------------------

    def _init_artists(self):
        """
        Create all matplotlib artists updated each frame.
        Scatter plots are used for the trail (support per-point colour/alpha).
        """
        ax = self.ax

        self.trail_scatter = ax.scatter(
            [], [], [], c=[], s=2, linewidths=0,
            depthshade=True, zorder=3
        )
        self.head_scatter = ax.scatter(
            [], [], [], c='white', s=60, zorder=5,
            edgecolors='#ff6b35', linewidths=1.5
        )

        if self.show_twin:
            self.trail_scatter2 = ax.scatter(
                [], [], [], c=[], s=2, linewidths=0,
                depthshade=True, zorder=3
            )
            self.head_scatter2 = ax.scatter(
                [], [], [], c='white', s=60, zorder=5,
                edgecolors='#00ffff', linewidths=1.5
            )

        self.time_text = ax.text2D(
            0.02, 0.95, '', transform=ax.transAxes,
            color='#aaaaaa', fontsize=9, fontfamily='monospace'
        )

        legend_lines = [
            plt.Line2D([0], [0], color='#ff6b35', lw=2,
                       label='Primary orbit  (0.1, 0, 0)'),
        ]
        if self.show_twin:
            legend_lines.append(
                plt.Line2D([0], [0], color='#00ffff', lw=2,
                           label='Twin orbit  (+1e-5 perturbation)')
            )
        ax.legend(handles=legend_lines, loc='upper right',
                  facecolor='#111111', edgecolor='#333333',
                  labelcolor='white', fontsize=8)

        # Fix axis limits from full trajectory extents
        pad = 5
        ax.set_xlim(self.traj[:, 0].min() - pad, self.traj[:, 0].max() + pad)
        ax.set_ylim(self.traj[:, 1].min() - pad, self.traj[:, 1].max() + pad)
        ax.set_zlim(self.traj[:, 2].min() - pad, self.traj[:, 2].max() + pad)

    # -- Widget callbacks -----------------------------------------------------

    def _on_speed_change(self, val):
        self.frame_skip = int(val)

    def _on_pause_click(self, event):
        self.paused = not self.paused
        self.pause_btn.label.set_text('Resume' if self.paused else 'Pause')
        self.fig.canvas.draw_idle()

    # -- Animation update -----------------------------------------------------

    def _update(self, frame):
        """
        Called by FuncAnimation each frame.

        1. Advance current_step by frame_skip (unless paused).
        2. Slice pre-computed trajectory for the trail window.
        3. Update scatter offsets and face-colours in-place.
        4. Loop back to start when trajectory is exhausted.
        """
        if not self.paused:
            self.current_step = min(
                self.current_step + self.frame_skip,
                self.n_steps - 1
            )
            if self.current_step >= self.n_steps - 1:
                self.current_step = self.trail_length

        step = self.current_step
        tl   = self.trail_length

        # Primary trail
        start      = max(0, step - tl)
        window     = self.traj[start:step]
        actual_len = len(window)
        colors_trimmed = self.trail_colors[-actual_len:]

        self.trail_scatter._offsets3d = (
            window[:, 0], window[:, 1], window[:, 2]
        )
        self.trail_scatter.set_facecolor(colors_trimmed)

        head = self.traj[step]
        self.head_scatter._offsets3d = ([head[0]], [head[1]], [head[2]])

        # Twin trail
        if self.show_twin:
            window2         = self.traj2[start:step]
            actual_len2     = len(window2)
            colors_trimmed2 = self.trail_colors2[-actual_len2:]

            self.trail_scatter2._offsets3d = (
                window2[:, 0], window2[:, 1], window2[:, 2]
            )
            self.trail_scatter2.set_facecolor(colors_trimmed2)

            head2 = self.traj2[step]
            self.head_scatter2._offsets3d = (
                [head2[0]], [head2[1]], [head2[2]]
            )

        # Annotation
        self.time_text.set_text(
            f't = {self.time[step]:7.2f}   step = {step:6d}/{self.n_steps}'
        )

        return (self.trail_scatter, self.head_scatter, self.time_text)

    # -- Public run method ----------------------------------------------------

    def run(self, interval=20, save_path=None):
        """
        Start the animation.

        Parameters
        ----------
        interval  : int - milliseconds between frames
        save_path : str - optional file path to save (.mp4 requires ffmpeg,
                          .gif requires pillow)
        """
        n_frames = (self.n_steps - self.trail_length) // self.frame_skip + 1
        print(f"Starting animation: {n_frames} frames, interval={interval}ms")

        self.anim = animation.FuncAnimation(
            self.fig,
            self._update,
            frames=n_frames,
            interval=interval,
            blit=False,   # blit=True breaks 3D mouse rotation
            repeat=True
        )

        if save_path:
            print(f"Saving animation to {save_path} ...")
            writer = (animation.FFMpegWriter(fps=30, bitrate=2000)
                      if save_path.endswith('.mp4')
                      else animation.PillowWriter(fps=20))
            self.anim.save(save_path, writer=writer, dpi=120)
            print("Saved.")

        plt.tight_layout(rect=[0, 0.12, 1, 1])
        plt.show()


# -----------------------------------------------------------------------------
# 4. BONUS: STATIC FULL-TRAJECTORY PLOT
# -----------------------------------------------------------------------------

def plot_full_attractor(traj, title='Lorenz Attractor - Full Trajectory'):
    """
    Render the complete trajectory as a static 3D line plot.
    Colour encodes time: early = purple, late = yellow (viridis).
    """
    print("Rendering static full-attractor plot ...")
    fig = plt.figure(figsize=(10, 8), facecolor='#0a0a0a')
    ax  = fig.add_subplot(111, projection='3d')
    ax.set_facecolor('#0a0a0a')
    ax.set_title(title, color='white', pad=15)

    n    = len(traj)
    cmap = plt.get_cmap('viridis')
    for i in range(0, n - 1, 50):
        end = min(i + 51, n)
        ax.plot(traj[i:end, 0], traj[i:end, 1], traj[i:end, 2],
                color=cmap(i / n), lw=0.4, alpha=0.8)

    ax.set_xlabel('X', color='grey')
    ax.set_ylabel('Y', color='grey')
    ax.set_zlabel('Z', color='grey')
    ax.tick_params(colors='#444444')
    for pane in (ax.xaxis.pane, ax.yaxis.pane, ax.zaxis.pane):
        pane.fill = False

    sm = plt.cm.ScalarMappable(cmap='viridis',
                                norm=plt.Normalize(vmin=0, vmax=n * 0.005))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, shrink=0.5, pad=0.1)
    cbar.set_label('Time', color='white')
    cbar.ax.yaxis.set_tick_params(color='white')
    plt.setp(cbar.ax.yaxis.get_ticklabels(), color='white')

    plt.tight_layout()
    plt.show()
    print("Static plot closed.")


# -----------------------------------------------------------------------------
# 5. ENTRY POINT
# -----------------------------------------------------------------------------

if __name__ == '__main__':

    INITIAL_STATE = (0.1, 0.0, 0.0)
    DT            = 0.005
    N_STEPS       = 20_000
    TRAIL_LENGTH  = 600
    FRAME_SKIP    = 4
    SHOW_TWIN     = True
    TWIN_EPSILON  = 1e-5

    # Optional: static full-attractor view first
    print("Pre-computing trajectory for static plot ...")
    static_traj, _ = compute_trajectory(INITIAL_STATE, DT, N_STEPS)
    print(f"Static trajectory shape: {static_traj.shape}")
    plot_full_attractor(static_traj)

    # Interactive animation
    print("Initialising LorenzAnimator ...")
    animator = LorenzAnimator(
        initial_state = INITIAL_STATE,
        dt            = DT,
        n_steps       = N_STEPS,
        trail_length  = TRAIL_LENGTH,
        frame_skip    = FRAME_SKIP,
        show_twin     = SHOW_TWIN,
        twin_epsilon  = TWIN_EPSILON,
    )

    # Save options (uncomment as needed):
    # animator.run(interval=20, save_path='lorenz.mp4')  # requires ffmpeg
    # animator.run(interval=20, save_path='lorenz.gif')  # requires pillow
    animator.run(interval=20)
