# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-04 12:06:20
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.widgets import Slider
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from scipy.integrate import odeint

print("Starting 3D Mass-Spring-Damper Visualization...")

# ── simulation parameters ──────────────────────────────────────────────────
m  = 1.0          # mass  [kg]
k  = 10.0         # spring stiffness  [N/m]
c0 = 1.0          # initial damping coefficient  [N·s/m]

t  = np.linspace(0, 10, 2000)
x0 = [1.0, 0.0]   # initial displacement = 1 m, velocity = 0

def msd(state, t, m, c, k):
    x, v = state
    dxdt = v
    dvdt = -(c/m)*v - (k/m)*x
    return [dxdt, dvdt]

def solve(c):
    sol = odeint(msd, x0, t, args=(m, c, k))
    return sol[:, 0]   # displacement

# ── figure layout ──────────────────────────────────────────────────────────
fig = plt.figure(figsize=(14, 8))
fig.patch.set_facecolor('#1a1a2e')

gs = gridspec.GridSpec(2, 2,
                       left=0.06, right=0.97,
                       top=0.92, bottom=0.15,
                       wspace=0.35, hspace=0.45)

ax3d   = fig.add_subplot(gs[:, 0], projection='3d')   # left: 3-D view
ax_wav = fig.add_subplot(gs[0, 1])                     # top-right: waveform
ax_ph  = fig.add_subplot(gs[1, 1])                     # bottom-right: phase

for ax in [ax_wav, ax_ph]:
    ax.set_facecolor('#0f0f23')
    ax.tick_params(colors='white')
    for spine in ax.spines.values():
        spine.set_edgecolor('#444466')

ax3d.set_facecolor('#0f0f23')

# ── helper: draw the 3-D mass-spring-damper ────────────────────────────────
def draw_3d(ax, disp, c):
    ax.cla()
    ax.set_facecolor('#0f0f23')

    # colour the spring cyan, damper orange, mass blue
    wall_x = -0.5

    # --- wall ---
    wall_verts = [[(wall_x, -0.3, 0),
                   (wall_x,  0.3, 0),
                   (wall_x,  0.3, 0.6),
                   (wall_x, -0.3, 0.6)]]
    wall = Poly3DCollection(wall_verts, alpha=0.6,
                            facecolor='#555577', edgecolor='#8888aa')
    ax.add_collection3d(wall)

    # --- spring (zigzag along x-axis, centred at z=0.45) ---
    spring_end = disp          # right end of spring
    n_coils    = 8
    xs = np.linspace(wall_x, spring_end, n_coils * 20)
    ys = 0.12 * np.sin(np.linspace(0, n_coils * 2 * np.pi, len(xs)))
    zs = np.full_like(xs, 0.45)
    ax.plot(xs, ys, zs, color='#00ffcc', lw=2, label='Spring')

    # --- damper (parallel path, z=0.15) ---
    # cylinder body
    dam_xs = np.linspace(wall_x, spring_end, 60)
    dam_ys = 0.08 * np.sin(np.linspace(0, 2 * np.pi, 60))
    dam_zs = np.full_like(dam_xs, 0.15)
    ax.plot(dam_xs, dam_ys, dam_zs, color='#ff8800', lw=3, label='Damper')
    # piston rod
    ax.plot([spring_end - 0.05, spring_end],
            [0, 0], [0.15, 0.15],
            color='#ffcc00', lw=4)

    # --- mass (box) ---
    bx, by, bz = disp, -0.2, 0.0
    bw, bd, bh  = 0.25, 0.4, 0.6
    verts = [
        [(bx, by, bz),       (bx+bw, by, bz),       (bx+bw, by+bd, bz),       (bx, by+bd, bz)],
        [(bx, by, bz+bh),    (bx+bw, by, bz+bh),    (bx+bw, by+bd, bz+bh),    (bx, by+bd, bz+bh)],
        [(bx, by, bz),       (bx+bw, by, bz),        (bx+bw, by, bz+bh),       (bx, by, bz+bh)],
        [(bx, by+bd, bz),    (bx+bw, by+bd, bz),     (bx+bw, by+bd, bz+bh),    (bx, by+bd, bz+bh)],
        [(bx, by, bz),       (bx, by+bd, bz),         (bx, by+bd, bz+bh),       (bx, by, bz+bh)],
        [(bx+bw, by, bz),    (bx+bw, by+bd, bz),     (bx+bw, by+bd, bz+bh),    (bx+bw, by, bz+bh)],
    ]
    mass_col = Poly3DCollection(verts, alpha=0.85,
                                facecolor='#3399ff', edgecolor='#aaddff')
    ax.add_collection3d(mass_col)

    # --- ground ---
    gx = np.array([wall_x - 0.1, 1.8])
    gy = np.array([-0.5, 0.5])
    GX, GY = np.meshgrid(gx, gy)
    GZ = np.zeros_like(GX)
    ax.plot_surface(GX, GY, GZ, alpha=0.2, color='#334455')

    # labels / limits
    ax.set_xlim(wall_x - 0.1, 1.8)
    ax.set_ylim(-0.5, 0.5)
    ax.set_zlim(-0.1, 0.8)
    ax.set_xlabel('X', color='white', fontsize=8)
    ax.set_ylabel('Y', color='white', fontsize=8)
    ax.set_zlabel('Z', color='white', fontsize=8)
    ax.tick_params(colors='white', labelsize=7)
    ax.xaxis.pane.fill = False
    ax.yaxis.pane.fill = False
    ax.zaxis.pane.fill = False
    ax.xaxis.pane.set_edgecolor('#334455')
    ax.yaxis.pane.set_edgecolor('#334455')
    ax.zaxis.pane.set_edgecolor('#334455')
    ax.grid(True, color='#334455', linewidth=0.5)

    wn   = np.sqrt(k / m)
    zeta = c / (2 * np.sqrt(m * k))
    regime = ('Under-damped' if zeta < 1
              else 'Critically damped' if abs(zeta - 1) < 0.01
              else 'Over-damped')
    ax.set_title(f'3D Mass-Spring-Damper\nc={c:.2f}  ζ={zeta:.3f}  ({regime})',
                 color='white', fontsize=9, pad=6)

# ── initial plot ───────────────────────────────────────────────────────────
x_disp = solve(c0)

# 3-D snapshot at t=0 (equilibrium displaced by x0[0])
draw_3d(ax3d, x0[0], c0)

# waveform
line_wav, = ax_wav.plot(t, x_disp, color='#00ffcc', lw=1.5)
ax_wav.axhline(0, color='#555577', lw=0.8, ls='--')
ax_wav.set_xlabel('Time [s]', color='white', fontsize=9)
ax_wav.set_ylabel('Displacement [m]', color='white', fontsize=9)
ax_wav.set_title('Output Waveform', color='white', fontsize=10)
ax_wav.set_xlim(t[0], t[-1])
ax_wav.set_ylim(-1.2, 1.2)

# phase portrait
line_ph, = ax_ph.plot(x_disp, np.gradient(x_disp, t),
                      color='#ff8800', lw=1.2)
ax_ph.set_xlabel('Displacement [m]', color='white', fontsize=9)
ax_ph.set_ylabel('Velocity [m/s]', color='white', fontsize=9)
ax_ph.set_title('Phase Portrait', color='white', fontsize=10)

fig.suptitle('Mass-Spring-Damper System', color='white',
             fontsize=13, fontweight='bold')

# ── slider ─────────────────────────────────────────────────────────────────
ax_slider = fig.add_axes([0.25, 0.04, 0.50, 0.025])
ax_slider.set_facecolor('#1a1a2e')
slider = Slider(ax_slider, 'Damping c', 0.01, 12.0,
                valinit=c0, color='#3399ff')
slider.label.set_color('white')
slider.valtext.set_color('white')

def update(val):
    c = slider.val
    xd = solve(c)
    vd = np.gradient(xd, t)

    line_wav.set_ydata(xd)
    line_ph.set_xdata(xd)
    line_ph.set_ydata(vd)

    ax_ph.relim()
    ax_ph.autoscale_view()

    draw_3d(ax3d, x0[0], c)
    fig.canvas.draw_idle()
    print(f"  c={c:.3f}  ζ={c/(2*np.sqrt(m*k)):.4f}")

slider.on_changed(update)

print("Visualization ready. Use the slider to change damping coefficient.")
plt.show()