# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# AutoCoder System - System Monitor

import psutil
import time
import os
import platform
from datetime import datetime
import threading

try:
    import curses
    CURSES_AVAILABLE = True
except ImportError:
    CURSES_AVAILABLE = False


# ============================================================
# DATA COLLECTION
# ============================================================

class SystemMonitor:
    def __init__(self):
        self.data = {}
        self.running = True
        self.history = {
            "cpu": [],
            "memory": [],
            "network_sent": [],
            "network_recv": []
        }
        self.max_history = 30
        self.net_io_prev = psutil.net_io_counters()
        self.prev_time = time.time()

    def collect(self):
        now = time.time()
        elapsed = max(now - self.prev_time, 0.001)

        # CPU (warm-up call improves accuracy)
        psutil.cpu_percent(interval=0.1)
        cpu_percent = psutil.cpu_percent(interval=None)
        cpu_per_core = psutil.cpu_percent(interval=None, percpu=True)
        cpu_freq = psutil.cpu_freq()

        # Memory
        mem = psutil.virtual_memory()
        swap = psutil.swap_memory()

        # Disk (portable)
        disk = psutil.disk_usage(os.path.abspath(os.sep))
        disk_io = psutil.disk_io_counters()

        # Network
        net_io = psutil.net_io_counters()
        net_sent_speed = (net_io.bytes_sent - self.net_io_prev.bytes_sent) / elapsed
        net_recv_speed = (net_io.bytes_recv - self.net_io_prev.bytes_recv) / elapsed
        self.net_io_prev = net_io
        self.prev_time = now

        # Processes
        processes = []
        for proc in psutil.process_iter(['pid', 'name', 'cpu_percent', 'memory_percent', 'status']):
            try:
                processes.append(proc.info)
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass
        top_processes = sorted(processes, key=lambda x: x['cpu_percent'] or 0, reverse=True)[:8]

        # Battery
        battery = psutil.sensors_battery() if hasattr(psutil, 'sensors_battery') else None

        # Temps
        temps = {}
        if hasattr(psutil, 'sensors_temperatures'):
            try:
                temps = psutil.sensors_temperatures()
            except Exception:
                pass

        self.data = {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "cpu": {
                "percent": cpu_percent,
                "per_core": cpu_per_core,
                "freq_current": cpu_freq.current if cpu_freq else 0,
                "freq_max": cpu_freq.max if cpu_freq else 0,
                "count_logical": psutil.cpu_count(logical=True),
                "count_physical": psutil.cpu_count(logical=False),
            },
            "memory": {
                "total": mem.total,
                "used": mem.used,
                "available": mem.available,
                "percent": mem.percent,
                "swap_total": swap.total,
                "swap_used": swap.used,
                "swap_percent": swap.percent,
            },
            "disk": {
                "total": disk.total,
                "used": disk.used,
                "free": disk.free,
                "percent": disk.percent,
                "read_bytes": disk_io.read_bytes if disk_io else 0,
                "write_bytes": disk_io.write_bytes if disk_io else 0,
            },
            "network": {
                "bytes_sent": net_io.bytes_sent,
                "bytes_recv": net_io.bytes_recv,
                "sent_speed": net_sent_speed,
                "recv_speed": net_recv_speed,
            },
            "processes": top_processes,
            "battery": battery,
            "temps": temps,
            "platform": platform.system(),
            "hostname": platform.node(),
            "uptime": time.time() - psutil.boot_time(),
        }

        self._update_history("cpu", cpu_percent)
        self._update_history("memory", mem.percent)
        self._update_history("network_sent", net_sent_speed / 1024)
        self._update_history("network_recv", net_recv_speed / 1024)

    def _update_history(self, key, value):
        self.history[key].append(value)
        if len(self.history[key]) > self.max_history:
            self.history[key].pop(0)

    def start_background(self, interval=1.0):
        def loop():
            while self.running:
                self.collect()
                time.sleep(interval)
        threading.Thread(target=loop, daemon=True).start()

    def stop(self):
        self.running = False


# ============================================================
# SIMPLE TEXT VIEW (fallback or default)
# ============================================================

def bytes_to_human(n):
    for unit in ['B','KB','MB','GB','TB']:
        if n < 1024:
            return f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} PB"

def seconds_to_human(s):
    d = int(s // 86400)
    h = int((s % 86400) // 3600)
    m = int((s % 3600) // 60)
    return f"{d}d {h}h {m}m"

def make_bar(p, w=30):
    filled = int(w * p / 100)
    return "[" + "#" * filled + "-" * (w - filled) + "]"


def plain_text_monitor(monitor):
    monitor.collect()
    monitor.start_background(interval=2.0)

    while True:
        try:
            time.sleep(1)
            d = monitor.data
            if not d:
                continue

            os.system('cls' if os.name == 'nt' else 'clear')

            print("="*60)
            print(f"SYSTEM MONITOR | {d['hostname']} | {d['timestamp']}")
            print(f"Uptime: {seconds_to_human(d['uptime'])}")
            print("="*60)

            cpu = d["cpu"]
            print("\nCPU")
            print(f"{cpu['percent']:5.1f}% {make_bar(cpu['percent'])}")

            mem = d["memory"]
            print("\nMEMORY")
            print(f"{mem['percent']:5.1f}% {make_bar(mem['percent'])}")

            disk = d["disk"]
            print("\nDISK")
            print(f"{disk['percent']:5.1f}% {make_bar(disk['percent'])}")

            net = d["network"]
            print("\nNETWORK")
            print(f"Up: {bytes_to_human(net['sent_speed'])}/s")
            print(f"Down: {bytes_to_human(net['recv_speed'])}/s")

            print("\nTop Processes")
            for p in d["processes"][:5]:
                print(f"{p['pid']:>6} {p['name'][:20]:<20} {p['cpu_percent']:5.1f}%")

            print("\nCtrl+C to quit")

        except KeyboardInterrupt:
            monitor.stop()
            break


# ============================================================
# MAIN
# ============================================================

def main():
    monitor = SystemMonitor()
    plain_text_monitor(monitor)

if __name__ == "__main__":
    main()