# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-14 06:48:38
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# Define the matrix A
A = np.array([[1, 0, 0],
              [2, 2, 0],
              [3, 3, 3]], dtype=float)

# Compute the true inverse for comparison
A_inv_true = np.linalg.inv(A)

print("Matrix A:")
print(A)
print("\nTrue Inverse (numpy):")
print(A_inv_true)

# ─── Newton-Schulz Iteration ───────────────────────────────────────────────
# X_{k+1} = X_k (2I - A X_k)
# Initialization: X_0 = alpha * A^T  where alpha = 1 / (||A||_1 * ||A||_inf)
# This guarantees convergence when ||I - A X_0|| < 1

norm_1   = np.linalg.norm(A, ord=1)
norm_inf = np.linalg.norm(A, ord=np.inf)
alpha    = 1.0 / (norm_1 * norm_inf)

X = alpha * A.T          # Initial guess
I = np.eye(A.shape[0])

errors          = []     # ||X_k - A^{-1}||_F
residuals       = []     # ||I - A X_k||_F
frobenius_norms = []     # ||X_k||_F

max_iter = 50
tol      = 1e-12

print("\nNewton-Schulz Iterations:")
print(f"{'Iter':>5}  {'||X_k - A_inv||_F':>20}  {'||I - A X_k||_F':>18}")
print("-" * 50)

for k in range(max_iter):
    err      = np.linalg.norm(X - A_inv_true, 'fro')
    residual = np.linalg.norm(I - A @ X, 'fro')
    frob     = np.linalg.norm(X, 'fro')

    errors.append(err)
    residuals.append(residual)
    frobenius_norms.append(frob)

    print(f"{k:>5}  {err:>20.6e}  {residual:>18.6e}")

    if err < tol:
        print(f"\nConverged at iteration {k}  (error < {tol})")
        break

    # Newton-Schulz update
    X = X @ (2 * I - A @ X)

X_ns = X   # Final approximation

print("\nNewton-Schulz Inverse:")
print(X_ns)
print(f"\nFinal error ||X - A^{{-1}}||_F = {errors[-1]:.6e}")

# ─── Plotting ──────────────────────────────────────────────────────────────
iters = list(range(len(errors)))

fig = plt.figure(figsize=(14, 10), facecolor='#0d1117')
fig.suptitle('Newton-Schulz Matrix Inversion  -  Convergence Analysis',
             fontsize=16, color='white', fontweight='bold', y=0.97)

gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.42, wspace=0.35,
                       left=0.08, right=0.96, top=0.91, bottom=0.08)

ax_colors = ['#0d1117'] * 4
line_colors = ['#00d4ff', '#ff6b6b', '#a8ff78', '#ffd700']

# ── Plot 1: Error vs Iteration (log scale) ──────────────────────────────
ax1 = fig.add_subplot(gs[0, 0], facecolor='#161b22')
ax1.semilogy(iters, errors, color=line_colors[0], linewidth=2.2,
             marker='o', markersize=5, markerfacecolor='white',
             markeredgecolor=line_colors[0], label='||X_k - A_inv||_F')
ax1.set_title('Error vs Iteration', color='white', fontsize=12, pad=8)
ax1.set_xlabel('Iteration', color='#aaaaaa', fontsize=10)
ax1.set_ylabel('Frobenius Error (log)', color='#aaaaaa', fontsize=10)
ax1.tick_params(colors='#aaaaaa')
ax1.spines[:].set_color('#30363d')
ax1.grid(True, color='#21262d', linestyle='--', linewidth=0.8)
ax1.legend(fontsize=9, facecolor='#21262d', edgecolor='#30363d',
           labelcolor='white')

# ── Plot 2: Residual vs Iteration (log scale) ───────────────────────────
ax2 = fig.add_subplot(gs[0, 1], facecolor='#161b22')
ax2.semilogy(iters, residuals, color=line_colors[1], linewidth=2.2,
             marker='s', markersize=5, markerfacecolor='white',
             markeredgecolor=line_colors[1], label='||I - A X_k||_F')
ax2.set_title('Residual vs Iteration', color='white', fontsize=12, pad=8)
ax2.set_xlabel('Iteration', color='#aaaaaa', fontsize=10)
ax2.set_ylabel('Residual (log)', color='#aaaaaa', fontsize=10)
ax2.tick_params(colors='#aaaaaa')
ax2.spines[:].set_color('#30363d')
ax2.grid(True, color='#21262d', linestyle='--', linewidth=0.8)
ax2.legend(fontsize=9, facecolor='#21262d', edgecolor='#30363d',
           labelcolor='white')

# ── Plot 3: Frobenius norm of X_k ───────────────────────────────────────
ax3 = fig.add_subplot(gs[1, 0], facecolor='#161b22')
ax3.plot(iters, frobenius_norms, color=line_colors[2], linewidth=2.2,
         marker='^', markersize=5, markerfacecolor='white',
         markeredgecolor=line_colors[2], label='||X_k||_F')
true_frob = np.linalg.norm(A_inv_true, 'fro')
ax3.axhline(true_frob, color='#ffd700', linestyle='--', linewidth=1.5,
            label=f'||A_inv||_F = {true_frob:.4f}')
ax3.set_title('Frobenius Norm of Iterate X_k', color='white', fontsize=12, pad=8)
ax3.set_xlabel('Iteration', color='#aaaaaa', fontsize=10)
ax3.set_ylabel('||X_k||_F', color='#aaaaaa', fontsize=10)
ax3.tick_params(colors='#aaaaaa')
ax3.spines[:].set_color('#30363d')
ax3.grid(True, color='#21262d', linestyle='--', linewidth=0.8)
ax3.legend(fontsize=9, facecolor='#21262d', edgecolor='#30363d',
           labelcolor='white')

# ── Plot 4: Heatmap comparison of true vs NS inverse ────────────────────
ax4 = fig.add_subplot(gs[1, 1], facecolor='#161b22')

# Stack true and NS inverse side by side for visual comparison
combined = np.hstack([A_inv_true, np.full((3, 1), np.nan), X_ns])
im = ax4.imshow(combined, cmap='RdYlGn', aspect='auto',
                vmin=combined[~np.isnan(combined)].min(),
                vmax=combined[~np.isnan(combined)].max())

ax4.set_title('True Inverse  |  NS Inverse', color='white', fontsize=12, pad=8)
ax4.set_xticks([0, 1, 2, 4, 5, 6])
ax4.set_xticklabels(['c1', 'c2', 'c3', 'c1', 'c2', 'c3'],
                    color='#aaaaaa', fontsize=9)
ax4.set_yticks([0, 1, 2])
ax4.set_yticklabels(['r1', 'r2', 'r3'], color='#aaaaaa', fontsize=9)
ax4.spines[:].set_color('#30363d')

# Annotate cells with values
for i in range(3):
    for j in [0, 1, 2, 4, 5, 6]:
        col_idx = j if j < 3 else j - 4
        matrix  = A_inv_true if j < 3 else X_ns
        val     = matrix[i, col_idx]
        ax4.text(j, i, f'{val:.3f}', ha='center', va='center',
                 color='black', fontsize=8, fontweight='bold')

# Divider line
ax4.axvline(3, color='white', linewidth=2)
plt.colorbar(im, ax=ax4, fraction=0.046, pad=0.04).ax.yaxis.set_tick_params(color='white')

plt.savefig('newton_schulz_convergence.png', dpi=150, bbox_inches='tight',
            facecolor='#0d1117')
print("\nPlot saved as 'newton_schulz_convergence.png'")
plt.show()