# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-26 15:51:03
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.collections import LineCollection
from matplotlib.lines import Line2D

# -- Physics parameters ------------------------------------------------------
G  = 9.81
L1 = 1.0
L2 = 1.0
M1 = 1.0
M2 = 1.0

def derivatives(state, t):
    th1, w1, th2, w2 = state
    d  = th2 - th1
    sd = np.sin(d)
    cd = np.cos(d)
    den1 = (M1 + M2) * L1 - M2 * L1 * cd ** 2
    den2 = (L2 / L1) * den1

    dth1 = w1
    dw1  = (M2 * L1 * w1**2 * sd * cd
            + M2 * G * np.sin(th2) * cd
            + M2 * L2 * w2**2 * sd
            - (M1 + M2) * G * np.sin(th1)) / den1

    dth2 = w2
    dw2  = (-M2 * L2 * w2**2 * sd * cd
            + (M1 + M2) * G * np.sin(th1) * cd
            - (M1 + M2) * L1 * w1**2 * sd
            - (M1 + M2) * G * np.sin(th2)) / den2

    return np.array([dth1, dw1, dth2, dw2])

def rk4(state, t, dt):
    k1 = derivatives(state, t)
    k2 = derivatives(state + 0.5*dt*k1, t + 0.5*dt)
    k3 = derivatives(state + 0.5*dt*k2, t + 0.5*dt)
    k4 = derivatives(state + dt*k3,     t + dt)
    return state + (dt/6.0)*(k1 + 2*k2 + 2*k3 + k4)

# -- Simulation --------------------------------------------------------------
dt      = 0.02
T_total = 30.0
steps   = int(T_total / dt)

eps = 0.001
ic1 = np.array([np.pi/2,       0.0, np.pi/2,       0.0])
ic2 = np.array([np.pi/2 + eps, 0.0, np.pi/2 + eps, 0.0])

def simulate(ic):
    states = np.empty((steps, 4))
    states[0] = ic
    for i in range(1, steps):
        states[i] = rk4(states[i-1], i*dt, dt)
    return states

print("Simulating pendulum 1 ...")
s1 = simulate(ic1)
print("Simulating pendulum 2 ...")
s2 = simulate(ic2)

def to_xy(states):
    x1 =  L1 * np.sin(states[:, 0])
    y1 = -L1 * np.cos(states[:, 0])
    x2 = x1 + L2 * np.sin(states[:, 2])
    y2 = y1 - L2 * np.cos(states[:, 2])
    return x1, y1, x2, y2

x1a, y1a, x2a, y2a = to_xy(s1)
x1b, y1b, x2b, y2b = to_xy(s2)

print("Simulation complete. Building animation ...")

# -- Colours -----------------------------------------------------------------
COL_A     = "#00FFFF"
COL_B     = "#FF4080"
TRAIL_LEN = 300

# -- Figure ------------------------------------------------------------------
plt.style.use("dark_background")
fig, ax = plt.subplots(figsize=(8, 8), facecolor="#050510")
ax.set_facecolor("#050510")
ax.set_xlim(-2.3, 2.3)
ax.set_ylim(-2.5, 2.1)
ax.set_aspect("equal")
ax.axis("off")

fig.suptitle("Double Pendulum  |  Chaos Theory", y=0.98,
             color="white", fontsize=14, fontweight="bold", fontfamily="monospace")
ax.set_title("Two trajectories, initial angle offset = " + str(eps) + " rad",
             color="#aaaacc", fontsize=9, pad=6, fontfamily="monospace")

# -- Static glow rings at pivot ----------------------------------------------
for r, a in [(0.08, 0.15), (0.05, 0.30), (0.025, 0.60)]:
    ax.add_patch(plt.Circle((0, 0), r, color="white", alpha=a, zorder=3))

# -- Trail line collections --------------------------------------------------
def make_lc(color):
    lc = LineCollection([], linewidths=1.2, alpha=0.75,
                        color=color, capstyle="round")
    ax.add_collection(lc)
    return lc

trail_a = make_lc(COL_A)
trail_b = make_lc(COL_B)

glow_a = make_lc(COL_A)
glow_a.set_linewidth(4)
glow_a.set_alpha(0.15)

glow_b = make_lc(COL_B)
glow_b.set_linewidth(4)
glow_b.set_alpha(0.15)

# -- Rod lines ---------------------------------------------------------------
rod_a1, = ax.plot([], [], color=COL_A, lw=1.5, alpha=0.7, zorder=5)
rod_a2, = ax.plot([], [], color=COL_A, lw=1.5, alpha=0.7, zorder=5)
rod_b1, = ax.plot([], [], color=COL_B, lw=1.5, alpha=0.7, zorder=5)
rod_b2, = ax.plot([], [], color=COL_B, lw=1.5, alpha=0.7, zorder=5)

# -- Bob markers -------------------------------------------------------------
bob_a1, = ax.plot([], [], 'o', color=COL_A, ms=7,  zorder=8,
                  markeredgecolor="white", markeredgewidth=0.5)
bob_a2, = ax.plot([], [], 'o', color=COL_A, ms=10, zorder=8,
                  markeredgecolor="white", markeredgewidth=0.5)
bob_b1, = ax.plot([], [], 'o', color=COL_B, ms=7,  zorder=8,
                  markeredgecolor="white", markeredgewidth=0.5)
bob_b2, = ax.plot([], [], 'o', color=COL_B, ms=10, zorder=8,
                  markeredgecolor="white", markeredgewidth=0.5)

# -- Legend ------------------------------------------------------------------
legend_elements = [
    Line2D([0], [0], color=COL_A, lw=2, label="IC 1  (theta = pi/2)"),
    Line2D([0], [0], color=COL_B, lw=2, label="IC 2  (theta = pi/2 + " + str(eps) + ")"),
]
ax.legend(handles=legend_elements, loc="lower left",
          framealpha=0.25, fontsize=8, labelcolor="white",
          facecolor="#111122", edgecolor="#333355")

# -- Time label --------------------------------------------------------------
time_text = ax.text(0.02, 0.96, "", transform=ax.transAxes,
                    color="#888899", fontsize=9, fontfamily="monospace",
                    va="top")

# -- Segment builder ---------------------------------------------------------
def build_segments(xs, ys):
    pts = np.column_stack([xs, ys]).reshape(-1, 1, 2)
    return np.concatenate([pts[:-1], pts[1:]], axis=1)

# -- Animation ---------------------------------------------------------------
SKIP = 2

def init():
    for artist in (trail_a, trail_b, glow_a, glow_b,
                   rod_a1, rod_a2, rod_b1, rod_b2,
                   bob_a1, bob_a2, bob_b1, bob_b2):
        try:
            artist.set_data([], [])
        except AttributeError:
            artist.set_segments([])
    time_text.set_text("")
    return (trail_a, trail_b, glow_a, glow_b,
            rod_a1, rod_a2, rod_b1, rod_b2,
            bob_a1, bob_a2, bob_b1, bob_b2, time_text)

def update(frame):
    i = frame * SKIP
    if i >= steps:
        i = steps - 1

    lo = max(0, i - TRAIL_LEN)

    # Pendulum A
    tx, ty = x2a[lo:i+1], y2a[lo:i+1]
    if len(tx) > 1:
        segs = build_segments(tx, ty)
        n = len(segs)
        trail_a.set_segments(segs)
        trail_a.set_array(np.linspace(0, 1, n))
        glow_a.set_segments(segs)

    rod_a1.set_data([0, x1a[i]], [0, y1a[i]])
    rod_a2.set_data([x1a[i], x2a[i]], [y1a[i], y2a[i]])
    bob_a1.set_data([x1a[i]], [y1a[i]])
    bob_a2.set_data([x2a[i]], [y2a[i]])

    # Pendulum B
    tx, ty = x2b[lo:i+1], y2b[lo:i+1]
    if len(tx) > 1:
        segs = build_segments(tx, ty)
        trail_b.set_segments(segs)
        glow_b.set_segments(segs)

    rod_b1.set_data([0, x1b[i]], [0, y1b[i]])
    rod_b2.set_data([x1b[i], x2b[i]], [y1b[i], y2b[i]])
    bob_b1.set_data([x1b[i]], [y1b[i]])
    bob_b2.set_data([x2b[i]], [y2b[i]])

    time_text.set_text("t = " + f"{i*dt:.2f}" + " s")

    return (trail_a, trail_b, glow_a, glow_b,
            rod_a1, rod_a2, rod_b1, rod_b2,
            bob_a1, bob_a2, bob_b1, bob_b2, time_text)

frames = steps // SKIP
ani = animation.FuncAnimation(
    fig, update, frames=frames,
    init_func=init, interval=20, blit=True
)

print("Launching animation window ...")
plt.subplots_adjust(left=0.05, right=0.95, top=0.93, bottom=0.02)
plt.show()
print("Done.")