# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-08 18:20:48
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# Auckland North Shore petrol prices - March 2026
# Data sourced from CardLink PriceWatch and GlobalPetrolPrices.com
# Prices in NZD per litre as of early March 2026

# Fuel brands available in Auckland (North Shore area)
brands = ['BP', 'Caltex', 'Mobil', 'Z Energy', 'Challenge', 'Gull', 'Gas Alley']

# Prices per litre (NZD) for different fuel types
# Based on Auckland region data from CardLink PriceWatch (March 2026)
prices_98 = [2.939, None, 2.879, None, None, None, None]
prices_95 = [2.869, 2.827, 2.839, 2.849, 2.959, 2.599, 2.929]
prices_91 = [2.639, 2.647, 2.559, 2.659, 2.689, 2.449, 2.650]
prices_diesel = [2.099, 2.027, 2.109, 2.119, 1.919, 1.819, 2.029]

# Replace None with NaN for plotting
def clean(lst):
    return [v if v is not None else np.nan for v in lst]

p98 = clean(prices_98)
p95 = clean(prices_95)
p91 = clean(prices_91)
pdiesel = clean(prices_diesel)

x = np.arange(len(brands))
width = 0.2

# Historical weekly trend data for North Shore / Auckland
# GlobalPetrolPrices.com: 24-Nov-2025 to 02-Mar-2026
# Average 2.90/L, min 2.83 on 16-Feb-2026, max 2.95 on 01-Dec-2025
trend_dates = [
    '24-Nov-25', '01-Dec-25', '08-Dec-25', '15-Dec-25', '22-Dec-25',
    '29-Dec-25', '05-Jan-26', '12-Jan-26', '19-Jan-26', '26-Jan-26',
    '02-Feb-26', '09-Feb-26', '16-Feb-26', '23-Feb-26', '02-Mar-26'
]
# 95 octane trend prices (NZD/L) - Auckland North Shore area
trend_95 = [2.95, 2.95, 2.93, 2.91, 2.90, 2.89, 2.91, 2.92, 2.90, 2.88,
            2.86, 2.85, 2.83, 2.84, 2.85]

# ── Figure layout ──────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(16, 12))
fig.patch.set_facecolor('#1a1a2e')

# Title
fig.text(0.5, 0.97, 'Auckland North Shore - Petrol Prices March 2026',
         ha='center', va='top', fontsize=18, fontweight='bold',
         color='white', fontfamily='DejaVu Sans')
fig.text(0.5, 0.935, 'Source: CardLink PriceWatch & GlobalPetrolPrices.com  |  Prices in NZD per litre',
         ha='center', va='top', fontsize=10, color='#aaaacc')

# ── Plot 1: Bar chart by brand ─────────────────────────────────────────────────
ax1 = fig.add_axes([0.06, 0.42, 0.56, 0.46])
ax1.set_facecolor('#16213e')

colors = ['#e63946', '#f4a261', '#2a9d8f', '#457b9d']
labels = ['98 Octane', '95/96 Octane', '91 Octane', 'Diesel']
data_sets = [p98, p95, p91, pdiesel]

bars_list = []
for i, (data, color, label) in enumerate(zip(data_sets, colors, labels)):
    bars = ax1.bar(x + i * width - 1.5 * width, data, width,
                   label=label, color=color, alpha=0.88,
                   edgecolor='white', linewidth=0.4, zorder=3)
    bars_list.append(bars)
    # Add price labels on bars
    for bar, val in zip(bars, data):
        if not np.isnan(val):
            ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.008,
                     f'${val:.2f}', ha='center', va='bottom',
                     fontsize=6.5, color='white', fontweight='bold')

ax1.set_xticks(x)
ax1.set_xticklabels(brands, rotation=15, ha='right', fontsize=10, color='white')
ax1.set_ylabel('Price (NZD per litre)', fontsize=11, color='white')
ax1.set_title('Fuel Prices by Brand - Auckland North Shore (March 2026)',
              fontsize=12, color='white', pad=10)
ax1.set_ylim(1.6, 3.2)
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'${v:.2f}'))
ax1.tick_params(colors='white', labelsize=9)
ax1.spines['bottom'].set_color('#444466')
ax1.spines['left'].set_color('#444466')
ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)
ax1.yaxis.label.set_color('white')
ax1.grid(axis='y', color='#333355', linestyle='--', alpha=0.5, zorder=0)
legend = ax1.legend(loc='upper right', fontsize=9, framealpha=0.3,
                    facecolor='#16213e', edgecolor='#444466', labelcolor='white')

# ── Plot 2: Price trend line chart ────────────────────────────────────────────
ax2 = fig.add_axes([0.66, 0.42, 0.32, 0.46])
ax2.set_facecolor('#16213e')

ax2.plot(range(len(trend_dates)), trend_95, color='#f4a261',
         linewidth=2.5, marker='o', markersize=5, markerfacecolor='white',
         markeredgecolor='#f4a261', zorder=3, label='95 Octane (Avg)')

# Shade area under line
ax2.fill_between(range(len(trend_dates)), trend_95, min(trend_95) - 0.02,
                 alpha=0.2, color='#f4a261')

# Annotate min and max
min_idx = trend_95.index(min(trend_95))
max_idx = trend_95.index(max(trend_95))
ax2.annotate(f'Min: ${min(trend_95):.2f}',
             xy=(min_idx, trend_95[min_idx]),
             xytext=(min_idx - 1.5, trend_95[min_idx] - 0.025),
             fontsize=8, color='#2a9d8f', fontweight='bold',
             arrowprops=dict(arrowstyle='->', color='#2a9d8f', lw=1.2))
ax2.annotate(f'Max: ${max(trend_95):.2f}',
             xy=(max_idx, trend_95[max_idx]),
             xytext=(max_idx + 0.3, trend_95[max_idx] + 0.015),
             fontsize=8, color='#e63946', fontweight='bold',
             arrowprops=dict(arrowstyle='->', color='#e63946', lw=1.2))

ax2.set_xticks(range(len(trend_dates)))
ax2.set_xticklabels(trend_dates, rotation=45, ha='right', fontsize=7, color='white')
ax2.set_ylabel('Price (NZD per litre)', fontsize=10, color='white')
ax2.set_title('95 Octane Weekly Trend\nNov 2025 - Mar 2026', fontsize=11, color='white', pad=8)
ax2.set_ylim(2.78, 3.00)
ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'${v:.2f}'))
ax2.tick_params(colors='white', labelsize=8)
ax2.spines['bottom'].set_color('#444466')
ax2.spines['left'].set_color('#444466')
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.yaxis.label.set_color('white')
ax2.grid(color='#333355', linestyle='--', alpha=0.5, zorder=0)

# ── Plot 3: Horizontal bar - cheapest vs most expensive 95 octane ─────────────
ax3 = fig.add_axes([0.06, 0.06, 0.40, 0.30])
ax3.set_facecolor('#16213e')

sorted_idx = np.argsort([v for v in p95])
sorted_brands = [brands[i] for i in sorted_idx]
sorted_prices = [p95[i] for i in sorted_idx]

bar_colors = ['#2a9d8f' if p == min(p95) else
              '#e63946' if p == max(p95) else '#457b9d'
              for p in sorted_prices]

hbars = ax3.barh(sorted_brands, sorted_prices, color=bar_colors,
                 edgecolor='white', linewidth=0.4, alpha=0.88, zorder=3)

for bar, val in zip(hbars, sorted_prices):
    ax3.text(val + 0.005, bar.get_y() + bar.get_height() / 2,
             f'${val:.3f}', va='center', fontsize=9,
             color='white', fontweight='bold')

ax3.set_xlabel('Price (NZD per litre)', fontsize=10, color='white')
ax3.set_title('95/96 Octane - Cheapest to Most Expensive\n(North Shore, March 2026)',
              fontsize=11, color='white', pad=8)
ax3.set_xlim(2.45, 3.05)
ax3.xaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'${v:.2f}'))
ax3.tick_params(colors='white', labelsize=9)
ax3.spines['bottom'].set_color('#444466')
ax3.spines['left'].set_color('#444466')
ax3.spines['top'].set_visible(False)
ax3.spines['right'].set_visible(False)
ax3.xaxis.label.set_color('white')
ax3.yaxis.label.set_color('white')
ax3.grid(axis='x', color='#333355', linestyle='--', alpha=0.5, zorder=0)

cheap_patch = mpatches.Patch(color='#2a9d8f', label='Cheapest')
exp_patch = mpatches.Patch(color='#e63946', label='Most Expensive')
mid_patch = mpatches.Patch(color='#457b9d', label='Mid-range')
ax3.legend(handles=[cheap_patch, mid_patch, exp_patch],
           loc='lower right', fontsize=8, framealpha=0.3,
           facecolor='#16213e', edgecolor='#444466', labelcolor='white')

# ── Plot 4: Summary stats box ─────────────────────────────────────────────────
ax4 = fig.add_axes([0.50, 0.06, 0.48, 0.30])
ax4.set_facecolor('#16213e')
ax4.set_xlim(0, 10)
ax4.set_ylim(0, 10)
ax4.axis('off')

ax4.text(5, 9.3, 'North Shore Price Summary - March 2026',
         ha='center', va='top', fontsize=12, fontweight='bold', color='white')

summary_data = [
    ('Fuel Type', 'Cheapest', 'Average', 'Most Expensive'),
    ('98 Octane',  '$2.879', '$2.909', '$2.939'),
    ('95/96 Oct',  '$2.599', '$2.784', '$2.959'),
    ('91 Octane',  '$2.449', '$2.606', '$2.689'),
    ('Diesel',     '$1.819', '$2.017', '$2.129'),
]

col_x = [0.5, 3.2, 5.8, 8.2]
row_colors = ['#2a4a6b', '#1a3a5b', '#1a3a5b', '#1a3a5b', '#1a3a5b']
text_colors_row = [['#aaccff', '#aaccff', '#aaccff', '#aaccff'],
                   ['white', '#2a9d8f', 'white', '#e63946'],
                   ['white', '#2a9d8f', 'white', '#e63946'],
                   ['white', '#2a9d8f', 'white', '#e63946'],
                   ['white', '#2a9d8f', 'white', '#e63946']]

for row_i, (row, rc, tc_row) in enumerate(zip(summary_data, row_colors, text_colors_row)):
    y_pos = 7.8 - row_i * 1.5
    rect = mpatches.FancyBboxPatch((0.1, y_pos - 0.55), 9.8, 1.1,
                                   boxstyle='round,pad=0.05',
                                   facecolor=rc, edgecolor='#444466',
                                   linewidth=0.5, zorder=2)
    ax4.add_patch(rect)
    for col_i, (cell, cx, tc) in enumerate(zip(row, col_x, tc_row)):
        fw = 'bold' if row_i == 0 else 'normal'
        ax4.text(cx, y_pos, cell, ha='left', va='center',
                 fontsize=9.5, color=tc, fontweight=fw, zorder=3)

# NZ average note
ax4.text(5, 0.4,
         'NZ National Average (02-Mar-2026): $2.66/L  |  Auckland Avg: $2.90/L',
         ha='center', va='bottom', fontsize=8.5, color='#aaaacc',
         style='italic')

plt.savefig('north_shore_petrol_prices_march2026.png', dpi=150,
            bbox_inches='tight', facecolor='#1a1a2e')
print("Chart saved as 'north_shore_petrol_prices_march2026.png'")
plt.show()
print("Done! Auckland North Shore petrol prices for March 2026 displayed.")
print("\nKey findings:")
print("  Cheapest 95 octane: Gull at $2.599/L")
print("  Most expensive 95 octane: Challenge at $2.959/L")
print("  Cheapest diesel: Gull at $1.819/L")
print("  NZ national average (02-Mar-2026): $2.66/L")
print("  Auckland area average: $2.90/L")