# Generated by: qwen3-coder:30b (Ollama)
# Date: 2026-03-03 12:42:30
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider
import control as ct

# Define the plant transfer function (example: G(s) = 1/(s^2 + 2s + 1))
num = [1]
den = [1, 2, 1]
plant = ct.tf(num, den)

# Define the PID controller transfer function
Kp = 1.0
Ki = 0.5
Kd = 0.1

# PID controller: C(s) = Kp + Ki/s + Kd*s
pid = ct.tf([Kd, Kp, Ki], [1, 0])

# Closed-loop system: T(s) = C(s)*G(s)/(1 + C(s)*G(s))
sys_cl = ct.feedback(pid * plant, 1)


# Create a square wave setpoint
def square_wave(t):
    return np.where((t % 2) < 1, 1, -1)


# Time vector
t = np.linspace(0, 10, 1000)

# Simulate the closed-loop system with square wave input
# We'll use a step input to simulate the square wave behavior
# For a square wave, we can simulate it as a series of step changes
# Here we'll simulate a square wave with period 2 seconds
u = np.array([square_wave(ti) for ti in t])

# Simulate the system response
t_sim, y_sim = ct.step_response(sys_cl, T=t)

# Create the plot
fig, ax = plt.subplots(figsize=(10, 6))
plt.subplots_adjust(bottom=0.35)

# Plot the response
line, = ax.plot(t_sim, y_sim, 'b-', linewidth=2)
ax.set_xlabel('Time (s)')
ax.set_ylabel('Response')
ax.set_title('Closed Loop System Response with PID Controller')
ax.grid(True)

# Set initial y-axis limits
ax.set_ylim(-1.5, 1.5)

# Create sliders
axcolor = 'lightgoldenrodyellow'
ax_Kp = plt.axes([0.2, 0.2, 0.6, 0.03], facecolor=axcolor)
ax_Ki = plt.axes([0.2, 0.15, 0.6, 0.03], facecolor=axcolor)
ax_Kd = plt.axes([0.2, 0.1, 0.6, 0.03], facecolor=axcolor)

s_Kp = Slider(ax_Kp, 'Kp', 0.0, 5.0, valinit=Kp)
s_Ki = Slider(ax_Ki, 'Ki', 0.0, 5.0, valinit=Ki)
s_Kd = Slider(ax_Kd, 'Kd', 0.0, 5.0, valinit=Kd)


# Update function for sliders
def update(val):
    Kp_new = s_Kp.val
    Ki_new = s_Ki.val
    Kd_new = s_Kd.val

    # Update the PID controller
    pid_new = ct.tf([Kd_new, Kp_new, Ki_new], [1, 0])

    # Recompute the closed-loop system
    sys_cl_new = ct.feedback(pid_new * plant, 1)

    # Simulate the system response
    t_sim_new, y_sim_new = ct.step_response(sys_cl_new, T=t)

    # Update the plot
    line.set_ydata(y_sim_new)

    # Autoscale y-axis
    y_min = np.min(y_sim_new)
    y_max = np.max(y_sim_new)
    y_range = y_max - y_min
    if y_range == 0:
        y_range = 1
    ax.set_ylim(y_min - 0.1 * y_range, y_max + 0.1 * y_range)

    fig.canvas.draw_idle()


# Connect the update function to the sliders
s_Kp.on_changed(update)
s_Ki.on_changed(update)
s_Kd.on_changed(update)

# Show the plot
plt.show()

print("Closed loop system with PID controller and square wave setpoint is ready.")
print("Use the sliders to adjust Kp, Ki, and Kd values.")
print("Y-axis is autoscaled.")