# Generated by: qwen/qwen3-coder (Ollama)
# Date: 2026-03-04 07:44:40
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider
import control as ct

print("Initializing Second-Order System with PID Controller...")
# Define system parameters
z = 0.1
w = 6.28e3

# Define the transfer function G(s)
num1 = [100]
den1 = [3.2e-3, 1, 0]
sys1 = ct.tf(num1, den1)

num2 = [w**2]
den2 = [1, 2*z*w, w**2]
sys2 = ct.tf(num2, den2)

G = sys1 * sys2


system_tf = G

# Convert to state-space for simulation
system_ss = ct.tf2ss(system_tf)

# Time vector for simulation
t = np.linspace(0, 10, 1000)

# Initial conditions
x0 = np.zeros((2, 1))

# Setpoint
setpoint = 1.0

# Create figure and axes
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))
plt.subplots_adjust(bottom=0.35)

# Initial empty plots
line_output, = ax1.plot([], [], label='System Output')
line_setpoint, = ax1.plot([], [], 'r--', label='Setpoint')
line_error, = ax2.plot([], [], 'g-', label='Steady-State Error')

# Configure axes
ax1.set_title('System Response with PID Control')
ax1.set_ylabel('Output')
ax1.legend()
ax1.grid(True)

ax2.set_title('Steady-State Error')
ax2.set_xlabel('Time [s]')
ax2.set_ylabel('Error')
ax2.legend()
ax2.grid(True)

# Create axes for sliders
ax_p = plt.axes([0.02, 0.25, 0.5, 0.03])
ax_i = plt.axes([0.02, 0.20, 0.5, 0.03])
ax_d = plt.axes([0.02, 0.15, 0.5, 0.03])

# Create sliders
slider_p = Slider(ax_p, 'P', 0.0, 1.0, valinit=0.17)
slider_i = Slider(ax_i, 'I', 0.0, 30.0, valinit=0.3)
slider_d = Slider(ax_d, 'D', 0.0, 0.05, valinit=0.01)


# Function to update plots
def update(val):
    Kp = slider_p.val
    Ki = slider_i.val
    Kd = slider_d.val

    # Define PID controller
    pid_tf = ct.TransferFunction([Kd, Kp, Ki], [1, 0])

    # Create closed-loop system
    closed_loop = ct.feedback(pid_tf * system_tf, 1)

    # Step response with setpoint
    t_out, y_out = ct.step_response(closed_loop, T=t)
    y_out = y_out * setpoint  # Scale by setpoint

    # Calculate error
    error = setpoint - y_out

    # Update plots
    line_output.set_data(t_out, y_out)
    line_setpoint.set_data(t_out, [setpoint] * len(t_out))
    line_error.set_data(t_out, error)

    # Auto-scale axes
    ax1.relim()
    ax1.autoscale_view()
    ax2.relim()
    ax2.autoscale_view()

    fig.canvas.draw_idle()


# Connect sliders to update function
slider_p.on_changed(update)
slider_i.on_changed(update)
slider_d.on_changed(update)

# Initial update
update(0)

print("System initialized. Use sliders to adjust PID parameters.")

plt.show()
