# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-18 09:16:32
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch
import matplotlib.patheffects as pe
import numpy as np

fig, ax = plt.subplots(figsize=(16, 10))
ax.set_xlim(0, 16)
ax.set_ylim(0, 10)
ax.axis('off')
ax.set_facecolor('#0d1117')
fig.patch.set_facecolor('#0d1117')

# ── colour palette ──────────────────────────────────────────────────────────
BG      = '#0d1117'
BOX_PD  = '#1a3a5c'
BOX_LPF = '#1a4a2e'
BOX_VCO = '#4a1a1a'
BOX_DIV = '#3a2a5c'
BORDER  = '#4fc3f7'
TEXT_C  = '#e0e0e0'
ARROW_C = '#4fc3f7'
WIRE_C  = '#78909c'
TITLE_C = '#4fc3f7'
SIGNAL_C= '#ffb300'

def draw_box(ax, cx, cy, w, h, label, sublabel, color, border):
    box = FancyBboxPatch((cx - w/2, cy - h/2), w, h,
                         boxstyle="round,pad=0.08",
                         facecolor=color, edgecolor=border, linewidth=2.5,
                         zorder=3)
    ax.add_patch(box)
    ax.text(cx, cy + 0.12, label, ha='center', va='center',
            fontsize=12, fontweight='bold', color=TEXT_C, zorder=4)
    if sublabel:
        ax.text(cx, cy - 0.38, sublabel, ha='center', va='center',
                fontsize=8.5, color='#aaaaaa', zorder=4)

def arrow(ax, x1, y1, x2, y2, color=ARROW_C, lw=2.2, style='->', head=12):
    ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                arrowprops=dict(arrowstyle=f'->', color=color,
                                lw=lw, mutation_scale=head),
                zorder=5)

def wire(ax, xs, ys, color=WIRE_C, lw=2.0, ls='-'):
    ax.plot(xs, ys, color=color, lw=lw, linestyle=ls, zorder=2)

# ── Title ────────────────────────────────────────────────────────────────────
ax.text(8, 9.4, 'Phase Locked Loop (PLL)', ha='center', va='center',
        fontsize=20, fontweight='bold', color=TITLE_C, zorder=6)
ax.text(8, 8.9, 'Closed-loop feedback system for phase/frequency synchronisation',
        ha='center', va='center', fontsize=10, color='#aaaaaa', zorder=6)

# ── Block positions (main forward path) ─────────────────────────────────────
#  Reference In  ->  PD  ->  LPF  ->  VCO  ->  Output
#                                        |
#                                     Divider
#                                        |
#                      <----- feedback -----

PD_X,  PD_Y  = 4.0,  5.5
LPF_X, LPF_Y = 7.2,  5.5
VCO_X, VCO_Y = 10.5, 5.5
DIV_X, DIV_Y = 10.5, 3.0

BW, BH = 2.2, 1.1   # box width / height

draw_box(ax, PD_X,  PD_Y,  BW, BH, 'Phase Detector', '(PD / XOR / Mixer)', BOX_PD,  BORDER)
draw_box(ax, LPF_X, LPF_Y, BW, BH, 'Low Pass Filter', '(Loop Filter)',      BOX_LPF, '#66bb6a')
draw_box(ax, VCO_X, VCO_Y, BW, BH, 'VCO',             '(Voltage Ctrl Osc)', BOX_VCO, '#ef5350')
draw_box(ax, DIV_X, DIV_Y, BW, BH, 'Feedback Divider', '(/N counter)',       BOX_DIV, '#ab47bc')

# ── Reference input ──────────────────────────────────────────────────────────
ax.text(1.1, 5.5, 'Reference\nInput', ha='center', va='center',
        fontsize=9, color=SIGNAL_C, fontweight='bold', zorder=6)
ax.text(1.1, 4.95, 'f_ref', ha='center', va='center',
        fontsize=8, color='#aaaaaa', zorder=6)
arrow(ax, 1.7, 5.5, PD_X - BW/2, 5.5)

# ── PD -> LPF ────────────────────────────────────────────────────────────────
arrow(ax, PD_X + BW/2, 5.5, LPF_X - BW/2, 5.5)
ax.text((PD_X + BW/2 + LPF_X - BW/2)/2, 5.75, 'Error\nVoltage',
        ha='center', va='center', fontsize=7.5, color='#ffcc80', zorder=6)

# ── LPF -> VCO ───────────────────────────────────────────────────────────────
arrow(ax, LPF_X + BW/2, 5.5, VCO_X - BW/2, 5.5)
ax.text((LPF_X + BW/2 + VCO_X - BW/2)/2, 5.75, 'Control\nVoltage',
        ha='center', va='center', fontsize=7.5, color='#ffcc80', zorder=6)

# ── VCO -> Output ────────────────────────────────────────────────────────────
arrow(ax, VCO_X + BW/2, 5.5, 14.5, 5.5)
ax.text(14.0, 5.85, 'Output', ha='center', va='center',
        fontsize=9, color=SIGNAL_C, fontweight='bold', zorder=6)
ax.text(14.0, 5.35, 'f_out', ha='center', va='center',
        fontsize=8, color='#aaaaaa', zorder=6)

# ── VCO down to Divider ───────────────────────────────────────────────────────
wire(ax, [VCO_X + BW/2 + 0.3, VCO_X + BW/2 + 0.3], [5.5, 3.0])
wire(ax, [VCO_X + BW/2 + 0.3, DIV_X + BW/2], [3.0, 3.0])
arrow(ax, VCO_X + BW/2, 5.5, VCO_X + BW/2 + 0.3, 5.5, color=WIRE_C)

# ── Divider -> feedback wire back to PD ──────────────────────────────────────
wire(ax, [DIV_X - BW/2, 2.0], [3.0, 3.0])
wire(ax, [2.0, 2.0], [3.0, 5.5])
arrow(ax, 2.0, 5.5, PD_X - BW/2, 5.5, color='#ab47bc')
ax.text(2.0, 2.6, 'Feedback\nSignal  f_fb',
        ha='center', va='center', fontsize=7.5, color='#ce93d8', zorder=6)

# ── Summing node label on PD ─────────────────────────────────────────────────
ax.text(PD_X, 6.25, 'Phase\nComparison', ha='center', va='center',
        fontsize=7.5, color='#80cbc4', zorder=6)

# ── Waveform sketches ────────────────────────────────────────────────────────
def sine_sketch(ax, cx, cy, amp, freq, color, label):
    t = np.linspace(0, 2*np.pi, 120)
    x = cx + (t / (2*np.pi)) * 1.4
    y = cy + amp * np.sin(freq * t)
    ax.plot(x, y, color=color, lw=1.5, zorder=4)
    ax.text(cx + 0.7, cy - amp - 0.25, label, ha='center',
            fontsize=7, color=color, zorder=5)

# Reference waveform
sine_sketch(ax, 0.2, 7.8, 0.35, 1, SIGNAL_C, 'f_ref')
# Output waveform (same freq, locked)
sine_sketch(ax, 2.0, 7.8, 0.35, 1, '#ef5350', 'f_out (locked)')
ax.text(1.8, 8.55, 'When Locked: f_out = N x f_ref  (same phase)',
        ha='center', fontsize=8, color='#80cbc4', zorder=5)

# ── Annotations / callouts ───────────────────────────────────────────────────
notes = [
    (PD_X,  4.5,  'Detects phase\ndifference between\nref and feedback'),
    (LPF_X, 4.5,  'Removes high-freq\nnoise from error\nsignal'),
    (VCO_X, 4.5,  'Adjusts output\nfrequency based on\ncontrol voltage'),
    (DIV_X, 1.85, 'Divides output by N\nto set multiplication\nratio'),
]
for nx, ny, txt in notes:
    ax.text(nx, ny, txt, ha='center', va='center', fontsize=7.2,
            color='#b0bec5', zorder=5,
            bbox=dict(boxstyle='round,pad=0.3', facecolor='#1c2833',
                      edgecolor='#37474f', linewidth=1))

# ── Legend / Applications ────────────────────────────────────────────────────
apps = [
    'Applications:',
    '  Radio / FM tuning & frequency synthesis',
    '  CPU clock generation & multiplication',
    '  Wireless comms: carrier recovery',
    '  Motor speed control',
    '  Signal demodulation',
]
for i, line in enumerate(apps):
    fw = 'bold' if i == 0 else 'normal'
    col = TITLE_C if i == 0 else '#cfd8dc'
    ax.text(0.3, 2.5 - i*0.38, line, ha='left', va='center',
            fontsize=8, color=col, fontweight=fw, zorder=6)

# ── Border frame ─────────────────────────────────────────────────────────────
frame = FancyBboxPatch((0.1, 0.1), 15.8, 9.7,
                       boxstyle="round,pad=0.1",
                       facecolor='none', edgecolor='#263238', linewidth=2, zorder=1)
ax.add_patch(frame)

plt.subplots_adjust(left=0.01, right=0.99, top=0.99, bottom=0.01)
plt.savefig('pll_diagram.png', dpi=150, bbox_inches='tight',
            facecolor=fig.get_facecolor())
print("PLL diagram saved to pll_diagram.png")
plt.show()