# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-05 18:21:45
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import urllib.request
from PIL import Image
import io

# Past 5 presidents of the USA with their data
presidents = [
    {
        "name": "Bill Clinton",
        "number": "42nd",
        "term": "1993 - 2001",
        "party": "Democratic",
        "born": "August 19, 1946",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Bill_Clinton.jpg/200px-Bill_Clinton.jpg",
        "color": "#3333AA"
    },
    {
        "name": "George W. Bush",
        "number": "43rd",
        "term": "2001 - 2009",
        "party": "Republican",
        "born": "July 6, 1946",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/George-W-Bush.jpeg/200px-George-W-Bush.jpeg",
        "color": "#AA3333"
    },
    {
        "name": "Barack Obama",
        "number": "44th",
        "term": "2009 - 2017",
        "party": "Democratic",
        "born": "August 4, 1961",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/President_Barack_Obama.jpg/200px-President_Barack_Obama.jpg",
        "color": "#3333AA"
    },
    {
        "name": "Donald Trump",
        "number": "45th/47th",
        "term": "2017 - 2021 / 2025-",
        "party": "Republican",
        "born": "June 14, 1946",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Donald_Trump_official_portrait.jpg/200px-Donald_Trump_official_portrait.jpg",
        "color": "#AA3333"
    },
    {
        "name": "Joe Biden",
        "number": "46th",
        "term": "2021 - 2025",
        "party": "Democratic",
        "born": "November 20, 1942",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Joe_Biden_presidential_portrait.jpg/200px-Joe_Biden_presidential_portrait.jpg",
        "color": "#3333AA"
    },
]

def load_image_from_url(url):
    """Load an image from a URL and return as PIL Image."""
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=10) as response:
            img_data = response.read()
        img = Image.open(io.BytesIO(img_data))
        img = img.convert("RGB")
        return img
    except Exception as e:
        print(f"Could not load image from {url}: {e}")
        return None

def create_placeholder_image(color_hex, name):
    """Create a simple colored placeholder image with initials."""
    img_array = np.ones((200, 200, 3), dtype=np.uint8)
    # Parse hex color
    r = int(color_hex[1:3], 16)
    g = int(color_hex[3:5], 16)
    b = int(color_hex[5:7], 16)
    img_array[:, :, 0] = r
    img_array[:, :, 1] = g
    img_array[:, :, 2] = b
    return Image.fromarray(img_array)

print("Loading president images...")

# Create the main figure
fig = plt.figure(figsize=(18, 12))
fig.patch.set_facecolor('#1a1a2e')

# Title
fig.text(0.5, 0.96, "The Past 5 Presidents of the United States of America",
         ha='center', va='top', fontsize=20, fontweight='bold',
         color='white', fontfamily='serif')

fig.text(0.5, 0.92, "From Bill Clinton (1993) to Joe Biden (2025)",
         ha='center', va='top', fontsize=13, color='#cccccc', fontfamily='serif')

# Number of presidents
n = len(presidents)

for i, pres in enumerate(presidents):
    print(f"Processing: {pres['name']}...")

    # Calculate subplot position
    # Row 1: images, Row 2: info cards
    ax_img = fig.add_axes([0.03 + i * 0.19, 0.52, 0.16, 0.34])
    ax_info = fig.add_axes([0.03 + i * 0.19, 0.08, 0.16, 0.42])

    # --- Image panel ---
    img = load_image_from_url(pres["image_url"])
    if img is None:
        img = create_placeholder_image(pres["color"], pres["name"])

    # Add colored border frame
    ax_img.set_facecolor(pres["color"])
    for spine in ax_img.spines.values():
        spine.set_edgecolor('gold')
        spine.set_linewidth(3)

    ax_img.imshow(img, aspect='auto')
    ax_img.set_xticks([])
    ax_img.set_yticks([])

    # President name below image
    ax_img.set_xlabel(pres["name"], fontsize=10, fontweight='bold',
                      color='white', labelpad=6)

    # --- Info card panel ---
    ax_info.set_facecolor('#16213e')
    for spine in ax_info.spines.values():
        spine.set_edgecolor(pres["color"])
        spine.set_linewidth(2.5)
    ax_info.set_xticks([])
    ax_info.set_yticks([])

    # Party color banner at top of info card
    party_color = pres["color"]
    banner = mpatches.FancyBboxPatch((0.05, 0.82), 0.9, 0.14,
                                      boxstyle="round,pad=0.02",
                                      facecolor=party_color, edgecolor='none',
                                      transform=ax_info.transAxes)
    ax_info.add_patch(banner)

    ax_info.text(0.5, 0.895, pres["number"] + " President",
                 ha='center', va='center', fontsize=10, fontweight='bold',
                 color='white', transform=ax_info.transAxes)

    # Term dates - highlighted
    term_box = mpatches.FancyBboxPatch((0.05, 0.62), 0.9, 0.17,
                                        boxstyle="round,pad=0.02",
                                        facecolor='#0f3460', edgecolor='gold',
                                        linewidth=1.5,
                                        transform=ax_info.transAxes)
    ax_info.add_patch(term_box)

    ax_info.text(0.5, 0.735, "Term in Office",
                 ha='center', va='center', fontsize=8,
                 color='#aaaaaa', transform=ax_info.transAxes)
    ax_info.text(0.5, 0.675, pres["term"],
                 ha='center', va='center', fontsize=9, fontweight='bold',
                 color='gold', transform=ax_info.transAxes)

    # Party
    ax_info.text(0.5, 0.54, "Party",
                 ha='center', va='center', fontsize=8,
                 color='#aaaaaa', transform=ax_info.transAxes)
    ax_info.text(0.5, 0.47, pres["party"],
                 ha='center', va='center', fontsize=10, fontweight='bold',
                 color=party_color, transform=ax_info.transAxes)

    # Born
    ax_info.text(0.5, 0.35, "Born",
                 ha='center', va='center', fontsize=8,
                 color='#aaaaaa', transform=ax_info.transAxes)
    ax_info.text(0.5, 0.27, pres["born"],
                 ha='center', va='center', fontsize=8.5,
                 color='#dddddd', transform=ax_info.transAxes)

    # Divider line
    ax_info.axhline(y=0.18, xmin=0.05, xmax=0.95, color='#444466', linewidth=1)

    # Number badge
    badge = mpatches.Circle((0.5, 0.10), 0.09,
                              facecolor=party_color, edgecolor='gold',
                              linewidth=2, transform=ax_info.transAxes)
    ax_info.add_patch(badge)
    ax_info.text(0.5, 0.10, "#" + pres["number"].split("/")[0].replace("th","").replace("nd","").replace("rd","").replace("st",""),
                 ha='center', va='center', fontsize=9, fontweight='bold',
                 color='white', transform=ax_info.transAxes)

# Timeline bar at the bottom
ax_timeline = fig.add_axes([0.03, 0.02, 0.94, 0.04])
ax_timeline.set_facecolor('#0f3460')
ax_timeline.set_xlim(1993, 2026)
ax_timeline.set_ylim(0, 1)
ax_timeline.set_yticks([])

# Draw timeline segments
timeline_data = [
    ("Clinton", 1993, 2001, "#3333AA"),
    ("G.W. Bush", 2001, 2009, "#AA3333"),
    ("Obama", 2009, 2017, "#3333AA"),
    ("Trump", 2017, 2021, "#AA3333"),
    ("Biden", 2021, 2025, "#3333AA"),
    ("Trump", 2025, 2026, "#AA3333"),
]

for label, start, end, color in timeline_data:
    ax_timeline.barh(0.5, end - start, left=start, height=0.7,
                     color=color, edgecolor='gold', linewidth=0.8, align='center')
    mid = (start + end) / 2
    ax_timeline.text(mid, 0.5, label, ha='center', va='center',
                     fontsize=7.5, fontweight='bold', color='white')

# Year labels
for year in range(1993, 2027, 4):
    ax_timeline.text(year, -0.15, str(year), ha='center', va='top',
                     fontsize=7, color='#cccccc')

ax_timeline.spines['top'].set_visible(False)
ax_timeline.spines['right'].set_visible(False)
ax_timeline.spines['left'].set_visible(False)
ax_timeline.spines['bottom'].set_color('#444466')

# Legend
dem_patch = mpatches.Patch(color='#3333AA', label='Democratic Party')
rep_patch = mpatches.Patch(color='#AA3333', label='Republican Party')
fig.legend(handles=[dem_patch, rep_patch],
           loc='lower right', bbox_to_anchor=(0.99, 0.07),
           fontsize=10, facecolor='#16213e', edgecolor='gold',
           labelcolor='white', framealpha=0.9)

plt.suptitle("")
print("Displaying the graphic...")
plt.savefig("presidents.png", dpi=120, bbox_inches='tight',
            facecolor='#1a1a2e')
print("Saved as presidents.png")
plt.show()
print("Done!")