# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-14 15:29:53
# AutoCoder System - Automated Code Generation

import pygame
import math
import random
import sys

# Initialize pygame
pygame.init()

# Screen dimensions
WIDTH, HEIGHT = 800, 800
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Radar System Simulation")

# Colors
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
DARK_GREEN = (0, 80, 0)
BRIGHT_GREEN = (0, 255, 0)
RED = (255, 50, 50)
WHITE = (255, 255, 255)
CYAN = (0, 255, 255)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)
GRAY = (100, 100, 100)
DARK_GRAY = (30, 30, 30)

# Radar parameters
CENTER_X, CENTER_Y = WIDTH // 2, HEIGHT // 2
MAX_RADIUS = 340
NUM_RINGS = 5
SWEEP_SPEED = 1.5  # degrees per frame
FADE_SPEED = 3     # how fast trails fade

# Font
font_large = pygame.font.SysFont("monospace", 22, bold=True)
font_med = pygame.font.SysFont("monospace", 16)
font_small = pygame.font.SysFont("monospace", 13)

print("Radar System Simulation Starting...")
print("Simulating rotating radar sweep with target detection.")

# Target class
class Target:
    def __init__(self):
        self.reset()

    def reset(self):
        angle = random.uniform(0, 2 * math.pi)
        dist = random.uniform(MAX_RADIUS * 0.15, MAX_RADIUS * 0.92)
        self.x = CENTER_X + dist * math.cos(angle)
        self.y = CENTER_Y + dist * math.sin(angle)
        self.vx = random.uniform(-0.4, 0.4)
        self.vy = random.uniform(-0.4, 0.4)
        self.size = random.randint(3, 6)
        self.label = f"T{random.randint(1,99):02d}"
        self.detected = False
        self.blip_alpha = 0
        self.blip_timer = 0
        self.color = random.choice([RED, ORANGE, YELLOW, CYAN])

    def update(self):
        self.x += self.vx
        self.y += self.vy
        # Bounce off radar boundary
        dx = self.x - CENTER_X
        dy = self.y - CENTER_Y
        dist = math.sqrt(dx*dx + dy*dy)
        if dist > MAX_RADIUS * 0.92:
            self.vx *= -1
            self.vy *= -1
        if self.blip_timer > 0:
            self.blip_timer -= 1
            self.blip_alpha = max(0, self.blip_alpha - 2)

    def get_angle(self):
        dx = self.x - CENTER_X
        dy = self.y - CENTER_Y
        return math.degrees(math.atan2(dy, dx)) % 360

    def get_dist(self):
        dx = self.x - CENTER_X
        dy = self.y - CENTER_Y
        return math.sqrt(dx*dx + dy*dy)

# Create targets
targets = [Target() for _ in range(8)]

# Sweep trail surface (for fading effect)
trail_surface = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
trail_surface.fill((0, 0, 0, 0))

# Blip surface
blip_surface = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)

# Sweep angle
sweep_angle = 0.0

# Clock
clock = pygame.time.Clock()

# Detection log
detection_log = []

def draw_radar_background():
    """Draw radar rings, crosshairs, and labels."""
    # Background circle
    pygame.draw.circle(screen, (5, 15, 5), (CENTER_X, CENTER_Y), MAX_RADIUS)

    # Rings
    for i in range(1, NUM_RINGS + 1):
        r = int(MAX_RADIUS * i / NUM_RINGS)
        pygame.draw.circle(screen, DARK_GREEN, (CENTER_X, CENTER_Y), r, 1)
        # Range label
        range_km = int(100 * i / NUM_RINGS)
        lbl = font_small.render(f"{range_km}km", True, DARK_GREEN)
        screen.blit(lbl, (CENTER_X + r - 28, CENTER_Y - 10))

    # Crosshairs
    pygame.draw.line(screen, DARK_GREEN, (CENTER_X - MAX_RADIUS, CENTER_Y),
                     (CENTER_X + MAX_RADIUS, CENTER_Y), 1)
    pygame.draw.line(screen, DARK_GREEN, (CENTER_X, CENTER_Y - MAX_RADIUS),
                     (CENTER_X, CENTER_Y + MAX_RADIUS), 1)

    # Diagonal lines
    for angle_deg in [45, 135, 225, 315]:
        rad = math.radians(angle_deg)
        ex = CENTER_X + MAX_RADIUS * math.cos(rad)
        ey = CENTER_Y + MAX_RADIUS * math.sin(rad)
        pygame.draw.line(screen, DARK_GREEN, (CENTER_X, CENTER_Y), (int(ex), int(ey)), 1)

    # Degree labels
    for deg in [0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330]:
        rad = math.radians(deg)
        lx = CENTER_X + (MAX_RADIUS + 18) * math.cos(rad)
        ly = CENTER_Y + (MAX_RADIUS + 18) * math.sin(rad)
        lbl = font_small.render(f"{deg}", True, GREEN)
        screen.blit(lbl, (int(lx) - 10, int(ly) - 8))

    # Outer border circle
    pygame.draw.circle(screen, GREEN, (CENTER_X, CENTER_Y), MAX_RADIUS, 2)

    # Center dot
    pygame.draw.circle(screen, GREEN, (CENTER_X, CENTER_Y), 4)

def draw_sweep(angle_deg):
    """Draw the rotating sweep line with gradient trail."""
    # Draw fading trail (multiple lines behind sweep)
    num_trail = 60
    for i in range(num_trail):
        trail_angle = angle_deg - i * 1.0
        alpha = int(180 * (1 - i / num_trail))
        if alpha <= 0:
            continue
        rad = math.radians(trail_angle)
        ex = CENTER_X + MAX_RADIUS * math.cos(rad)
        ey = CENTER_Y + MAX_RADIUS * math.sin(rad)
        color = (0, alpha, 0)
        pygame.draw.line(screen, color, (CENTER_X, CENTER_Y), (int(ex), int(ey)), 2)

    # Main sweep line (bright)
    rad = math.radians(angle_deg)
    ex = CENTER_X + MAX_RADIUS * math.cos(rad)
    ey = CENTER_Y + MAX_RADIUS * math.sin(rad)
    pygame.draw.line(screen, (100, 255, 100), (CENTER_X, CENTER_Y), (int(ex), int(ey)), 2)

def check_detection(target, sweep_angle):
    """Check if sweep line passes over target."""
    t_angle = target.get_angle()
    diff = (sweep_angle - t_angle) % 360
    if diff < SWEEP_SPEED * 2:
        target.detected = True
        target.blip_alpha = 255
        target.blip_timer = 200
        return True
    return False

def draw_blips():
    """Draw detected target blips."""
    for t in targets:
        if t.blip_timer > 0:
            alpha = min(255, t.blip_alpha)
            # Blip circle
            blip_color = (*t.color[:3], alpha)
            # Draw expanding ring
            ring_size = t.size + int((200 - t.blip_timer) / 20)
            pygame.draw.circle(screen, t.color,
                                (int(t.x), int(t.y)), ring_size, 2)
            pygame.draw.circle(screen, t.color,
                                (int(t.x), int(t.y)), t.size)
            # Label
            lbl = font_small.render(t.label, True, t.color)
            screen.blit(lbl, (int(t.x) + t.size + 2, int(t.y) - 8))

def draw_hud(sweep_angle, num_detected):
    """Draw HUD overlay with radar info."""
    # Top panel
    pygame.draw.rect(screen, DARK_GRAY, (0, 0, WIDTH, 60))
    pygame.draw.line(screen, GREEN, (0, 60), (WIDTH, 60), 1)

    title = font_large.render("RADAR SYSTEM SIMULATION", True, GREEN)
    screen.blit(title, (WIDTH // 2 - title.get_width() // 2, 10))

    sub = font_med.render("Rotating Phased Array | Range: 100km | Mode: SURVEILLANCE", True, DARK_GREEN)
    screen.blit(sub, (WIDTH // 2 - sub.get_width() // 2, 36))

    # Bottom panel
    pygame.draw.rect(screen, DARK_GRAY, (0, HEIGHT - 80, WIDTH, 80))
    pygame.draw.line(screen, GREEN, (0, HEIGHT - 80), (WIDTH, HEIGHT - 80), 1)

    angle_txt = font_med.render(f"Azimuth: {sweep_angle:6.1f} deg", True, CYAN)
    screen.blit(angle_txt, (20, HEIGHT - 65))

    det_txt = font_med.render(f"Targets Detected: {num_detected}", True, YELLOW)
    screen.blit(det_txt, (20, HEIGHT - 42))

    fps_txt = font_med.render(f"Sweep Rate: {SWEEP_SPEED:.1f} deg/frame", True, GREEN)
    screen.blit(fps_txt, (WIDTH - 280, HEIGHT - 65))

    status_txt = font_med.render("STATUS: ACTIVE  |  SCANNING...", True, GREEN)
    screen.blit(status_txt, (WIDTH - 280, HEIGHT - 42))

    # Right side info
    pygame.draw.rect(screen, DARK_GRAY, (WIDTH - 160, 65, 160, HEIGHT - 145))
    pygame.draw.line(screen, GREEN, (WIDTH - 160, 65), (WIDTH - 160, HEIGHT - 80), 1)

    info_title = font_med.render("CONTACTS", True, GREEN)
    screen.blit(info_title, (WIDTH - 145, 72))
    pygame.draw.line(screen, DARK_GREEN, (WIDTH - 155, 92), (WIDTH - 5, 92), 1)

    y_off = 100
    for i, t in enumerate(targets):
        if t.blip_timer > 0:
            dist_km = int(t.get_dist() / MAX_RADIUS * 100)
            ang = int(t.get_angle())
            c_txt = font_small.render(f"{t.label}: {dist_km}km", True, t.color)
            screen.blit(c_txt, (WIDTH - 150, y_off + i * 22))
            a_txt = font_small.render(f"  Az:{ang:3d}deg", True, GRAY)
            screen.blit(a_txt, (WIDTH - 150, y_off + i * 22 + 11))

# Main loop
running = True
frame = 0
num_detected = 0

print("Radar simulation running. Close window to exit.")

while running:
    clock.tick(60)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False

    # Clear screen
    screen.fill(BLACK)

    # Draw radar background
    draw_radar_background()

    # Draw sweep
    draw_sweep(sweep_angle)

    # Update and check targets
    num_detected = 0
    for t in targets:
        t.update()
        check_detection(t, sweep_angle)
        if t.blip_timer > 0:
            num_detected += 1

    # Draw blips
    draw_blips()

    # Draw HUD
    draw_hud(sweep_angle, num_detected)

    # Advance sweep angle
    sweep_angle = (sweep_angle + SWEEP_SPEED) % 360

    pygame.display.flip()
    frame += 1

    if frame % 300 == 0:
        print(f"Frame {frame}: Sweep angle={sweep_angle:.1f} deg, Targets detected={num_detected}")

print("Radar simulation ended.")
pygame.quit()
sys.exit()