# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-04 11:47:55
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.widgets import Slider
from matplotlib.patches import FancyArrowPatch, Arc
import matplotlib.patheffects as pe
from scipy import signal

print("Starting RLC Circuit Simulator...")

# ─────────────────────────────────────────────
# Circuit / signal parameters
# ─────────────────────────────────────────────
L_val   = 0.01      # Henry
C_val   = 1e-5      # Farad
R_init  = 10.0      # Ohm  (slider will change this)
f_sq    = 100.0     # Hz  square-wave frequency
fs      = 50_000    # samples / second
t_end   = 0.05      # seconds to display

t = np.linspace(0, t_end, int(fs * t_end), endpoint=False)
u = signal.square(2 * np.pi * f_sq * t)   # ±1 square wave

def compute_output(R):
    """Simulate series RLC driven by square wave; return output voltage across C."""
    # Transfer function  H(s) = ω₀² / (s² + 2ζω₀ s + ω₀²)
    w0 = 1.0 / np.sqrt(L_val * C_val)
    num = [w0**2]
    den = [1.0, R / L_val, w0**2]
    sys = signal.TransferFunction(num, den)
    _, y, _ = signal.lsim(sys, u, t)
    return y

# ─────────────────────────────────────────────
# Figure layout
# ─────────────────────────────────────────────
fig = plt.figure(figsize=(14, 9))
fig.patch.set_facecolor('#1a1a2e')

# Axes: circuit diagram (top-left), waveforms (right), slider (bottom)
ax_ckt  = fig.add_axes([0.02, 0.38, 0.38, 0.55])   # circuit
ax_in   = fig.add_axes([0.45, 0.62, 0.52, 0.30])   # input waveform
ax_out  = fig.add_axes([0.45, 0.22, 0.52, 0.30])   # output waveform
ax_sl   = fig.add_axes([0.15, 0.08, 0.70, 0.04])   # slider

for ax in [ax_ckt, ax_in, ax_out]:
    ax.set_facecolor('#0f0f23')
    for spine in ax.spines.values():
        spine.set_edgecolor('#444466')

# ─────────────────────────────────────────────
# Draw circuit diagram (static except R label)
# ─────────────────────────────────────────────
def draw_circuit(ax, R):
    ax.cla()
    ax.set_facecolor('#0f0f23')
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 8)
    ax.set_aspect('equal')
    ax.axis('off')
    ax.set_title('Series RLC Circuit', color='#e0e0ff', fontsize=12, pad=6)

    lw = 2.5
    wire_kw  = dict(color='#00d4ff', lw=lw, solid_capstyle='round')
    comp_kw  = dict(color='#ffdd44', lw=lw, solid_capstyle='round')

    # ── Outer rectangle wires ──────────────────────────────────────────
    # Top wire: left node → R → L → right node
    # Bottom wire: right node → C → left node (with voltage source on left)

    # Nodes
    x_left, x_right = 1.0, 9.0
    y_top,  y_bot   = 6.5, 1.5

    # Left vertical wire (source)
    ax.plot([x_left, x_left], [y_bot, y_top], **wire_kw)

    # Top wire segments
    ax.plot([x_left, 2.5],   [y_top, y_top], **wire_kw)   # left → R
    ax.plot([4.5, 6.0],      [y_top, y_top], **wire_kw)   # R → L
    ax.plot([8.0, x_right],  [y_top, y_top], **wire_kw)   # L → right node

    # Right vertical wire
    ax.plot([x_right, x_right], [y_top, y_bot], **wire_kw)

    # Bottom wire segments
    ax.plot([x_right, 7.0], [y_bot, y_bot], **wire_kw)    # right → C
    ax.plot([5.0, x_left],  [y_bot, y_bot], **wire_kw)    # C → left

    # ── Voltage source (left side) ─────────────────────────────────────
    cx, cy = x_left, (y_top + y_bot) / 2
    circle = plt.Circle((cx, cy), 0.55, color='#ff6b6b', fill=False, lw=lw)
    ax.add_patch(circle)
    ax.text(cx, cy + 0.18, '+', color='#ff6b6b', ha='center', va='center', fontsize=11, fontweight='bold')
    ax.text(cx, cy - 0.22, '−', color='#ff6b6b', ha='center', va='center', fontsize=13, fontweight='bold')
    ax.text(cx - 0.9, cy, 'Vin\n(sq)', color='#ff6b6b', ha='center', va='center', fontsize=8)

    # ── Resistor (top, left section) ──────────────────────────────────
    rx0, rx1 = 2.5, 4.5
    ry = y_top
    # Zigzag
    n_teeth = 6
    xs = np.linspace(rx0, rx1, n_teeth * 2 + 1)
    ys = np.array([ry + (0.3 if i % 2 == 1 else -0.3) if 0 < i < len(xs)-1 else ry
                   for i in range(len(xs))])
    ys[0] = ry; ys[-1] = ry
    ax.plot(xs, ys, **comp_kw)
    ax.text((rx0+rx1)/2, ry + 0.75, f'R = {R:.1f} Ω', color='#ffdd44',
            ha='center', va='bottom', fontsize=10, fontweight='bold')

    # ── Inductor (top, right section) ─────────────────────────────────
    lx0, lx1 = 6.0, 8.0
    ly = y_top
    n_bumps = 4
    bump_w  = (lx1 - lx0) / n_bumps
    for i in range(n_bumps):
        cx_b = lx0 + (i + 0.5) * bump_w
        arc = Arc((cx_b, ly), bump_w, 0.55, angle=0,
                  theta1=0, theta2=180, color='#44ff88', lw=lw)
        ax.add_patch(arc)
    ax.text((lx0+lx1)/2, ly + 0.75, f'L = {L_val*1000:.0f} mH', color='#44ff88',
            ha='center', va='bottom', fontsize=10)

    # ── Capacitor (bottom) ────────────────────────────────────────────
    cx0, cx1 = 5.0, 7.0
    cy_c = y_bot
    mid  = (cx0 + cx1) / 2
    gap  = 0.18
    plate_h = 0.55
    ax.plot([cx0, mid - gap], [cy_c, cy_c], **comp_kw)
    ax.plot([mid + gap, cx1], [cy_c, cy_c], **comp_kw)
    ax.plot([mid - gap, mid - gap], [cy_c - plate_h, cy_c + plate_h], color='#bb88ff', lw=3)
    ax.plot([mid + gap, mid + gap], [cy_c - plate_h, cy_c + plate_h], color='#bb88ff', lw=3)
    ax.text(mid, cy_c - 0.85, f'C = {C_val*1e6:.0f} µF', color='#bb88ff',
            ha='center', va='top', fontsize=10)

    # ── Output label ──────────────────────────────────────────────────
    ax.annotate('', xy=(x_right, y_bot + 0.3), xytext=(x_right, y_top - 0.3),
                arrowprops=dict(arrowstyle='<->', color='#ff9944', lw=1.5))
    ax.text(x_right + 0.35, (y_top + y_bot)/2, 'Vout', color='#ff9944',
            ha='left', va='center', fontsize=9, rotation=90)

# ─────────────────────────────────────────────
# Draw waveforms
# ─────────────────────────────────────────────
def draw_waveforms(ax_in, ax_out, R):
    y_out = compute_output(R)

    # Input
    ax_in.cla()
    ax_in.set_facecolor('#0f0f23')
    ax_in.plot(t * 1000, u, color='#00d4ff', lw=1.5, label='Input (square wave)')
    ax_in.set_ylabel('Amplitude (V)', color='#aaaacc', fontsize=9)
    ax_in.set_title('Input Square Wave', color='#e0e0ff', fontsize=10)
    ax_in.tick_params(colors='#aaaacc', labelsize=8)
    ax_in.set_xlim(0, t_end * 1000)
    ax_in.set_ylim(-1.5, 1.5)
    ax_in.axhline(0, color='#444466', lw=0.8)
    ax_in.grid(True, color='#222244', lw=0.5)
    for sp in ax_in.spines.values(): sp.set_edgecolor('#444466')

    # Output
    ax_out.cla()
    ax_out.set_facecolor('#0f0f23')
    ax_out.plot(t * 1000, y_out, color='#ff6b6b', lw=1.5, label='Output (across C)')
    ax_out.set_xlabel('Time (ms)', color='#aaaacc', fontsize=9)
    ax_out.set_ylabel('Amplitude (V)', color='#aaaacc', fontsize=9)
    w0 = 1.0 / np.sqrt(L_val * C_val)
    zeta = R / (2 * np.sqrt(L_val / C_val))
    ax_out.set_title(f'Output Voltage (across C)   |   R={R:.1f} Ω   ζ={zeta:.3f}   f₀={w0/(2*np.pi):.1f} Hz',
                     color='#e0e0ff', fontsize=10)
    ax_out.tick_params(colors='#aaaacc', labelsize=8)
    ax_out.set_xlim(0, t_end * 1000)
    ax_out.axhline(0, color='#444466', lw=0.8)
    ax_out.grid(True, color='#222244', lw=0.5)
    for sp in ax_out.spines.values(): sp.set_edgecolor('#444466')

# ─────────────────────────────────────────────
# Initial draw
# ─────────────────────────────────────────────
draw_circuit(ax_ckt, R_init)
draw_waveforms(ax_in, ax_out, R_init)

# ─────────────────────────────────────────────
# Slider
# ─────────────────────────────────────────────
ax_sl.set_facecolor('#1a1a2e')
slider = Slider(ax_sl, 'R (Ω)', 0.1, 200.0, valinit=R_init, color='#00d4ff')
slider.label.set_color('#e0e0ff')
slider.valtext.set_color('#ffdd44')

def on_slider(val):
    R = slider.val
    draw_circuit(ax_ckt, R)
    draw_waveforms(ax_in, ax_out, R)
    fig.canvas.draw_idle()

slider.on_changed(on_slider)

# ─────────────────────────────────────────────
# Info text
# ─────────────────────────────────────────────
fig.text(0.50, 0.97, 'Interactive RLC Circuit Simulator',
         color='#e0e0ff', ha='center', va='top', fontsize=14, fontweight='bold')
fig.text(0.50, 0.14,
         'Drag the slider to change R and observe the effect on the output waveform in real time.',
         color='#8888aa', ha='center', va='top', fontsize=9)

print("RLC Circuit Simulator ready.")
print(f"  L = {L_val*1000:.0f} mH,  C = {C_val*1e6:.0f} µF")
print(f"  Natural frequency f0 = {1/(2*np.pi*np.sqrt(L_val*C_val)):.1f} Hz")
print("  Move the R slider to see under/over/critically-damped responses.")

plt.show()