# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-09 05:17:55
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
from matplotlib.widgets import Slider
from matplotlib.animation import FuncAnimation
from matplotlib.patches import FancyBboxPatch, Circle, FancyArrowPatch
import matplotlib.gridspec as gridspec
from matplotlib.lines import Line2D
import matplotlib.transforms as transforms
import warnings
warnings.filterwarnings('ignore')

# Try to set Orbitron-like font, fallback gracefully
plt.rcParams['font.family'] = 'monospace'

# ─── Color Palette ───────────────────────────────────────────────────────────
BG_COLOR       = '#0A0A0F'
NAVY_VIGNETTE  = '#050510'
TEAL           = '#00E5CC'
PHOSPHOR       = '#39FF14'
PHOSPHOR_DIM   = '#1A4A0A'
AMBER          = '#FF9F1C'
WHITE_GOLD     = '#FFE87C'
GRID_BG        = '#111118'
GRIDLINE       = '#1A2A1A'
VIOLET         = '#BF5FFF'
GOLD           = '#FFD700'
CORAL          = '#FF4F4F'
CHARCOAL       = '#1E1E2E'
ICY_WHITE      = '#E8F4FF'
FROST_BG       = '#FFFFFF10'

print("Initializing RLC Circuit Pulse Response Simulator...")

# ─── RLC Physics ─────────────────────────────────────────────────────────────
def compute_rlc_response(R, L, C, t_end=0.05, n_points=2000):
    """Compute step response of series RLC circuit."""
    t = np.linspace(0, t_end, n_points)
    omega0 = 1.0 / np.sqrt(L * C)
    alpha  = R / (2 * L)
    zeta   = alpha / omega0

    if zeta < 1.0 - 1e-6:
        # Underdamped
        omega_d = omega0 * np.sqrt(1 - zeta**2)
        v = 1 - np.exp(-alpha * t) * (np.cos(omega_d * t) + (alpha / omega_d) * np.sin(omega_d * t))
        regime = 'underdamped'
    elif zeta > 1.0 + 1e-6:
        # Overdamped
        s1 = -alpha + np.sqrt(alpha**2 - omega0**2)
        s2 = -alpha - np.sqrt(alpha**2 - omega0**2)
        A  =  s2 / (s2 - s1)
        B  = -s1 / (s2 - s1)
        v  = 1 + A * np.exp(s1 * t) + B * np.exp(s2 * t)
        regime = 'overdamped'
    else:
        # Critically damped
        v = 1 - np.exp(-alpha * t) * (1 + alpha * t)
        regime = 'critically_damped'

    v = np.clip(v, -2, 3)
    return t, v, regime, zeta

# ─── Circuit Schematic Drawing ────────────────────────────────────────────────
def draw_schematic(ax, pulse_phase=0.0):
    ax.clear()
    ax.set_facecolor(BG_COLOR)
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis('off')

    glow_alpha = 0.4 + 0.3 * np.sin(2 * np.pi * pulse_phase / 1.2)

    def teal_line(x1, y1, x2, y2, lw=1.5):
        ax.plot([x1, x2], [y1, y2], color=TEAL, lw=lw, solid_capstyle='round',
                path_effects=[pe.withStroke(linewidth=lw+4, foreground='#00E5CC22')])

    # Circuit path: top wire → R → L → C → bottom wire → source
    # Top rail: left to right
    teal_line(1, 7, 2.5, 7)   # left top wire
    teal_line(4.5, 7, 6, 7)   # mid top wire
    teal_line(7.5, 7, 9, 7)   # right top wire
    # Bottom rail
    teal_line(1, 3, 9, 3)
    # Verticals
    teal_line(1, 3, 1, 7)     # source left
    teal_line(9, 3, 9, 7)     # source right

    # ── Resistor (zigzag) ──
    rx = np.linspace(2.5, 4.5, 13)
    ry = np.array([7, 7.4, 6.6, 7.4, 6.6, 7.4, 6.6, 7.4, 6.6, 7.4, 6.6, 7.4, 7])
    ax.plot(rx, ry, color=TEAL, lw=1.5,
            path_effects=[pe.withStroke(linewidth=5, foreground=f'#00E5CC{int(glow_alpha*99):02X}')])
    ax.text(3.5, 8.0, 'R', color=TEAL, fontsize=8, ha='center', va='bottom',
            fontweight='bold', alpha=0.9)

    # ── Inductor (bumps) ──
    theta = np.linspace(0, np.pi, 8)
    ix_base = np.linspace(6.0, 7.5, 4)
    ix_all, iy_all = [], []
    for i, xb in enumerate(ix_base[:-1]):
        xc = (ix_base[i] + ix_base[i+1]) / 2
        r  = (ix_base[i+1] - ix_base[i]) / 2
        ix_all.extend(xc + r * np.cos(np.pi - theta))
        iy_all.extend(7 + r * np.sin(theta))
    ax.plot(ix_all, iy_all, color=TEAL, lw=1.5,
            path_effects=[pe.withStroke(linewidth=5, foreground=f'#00E5CC{int(glow_alpha*99):02X}')])
    ax.text(6.75, 8.0, 'L', color=TEAL, fontsize=8, ha='center', va='bottom',
            fontweight='bold', alpha=0.9)

    # ── Capacitor (two plates) ──
    cx = 9.0
    ax.plot([cx, cx], [3, 4.8], color=TEAL, lw=1.5)
    ax.plot([cx, cx], [5.2, 7], color=TEAL, lw=1.5)
    ax.plot([cx-0.5, cx+0.5], [4.8, 4.8], color=TEAL, lw=2.5,
            path_effects=[pe.withStroke(linewidth=6, foreground=f'#00E5CC{int(glow_alpha*99):02X}')])
    ax.plot([cx-0.5, cx+0.5], [5.2, 5.2], color=TEAL, lw=2.5,
            path_effects=[pe.withStroke(linewidth=6, foreground=f'#00E5CC{int(glow_alpha*99):02X}')])
    ax.text(cx + 0.7, 5.0, 'C', color=TEAL, fontsize=8, ha='left', va='center',
            fontweight='bold', alpha=0.9)

    # ── Voltage source (circle with +/-) ──
    src = Circle((1, 5), 0.6, fill=False, edgecolor=TEAL, lw=1.5)
    ax.add_patch(src)
    ax.text(1, 5.25, '+', color=TEAL, fontsize=9, ha='center', va='center', fontweight='bold')
    ax.text(1, 4.75, '-', color=TEAL, fontsize=9, ha='center', va='center', fontweight='bold')
    ax.text(1, 2.3, 'Vin', color=TEAL, fontsize=7, ha='center', va='center', alpha=0.8)

    # ── Title ──
    ax.text(5, 9.5, 'RLC SERIES CIRCUIT', color=TEAL, fontsize=8,
            ha='center', va='top', fontweight='bold', alpha=0.85,
            fontfamily='monospace')

# ─── Build Figure ─────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(16, 9), facecolor=BG_COLOR)
fig.patch.set_facecolor(BG_COLOR)

# Layout: left panel (schematic + sliders) | right panel (oscilloscope)
gs_outer = gridspec.GridSpec(1, 2, figure=fig, width_ratios=[1, 2.2],
                              left=0.02, right=0.98, top=0.96, bottom=0.04,
                              wspace=0.04)

gs_left = gridspec.GridSpecFromSubplotSpec(2, 1, subplot_spec=gs_outer[0],
                                            height_ratios=[1.4, 1], hspace=0.05)

ax_schem  = fig.add_subplot(gs_left[0])
ax_sliders_bg = fig.add_subplot(gs_left[1])
ax_osc    = fig.add_subplot(gs_outer[1])

for ax in [ax_schem, ax_sliders_bg, ax_osc]:
    ax.set_facecolor(BG_COLOR)

ax_sliders_bg.axis('off')

# ─── Oscilloscope Axes Styling ────────────────────────────────────────────────
ax_osc.set_facecolor(GRID_BG)
for spine in ax_osc.spines.values():
    spine.set_color('#2A3A2A')
    spine.set_linewidth(1.5)

ax_osc.tick_params(colors='#4A6A4A', labelsize=7)
ax_osc.xaxis.label.set_color('#4A6A4A')
ax_osc.yaxis.label.set_color('#4A6A4A')

# Grid
ax_osc.set_xlim(0, 1)
ax_osc.set_ylim(-0.3, 1.5)
ax_osc.grid(True, color=GRIDLINE, linewidth=0.5, alpha=0.8)
ax_osc.set_xlabel('Time (ms)', color='#4A6A4A', fontsize=8, fontfamily='monospace')
ax_osc.set_ylabel('Voltage (V)', color='#4A6A4A', fontsize=8, fontfamily='monospace')

# Reference line at V=1
ax_osc.axhline(1.0, color='#2A4A2A', lw=0.8, ls='--', alpha=0.6)
ax_osc.axhline(0.0, color='#2A4A2A', lw=0.8, ls='--', alpha=0.4)

# ─── Sliders ──────────────────────────────────────────────────────────────────
slider_color  = CHARCOAL
thumb_color   = AMBER

# Slider axes positions [left, bottom, width, height]
ax_R = fig.add_axes([0.04, 0.30, 0.26, 0.025])
ax_L = fig.add_axes([0.04, 0.22, 0.26, 0.025])
ax_C = fig.add_axes([0.04, 0.14, 0.26, 0.025])

for sax in [ax_R, ax_L, ax_C]:
    sax.set_facecolor(CHARCOAL)

sl_R = Slider(ax_R, 'R (Ω)', 1.0,  500.0, valinit=50.0,  color=AMBER, initcolor=AMBER)
sl_L = Slider(ax_L, 'L (mH)', 0.5, 100.0, valinit=10.0,  color=AMBER, initcolor=AMBER)
sl_C = Slider(ax_C, 'C (µF)', 0.1,  50.0, valinit=10.0,  color=AMBER, initcolor=AMBER)

for sl in [sl_R, sl_L, sl_C]:
    sl.label.set_color(AMBER)
    sl.label.set_fontsize(8)
    sl.label.set_fontfamily('monospace')
    sl.valtext.set_color(WHITE_GOLD)
    sl.valtext.set_fontsize(7)
    sl.valtext.set_fontfamily('monospace')
    sl.poly.set_facecolor(CHARCOAL)

# Slider panel labels
fig.text(0.165, 0.38, 'PARAMETERS', color=AMBER, fontsize=9,
         ha='center', va='center', fontweight='bold', fontfamily='monospace',
         alpha=0.9)

# ─── Regime Label (upper right of oscilloscope) ───────────────────────────────
regime_text = ax_osc.text(0.98, 0.96, '', transform=ax_osc.transAxes,
                           fontsize=13, ha='right', va='top',
                           fontweight='bold', fontfamily='monospace',
                           color=VIOLET, alpha=0.0)

zeta_text = ax_osc.text(0.98, 0.88, '', transform=ax_osc.transAxes,
                         fontsize=8, ha='right', va='top',
                         fontfamily='monospace', color='#8888AA', alpha=0.0)

# Oscilloscope title
ax_osc.text(0.02, 0.97, 'OSCILLOSCOPE  //  VOLTAGE RESPONSE',
            transform=ax_osc.transAxes, fontsize=9, ha='left', va='top',
            color=PHOSPHOR, fontfamily='monospace', fontweight='bold', alpha=0.7)

# ─── Waveform Lines ───────────────────────────────────────────────────────────
# Glow layers: wide dim → medium → bright core
waveform_glow2, = ax_osc.plot([], [], color=PHOSPHOR_DIM, lw=8,  alpha=0.15, solid_capstyle='round')
waveform_glow1, = ax_osc.plot([], [], color='#20AA08',    lw=4,  alpha=0.30, solid_capstyle='round')
waveform_core,  = ax_osc.plot([], [], color=PHOSPHOR,     lw=1.5, alpha=0.95, solid_capstyle='round')

# Traveling dot on waveform
travel_dot, = ax_osc.plot([], [], 'o', color=WHITE_GOLD, ms=7, zorder=10,
                           markeredgecolor='white', markeredgewidth=0.5)
travel_tail, = ax_osc.plot([], [], color=WHITE_GOLD, lw=2, alpha=0.5, solid_capstyle='round')

# Crosshair
crosshair_v = ax_osc.axvline(x=0, color=ICY_WHITE, lw=0.8, ls='--', alpha=0, zorder=8)
crosshair_h = ax_osc.axhline(y=0, color=ICY_WHITE, lw=0.8, ls='--', alpha=0, zorder=8)

# Tooltip annotation
tooltip = ax_osc.annotate('', xy=(0, 0), xytext=(20, 20),
                           textcoords='offset points',
                           bbox=dict(boxstyle='round,pad=0.5', facecolor='#0A0A1A',
                                     edgecolor='#FFFFFF44', alpha=0.85, lw=1),
                           color=ICY_WHITE, fontsize=7.5, fontfamily='monospace',
                           zorder=15, annotation_clip=False)
tooltip.set_visible(False)

# ─── State ────────────────────────────────────────────────────────────────────
state = {
    't': np.array([]),
    'v': np.array([]),
    'regime': 'underdamped',
    'zeta': 0.0,
    'anim_frame': 0,
    'total_frames': 80,
    'pulse_phase': 0.0,
    'needs_update': True,
    'sweep_active': False,
}

def recalculate():
    R = sl_R.val
    L = sl_L.val * 1e-3   # mH → H
    C = sl_C.val * 1e-6   # µF → F
    t, v, regime, zeta = compute_rlc_response(R, L, C, t_end=0.05, n_points=2000)
    state['t'] = t * 1000  # s → ms
    state['v'] = v
    state['regime'] = regime
    state['zeta']   = zeta
    state['anim_frame'] = 0
    state['sweep_active'] = True
    state['needs_update'] = True

    # Update oscilloscope x-axis
    t_max = state['t'][-1]
    ax_osc.set_xlim(0, t_max)
    margin = max(0.1, (v.max() - v.min()) * 0.15)
    ax_osc.set_ylim(min(-0.2, v.min() - margin), max(1.4, v.max() + margin))

    # Update regime label
    regime_labels = {
        'underdamped':     ('UNDERDAMPED',     VIOLET),
        'critically_damped': ('CRITICALLY DAMPED', GOLD),
        'overdamped':      ('OVERDAMPED',      CORAL),
    }
    label, color = regime_labels[regime]
    regime_text.set_text(label)
    regime_text.set_color(color)
    regime_text.set_alpha(0.0)

    zeta_text.set_text(f'zeta = {zeta:.4f}')
    zeta_text.set_alpha(0.0)

    print(f"  R={R:.1f}Ω  L={sl_L.val:.1f}mH  C={sl_C.val:.1f}µF  "
          f"regime={regime}  zeta={zeta:.4f}")

# Initial calculation
recalculate()

# ─── Animation ────────────────────────────────────────────────────────────────
SWEEP_FRAMES = 80
TAIL_LEN = 60

def animate(frame):
    state['pulse_phase'] += 0.016  # ~60fps tick

    # Redraw schematic with glow pulse
    draw_schematic(ax_schem, state['pulse_phase'])

    t_full = state['t']
    v_full = state['v']

    if len(t_full) == 0:
        return

    # Sweep animation
    if state['sweep_active']:
        state['anim_frame'] = min(state['anim_frame'] + 1, SWEEP_FRAMES)
        frac = state['anim_frame'] / SWEEP_FRAMES
        if state['anim_frame'] >= SWEEP_FRAMES:
            state['sweep_active'] = False

        # Fade in regime label
        alpha_label = min(1.0, (state['anim_frame'] - SWEEP_FRAMES * 0.7) / (SWEEP_FRAMES * 0.3))
        regime_text.set_alpha(max(0, alpha_label))
        zeta_text.set_alpha(max(0, alpha_label))
    else:
        frac = 1.0

    n_show = max(2, int(len(t_full) * frac))
    t_show = t_full[:n_show]
    v_show = v_full[:n_show]

    waveform_glow2.set_data(t_show, v_show)
    waveform_glow1.set_data(t_show, v_show)
    waveform_core.set_data(t_show, v_show)

    # Traveling dot at sweep head
    if state['sweep_active'] and n_show > 1:
        dot_t = t_show[-1]
        dot_v = v_show[-1]
        travel_dot.set_data([dot_t], [dot_v])
        tail_start = max(0, n_show - TAIL_LEN)
        travel_tail.set_data(t_show[tail_start:], v_show[tail_start:])
        travel_dot.set_alpha(1.0)
        travel_tail.set_alpha(0.6)
    else:
        travel_dot.set_alpha(0.0)
        travel_tail.set_alpha(0.0)

    return (waveform_glow2, waveform_glow1, waveform_core,
            travel_dot, travel_tail, regime_text, zeta_text)

# ─── Slider Callbacks ─────────────────────────────────────────────────────────
def on_slider_change(val):
    recalculate()

sl_R.on_changed(on_slider_change)
sl_L.on_changed(on_slider_change)
sl_C.on_changed(on_slider_change)

# ─── Mouse Hover (Crosshair + Tooltip) ────────────────────────────────────────
def on_mouse_move(event):
    if event.inaxes != ax_osc:
        crosshair_v.set_alpha(0)
        crosshair_h.set_alpha(0)
        tooltip.set_visible(False)
        fig.canvas.draw_idle()
        return

    t_full = state['t']
    v_full = state['v']
    if len(t_full) == 0:
        return

    mx = event.xdata
    if mx is None:
        return

    # Snap to nearest data point
    idx = np.argmin(np.abs(t_full - mx))
    snap_t = t_full[idx]
    snap_v = v_full[idx]

    crosshair_v.set_xdata([snap_t])
    crosshair_v.set_alpha(0.7)
    crosshair_h.set_ydata([snap_v])
    crosshair_h.set_alpha(0.5)

    tooltip.xy = (snap_t, snap_v)
    tooltip.set_text(f't = {snap_t:.3f} ms\nV = {snap_v:.4f} V')
    tooltip.set_visible(True)

    fig.canvas.draw_idle()

fig.canvas.mpl_connect('motion_notify_event', on_mouse_move)

# ─── Vignette Overlay ─────────────────────────────────────────────────────────
def add_vignette():
    """Draw a dark vignette border over the figure."""
    vax = fig.add_axes([0, 0, 1, 1], zorder=100)
    vax.set_xlim(0, 1)
    vax.set_ylim(0, 1)
    vax.axis('off')
    vax.patch.set_alpha(0)

    from matplotlib.patches import Rectangle
    # Semi-transparent dark edges
    for alpha, lw in [(0.35, 0.18), (0.20, 0.10), (0.10, 0.05)]:
        rect = FancyBboxPatch((lw, lw), 1 - 2*lw, 1 - 2*lw,
                               boxstyle='round,pad=0.01',
                               facecolor='none',
                               edgecolor=NAVY_VIGNETTE,
                               linewidth=60 * lw,
                               alpha=alpha,
                               transform=fig.transFigure,
                               figure=fig)
        fig.add_artist(rect)

add_vignette()

# ─── Panel Labels ─────────────────────────────────────────────────────────────
fig.text(0.165, 0.96, 'RLC  PULSE  RESPONSE  SIMULATOR',
         color=TEAL, fontsize=11, ha='center', va='top',
         fontweight='bold', fontfamily='monospace',
         path_effects=[pe.withStroke(linewidth=3, foreground='#00E5CC22')])

fig.text(0.165, 0.92, 'CIRCUIT  SCHEMATIC',
         color='#4A8A8A', fontsize=7, ha='center', va='top',
         fontfamily='monospace')

# ─── Run Animation ────────────────────────────────────────────────────────────
anim = FuncAnimation(fig, animate, interval=33, blit=False, cache_frame_data=False)

print("RLC Circuit Pulse Response Simulator running.")
print("Drag the R, L, C sliders to change parameters.")
print("Hover over the waveform to see crosshair and tooltip.")
print("Regime is auto-detected: underdamped / critically damped / overdamped")

plt.show()