# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-04 19:49:26
# AutoCoder System - Automated Code Generation

import numpy as np
import sounddevice as sd
import tkinter as tk
from tkinter import font as tkfont
import threading
import time

# Sample rate
SAMPLE_RATE = 44100

# C4 frequency
C4_FREQ = 261.63

# 12th root of 2
SEMITONE = 2 ** (1 / 12)


def note_freq(base_freq, semitones):
    """Calculate frequency given base frequency and number of semitones."""
    return base_freq * (SEMITONE ** semitones)


# C Major scale intervals (semitones from C4)
# C D E F G A B C
C_MAJOR_SEMITONES = [0, 2, 4, 5, 7, 9, 11, 12]
C_MAJOR_NAMES = ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5']

# C Harmonic Minor scale intervals (semitones from C4)
# C D Eb F G Ab B C
C_HARM_MINOR_SEMITONES = [0, 2, 3, 5, 7, 8, 11, 12]
C_HARM_MINOR_NAMES = ['C4', 'D4', 'Eb4', 'F4', 'G4', 'Ab4', 'B4', 'C5']


def generate_tone(frequency, duration, sample_rate=SAMPLE_RATE, amplitude=0.5):
    """Generate a sine wave tone with fade in/out to avoid clicks."""
    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
    wave = amplitude * np.sin(2 * np.pi * frequency * t)

    # Apply fade in/out (10ms each)
    fade_samples = int(0.01 * sample_rate)
    fade_in = np.linspace(0, 1, fade_samples)
    fade_out = np.linspace(1, 0, fade_samples)

    if len(wave) > 2 * fade_samples:
        wave[:fade_samples] *= fade_in
        wave[-fade_samples:] *= fade_out

    # Make stereo (2D array with shape (samples, 2))
    stereo_wave = np.column_stack([wave, wave])
    return stereo_wave.astype(np.float32)


def play_scale(semitones, note_names, note_duration=0.6, highlight_callback=None):
    """Play a scale given semitone intervals from C4."""
    for i, semitones_val in enumerate(semitones):
        freq = note_freq(C4_FREQ, semitones_val)
        print(f"Playing {note_names[i]}: {freq:.2f} Hz")

        # Highlight the note in the UI
        if highlight_callback:
            highlight_callback(i)

        # Generate and play the tone
        tone = generate_tone(freq, note_duration)
        sd.play(tone, samplerate=SAMPLE_RATE)
        sd.wait()

        # Small gap between notes
        time.sleep(0.05)

    # Clear highlight
    if highlight_callback:
        highlight_callback(-1)


class ScaleDisplayApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Piano Scales: C Major & C Harmonic Minor")
        self.root.configure(bg='#1a1a2e')
        self.root.resizable(False, False)

        # Fonts
        title_font = tkfont.Font(family='Helvetica', size=18, weight='bold')
        scale_font = tkfont.Font(family='Helvetica', size=14, weight='bold')
        note_font = tkfont.Font(family='Helvetica', size=16, weight='bold')
        info_font = tkfont.Font(family='Helvetica', size=11)

        # Title
        title_label = tk.Label(
            root, text="🎵 Piano Scales 🎵",
            font=title_font, bg='#1a1a2e', fg='#e0e0e0'
        )
        title_label.pack(pady=(20, 10))

        # Info label
        info_label = tk.Label(
            root,
            text="Semitones use the 12th root of 2 (equal temperament)",
            font=info_font, bg='#1a1a2e', fg='#a0a0c0'
        )
        info_label.pack(pady=(0, 15))

        # ---- C Major Scale Frame ----
        major_frame = tk.LabelFrame(
            root, text=" C Major Scale ",
            font=scale_font, bg='#16213e', fg='#4fc3f7',
            bd=2, relief='groove', padx=15, pady=15
        )
        major_frame.pack(padx=30, pady=10, fill='x')

        # Semitone info for major
        major_info = tk.Label(
            major_frame,
            text="Intervals (semitones): 0 - 2 - 4 - 5 - 7 - 9 - 11 - 12",
            font=info_font, bg='#16213e', fg='#90caf9'
        )
        major_info.pack(pady=(0, 10))

        self.major_note_frame = tk.Frame(major_frame, bg='#16213e')
        self.major_note_frame.pack()

        self.major_labels = []
        self.major_freq_labels = []

        for i, (name, semi) in enumerate(zip(C_MAJOR_NAMES, C_MAJOR_SEMITONES)):
            freq = note_freq(C4_FREQ, semi)

            col_frame = tk.Frame(self.major_note_frame, bg='#16213e')
            col_frame.grid(row=0, column=i, padx=5, pady=5)

            note_lbl = tk.Label(
                col_frame, text=name,
                font=note_font, bg='#0d47a1', fg='white',
                width=5, height=2, relief='raised', bd=2
            )
            note_lbl.pack()

            freq_lbl = tk.Label(
                col_frame, text=f"{freq:.1f}Hz",
                font=tkfont.Font(family='Helvetica', size=9),
                bg='#16213e', fg='#90caf9'
            )
            freq_lbl.pack(pady=(2, 0))

            self.major_labels.append(note_lbl)
            self.major_freq_labels.append(freq_lbl)

        # Play Major button
        self.major_btn = tk.Button(
            major_frame, text="▶ Play C Major Scale",
            font=scale_font, bg='#1565c0', fg='white',
            activebackground='#1976d2', activeforeground='white',
            relief='raised', bd=3, padx=10, pady=5,
            command=self.play_major
        )
        self.major_btn.pack(pady=(15, 5))

        # ---- C Harmonic Minor Scale Frame ----
        minor_frame = tk.LabelFrame(
            root, text=" C Harmonic Minor Scale ",
            font=scale_font, bg='#16213e', fg='#ef9a9a',
            bd=2, relief='groove', padx=15, pady=15
        )
        minor_frame.pack(padx=30, pady=10, fill='x')

        # Semitone info for harmonic minor
        minor_info = tk.Label(
            minor_frame,
            text="Intervals (semitones): 0 - 2 - 3 - 5 - 7 - 8 - 11 - 12",
            font=info_font, bg='#16213e', fg='#ef9a9a'
        )
        minor_info.pack(pady=(0, 10))

        self.minor_note_frame = tk.Frame(minor_frame, bg='#16213e')
        self.minor_note_frame.pack()

        self.minor_labels = []
        self.minor_freq_labels = []

        for i, (name, semi) in enumerate(zip(C_HARM_MINOR_NAMES, C_HARM_MINOR_SEMITONES)):
            freq = note_freq(C4_FREQ, semi)

            col_frame = tk.Frame(self.minor_note_frame, bg='#16213e')
            col_frame.grid(row=0, column=i, padx=5, pady=5)

            note_lbl = tk.Label(
                col_frame, text=name,
                font=note_font, bg='#b71c1c', fg='white',
                width=5, height=2, relief='raised', bd=2
            )
            note_lbl.pack()

            freq_lbl = tk.Label(
                col_frame, text=f"{freq:.1f}Hz",
                font=tkfont.Font(family='Helvetica', size=9),
                bg='#16213e', fg='#ef9a9a'
            )
            freq_lbl.pack(pady=(2, 0))

            self.minor_labels.append(note_lbl)
            self.minor_freq_labels.append(freq_lbl)

        # Play Minor button
        self.minor_btn = tk.Button(
            minor_frame, text="▶ Play C Harmonic Minor Scale",
            font=scale_font, bg='#c62828', fg='white',
            activebackground='#d32f2f', activeforeground='white',
            relief='raised', bd=3, padx=10, pady=5,
            command=self.play_minor
        )
        self.minor_btn.pack(pady=(15, 5))

        # Play Both button
        both_btn = tk.Button(
            root, text="▶▶ Play Both Scales",
            font=scale_font, bg='#4a148c', fg='white',
            activebackground='#6a1b9a', activeforeground='white',
            relief='raised', bd=3, padx=15, pady=8,
            command=self.play_both
        )
        both_btn.pack(pady=(5, 20))

        # Status label
        self.status_var = tk.StringVar(value="Ready to play!")
        self.status_label = tk.Label(
            root, textvariable=self.status_var,
            font=info_font, bg='#1a1a2e', fg='#80cbc4'
        )
        self.status_label.pack(pady=(0, 15))

        self.playing = False

        print("ScaleDisplayApp initialized successfully.")
        print(f"\nC Major Scale notes and frequencies:")
        for name, semi in zip(C_MAJOR_NAMES, C_MAJOR_SEMITONES):
            print(f"  {name}: {note_freq(C4_FREQ, semi):.2f} Hz (semitone {semi})")

        print(f"\nC Harmonic Minor Scale notes and frequencies:")
        for name, semi in zip(C_HARM_MINOR_NAMES, C_HARM_MINOR_SEMITONES):
            print(f"  {name}: {note_freq(C4_FREQ, semi):.2f} Hz (semitone {semi})")

    def highlight_major(self, index):
        """Highlight a note in the major scale display."""
        for i, lbl in enumerate(self.major_labels):
            if i == index:
                lbl.config(bg='#ffeb3b', fg='#1a1a2e')
            else:
                lbl.config(bg='#0d47a1', fg='white')
        self.root.update_idletasks()

    def highlight_minor(self, index):
        """Highlight a note in the minor scale display."""
        for i, lbl in enumerate(self.minor_labels):
            if i == index:
                lbl.config(bg='#ffeb3b', fg='#1a1a2e')
            else:
                lbl.config(bg='#b71c1c', fg='white')
        self.root.update_idletasks()

    def set_buttons_state(self, state):
        self.major_btn.config(state=state)
        self.minor_btn.config(state=state)

    def play_major(self):
        if self.playing:
            return
        self.playing = True
        self.set_buttons_state('disabled')
        self.status_var.set("Playing C Major Scale...")

        def run():
            play_scale(
                C_MAJOR_SEMITONES,
                C_MAJOR_NAMES,
                note_duration=0.6,
                highlight_callback=self.highlight_major
            )
            self.playing = False
            self.set_buttons_state('normal')
            self.status_var.set("C Major Scale complete!")
            print("C Major Scale playback complete.")

        t = threading.Thread(target=run, daemon=True)
        t.start()

    def play_minor(self):
        if self.playing:
            return
        self.playing = True
        self.set_buttons_state('disabled')
        self.status_var.set("Playing C Harmonic Minor Scale...")

        def run():
            play_scale(
                C_HARM_MINOR_SEMITONES,
                C_HARM_MINOR_NAMES,
                note_duration=0.6,
                highlight_callback=self.highlight_minor
            )
            self.playing = False
            self.set_buttons_state('normal')
            self.status_var.set("C Harmonic Minor Scale complete!")
            print("C Harmonic Minor Scale playback complete.")

        t = threading.Thread(target=run, daemon=True)
        t.start()

    def play_both(self):
        if self.playing:
            return
        self.playing = True
        self.set_buttons_state('disabled')
        self.status_var.set("Playing C Major Scale...")

        def run():
            print("\n--- Playing C Major Scale ---")
            play_scale(
                C_MAJOR_SEMITONES,
                C_MAJOR_NAMES,
                note_duration=0.6,
                highlight_callback=self.highlight_major
            )
            time.sleep(0.5)

            self.status_var.set("Playing C Harmonic Minor Scale...")
            print("\n--- Playing C Harmonic Minor Scale ---")
            play_scale(
                C_HARM_MINOR_SEMITONES,
                C_HARM_MINOR_NAMES,
                note_duration=0.6,
                highlight_callback=self.highlight_minor
            )

            self.playing = False
            self.set_buttons_state('normal')
            self.status_var.set("Both scales complete!")
            print("\nBoth scales playback complete.")

        t = threading.Thread(target=run, daemon=True)
        t.start()


def main():
    print("Starting Piano Scales Application...")
    print(f"C4 base frequency: {C4_FREQ} Hz")
    print(f"Semitone ratio (12th root of 2): {SEMITONE:.6f}")

    root = tk.Tk()
    app = ScaleDisplayApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()