# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-28 05:44:01
# AutoCoder System - Automated Code Generation

import requests
from bs4 import BeautifulSoup

# Target URL - using a reliable, scrapable site
URL = "https://books.toscrape.com/"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

print(f"Fetching: {URL}\n")
response = requests.get(URL, headers=headers, timeout=10)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

# Extract page title
title = soup.find("title")
print(f"Page Title: {title.text.strip() if title else 'N/A'}")
print("-" * 60)

# Extract all book listings
books = soup.find_all("article", class_="product_pod")
print(f"Found {len(books)} books on the page\n")

book_data = []
for book in books:
    name_tag = book.find("h3").find("a")
    name = name_tag["title"] if name_tag and "title" in name_tag.attrs else name_tag.text.strip()

    price_tag = book.find("p", class_="price_color")
    price = price_tag.text.strip() if price_tag else "N/A"

    rating_tag = book.find("p", class_="star-rating")
    rating_word = rating_tag["class"][1] if rating_tag else "N/A"
    rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
    rating = rating_map.get(rating_word, 0)

    availability_tag = book.find("p", class_="instock")
    availability = availability_tag.text.strip() if availability_tag else "Out of stock"

    book_data.append({
        "name": name,
        "price": price,
        "rating": rating,
        "availability": availability
    })

# Print results
print(f"{'#':<4} {'Title':<45} {'Price':<10} {'Rating':<8} {'Available'}")
print("-" * 90)
for i, b in enumerate(book_data, 1):
    stars = "*" * b["rating"]
    print(f"{i:<4} {b['name'][:44]:<45} {b['price']:<10} {stars:<8} {b['availability']}")

# --- Matplotlib visualisation ---
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

prices_numeric = []
for b in book_data:
    try:
        # Handle various currency symbol encodings
        clean_price = b["price"].encode("ascii", "ignore").decode("ascii")
        clean_price = clean_price.replace("£", "").replace("Â", "").strip()
        prices_numeric.append(float(clean_price))
    except ValueError:
        prices_numeric.append(0.0)

ratings = [b["rating"] for b in book_data]
names_short = [b["name"][:20] + "..." if len(b["name"]) > 20 else b["name"] for b in book_data]

rating_counts = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}
for r in ratings:
    if r in rating_counts:
        rating_counts[r] += 1

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
plt.suptitle("Books to Scrape - Web Scraper Results", y=0.98, fontsize=14, fontweight="bold")

colors = ["#d9534f", "#f0ad4e", "#f0e040", "#5cb85c", "#337ab7"]

# 1. Price distribution histogram
ax1 = axes[0, 0]
ax1.hist(prices_numeric, bins=10, color="steelblue", edgecolor="white", linewidth=0.8)
ax1.set_title("Price Distribution")
ax1.set_xlabel("Price (GBP)")
ax1.set_ylabel("Number of Books")
mean_price = np.mean(prices_numeric)
ax1.axvline(mean_price, color="red", linestyle="--", linewidth=1.5,
            label=f"Mean: GBP{mean_price:.2f}")
ax1.legend(fontsize=9)

# 2. Rating distribution bar chart
ax2 = axes[0, 1]
bars = ax2.bar(rating_counts.keys(), rating_counts.values(), color=colors, edgecolor="white")
ax2.set_title("Star Rating Distribution")
ax2.set_xlabel("Star Rating")
ax2.set_ylabel("Number of Books")
ax2.set_xticks([1, 2, 3, 4, 5])
for bar, val in zip(bars, rating_counts.values()):
    ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.1,
             str(val), ha="center", va="bottom", fontsize=10, fontweight="bold")

# 3. Price vs Rating scatter
ax3 = axes[1, 0]
scatter_colors = [colors[r - 1] if r > 0 else "#aaaaaa" for r in ratings]
ax3.scatter(ratings, prices_numeric, c=scatter_colors, s=60, alpha=0.8,
            edgecolors="grey", linewidth=0.5)
ax3.set_title("Price vs Star Rating")
ax3.set_xlabel("Star Rating")
ax3.set_ylabel("Price (GBP)")
ax3.set_xticks([1, 2, 3, 4, 5])
patches = [mpatches.Patch(color=colors[i], label=f"{i+1} Star") for i in range(5)]
ax3.legend(handles=patches, fontsize=8, loc="upper right")

# 4. Top 10 most expensive books
ax4 = axes[1, 1]
sorted_indices = np.argsort(prices_numeric)[::-1][:10]
top_names = [names_short[i] for i in sorted_indices]
top_prices = [prices_numeric[i] for i in sorted_indices]
top_ratings = [ratings[i] for i in sorted_indices]
bar_colors = [colors[r - 1] if r > 0 else "#aaaaaa" for r in top_ratings]

bars2 = ax4.barh(range(len(top_names)), top_prices, color=bar_colors, edgecolor="white")
ax4.set_yticks(range(len(top_names)))
ax4.set_yticklabels(top_names, fontsize=8)
ax4.invert_yaxis()
ax4.set_title("Top 10 Most Expensive Books")
ax4.set_xlabel("Price (GBP)")
for bar, price in zip(bars2, top_prices):
    ax4.text(bar.get_width() + 0.2, bar.get_y() + bar.get_height() / 2,
             f"GBP{price:.2f}", va="center", fontsize=8)

plt.tight_layout()
plt.savefig("books_scraper_results.png", dpi=120, bbox_inches="tight")
plt.show()

print(f"\nScraping complete. {len(book_data)} books parsed.")
print(f"Average price: GBP{np.mean(prices_numeric):.2f}")
print(f"Price range: GBP{min(prices_numeric):.2f} - GBP{max(prices_numeric):.2f}")
print("Chart saved to books_scraper_results.png")