# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-10 22:19:36
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.widgets import Slider
import control

def compute_step_response(zeta, wn=1.0, t_end=20.0, num_points=1000):
    """Compute step response for a second-order system."""
    # Transfer function: wn^2 / (s^2 + 2*zeta*wn*s + wn^2)
    num = [wn**2]
    den = [1, 2 * zeta * wn, wn**2]
    sys = control.tf(num, den)
    t = np.linspace(0, t_end, num_points)
    t_out, y_out = control.step_response(sys, T=t)
    return t_out, y_out

# Initial damping factors
zeta_init = [0.3, 0.7, 1.2]
colors = ['blue', 'green', 'red']
labels_template = ['zeta1 = {:.2f}', 'zeta2 = {:.2f}', 'zeta3 = {:.2f}']

wn = 1.0  # Natural frequency

# Create figure and axes
fig = plt.figure(figsize=(12, 9))
fig.patch.set_facecolor('#f5f5f5')

# Main plot area
ax = fig.add_axes([0.1, 0.45, 0.85, 0.48])
ax.set_facecolor('#ffffff')
ax.set_xlabel('Time (s)', fontsize=12)
ax.set_ylabel('Amplitude', fontsize=12)
ax.set_title('Step Response of Second-Order System\n'
             'H(s) = wn^2 / (s^2 + 2*zeta*wn*s + wn^2),  wn = 1.0 rad/s',
             fontsize=13)
ax.axhline(y=1.0, color='black', linestyle='--', linewidth=1, alpha=0.5, label='Steady State = 1')
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 20)
ax.set_ylim(-0.2, 2.0)

# Initial plot lines
lines = []
for i, (zeta, color) in enumerate(zip(zeta_init, colors)):
    t_out, y_out = compute_step_response(zeta, wn)
    line, = ax.plot(t_out, y_out, color=color, linewidth=2.5,
                    label=labels_template[i].format(zeta))
    lines.append(line)

ax.legend(loc='upper right', fontsize=11)

# Slider axes
ax_slider1 = fig.add_axes([0.15, 0.30, 0.70, 0.04])
ax_slider2 = fig.add_axes([0.15, 0.22, 0.70, 0.04])
ax_slider3 = fig.add_axes([0.15, 0.14, 0.70, 0.04])

slider_color = '#aad4f5'

slider1 = Slider(ax_slider1, 'Damping 1 (blue)', 0.01, 3.0,
                 valinit=zeta_init[0], color=slider_color)
slider2 = Slider(ax_slider2, 'Damping 2 (green)', 0.01, 3.0,
                 valinit=zeta_init[1], color=slider_color)
slider3 = Slider(ax_slider3, 'Damping 3 (red)', 0.01, 3.0,
                 valinit=zeta_init[2], color=slider_color)

# Info text area
ax_info = fig.add_axes([0.1, 0.02, 0.85, 0.09])
ax_info.axis('off')
info_text = ax_info.text(0.5, 0.5, '', transform=ax_info.transAxes,
                          fontsize=10, ha='center', va='center',
                          bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

def get_system_info(zeta):
    """Return system type description."""
    if zeta < 1.0:
        return f"zeta={zeta:.2f} -> Underdamped (oscillatory)"
    elif abs(zeta - 1.0) < 0.001:
        return f"zeta={zeta:.2f} -> Critically damped"
    else:
        return f"zeta={zeta:.2f} -> Overdamped (no oscillation)"

def update(val):
    """Update plot when sliders change."""
    zeta1 = slider1.val
    zeta2 = slider2.val
    zeta3 = slider3.val
    zetas = [zeta1, zeta2, zeta3]

    for i, (zeta, line, color) in enumerate(zip(zetas, lines, colors)):
        t_out, y_out = compute_step_response(zeta, wn)
        line.set_xdata(t_out)
        line.set_ydata(y_out)
        line.set_label(labels_template[i].format(zeta))

    ax.legend(loc='upper right', fontsize=11)

    # Update info text
    info_parts = [get_system_info(z) for z in zetas]
    info_text.set_text('  |  '.join(info_parts))

    fig.canvas.draw_idle()

slider1.on_changed(update)
slider2.on_changed(update)
slider3.on_changed(update)

# Initial info text
zetas_init = [slider1.val, slider2.val, slider3.val]
info_parts = [get_system_info(z) for z in zetas_init]
info_text.set_text('  |  '.join(info_parts))

print("Second-Order System Step Response Viewer")
print("==========================================")
print(f"Transfer Function: H(s) = wn^2 / (s^2 + 2*zeta*wn*s + wn^2)")
print(f"Natural Frequency (wn): {wn} rad/s")
print(f"Initial damping factors: {zeta_init}")
print()
print("System behavior:")
print("  zeta < 1.0  -> Underdamped  (oscillatory response)")
print("  zeta = 1.0  -> Critically damped (fastest non-oscillatory)")
print("  zeta > 1.0  -> Overdamped   (slow, no oscillation)")
print()
print("Use the sliders to control each damping factor independently.")
print("Close the plot window to exit.")

plt.suptitle('Interactive Second-Order System Step Response', fontsize=14, fontweight='bold', y=0.99)
plt.show()