# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-04 19:58:18
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# Self-Tuning LQG Controller Simulation
# LQG = Linear Quadratic Gaussian (LQR + Kalman Filter)
# Self-tuning: parameters estimated online using Recursive Least Squares (RLS)

np.random.seed(42)

# ============================================================
# System Definition (True Unknown System)
# ============================================================
# True system: x(k+1) = A*x(k) + B*u(k) + w(k)
#              y(k)   = C*x(k) + v(k)

dt = 0.1  # sampling time
n_states = 2
n_inputs = 1
n_outputs = 1

# True system matrices (unknown to controller initially)
A_true = np.array([[1.0, dt],
                   [0.0, 1.0]])  # Double integrator

B_true = np.array([[0.5 * dt ** 2],
                   [dt]])

C_true = np.array([[1.0, 0.0]])

# Noise covariances
Q_noise = np.diag([0.01, 0.01])  # Process noise covariance
R_noise = np.array([[0.1]])  # Measurement noise covariance

# ============================================================
# LQR Cost Matrices
# ============================================================
Q_lqr = np.diag([100.0, 1.0])  # State cost
R_lqr = np.array([[0.1]])  # Control cost

# ============================================================
# Simulation Parameters
# ============================================================
N = 300  # Number of time steps
t = np.arange(N) * dt

# Reference trajectory (step + sinusoidal)
r = np.zeros(N)
r[:100] = 1.0
r[100:200] = -0.5
r[200:] = 0.5


# ============================================================
# Helper Functions
# ============================================================

def dare(A, B, Q, R):
    """Solve Discrete Algebraic Riccati Equation using iteration."""
    P = Q.copy()
    for _ in range(1000):
        P_new = (A.T @ P @ A -
                 A.T @ P @ B @ np.linalg.inv(R + B.T @ P @ B) @ B.T @ P @ A + Q)
        if np.max(np.abs(P_new - P)) < 1e-8:
            break
        P = P_new
    return P


def compute_lqr_gain(A, B, Q, R):
    """Compute LQR gain K."""
    try:
        P = dare(A, B, Q, R)
        K = np.linalg.inv(R + B.T @ P @ B) @ B.T @ P @ A
        return K
    except np.linalg.LinAlgError:
        return np.zeros((n_inputs, n_states))


def kalman_predict(x_est, P_est, A, B, u, Q):
    """Kalman Filter prediction step."""
    x_pred = A @ x_est + B @ u
    P_pred = A @ P_est @ A.T + Q
    return x_pred, P_pred


def kalman_update(x_pred, P_pred, y, C, R):
    """Kalman Filter update step."""
    S = C @ P_pred @ C.T + R
    K_kalman = P_pred @ C.T @ np.linalg.inv(S)
    innovation = y - C @ x_pred
    x_est = x_pred + K_kalman @ innovation
    P_est = (np.eye(len(x_pred)) - K_kalman @ C) @ P_pred
    return x_est, P_est, K_kalman


# ============================================================
# Recursive Least Squares (RLS) for System Identification
# ============================================================
class RLS:
    """Recursive Least Squares estimator for system identification."""

    def __init__(self, n_params, forgetting_factor=0.98):
        self.n = n_params
        self.lam = forgetting_factor
        self.theta = np.zeros(n_params)  # Parameter estimates
        self.P = 1000 * np.eye(n_params)  # Covariance matrix

    def update(self, phi, y):
        """Update parameter estimates."""
        # Innovation
        y_pred = phi @ self.theta
        e = y - y_pred

        # Kalman gain for RLS
        denom = self.lam + phi @ self.P @ phi
        K_rls = self.P @ phi / denom

        # Update estimates
        self.theta = self.theta + K_rls * e
        self.P = (self.P - np.outer(K_rls, phi @ self.P)) / self.lam

        return self.theta.copy(), e


# ============================================================
# Initialize Self-Tuning LQG Controller
# ============================================================

# Initial (incorrect) model estimates
A_est = np.array([[1.0, dt],
                  [0.0, 0.9]])  # Slightly wrong

B_est = np.array([[0.3 * dt ** 2],
                  [0.8 * dt]])  # Slightly wrong

# RLS estimators for each state equation
# State 1: x1(k+1) = a11*x1(k) + a12*x2(k) + b1*u(k)
# State 2: x2(k+1) = a21*x1(k) + a22*x2(k) + b2*u(k)
rls_state1 = RLS(n_params=3, forgetting_factor=0.97)
rls_state2 = RLS(n_params=3, forgetting_factor=0.97)

# Initialize RLS with rough estimates
rls_state1.theta = np.array([A_est[0, 0], A_est[0, 1], B_est[0, 0]])
rls_state2.theta = np.array([A_est[1, 0], A_est[1, 1], B_est[1, 0]])

# Kalman filter state
x_est = np.zeros(n_states)
P_est = np.eye(n_states) * 1.0

# LQR gain (initial)
K_lqr = compute_lqr_gain(A_est, B_est, Q_lqr, R_lqr)

# ============================================================
# Storage Arrays
# ============================================================
x_true_hist = np.zeros((N, n_states))
x_est_hist = np.zeros((N, n_states))
u_hist = np.zeros(N)
y_hist = np.zeros(N)
r_hist = r.copy()

A11_hist = np.zeros(N)
A12_hist = np.zeros(N)
A21_hist = np.zeros(N)
A22_hist = np.zeros(N)
B1_hist = np.zeros(N)
B2_hist = np.zeros(N)

K_lqr_hist = np.zeros((N, n_states))
innovation_hist = np.zeros(N)

# True system state
x_true = np.array([0.0, 0.0])

print("=" * 60)
print("Self-Tuning LQG Controller Simulation")
print("=" * 60)
print(f"True System A:\n{A_true}")
print(f"True System B:\n{B_true}")
print(f"Initial Estimated A:\n{A_est}")
print(f"Initial Estimated B:\n{B_est}")
print(f"Simulation steps: {N}, dt={dt}s")
print("=" * 60)

# ============================================================
# Main Simulation Loop
# ============================================================
update_interval = 5  # Update model every N steps

for k in range(N):
    # --- Reference tracking ---
    ref = r[k]

    # --- Compute LQR control (with integral action for tracking) ---
    # Augmented state for reference tracking
    x_error = x_est.copy()
    x_error[0] -= ref  # Position error

    u = -K_lqr @ x_error
    u = np.clip(u, -10.0, 10.0)  # Actuator saturation
    u_scalar = float(u[0]) if hasattr(u, '__len__') else float(u)

    # --- Apply control to true system ---
    w = np.random.multivariate_normal(np.zeros(n_states), Q_noise)
    x_true_new = A_true @ x_true + B_true.flatten() * u_scalar + w

    # --- Measurement ---
    v = np.random.multivariate_normal(np.zeros(n_outputs), R_noise)
    y = C_true @ x_true + v
    y_scalar = float(y[0])

    # --- Store data ---
    x_true_hist[k] = x_true
    y_hist[k] = y_scalar
    u_hist[k] = u_scalar

    # --- Kalman Filter (using current model estimate) ---
    u_vec = np.array([u_scalar])
    x_pred, P_pred = kalman_predict(x_est, P_est, A_est, B_est, u_vec, Q_noise)
    x_est, P_est, K_kalman = kalman_update(x_pred, P_pred,
                                           np.array([y_scalar]), C_true, R_noise)

    x_est_hist[k] = x_est
    innovation_hist[k] = y_scalar - float(C_true @ x_pred)

    # --- RLS System Identification ---
    if k > 0:
        phi = np.array([x_true_hist[k - 1, 0], x_true_hist[k - 1, 1], u_hist[k - 1]])

        # Update state 1 model
        theta1, e1 = rls_state1.update(phi, x_true[0])
        # Update state 2 model
        theta2, e2 = rls_state2.update(phi, x_true[1])

        # Update model estimates
        A_est[0, 0] = theta1[0]
        A_est[0, 1] = theta1[1]
        B_est[0, 0] = theta1[2]
        A_est[1, 0] = theta2[0]
        A_est[1, 1] = theta2[1]
        B_est[1, 0] = theta2[2]

        # Recompute LQR gain periodically
        if k % update_interval == 0:
            K_lqr_new = compute_lqr_gain(A_est, B_est, Q_lqr, R_lqr)
            if not np.any(np.isnan(K_lqr_new)):
                K_lqr = K_lqr_new

    # --- Store parameter estimates ---
    A11_hist[k] = A_est[0, 0]
    A12_hist[k] = A_est[0, 1]
    A21_hist[k] = A_est[1, 0]
    A22_hist[k] = A_est[1, 1]
    B1_hist[k] = B_est[0, 0]
    B2_hist[k] = B_est[1, 0]
    K_lqr_hist[k] = K_lqr.flatten()

    # --- Update true state ---
    x_true = x_true_new

# ============================================================
# Performance Metrics
# ============================================================
tracking_error = r - x_true_hist[:, 0]
rmse = np.sqrt(np.mean(tracking_error ** 2))
rmse_steady = np.sqrt(np.mean(tracking_error[100:] ** 2))

print(f"\nPerformance Metrics:")
print(f"  Overall RMSE: {rmse:.4f}")
print(f"  Steady-state RMSE (after t=10s): {rmse_steady:.4f}")
print(f"  Max control effort: {np.max(np.abs(u_hist)):.4f}")
print(f"\nFinal Parameter Estimates vs True:")
print(f"  A[0,0]: est={A_est[0, 0]:.4f}, true={A_true[0, 0]:.4f}")
print(f"  A[0,1]: est={A_est[0, 1]:.4f}, true={A_true[0, 1]:.4f}")
print(f"  A[1,0]: est={A_est[1, 0]:.4f}, true={A_true[1, 0]:.4f}")
print(f"  A[1,1]: est={A_est[1, 1]:.4f}, true={A_true[1, 1]:.4f}")
print(f"  B[0,0]: est={B_est[0, 0]:.4f}, true={B_true[0, 0]:.4f}")
print(f"  B[1,0]: est={B_est[1, 0]:.4f}, true={B_true[1, 0]:.4f}")

# ============================================================
# Plotting
# ============================================================
fig = plt.figure(figsize=(16, 14))
fig.suptitle('Self-Tuning LQG Controller Simulation', fontsize=14, fontweight='bold')
gs = GridSpec(4, 2, figure=fig, hspace=0.45, wspace=0.35)

# --- Plot 1: Position tracking ---
ax1 = fig.add_subplot(gs[0, :])
ax1.plot(t, r, 'k--', linewidth=2, label='Reference', alpha=0.8)
ax1.plot(t, x_true_hist[:, 0], 'b-', linewidth=1.5, label='True Position')
ax1.plot(t, x_est_hist[:, 0], 'r--', linewidth=1, label='Estimated Position', alpha=0.7)
ax1.set_xlabel('Time (s)')
ax1.set_ylabel('Position')
ax1.set_title('Position Tracking')
ax1.legend(loc='upper right')
ax1.grid(True, alpha=0.3)
ax1.fill_between(t, r, x_true_hist[:, 0], alpha=0.1, color='red', label='Error')

# --- Plot 2: Velocity ---
ax2 = fig.add_subplot(gs[1, 0])
ax2.plot(t, x_true_hist[:, 1], 'b-', linewidth=1.5, label='True Velocity')
ax2.plot(t, x_est_hist[:, 1], 'r--', linewidth=1, label='Estimated Velocity', alpha=0.7)
ax2.set_xlabel('Time (s)')
ax2.set_ylabel('Velocity')
ax2.set_title('Velocity State')
ax2.legend()
ax2.grid(True, alpha=0.3)

# --- Plot 3: Control Input ---
ax3 = fig.add_subplot(gs[1, 1])
ax3.plot(t, u_hist, 'g-', linewidth=1.5)
ax3.axhline(y=10, color='r', linestyle='--', alpha=0.5, label='Saturation')
ax3.axhline(y=-10, color='r', linestyle='--', alpha=0.5)
ax3.set_xlabel('Time (s)')
ax3.set_ylabel('Control Input u')
ax3.set_title('Control Signal')
ax3.legend()
ax3.grid(True, alpha=0.3)

# --- Plot 4: A matrix parameter convergence ---
ax4 = fig.add_subplot(gs[2, 0])
ax4.plot(t, A11_hist, 'b-', label=f'A[0,0] est', linewidth=1.5)
ax4.axhline(y=A_true[0, 0], color='b', linestyle='--', alpha=0.7, label=f'A[0,0] true={A_true[0, 0]:.2f}')
ax4.plot(t, A12_hist, 'r-', label=f'A[0,1] est', linewidth=1.5)
ax4.axhline(y=A_true[0, 1], color='r', linestyle='--', alpha=0.7, label=f'A[0,1] true={A_true[0, 1]:.2f}')
ax4.plot(t, A22_hist, 'g-', label=f'A[1,1] est', linewidth=1.5)
ax4.axhline(y=A_true[1, 1], color='g', linestyle='--', alpha=0.7, label=f'A[1,1] true={A_true[1, 1]:.2f}')
ax4.set_xlabel('Time (s)')
ax4.set_ylabel('Parameter Value')
ax4.set_title('A Matrix Parameter Convergence (RLS)')
ax4.legend(fontsize=7)
ax4.grid(True, alpha=0.3)

# --- Plot 5: B matrix parameter convergence ---
ax5 = fig.add_subplot(gs[2, 1])
ax5.plot(t, B1_hist, 'b-', label=f'B[0,0] est', linewidth=1.5)
ax5.axhline(y=B_true[0, 0], color='b', linestyle='--', alpha=0.7, label=f'B[0,0] true={B_true[0, 0]:.4f}')
ax5.plot(t, B2_hist, 'r-', label=f'B[1,0] est', linewidth=1.5)
ax5.axhline(y=B_true[1, 0], color='r', linestyle='--', alpha=0.7, label=f'B[1,0] true={B_true[1, 0]:.2f}')
ax5.set_xlabel('Time (s)')
ax5.set_ylabel('Parameter Value')
ax5.set_title('B Matrix Parameter Convergence (RLS)')
ax5.legend(fontsize=8)
ax5.grid(True, alpha=0.3)

# --- Plot 6: LQR Gain Evolution ---
ax6 = fig.add_subplot(gs[3, 0])
ax6.plot(t, K_lqr_hist[:, 0], 'b-', linewidth=1.5, label='K[0] (position gain)')
ax6.plot(t, K_lqr_hist[:, 1], 'r-', linewidth=1.5, label='K[1] (velocity gain)')
ax6.set_xlabel('Time (s)')
ax6.set_ylabel('Gain Value')
ax6.set_title('Adaptive LQR Gain Evolution')
ax6.legend()
ax6.grid(True, alpha=0.3)

# --- Plot 7: Innovation / Tracking Error ---
ax7 = fig.add_subplot(gs[3, 1])
ax7.plot(t, tracking_error, 'purple', linewidth=1.5, label='Tracking Error')
ax7.plot(t, innovation_hist, 'orange', linewidth=1, label='Kalman Innovation', alpha=0.7)
ax7.axhline(y=0, color='k', linestyle='-', alpha=0.3)
ax7.set_xlabel('Time (s)')
ax7.set_ylabel('Error')
ax7.set_title(f'Tracking Error & Innovation (RMSE={rmse:.4f})')
ax7.legend()
ax7.grid(True, alpha=0.3)

plt.savefig('self_tuning_lqg.png', dpi=100, bbox_inches='tight')
print("\nPlot saved as 'self_tuning_lqg.png'")
plt.show()

print("\n" + "=" * 60)
print("Simulation Complete!")
print("=" * 60)
print("\nController Architecture:")
print("  • Kalman Filter: State estimation from noisy measurements")
print("  • LQR: Optimal state feedback control")
print("  • RLS: Online system identification (self-tuning)")
print("  • Self-tuning: LQR gains updated as model improves")