# Generated by: ministral-3:latest (Ollama)
# Date: 2026-02-16 19:51:01
# AutoCoder System - Automated Code Generation

import tkinter as tk
from tkinter import messagebox
import sounddevice as sd
import numpy as np
import time
import threading

# Morse code dictionary
MORSE_CODE_DICT = {
    'S': '...',
    'O': '---',
    ' ': '/'
}

# Audio parameters
SAMPLE_RATE = 44100
DURATION = 0.5  # seconds per dot/dash
DOT_FREQ = 800  # Hz for dot
DASH_FREQ = 400  # Hz for dash (lower frequency for dash)
SPACE_BETWEEN = 0.2  # seconds between symbols
WORD_SPACE = 3.0  # seconds between words

def play_tone(frequency, duration):
    """Generate and play a tone for given frequency and duration"""
    t = np.linspace(0, duration, int(SAMPLE_RATE * duration), False)
    audio = 0.5 * np.sin(2 * np.pi * frequency * t)
    sd.play(audio, SAMPLE_RATE)
    sd.wait()

def play_morse_code(text):
    """Play Morse code for given text"""
    for char in text:
        if char in MORSE_CODE_DICT:
            for symbol in MORSE_CODE_DICT[char]:
                if symbol == '.':
                    play_tone(DOT_FREQ, DURATION)
                elif symbol == '-':
                    play_tone(DASH_FREQ, DURATION * 3)
                time.sleep(SPACE_BETWEEN)
            time.sleep(WORD_SPACE if char == ' ' else SPACE_BETWEEN)

def continuous_sos():
    """Continuously play SOS Morse code"""
    while True:
        print("Playing SOS...")
        play_morse_code("SOS")
        time.sleep(1)  # Pause between SOS repetitions

def start_sos():
    """Start the continuous SOS playback in a separate thread"""
    global sos_thread
    if not sos_thread or not sos_thread.is_alive():
        sos_thread = threading.Thread(target=continuous_sos, daemon=True)
        sos_thread.start()
        status_var.set("SOS: Playing")
    else:
        messagebox.showwarning("Warning", "SOS is already playing!")

def stop_sos():
    """Stop the continuous SOS playback"""
    global sos_thread
    if sos_thread and sos_thread.is_alive():
        sos_thread = None
        status_var.set("SOS: Stopped")

def create_gui():
    """Create the Tkinter GUI"""
    global root, status_var

    root = tk.Tk()
    root.title("SOS Morse Code Player")
    root.geometry("400x200")

    status_var = tk.StringVar()
    status_var.set("SOS: Ready")

    tk.Label(root, text="SOS Morse Code Player", font=('Arial', 16)).pack(pady=10)

    play_button = tk.Button(root, text="Start SOS", command=start_sos, padx=20, pady=10)
    play_button.pack(pady=5)

    stop_button = tk.Button(root, text="Stop SOS", command=stop_sos, padx=20, pady=10)
    stop_button.pack(pady=5)

    status_label = tk.Label(root, textvariable=status_var, font=('Arial', 12))
    status_label.pack(pady=10)

    root.mainloop()

# Global variables
sos_thread = None

# Start the GUI
if __name__ == "__main__":
    print("Initializing SOS Morse Code Player...")
    create_gui()