# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-09 07:45:16
# AutoCoder System - Automated Code Generation

import requests
import sounddevice as sd
import numpy as np
import wave
import io
import tempfile
import os
import time

# Free WAV audio files from SoundBible.com
# Using direct download links from SoundBible.com
AUDIO_FILES = [
    {
        "name": "Service Bell Help",
        "url": "https://soundbible.com/grab.php?id=2218&type=wav",
    },
    {
        "name": "SOS Morse Code",
        "url": "https://soundbible.com/grab.php?id=2215&type=wav",
    },
    {
        "name": "Labrador Barking Dog",
        "url": "https://soundbible.com/grab.php?id=2216&type=wav",
    },
]

# Fallback: generate simple tones if downloads fail
def generate_tone(frequency=440, duration=2.0, sample_rate=44100, amplitude=0.5):
    """Generate a simple sine wave tone."""
    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
    tone = amplitude * np.sin(2 * np.pi * frequency * t)
    return tone.astype(np.float32), sample_rate

def download_wav(url, name):
    """Download a WAV file from a URL and return as bytes."""
    print(f"  Downloading: {name}")
    print(f"  URL: {url}")
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }
    try:
        response = requests.get(url, headers=headers, timeout=15)
        response.raise_for_status()
        content_type = response.headers.get("Content-Type", "")
        print(f"  Status: {response.status_code}, Content-Type: {content_type}, Size: {len(response.content)} bytes")
        return response.content
    except requests.exceptions.RequestException as e:
        print(f"  Download failed: {e}")
        return None

def read_wav_from_bytes(wav_bytes):
    """Read WAV data from bytes and return numpy array + sample rate."""
    try:
        with io.BytesIO(wav_bytes) as buf:
            with wave.open(buf, 'rb') as wf:
                n_channels = wf.getnchannels()
                sampwidth = wf.getsampwidth()
                framerate = wf.getframerate()
                n_frames = wf.getnframes()
                raw_data = wf.readframes(n_frames)

                print(f"  WAV info: channels={n_channels}, sample_width={sampwidth}, "
                      f"framerate={framerate}, frames={n_frames}")

                # Convert raw bytes to numpy array
                if sampwidth == 1:
                    dtype = np.uint8
                elif sampwidth == 2:
                    dtype = np.int16
                elif sampwidth == 4:
                    dtype = np.int32
                else:
                    print(f"  Unsupported sample width: {sampwidth}")
                    return None, None

                audio_data = np.frombuffer(raw_data, dtype=dtype)

                # Reshape for multiple channels
                if n_channels > 1:
                    audio_data = audio_data.reshape(-1, n_channels)

                # Normalize to float32 in range [-1, 1]
                if dtype == np.uint8:
                    audio_float = (audio_data.astype(np.float32) - 128) / 128.0
                elif dtype == np.int16:
                    audio_float = audio_data.astype(np.float32) / 32768.0
                elif dtype == np.int32:
                    audio_float = audio_data.astype(np.float32) / 2147483648.0

                return audio_float, framerate
    except Exception as e:
        print(f"  Error reading WAV: {e}")
        return None, None

def play_audio(audio_data, sample_rate, name):
    """Play audio using sounddevice."""
    print(f"\n  Playing: {name}")
    duration = len(audio_data) / sample_rate
    print(f"  Duration: {duration:.2f} seconds, Sample rate: {sample_rate} Hz")
    try:
        sd.play(audio_data, samplerate=sample_rate)
        sd.wait()  # Wait until playback is finished
        print(f"  Finished playing: {name}")
    except Exception as e:
        print(f"  Playback error: {e}")

def save_wav_temp(wav_bytes, name):
    """Save WAV bytes to a temp file and return path."""
    try:
        suffix = f"_{name.replace(' ', '_')}.wav"
        with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
            tmp.write(wav_bytes)
            return tmp.name
    except Exception as e:
        print(f"  Could not save temp file: {e}")
        return None

def main():
    print("=" * 60)
    print("Free WAV Audio Downloader and Player")
    print("Source: SoundBible.com")
    print("=" * 60)

    played_count = 0
    failed_downloads = []

    for audio_info in AUDIO_FILES:
        name = audio_info["name"]
        url = audio_info["url"]

        print(f"\n[{name}]")

        # Download the WAV file
        wav_bytes = download_wav(url, name)

        if wav_bytes and len(wav_bytes) > 100:
            # Save to temp file for reference
            temp_path = save_wav_temp(wav_bytes, name)
            if temp_path:
                print(f"  Saved to: {temp_path}")

            # Read WAV data
            audio_data, sample_rate = read_wav_from_bytes(wav_bytes)

            if audio_data is not None and sample_rate is not None:
                play_audio(audio_data, sample_rate, name)
                played_count += 1

                # Clean up temp file
                if temp_path and os.path.exists(temp_path):
                    os.unlink(temp_path)
            else:
                print(f"  Could not decode WAV data for: {name}")
                failed_downloads.append(name)
        else:
            print(f"  Download failed or empty response for: {name}")
            failed_downloads.append(name)

        time.sleep(0.5)  # Small pause between sounds

    # If downloads failed, play generated tones as fallback
    if failed_downloads:
        print(f"\n{'=' * 60}")
        print(f"Downloads failed for {len(failed_downloads)} file(s).")
        print("Playing generated tones as fallback...")
        print("=" * 60)

        fallback_tones = [
            {"name": "A4 - 440 Hz Tone", "freq": 440, "duration": 2.0},
            {"name": "C5 - 523 Hz Tone", "freq": 523, "duration": 2.0},
            {"name": "E5 - 659 Hz Tone", "freq": 659, "duration": 2.0},
        ]

        for tone_info in fallback_tones:
            print(f"\n[{tone_info['name']}]")
            audio_data, sample_rate = generate_tone(
                frequency=tone_info["freq"],
                duration=tone_info["duration"]
            )
            play_audio(audio_data, sample_rate, tone_info["name"])
            played_count += 1
            time.sleep(0.3)

    print(f"\n{'=' * 60}")
    print(f"Playback complete. Played {played_count} audio file(s).")
    print("=" * 60)

if __name__ == "__main__":
    main()