# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-04 12:11:49
# AutoCoder System - Automated Code Generation

import pygame
import numpy as np
import sys
import random
import sounddevice as sd
from threading import Thread
import time

# Initialize pygame
pygame.init()

# Screen dimensions
WIDTH, HEIGHT = 800, 600
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Space Invaders")

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
CYAN = (0, 255, 255)
YELLOW = (255, 255, 0)
MAGENTA = (255, 0, 255)
ORANGE = (255, 165, 0)
DARK_GREEN = (0, 180, 0)
BLUE = (50, 100, 255)
PURPLE = (150, 0, 255)

# Clock
clock = pygame.time.Clock()
FPS = 60

# Sample rate for audio
SAMPLE_RATE = 44100


# ─── Sound Generation ───────────────────────────────────────────────────────

def generate_tone(freq, duration, volume=0.3, wave_type='sine', sample_rate=SAMPLE_RATE):
    """Generate a numpy audio buffer."""
    frames = int(sample_rate * duration)
    t = np.linspace(0, duration, frames, endpoint=False)
    if wave_type == 'sine':
        wave = np.sin(2 * np.pi * freq * t)
    elif wave_type == 'square':
        wave = np.sign(np.sin(2 * np.pi * freq * t))
    elif wave_type == 'sawtooth':
        wave = 2 * (t * freq - np.floor(t * freq + 0.5))
    elif wave_type == 'noise':
        wave = np.random.uniform(-1, 1, frames)
    else:
        wave = np.sin(2 * np.pi * freq * t)

    # Apply envelope
    envelope = np.ones(frames)
    attack = int(frames * 0.05)
    release = int(frames * 0.2)
    if attack > 0:
        envelope[:attack] = np.linspace(0, 1, attack)
    if release > 0:
        envelope[-release:] = np.linspace(1, 0, release)
    wave = wave * envelope * volume
    return wave.astype(np.float32)


def play_sound_async(wave):
    """Play a sound buffer asynchronously."""

    def _play():
        try:
            sd.play(wave, SAMPLE_RATE)
            sd.wait()
        except Exception:
            pass

    t = Thread(target=_play, daemon=True)
    t.start()


def make_shoot_sound():
    """Player shoot sound."""
    frames = int(SAMPLE_RATE * 0.15)
    t = np.linspace(0, 0.15, frames, endpoint=False)
    freq = np.linspace(800, 200, frames)
    wave = np.sin(2 * np.pi * freq * t)
    envelope = np.linspace(1, 0, frames) ** 2
    return (wave * envelope * 0.4).astype(np.float32)


def make_invader_shoot_sound():
    """Invader shoot sound."""
    frames = int(SAMPLE_RATE * 0.2)
    t = np.linspace(0, 0.2, frames, endpoint=False)
    freq = np.linspace(300, 100, frames)
    wave = np.sign(np.sin(2 * np.pi * freq * t))
    envelope = np.linspace(1, 0, frames) ** 1.5
    return (wave * envelope * 0.3).astype(np.float32)


def make_explosion_sound():
    """Explosion sound."""
    frames = int(SAMPLE_RATE * 0.4)
    noise = np.random.uniform(-1, 1, frames)
    t = np.linspace(0, 0.4, frames, endpoint=False)
    low_freq = np.sin(2 * np.pi * 60 * t)
    wave = noise * 0.7 + low_freq * 0.3
    envelope = np.exp(-t * 8)
    return (wave * envelope * 0.5).astype(np.float32)


def make_invader_death_sound():
    """Invader death sound."""
    frames = int(SAMPLE_RATE * 0.3)
    t = np.linspace(0, 0.3, frames, endpoint=False)
    freq = np.linspace(400, 50, frames)
    noise = np.random.uniform(-1, 1, frames)
    wave = np.sin(2 * np.pi * freq * t) * 0.5 + noise * 0.5
    envelope = np.exp(-t * 6)
    return (wave * envelope * 0.4).astype(np.float32)


def make_march_sound(freq):
    """Invader march sound."""
    frames = int(SAMPLE_RATE * 0.08)
    t = np.linspace(0, 0.08, frames, endpoint=False)
    wave = np.sign(np.sin(2 * np.pi * freq * t))
    envelope = np.ones(frames)
    release = int(frames * 0.3)
    envelope[-release:] = np.linspace(1, 0, release)
    return (wave * envelope * 0.2).astype(np.float32)


def make_ufo_sound_chunk(phase):
    """UFO sound chunk."""
    frames = int(SAMPLE_RATE * 0.05)
    t = np.arange(frames) / SAMPLE_RATE
    freq = 200 + 100 * np.sin(2 * np.pi * 3 * (phase + t))
    wave = np.sin(2 * np.pi * freq * t)
    return (wave * 0.25).astype(np.float32), phase + frames / SAMPLE_RATE


def make_level_up_sound():
    """Level up fanfare."""
    parts = []
    for freq in [523, 659, 784, 1047]:
        parts.append(generate_tone(freq, 0.1, 0.3, 'sine'))
    return np.concatenate(parts)


def make_game_over_sound():
    """Game over sound."""
    parts = []
    for freq in [400, 300, 200, 150]:
        parts.append(generate_tone(freq, 0.2, 0.4, 'square'))
    return np.concatenate(parts)


# Pre-generate sounds
SHOOT_SOUND = make_shoot_sound()
INVADER_SHOOT_SOUND = make_invader_shoot_sound()
EXPLOSION_SOUND = make_explosion_sound()
INVADER_DEATH_SOUND = make_invader_death_sound()
MARCH_SOUNDS = [make_march_sound(f) for f in [110, 138, 165, 138]]
LEVEL_UP_SOUND = make_level_up_sound()
GAME_OVER_SOUND = make_game_over_sound()


# ─── Drawing Helpers ─────────────────────────────────────────────────────────

def draw_star_field(surface, stars):
    for (x, y, brightness) in stars:
        c = int(brightness)
        pygame.draw.circle(surface, (c, c, c), (x, y), 1)


def draw_player(surface, x, y):
    """Draw a detailed spaceship."""
    # Main body
    body_pts = [
        (x, y - 20),
        (x - 8, y - 5),
        (x - 15, y + 10),
        (x + 15, y + 10),
        (x + 8, y - 5),
    ]
    pygame.draw.polygon(surface, CYAN, body_pts)
    pygame.draw.polygon(surface, WHITE, body_pts, 1)

    # Cockpit
    pygame.draw.ellipse(surface, BLUE, (x - 5, y - 12, 10, 10))

    # Wings
    left_wing = [(x - 15, y + 10), (x - 25, y + 15), (x - 10, y + 5)]
    right_wing = [(x + 15, y + 10), (x + 25, y + 15), (x + 10, y + 5)]
    pygame.draw.polygon(surface, BLUE, left_wing)
    pygame.draw.polygon(surface, BLUE, right_wing)
    pygame.draw.polygon(surface, WHITE, left_wing, 1)
    pygame.draw.polygon(surface, WHITE, right_wing, 1)

    # Engine glow
    glow_y = y + 10
    for i in range(3):
        alpha = 200 - i * 60
        r = 4 + i * 2
        pygame.draw.circle(surface, (255, 100 + i * 30, 0), (x, glow_y + i * 2), r)


def draw_invader(surface, x, y, inv_type, frame):
    """Draw pixel-art style invaders."""
    if inv_type == 0:  # Top row - squid
        color = MAGENTA
        # Body
        pygame.draw.rect(surface, color, (x - 8, y - 8, 16, 12))
        # Eyes
        pygame.draw.rect(surface, BLACK, (x - 5, y - 5, 3, 3))
        pygame.draw.rect(surface, BLACK, (x + 2, y - 5, 3, 3))
        # Tentacles
        if frame % 2 == 0:
            pygame.draw.rect(surface, color, (x - 10, y + 4, 4, 6))
            pygame.draw.rect(surface, color, (x - 2, y + 4, 4, 6))
            pygame.draw.rect(surface, color, (x + 6, y + 4, 4, 6))
        else:
            pygame.draw.rect(surface, color, (x - 12, y + 6, 4, 6))
            pygame.draw.rect(surface, color, (x - 2, y + 6, 4, 6))
            pygame.draw.rect(surface, color, (x + 8, y + 6, 4, 6))
    elif inv_type == 1:  # Middle rows - crab
        color = GREEN
        # Body
        pygame.draw.rect(surface, color, (x - 10, y - 6, 20, 10))
        # Eyes
        pygame.draw.rect(surface, BLACK, (x - 6, y - 4, 3, 3))
        pygame.draw.rect(surface, BLACK, (x + 3, y - 4, 3, 3))
        # Claws
        if frame % 2 == 0:
            pygame.draw.rect(surface, color, (x - 14, y - 2, 5, 8))
            pygame.draw.rect(surface, color, (x + 9, y - 2, 5, 8))
        else:
            pygame.draw.rect(surface, color, (x - 14, y + 2, 5, 8))
            pygame.draw.rect(surface, color, (x + 9, y + 2, 5, 8))
        # Legs
        for i in range(3):
            lx = x - 8 + i * 8
            pygame.draw.line(surface, color, (lx, y + 4), (lx - 3, y + 10), 2)
            pygame.draw.line(surface, color, (lx, y + 4), (lx + 3, y + 10), 2)
    else:  # Bottom rows - octopus
        color = YELLOW
        # Body
        pygame.draw.ellipse(surface, color, (x - 10, y - 8, 20, 14))
        # Eyes
        pygame.draw.circle(surface, BLACK, (x - 4, y - 3), 3)
        pygame.draw.circle(surface, BLACK, (x + 4, y - 3), 3)
        pygame.draw.circle(surface, WHITE, (x - 3, y - 4), 1)
        pygame.draw.circle(surface, WHITE, (x + 5, y - 4), 1)
        # Tentacles
        offsets = [-8, -4, 0, 4, 8] if frame % 2 == 0 else [-10, -5, 0, 5, 10]
        for ox in offsets:
            pygame.draw.line(surface, color, (x + ox, y + 6), (x + ox, y + 14), 2)


def draw_bullet(surface, x, y, color=YELLOW):
    pygame.draw.rect(surface, color, (x - 2, y - 8, 4, 16))
    pygame.draw.rect(surface, WHITE, (x - 1, y - 8, 2, 4))


def draw_invader_bullet(surface, x, y):
    pygame.draw.rect(surface, RED, (x - 2, y - 6, 4, 12))
    # Zigzag effect
    pygame.draw.line(surface, ORANGE, (x - 2, y - 6), (x + 2, y - 2), 2)
    pygame.draw.line(surface, ORANGE, (x + 2, y - 2), (x - 2, y + 2), 2)
    pygame.draw.line(surface, ORANGE, (x - 2, y + 2), (x + 2, y + 6), 2)


def draw_shield(surface, shield):
    for (bx, by, alive) in shield['blocks']:
        if alive:
            pygame.draw.rect(surface, DARK_GREEN, (bx, by, 6, 6))


def draw_explosion(surface, x, y, frame, max_frames):
    progress = frame / max_frames
    radius = int(30 * progress)
    alpha = int(255 * (1 - progress))
    colors = [
        (255, 200, 0),
        (255, 100, 0),
        (200, 50, 0),
    ]
    for i, c in enumerate(colors):
        r = radius - i * 5
        if r > 0:
            pygame.draw.circle(surface, c, (x, y), r, 2)
    # Sparks
    for i in range(8):
        angle = i * np.pi / 4 + progress * np.pi
        sx = int(x + np.cos(angle) * radius * 1.2)
        sy = int(y + np.sin(angle) * radius * 1.2)
        pygame.draw.circle(surface, YELLOW, (sx, sy), max(1, 3 - int(progress * 3)))


def draw_ufo(surface, x, y):
    # Body
    pygame.draw.ellipse(surface, RED, (x - 20, y - 8, 40, 16))
    # Dome
    pygame.draw.ellipse(surface, MAGENTA, (x - 10, y - 16, 20, 14))
    # Windows
    for wx in [-8, 0, 8]:
        pygame.draw.circle(surface, CYAN, (x + wx, y - 2), 3)
    # Glow
    pygame.draw.ellipse(surface, (255, 50, 50), (x - 22, y - 9, 44, 18), 1)


# ─── Game Classes ─────────────────────────────────────────────────────────────

class Particle:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        angle = random.uniform(0, 2 * np.pi)
        speed = random.uniform(1, 5)
        self.vx = np.cos(angle) * speed
        self.vy = np.sin(angle) * speed
        self.life = random.randint(20, 40)
        self.max_life = self.life
        self.color = random.choice([YELLOW, ORANGE, RED, WHITE])
        self.size = random.randint(2, 5)

    def update(self):
        self.x += self.vx
        self.y += self.vy
        self.vy += 0.1
        self.life -= 1

    def draw(self, surface):
        alpha = self.life / self.max_life
        r, g, b = self.color
        c = (int(r * alpha), int(g * alpha), int(b * alpha))
        pygame.draw.circle(surface, c, (int(self.x), int(self.y)), self.size)


class Game:
    def __init__(self):
        self.reset()
        self.high_score = 0
        self.stars = [(random.randint(0, WIDTH), random.randint(0, HEIGHT),
                       random.randint(50, 255)) for _ in range(150)]

    def reset(self):
        self.score = 0
        self.lives = 3
        self.level = 1
        self.player_x = WIDTH // 2
        self.player_y = HEIGHT - 60
        self.player_speed = 5
        self.bullets = []
        self.invader_bullets = []
        self.invaders = []
        self.explosions = []
        self.particles = []
        self.shields = []
        self.ufo = None
        self.ufo_timer = 0
        self.ufo_phase = 0.0
        self.ufo_playing = False
        self.march_index = 0
        self.march_timer = 0
        self.march_interval = 60
        self.invader_dir = 1
        self.invader_speed = 1.0
        self.invader_frame = 0
        self.frame_count = 0
        self.game_over = False
        self.game_won = False
        self.shoot_cooldown = 0
        self.invader_shoot_timer = 0
        self.invader_shoot_interval = 90
        self.player_hit_timer = 0
        self.scroll_offset = 0
        self.setup_level()

    def setup_level(self):
        self.invaders = []
        rows = 5
        cols = 11
        start_x = 80
        start_y = 80
        spacing_x = 60
        spacing_y = 50
        for row in range(rows):
            for col in range(cols):
                inv_type = 0 if row == 0 else (1 if row < 3 else 2)
                self.invaders.append({
                    'x': start_x + col * spacing_x,
                    'y': start_y + row * spacing_y,
                    'type': inv_type,
                    'alive': True,
                    'points': [30, 20, 10][inv_type],
                })

        # Shields
        self.shields = []
        for sx in [150, 300, 450, 600]:
            blocks = []
            for brow in range(4):
                for bcol in range(8):
                    bx = sx + bcol * 7
                    by = HEIGHT - 130 + brow * 7
                    blocks.append([bx, by, True])
            self.shields.append({'blocks': blocks})

        self.invader_speed = 1.0 + (self.level - 1) * 0.3
        self.march_interval = max(15, 60 - (self.level - 1) * 8)
        self.invader_shoot_interval = max(30, 90 - (self.level - 1) * 10)

    def get_alive_invaders(self):
        return [inv for inv in self.invaders if inv['alive']]

    def move_invaders(self):
        alive = self.get_alive_invaders()
        if not alive:
            return

        move_down = False
        for inv in alive:
            if inv['x'] > WIDTH - 40 and self.invader_dir > 0:
                move_down = True
                break
            if inv['x'] < 40 and self.invader_dir < 0:
                move_down = True
                break

        if move_down:
            self.invader_dir *= -1
            for inv in alive:
                inv['y'] += 20
        else:
            for inv in alive:
                inv['x'] += self.invader_speed * self.invader_dir

    def invader_shoot(self):
        alive = self.get_alive_invaders()
        if not alive:
            return
        shooter = random.choice(alive)
        self.invader_bullets.append({
            'x': shooter['x'],
            'y': shooter['y'] + 15,
            'speed': 4 + self.level * 0.5,
        })
        play_sound_async(INVADER_SHOOT_SOUND)

    def check_bullet_shield(self, bx, by, is_player_bullet):
        for shield in self.shields:
            for block in shield['blocks']:
                if block[2]:
                    if abs(bx - block[0]) < 8 and abs(by - block[1]) < 8:
                        block[2] = False
                        return True
        return False

    def update(self):
        if self.game_over or self.game_won:
            return

        self.frame_count += 1
        self.scroll_offset = (self.scroll_offset + 0.2) % HEIGHT

        # Player movement
        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT] or keys[pygame.K_a]:
            self.player_x = max(20, self.player_x - self.player_speed)
        if keys[pygame.K_RIGHT] or keys[pygame.K_d]:
            self.player_x = min(WIDTH - 20, self.player_x + self.player_speed)

        # Shooting
        if self.shoot_cooldown > 0:
            self.shoot_cooldown -= 1
        if (keys[pygame.K_SPACE] or keys[pygame.K_UP]) and self.shoot_cooldown == 0:
            self.bullets.append({'x': self.player_x, 'y': self.player_y - 20, 'speed': 10})
            play_sound_async(SHOOT_SOUND)
            self.shoot_cooldown = 20

        # Move player bullets
        for b in self.bullets[:]:
            b['y'] -= b['speed']
            if b['y'] < 0:
                self.bullets.remove(b)

        # Move invader bullets
        for b in self.invader_bullets[:]:
            b['y'] += b['speed']
            if b['y'] > HEIGHT:
                self.invader_bullets.remove(b)

        # March invaders
        self.march_timer += 1
        if self.march_timer >= self.march_interval:
            self.march_timer = 0
            self.move_invaders()
            self.invader_frame = (self.invader_frame + 1) % 2
            play_sound_async(MARCH_SOUNDS[self.march_index % 4])
            self.march_index += 1

        # Invader shooting
        self.invader_shoot_timer += 1
        if self.invader_shoot_timer >= self.invader_shoot_interval:
            self.invader_shoot_timer = 0
            self.invader_shoot()

        # UFO
        self.ufo_timer += 1
        if self.ufo_timer > 600 and self.ufo is None:
            self.ufo = {'x': -30, 'y': 40, 'speed': 2, 'points': random.choice([50, 100, 150, 300])}
            self.ufo_timer = 0

        if self.ufo:
            self.ufo['x'] += self.ufo['speed']
            if self.ufo['x'] > WIDTH + 30:
                self.ufo = None

        # Check player bullet hits
        for b in self.bullets[:]:
            # Hit invader
            for inv in self.invaders:
                if inv['alive']:
                    if abs(b['x'] - inv['x']) < 18 and abs(b['y'] - inv['y']) < 18:
                        inv['alive'] = False
                        self.score += inv['points']
                        self.bullets.remove(b)
                        self.explosions.append({'x': inv['x'], 'y': inv['y'], 'frame': 0, 'max': 20})
                        for _ in range(15):
                            self.particles.append(Particle(inv['x'], inv['y']))
                        play_sound_async(INVADER_DEATH_SOUND)
                        break
            else:
                # Hit UFO
                if self.ufo and b in self.bullets:
                    if abs(b['x'] - self.ufo['x']) < 25 and abs(b['y'] - self.ufo['y']) < 15:
                        self.score += self.ufo['points']
                        self.explosions.append({'x': self.ufo['x'], 'y': self.ufo['y'], 'frame': 0, 'max': 25})
                        for _ in range(20):
                            self.particles.append(Particle(self.ufo['x'], self.ufo['y']))
                        self.ufo = None
                        if b in self.bullets:
                            self.bullets.remove(b)
                        play_sound_async(EXPLOSION_SOUND)
                        continue

                # Hit shield
                if b in self.bullets:
                    if self.check_bullet_shield(b['x'], b['y'], True):
                        self.bullets.remove(b)

        # Check invader bullet hits
        for b in self.invader_bullets[:]:
            # Hit player
            if abs(b['x'] - self.player_x) < 18 and abs(b['y'] - self.player_y) < 20:
                self.invader_bullets.remove(b)
                self.lives -= 1
                self.player_hit_timer = 60
                self.explosions.append({'x': self.player_x, 'y': self.player_y, 'frame': 0, 'max': 30})
                for _ in range(25):
                    self.particles.append(Particle(self.player_x, self.player_y))
                play_sound_async(EXPLOSION_SOUND)
                if self.lives <= 0:
                    self.game_over = True
                    play_sound_async(GAME_OVER_SOUND)
                continue

            # Hit shield
            if self.check_bullet_shield(b['x'], b['y'], False):
                self.invader_bullets.remove(b)

        # Check invaders reached bottom
        for inv in self.get_alive_invaders():
            if inv['y'] > HEIGHT - 80:
                self.game_over = True
                play_sound_async(GAME_OVER_SOUND)

        # Update explosions
        for exp in self.explosions[:]:
            exp['frame'] += 1
            if exp['frame'] >= exp['max']:
                self.explosions.remove(exp)

        # Update particles
        for p in self.particles[:]:
            p.update()
            if p.life <= 0:
                self.particles.remove(p)

        # Check win
        if not self.get_alive_invaders():
            self.level += 1
            play_sound_async(LEVEL_UP_SOUND)
            self.bullets.clear()
            self.invader_bullets.clear()
            self.explosions.clear()
            self.particles.clear()
            self.ufo = None
            self.setup_level()

        # Update high score
        if self.score > self.high_score:
            self.high_score = self.score

    def draw(self, surface):
        surface.fill(BLACK)

        # Stars
        draw_star_field(surface, self.stars)

        # Nebula effect (subtle)
        for i in range(3):
            nx = (100 + i * 250) % WIDTH
            ny = (200 + i * 100) % HEIGHT
            for r in range(40, 0, -10):
                alpha_surf = pygame.Surface((r * 2, r * 2), pygame.SRCALPHA)
                col = [(30, 0, 60), (0, 20, 60), (0, 40, 20)][i]
                pygame.draw.circle(alpha_surf, (*col, 15), (r, r), r)
                surface.blit(alpha_surf, (nx - r, ny - r))

        # Shields
        for shield in self.shields:
            draw_shield(surface, shield)

        # Invaders
        for inv in self.invaders:
            if inv['alive']:
                draw_invader(surface, inv['x'], inv['y'], inv['type'], self.invader_frame)

        # UFO
        if self.ufo:
            draw_ufo(surface, self.ufo['x'], self.ufo['y'])
            # UFO score hint
            font_small = pygame.font.SysFont('monospace', 12)
            txt = font_small.render(f"?", True, YELLOW)
            surface.blit(txt, (self.ufo['x'] - 4, self.ufo['y'] - 25))

        # Player bullets
        for b in self.bullets:
            draw_bullet(surface, b['x'], b['y'])

        # Invader bullets
        for b in self.invader_bullets:
            draw_invader_bullet(surface, b['x'], b['y'])

        # Player
        if self.player_hit_timer > 0:
            self.player_hit_timer -= 1
            if self.player_hit_timer % 6 < 3:
                draw_player(surface, self.player_x, self.player_y)
        else:
            draw_player(surface, self.player_x, self.player_y)

        # Explosions
        for exp in self.explosions:
            draw_explosion(surface, exp['x'], exp['y'], exp['frame'], exp['max'])

        # Particles
        for p in self.particles:
            p.draw(surface)

        # HUD
        self.draw_hud(surface)

        # Game over / win screen
        if self.game_over:
            self.draw_overlay(surface, "GAME OVER", RED)
        elif self.game_won:
            self.draw_overlay(surface, "YOU WIN!", GREEN)

    def draw_hud(self, surface):
        font = pygame.font.SysFont('monospace', 20, bold=True)
        font_small = pygame.font.SysFont('monospace', 16)

        # Score
        score_txt = font.render(f"SCORE: {self.score:06d}", True, WHITE)
        surface.blit(score_txt, (10, 10))

        # High score
        hi_txt = font_small.render(f"HI: {self.high_score:06d}", True, YELLOW)
        surface.blit(hi_txt, (WIDTH // 2 - 60, 10))

        # Level
        lvl_txt = font.render(f"LEVEL: {self.level}", True, CYAN)
        surface.blit(lvl_txt, (WIDTH - 140, 10))

        # Lives
        lives_txt = font_small.render("LIVES:", True, WHITE)
        surface.blit(lives_txt, (10, HEIGHT - 35))
        for i in range(self.lives):
            draw_player(surface, 90 + i * 35, HEIGHT - 22)

        # Bottom line
        pygame.draw.line(surface, GREEN, (0, HEIGHT - 50), (WIDTH, HEIGHT - 50), 2)
        pygame.draw.line(surface, GREEN, (0, 35), (WIDTH, 35), 1)

    def draw_overlay(self, surface, text, color):
        overlay = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 120))
        surface.blit(overlay, (0, 0))

        font_big = pygame.font.SysFont('monospace', 64, bold=True)
        font_med = pygame.font.SysFont('monospace', 28)
        font_small = pygame.font.SysFont('monospace', 20)

        txt = font_big.render(text, True, color)
        surface.blit(txt, (WIDTH // 2 - txt.get_width() // 2, HEIGHT // 2 - 80))

        score_txt = font_med.render(f"FINAL SCORE: {self.score}", True, YELLOW)
        surface.blit(score_txt, (WIDTH // 2 - score_txt.get_width() // 2, HEIGHT // 2))

        restart_txt = font_small.render("Press R to Restart or Q to Quit", True, WHITE)
        surface.blit(restart_txt, (WIDTH // 2 - restart_txt.get_width() // 2, HEIGHT // 2 + 60))


# ─── Main ─────────────────────────────────────────────────────────────────────

def draw_title_screen(surface, stars):
    surface.fill(BLACK)
    draw_star_field(surface, stars)

    font_title = pygame.font.SysFont('monospace', 72, bold=True)
    font_sub = pygame.font.SysFont('monospace', 24)
    font_small = pygame.font.SysFont('monospace', 18)

    # Animated title
    t = time.time()
    r = int(127 + 127 * np.sin(t * 2))
    g = int(127 + 127 * np.sin(t * 2 + 2))
    b = int(127 + 127 * np.sin(t * 2 + 4))

    title = font_title.render("SPACE", True, (r, g, b))
    title2 = font_title.render("INVADERS", True, (b, r, g))
    surface.blit(title, (WIDTH // 2 - title.get_width() // 2, 100))
    surface.blit(title2, (WIDTH // 2 - title2.get_width() // 2, 170))

    # Score legend
    legend_items = [
        ("= 30 pts", MAGENTA, 0),
        ("= 20 pts", GREEN, 1),
        ("= 10 pts", YELLOW, 2),
        ("= ??? pts", RED, -1),
    ]

    for i, (label, color, inv_type) in enumerate(legend_items):
        y = 290 + i * 45
        if inv_type >= 0:
            draw_invader(surface, WIDTH // 2 - 80, y, inv_type, int(t * 2) % 2)
        else:
            draw_ufo(surface, WIDTH // 2 - 80, y)
        txt = font_sub.render(label, True, color)
        surface.blit(txt, (WIDTH // 2 - 50, y - 10))

    start_txt = font_small.render("Press SPACE or ENTER to Start", True, WHITE if int(t * 2) % 2 == 0 else CYAN)
    surface.blit(start_txt, (WIDTH // 2 - start_txt.get_width() // 2, 510))

    controls = font_small.render("Arrow Keys / WASD to Move | SPACE to Shoot", True, (150, 150, 150))
    surface.blit(controls, (WIDTH // 2 - controls.get_width() // 2, 545))


def main():
    print("Starting Space Invaders...")
    print("Controls: Arrow Keys or WASD to move, SPACE to shoot")
    print("Press R to restart, Q to quit")

    stars = [(random.randint(0, WIDTH), random.randint(0, HEIGHT),
              random.randint(50, 255)) for _ in range(150)]

    game = Game()
    title_screen = True

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN:
                if event.key in (pygame.K_q, pygame.K_ESCAPE):
                    running = False
                if title_screen:
                    if event.key in (pygame.K_SPACE, pygame.K_RETURN):
                        title_screen = False
                        print("Game started!")
                else:
                    if event.key == pygame.K_r:
                        game.reset()
                        print(f"Game restarted! High score: {game.high_score}")

        if title_screen:
            draw_title_screen(screen, stars)
        else:
            game.update()
            game.draw(screen)

        pygame.display.flip()
        clock.tick(FPS)

    pygame.quit()
    print("Thanks for playing Space Invaders!")
    print(f"Final High Score: {game.high_score}")
    sys.exit()


if __name__ == "__main__":
    main()