# Generated by: anthropic/claude-sonnet-4-6 (Ollama)
# Date: 2026-03-07 07:48:05
# AutoCoder System - Automated Code Generation

import pygame
import numpy as np
import sounddevice as sd
import threading
import math
import random
import time
from collections import deque

# ─────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────
WIDTH, HEIGHT = 1280, 720
NUM_STARS = 600
GRAVITY_RADIUS = 160
GRAVITY_STRENGTH = 0.18
SAMPLE_RATE = 44100
CHANNELS = 2

print("Initializing Stellar Drift...")

pygame.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Stellar Drift")
clock = pygame.time.Clock()

# ─────────────────────────────────────────────
# Audio Engine
# ─────────────────────────────────────────────
class AudioEngine:
    def __init__(self):
        self.lock = threading.Lock()
        self.sample_rate = SAMPLE_RATE
        self.phase_drone = 0.0
        self.phase_high = 0.0
        self.phase_whale = 0.0
        self.phase_whale2 = 0.0

        # Ambient parameters (modulated by star count)
        self.drone_freq = 55.0       # deep bass drone
        self.high_freq = 880.0       # glassy high tone
        self.whale_freq = 180.0      # alien whale
        self.star_count = 0          # stars in gravity field
        self.ambient_volume = 0.0
        self.target_volume = 0.0

        # Explosion / reverb tail
        self.explosion_samples = None
        self.explosion_pos = 0
        self.explosion_active = False
        self.explosion_pan = 0.5     # 0=left, 1=right

        # Reverb buffer (simple comb filter)
        self.reverb_buf_len = int(SAMPLE_RATE * 0.6)
        self.reverb_buf = np.zeros(self.reverb_buf_len)
        self.reverb_pos = 0

        self.stream = sd.OutputStream(
            samplerate=SAMPLE_RATE,
            channels=CHANNELS,
            dtype='float32',
            blocksize=512,
            callback=self._callback
        )
        self.stream.start()
        print("Audio engine started.")

    def _callback(self, outdata, frames, time_info, status):
        with self.lock:
            t = np.arange(frames) / self.sample_rate
            out = np.zeros((frames, 2), dtype=np.float32)

            # Smooth volume
            self.ambient_volume += (self.target_volume - self.ambient_volume) * 0.05

            if self.ambient_volume > 0.001:
                # Deep drone (two slightly detuned oscillators)
                f1 = self.drone_freq
                f2 = self.drone_freq * 1.005
                drone_phase_end = self.phase_drone + 2 * np.pi * f1 * frames / self.sample_rate
                drone_phase_end2 = self.phase_drone + 2 * np.pi * f2 * frames / self.sample_rate
                ph1 = self.phase_drone + 2 * np.pi * f1 * t
                ph2 = self.phase_drone + 2 * np.pi * f2 * t
                drone = (np.sin(ph1) * 0.5 + np.sin(ph2) * 0.3) * 0.18 * self.ambient_volume
                self.phase_drone = drone_phase_end % (2 * np.pi)

                # Glassy high tone (sine + 3rd harmonic)
                hf = self.high_freq
                ph_h = self.phase_high + 2 * np.pi * hf * t
                ph_h3 = self.phase_high + 2 * np.pi * hf * 3 * t
                high = (np.sin(ph_h) * 0.6 + np.sin(ph_h3) * 0.15) * 0.08 * self.ambient_volume
                self.phase_high = (self.phase_high + 2 * np.pi * hf * frames / self.sample_rate) % (2 * np.pi)

                # Alien whale-song (slow FM modulation)
                mod_rate = 0.3
                mod_depth = 40.0
                whale_mod = mod_depth * np.sin(2 * np.pi * mod_rate * t + self.phase_whale2)
                wf = self.whale_freq + whale_mod
                ph_w = self.phase_whale + 2 * np.pi * np.cumsum(wf) / self.sample_rate
                whale = np.sin(ph_w) * 0.12 * self.ambient_volume
                self.phase_whale = ph_w[-1] % (2 * np.pi)
                self.phase_whale2 = (self.phase_whale2 + 2 * np.pi * mod_rate * frames / self.sample_rate) % (2 * np.pi)

                ambient = drone + high + whale
                out[:, 0] += ambient.astype(np.float32)
                out[:, 1] += ambient.astype(np.float32)

            # Explosion playback with pan
            if self.explosion_active and self.explosion_samples is not None:
                remaining = len(self.explosion_samples) - self.explosion_pos
                n = min(frames, remaining)
                chunk = self.explosion_samples[self.explosion_pos:self.explosion_pos + n]
                pan = self.explosion_pan
                out[:n, 0] += (chunk * (1.0 - pan)).astype(np.float32)
                out[:n, 1] += (chunk * pan).astype(np.float32)
                self.explosion_pos += n
                if self.explosion_pos >= len(self.explosion_samples):
                    self.explosion_active = False

            # Soft clip
            out = np.tanh(out * 1.5) * 0.7
            outdata[:] = out

    def set_star_count(self, count):
        with self.lock:
            self.star_count = count
            ratio = min(count / 60.0, 1.0)
            self.target_volume = ratio
            self.drone_freq = 40.0 + ratio * 55.0
            self.high_freq = 660.0 + ratio * 880.0
            self.whale_freq = 120.0 + ratio * 160.0

    def trigger_explosion(self, pan_x):
        """Generate and play a booming explosion with reverb tail."""
        with self.lock:
            self.explosion_pan = pan_x / WIDTH
            dur = 3.0
            n = int(SAMPLE_RATE * dur)
            t = np.linspace(0, dur, n)

            # Boom: low sine burst
            boom_env = np.exp(-t * 4.0)
            boom = np.sin(2 * np.pi * 60 * t) * boom_env * 0.9
            boom += np.sin(2 * np.pi * 90 * t) * boom_env * 0.5
            boom += np.sin(2 * np.pi * 30 * t) * boom_env * 0.7

            # Noise burst
            noise_env = np.exp(-t * 8.0)
            noise = np.random.randn(n) * noise_env * 0.4

            # Crystalline reverb tail (high freq shimmer)
            shimmer_env = np.exp(-t * 1.2) * (1 - np.exp(-t * 0.05))
            freqs = [880, 1320, 1760, 2200, 3520]
            shimmer = np.zeros(n)
            for f in freqs:
                phase_offset = random.uniform(0, 2 * np.pi)
                shimmer += np.sin(2 * np.pi * f * t + phase_offset) * shimmer_env * 0.06

            explosion = boom + noise + shimmer

            # Simple comb reverb
            delay_samples = int(SAMPLE_RATE * 0.08)
            reverbed = explosion.copy()
            for i in range(delay_samples, n):
                reverbed[i] += reverbed[i - delay_samples] * 0.45

            # Normalize
            peak = np.max(np.abs(reverbed))
            if peak > 0:
                reverbed = reverbed / peak * 0.85

            self.explosion_samples = reverbed.astype(np.float32)
            self.explosion_pos = 0
            self.explosion_active = True

    def stop(self):
        self.stream.stop()
        self.stream.close()


# ─────────────────────────────────────────────
# Star class
# ─────────────────────────────────────────────
class Star:
    def __init__(self):
        self.reset(born=False)

    def reset(self, born=True):
        self.x = random.uniform(0, WIDTH)
        self.y = random.uniform(0, HEIGHT)
        self.ox = self.x  # origin
        self.oy = self.y
        self.vx = random.uniform(-0.08, 0.08)
        self.vy = random.uniform(-0.08, 0.08)
        self.size = random.choice([1, 1, 1, 2, 2, 3])
        self.base_brightness = random.uniform(0.5, 1.0)
        self.pulse_phase = random.uniform(0, 2 * math.pi)
        self.pulse_speed = random.uniform(0.5, 2.5)
        self.reborn = born
        self.trail = deque(maxlen=12)
        self.has_trail = False

        # Color: mostly white/blue, some amber
        r = random.random()
        if self.reborn:
            # Reborn stars: rose or electric green
            if random.random() < 0.5:
                self.color_base = (255, 80, 160)   # deep rose
            else:
                self.color_base = (80, 255, 120)   # electric green
            self.has_trail = True
        elif r < 0.6:
            self.color_base = (200, 220, 255)  # icy blue-white
        elif r < 0.85:
            self.color_base = (255, 255, 255)  # pure white
        else:
            self.color_base = (255, 220, 140)  # warm amber

        self.attracted = False

    def update(self, mx, my, dt):
        self.pulse_phase += self.pulse_speed * dt
        dx = mx - self.x
        dy = my - self.y
        dist = math.sqrt(dx * dx + dy * dy)

        self.attracted = dist < GRAVITY_RADIUS

        if self.attracted:
            strength = GRAVITY_STRENGTH * (1.0 - dist / GRAVITY_RADIUS) ** 1.5
            self.vx += dx * strength * dt
            self.vy += dy * strength * dt

        # Drift back toward origin gently
        self.vx += (self.ox - self.x) * 0.0003
        self.vy += (self.oy - self.y) * 0.0003

        # Damping
        self.vx *= 0.96
        self.vy *= 0.96

        # Store trail
        if self.has_trail:
            self.trail.append((int(self.x), int(self.y)))

        self.x += self.vx
        self.y += self.vy

        # Wrap
        self.x %= WIDTH
        self.y %= HEIGHT

    def draw(self, surface):
        pulse = 0.5 + 0.5 * math.sin(self.pulse_phase)
        brightness = self.base_brightness * (0.7 + 0.3 * pulse)
        r = int(self.color_base[0] * brightness)
        g = int(self.color_base[1] * brightness)
        b = int(self.color_base[2] * brightness)
        color = (min(r, 255), min(g, 255), min(b, 255))

        # Draw trail
        if self.has_trail and len(self.trail) > 1:
            pts = list(self.trail)
            for i in range(1, len(pts)):
                alpha = i / len(pts)
                tc = (int(color[0] * alpha * 0.5),
                      int(color[1] * alpha * 0.5),
                      int(color[2] * alpha * 0.5))
                pygame.draw.line(surface, tc, pts[i-1], pts[i], 1)

        # Glow (soft halo)
        if self.size >= 2:
            glow_r = int(r * 0.3)
            glow_g = int(g * 0.3)
            glow_b = int(b * 0.3)
            glow_color = (min(glow_r, 255), min(glow_g, 255), min(glow_b, 255))
            pygame.draw.circle(surface, glow_color,
                               (int(self.x), int(self.y)), self.size + 2)

        pygame.draw.circle(surface, color,
                           (int(self.x), int(self.y)), self.size)


# ─────────────────────────────────────────────
# Supernova / Explosion Effect
# ─────────────────────────────────────────────
class Supernova:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.t = 0.0
        self.duration = 2.2
        self.alive = True
        self.rings = [
            {'color': (255, 255, 255), 'speed': 180, 'width': 4},
            {'color': (180, 60, 220),  'speed': 140, 'width': 3},
            {'color': (180, 20, 60),   'speed': 100, 'width': 3},
            {'color': (0, 220, 200),   'speed': 70,  'width': 2},
        ]
        # Debris particles
        self.particles = []
        for _ in range(80):
            angle = random.uniform(0, 2 * math.pi)
            speed = random.uniform(30, 220)
            self.particles.append({
                'x': x, 'y': y,
                'vx': math.cos(angle) * speed,
                'vy': math.sin(angle) * speed,
                'life': random.uniform(0.6, 2.0),
                'age': 0.0,
                'size': random.randint(1, 3),
                'color': random.choice([
                    (255, 200, 100), (255, 100, 180),
                    (100, 255, 200), (200, 150, 255)
                ])
            })

    def update(self, dt):
        self.t += dt
        for p in self.particles:
            p['age'] += dt
            p['vx'] *= 0.97
            p['vy'] *= 0.97
            p['x'] += p['vx'] * dt
            p['y'] += p['vy'] * dt
        if self.t >= self.duration:
            self.alive = False

    def draw(self, surface):
        progress = self.t / self.duration

        # Flash at center
        if self.t < 0.15:
            flash_alpha = int(255 * (1 - self.t / 0.15))
            flash_r = min(int(self.t / 0.15 * 300), 80)
            flash_surf = pygame.Surface((flash_r * 2 + 2, flash_r * 2 + 2), pygame.SRCALPHA)
            pygame.draw.circle(flash_surf, (255, 255, 255, flash_alpha),
                               (flash_r + 1, flash_r + 1), flash_r)
            surface.blit(flash_surf, (int(self.x) - flash_r - 1, int(self.y) - flash_r - 1))

        # Expanding rings
        for ring in self.rings:
            radius = int(ring['speed'] * self.t)
            alpha = max(0, int(255 * (1 - progress) * 0.8))
            if radius > 0 and alpha > 5:
                ring_surf = pygame.Surface((radius * 2 + 10, radius * 2 + 10), pygame.SRCALPHA)
                c = ring['color'] + (alpha,)
                pygame.draw.circle(ring_surf, c,
                                   (radius + 5, radius + 5), radius, ring['width'])
                surface.blit(ring_surf, (int(self.x) - radius - 5, int(self.y) - radius - 5))

        # Debris particles
        for p in self.particles:
            if p['age'] < p['life']:
                fade = 1.0 - p['age'] / p['life']
                alpha = int(255 * fade)
                c = p['color'] + (alpha,)
                ps = pygame.Surface((p['size'] * 2 + 2, p['size'] * 2 + 2), pygame.SRCALPHA)
                pygame.draw.circle(ps, c, (p['size'] + 1, p['size'] + 1), p['size'])
                surface.blit(ps, (int(p['x']) - p['size'] - 1, int(p['y']) - p['size'] - 1))


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────
def main():
    audio = AudioEngine()
    stars = [Star() for _ in range(NUM_STARS)]
    supernovas = []

    # Background surface (static starfield layer)
    bg = pygame.Surface((WIDTH, HEIGHT))
    bg.fill((0, 0, 0))

    # Nebula background (subtle gradient blobs)
    nebula = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
    for _ in range(6):
        nx = random.randint(0, WIDTH)
        ny = random.randint(0, HEIGHT)
        nr = random.randint(120, 300)
        nc = random.choice([
            (20, 0, 40, 18), (0, 10, 40, 15), (30, 10, 0, 12)
        ])
        pygame.draw.circle(nebula, nc, (nx, ny), nr)

    running = True
    prev_time = time.time()

    print("Stellar Drift running. Move mouse to attract stars. Click for supernova. Close window to exit.")

    while running:
        now = time.time()
        dt = min(now - prev_time, 0.05)
        prev_time = now

        mx, my = pygame.mouse.get_pos()

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 1:
                    sx, sy = event.pos
                    supernovas.append(Supernova(sx, sy))
                    audio.trigger_explosion(sx)

                    # Affect nearby stars
                    explosion_radius = 200
                    for star in stars:
                        dx = star.x - sx
                        dy = star.y - sy
                        dist = math.sqrt(dx * dx + dy * dy)
                        if dist < explosion_radius:
                            # Blast outward
                            if dist > 1:
                                force = (explosion_radius - dist) / explosion_radius * 8.0
                                star.vx += (dx / dist) * force
                                star.vy += (dy / dist) * force
                            # Rebirth
                            star.reborn = True
                            star.has_trail = True
                            star.trail.clear()
                            if random.random() < 0.5:
                                star.color_base = (255, 80, 160)
                            else:
                                star.color_base = (80, 255, 120)

        # Update stars
        attracted_count = 0
        for star in stars:
            star.update(mx, my, dt)
            if star.attracted:
                attracted_count += 1

        audio.set_star_count(attracted_count)

        # Update supernovas
        for sn in supernovas:
            sn.update(dt)
        supernovas = [sn for sn in supernovas if sn.alive]

        # ── Draw ──
        screen.fill((0, 0, 2))
        screen.blit(nebula, (0, 0))

        # Draw stars
        for star in stars:
            star.draw(screen)

        # Draw supernovas
        for sn in supernovas:
            sn.draw(screen)

        # Subtle vignette
        vignette = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
        for r_step in range(5):
            radius = WIDTH // 2 + r_step * 40
            alpha = 8
            pygame.draw.circle(vignette, (0, 0, 0, alpha),
                               (WIDTH // 2, HEIGHT // 2), radius,
                               40 + r_step * 10)
        screen.blit(vignette, (0, 0))

        pygame.display.flip()
        clock.tick(60)

    audio.stop()
    pygame.quit()
    print("Stellar Drift closed.")


if __name__ == "__main__":
    main()