# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-07 15:48:26
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.animation import FuncAnimation
from scipy.integrate import solve_ivp

print("Setting up Three-Body Problem simulation...")

# Gravitational constant
G = 1.0

# Masses of the three bodies
m1 = 1.0
m2 = 1.0
m3 = 1.0

def three_body_equations(t, state):
    """
    Equations of motion for the three-body problem.
    state = [x1, y1, z1, x2, y2, z2, x3, y3, z3,
             vx1, vy1, vz1, vx2, vy2, vz2, vx3, vy3, vz3]
    """
    x1, y1, z1 = state[0], state[1], state[2]
    x2, y2, z2 = state[3], state[4], state[5]
    x3, y3, z3 = state[6], state[7], state[8]
    vx1, vy1, vz1 = state[9], state[10], state[11]
    vx2, vy2, vz2 = state[12], state[13], state[14]
    vx3, vy3, vz3 = state[15], state[16], state[17]

    # Distances between bodies
    r12 = np.sqrt((x2-x1)**2 + (y2-y1)**2 + (z2-z1)**2)
    r13 = np.sqrt((x3-x1)**2 + (y3-y1)**2 + (z3-z1)**2)
    r23 = np.sqrt((x3-x2)**2 + (y3-y2)**2 + (z3-z2)**2)

    # Softening parameter to avoid singularities
    eps = 1e-4

    r12 = max(r12, eps)
    r13 = max(r13, eps)
    r23 = max(r23, eps)

    # Accelerations
    ax1 = G * m2 * (x2-x1) / r12**3 + G * m3 * (x3-x1) / r13**3
    ay1 = G * m2 * (y2-y1) / r12**3 + G * m3 * (y3-y1) / r13**3
    az1 = G * m2 * (z2-z1) / r12**3 + G * m3 * (z3-z1) / r13**3

    ax2 = G * m1 * (x1-x2) / r12**3 + G * m3 * (x3-x2) / r23**3
    ay2 = G * m1 * (y1-y2) / r12**3 + G * m3 * (y3-y2) / r23**3
    az2 = G * m1 * (z1-z2) / r12**3 + G * m3 * (z3-z2) / r23**3

    ax3 = G * m1 * (x1-x3) / r13**3 + G * m2 * (x2-x3) / r23**3
    ay3 = G * m1 * (y1-y3) / r13**3 + G * m2 * (y2-y3) / r23**3
    az3 = G * m1 * (z1-z3) / r13**3 + G * m2 * (z2-z3) / r23**3

    return [vx1, vy1, vz1,
            vx2, vy2, vz2,
            vx3, vy3, vz3,
            ax1, ay1, az1,
            ax2, ay2, az2,
            ax3, ay3, az3]

# Initial conditions - chaotic configuration
# Positions
x1_0, y1_0, z1_0 = -1.0,  0.3,  0.2
x2_0, y2_0, z2_0 =  1.0, -0.3, -0.1
x3_0, y3_0, z3_0 =  0.0,  1.0,  0.5

# Velocities - chosen to produce chaotic orbits
vx1_0, vy1_0, vz1_0 =  0.2,  0.5, -0.3
vx2_0, vy2_0, vz2_0 = -0.3, -0.4,  0.2
vx3_0, vy3_0, vz3_0 =  0.1, -0.1,  0.1

state0 = [x1_0, y1_0, z1_0,
          x2_0, y2_0, z2_0,
          x3_0, y3_0, z3_0,
          vx1_0, vy1_0, vz1_0,
          vx2_0, vy2_0, vz2_0,
          vx3_0, vy3_0, vz3_0]

# Time span
t_start = 0
t_end = 20.0
dt = 0.01
t_eval = np.arange(t_start, t_end, dt)

print(f"Integrating equations of motion from t={t_start} to t={t_end}...")

# Solve the ODE
solution = solve_ivp(
    three_body_equations,
    [t_start, t_end],
    state0,
    method='RK45',
    t_eval=t_eval,
    rtol=1e-9,
    atol=1e-9,
    max_step=0.01
)

print(f"Integration complete. Steps: {len(solution.t)}, Success: {solution.success}")

# Extract trajectories
x1 = solution.y[0]
y1 = solution.y[1]
z1 = solution.y[2]

x2 = solution.y[3]
y2 = solution.y[4]
z2 = solution.y[5]

x3 = solution.y[6]
y3 = solution.y[7]
z3 = solution.y[8]

n_frames = len(solution.t)
trail_length = 200  # Number of past positions to show as trail

print(f"Setting up animation with {n_frames} frames...")

# Set up the figure
fig = plt.figure(figsize=(12, 9), facecolor='black')
ax = fig.add_subplot(111, projection='3d', facecolor='black')

# Style the axes
ax.tick_params(colors='gray', labelsize=7)
ax.xaxis.pane.fill = False
ax.yaxis.pane.fill = False
ax.zaxis.pane.fill = False
ax.xaxis.pane.set_edgecolor('gray')
ax.yaxis.pane.set_edgecolor('gray')
ax.zaxis.pane.set_edgecolor('gray')
ax.grid(True, color='gray', alpha=0.2, linewidth=0.5)

# Colors for each body
colors = ['#FF4444', '#44AAFF', '#44FF88']
body_colors = ['red', 'dodgerblue', 'limegreen']

# Initialize trail lines
trail1, = ax.plot([], [], [], '-', color=colors[0], alpha=0.6, linewidth=0.8, label='Body 1')
trail2, = ax.plot([], [], [], '-', color=colors[1], alpha=0.6, linewidth=0.8, label='Body 2')
trail3, = ax.plot([], [], [], '-', color=colors[2], alpha=0.6, linewidth=0.8, label='Body 3')

# Initialize body markers
body1, = ax.plot([], [], [], 'o', color=body_colors[0], markersize=10, zorder=5)
body2, = ax.plot([], [], [], 'o', color=body_colors[1], markersize=10, zorder=5)
body3, = ax.plot([], [], [], 'o', color=body_colors[2], markersize=10, zorder=5)

# Compute axis limits
all_x = np.concatenate([x1, x2, x3])
all_y = np.concatenate([y1, y2, y3])
all_z = np.concatenate([z1, z2, z3])

margin = 0.5
xlim = [all_x.min() - margin, all_x.max() + margin]
ylim = [all_y.min() - margin, all_y.max() + margin]
zlim = [all_z.min() - margin, all_z.max() + margin]

ax.set_xlim(xlim)
ax.set_ylim(ylim)
ax.set_zlim(zlim)

ax.set_xlabel('X', color='gray', fontsize=10)
ax.set_ylabel('Y', color='gray', fontsize=10)
ax.set_zlabel('Z', color='gray', fontsize=10)

title = ax.set_title('Three-Body Problem - Chaotic Orbits\nt = 0.00',
                      color='white', fontsize=13, pad=15)

legend = ax.legend(loc='upper left', facecolor='black', edgecolor='gray',
                   labelcolor='white', fontsize=9)

# Add mass labels as text
ax.text2D(0.02, 0.02, f'm1={m1}  m2={m2}  m3={m3}  G={G}',
          transform=ax.transAxes, color='gray', fontsize=8)

def init():
    trail1.set_data([], [])
    trail1.set_3d_properties([])
    trail2.set_data([], [])
    trail2.set_3d_properties([])
    trail3.set_data([], [])
    trail3.set_3d_properties([])
    body1.set_data([], [])
    body1.set_3d_properties([])
    body2.set_data([], [])
    body2.set_3d_properties([])
    body3.set_data([], [])
    body3.set_3d_properties([])
    return trail1, trail2, trail3, body1, body2, body3, title

def update(frame):
    # Compute trail indices
    start = max(0, frame - trail_length)
    end = frame + 1

    # Update trails
    trail1.set_data(x1[start:end], y1[start:end])
    trail1.set_3d_properties(z1[start:end])

    trail2.set_data(x2[start:end], y2[start:end])
    trail2.set_3d_properties(z2[start:end])

    trail3.set_data(x3[start:end], y3[start:end])
    trail3.set_3d_properties(z3[start:end])

    # Update body positions
    body1.set_data([x1[frame]], [y1[frame]])
    body1.set_3d_properties([z1[frame]])

    body2.set_data([x2[frame]], [y2[frame]])
    body2.set_3d_properties([z2[frame]])

    body3.set_data([x3[frame]], [y3[frame]])
    body3.set_3d_properties([z3[frame]])

    # Update title with time
    t_current = solution.t[frame]
    title.set_text(f'Three-Body Problem - Chaotic Orbits\nt = {t_current:.2f}')

    # Slowly rotate the view for 3D effect
    ax.view_init(elev=20 + 10 * np.sin(frame * 0.005),
                 azim=frame * 0.15)

    return trail1, trail2, trail3, body1, body2, body3, title

# Subsample frames for smoother animation
frame_step = 3
frames = range(0, n_frames, frame_step)

print("Starting animation...")
anim = FuncAnimation(
    fig,
    update,
    frames=frames,
    init_func=init,
    interval=20,
    blit=False
)

plt.tight_layout()
print("Animation running. Close the window to exit.")
print(f"Simulation time: {t_start} to {t_end} time units")
print(f"Total trajectory points: {n_frames}")
print("Watch for chaotic, unpredictable orbital paths!")
plt.show()