# Generated by: qwen3-coder:30b (Ollama)
# Date: 2026-03-08 19:22:21
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.animation import FuncAnimation
import matplotlib.colors as mcolors
import time

# Generate washing machine price data for 2026
np.random.seed(42)
brands = ['Whirlpool', 'Samsung', 'LG', 'GE', 'Maytag', 'Bosch', 'Electrolux', 'Amana']
models = ['WashMaster 5000', 'SmartWash X1', 'EcoClean Pro', 'UltraSpin 3000',
          'FreshWash 2000', 'PowerClean Elite', 'DreamWash 4000', 'CompactClean']
prices = np.random.uniform(400, 2300, len(brands))  # Prices between $400-$2300
features = ['Steam Cleaning', 'Smart Diagnostics', 'Front Load', 'Top Load',
            'Energy Efficient', 'Large Capacity', 'Quick Wash', 'Self-Cleaning']

# Create 3D visualization of washing machine prices
fig = plt.figure(figsize=(12, 9))
ax = fig.add_subplot(111, projection='3d')

# Create price bubbles with different sizes based on price
x = np.random.rand(len(brands)) * 10
y = np.random.rand(len(brands)) * 10
z = prices / 200  # Normalize for z-axis
sizes = prices / 10  # Bubble sizes based on price

# Create color map based on price
colors = plt.cm.viridis(np.linspace(0, 1, len(brands)))

# Plot 3D bubbles
bubble_scatter = ax.scatter(x, y, z, s=sizes, c=colors, alpha=0.7, edgecolors='white', linewidth=0.5)

# Add labels for each washing machine
for i, (brand, model, price) in enumerate(zip(brands, models, prices)):
    ax.text(x[i], y[i], z[i], f'{brand}\n${int(price)}',
            fontsize=8, ha='center', va='bottom')

# Set labels and title
ax.set_xlabel('Brand', fontsize=12)
ax.set_ylabel('Model Type', fontsize=12)
ax.set_zlabel('Price (Normalized)', fontsize=12)
ax.set_title('Washing Machine Prices 2026\nCyberpunk Market Explorer', fontsize=14, pad=20)

# Set background to dark theme
ax.xaxis.pane.fill = True
ax.yaxis.pane.fill = True
ax.zaxis.pane.fill = True
ax.xaxis.pane.set_edgecolor('w')
ax.yaxis.pane.set_edgecolor('w')
ax.zaxis.pane.set_edgecolor('w')
ax.xaxis.pane.set_alpha(0.1)
ax.yaxis.pane.set_alpha(0.1)
ax.zaxis.pane.set_alpha(0.1)

# Add grid
ax.grid(True, alpha=0.3)


# Animation function for pulsing effect
def animate(frame):
    # Create pulsing effect by changing alpha
    alpha = 0.5 + 0.3 * np.sin(frame * 0.1)
    bubble_scatter.set_alpha(alpha)

    # Rotate view
    ax.view_init(elev=20, azim=frame * 0.5)

    return bubble_scatter,


# Create animation
ani = FuncAnimation(fig, animate, frames=200, interval=50, blit=False, repeat=True)

# Add legend for price ranges
price_ranges = ['Budget ($400-$700)', 'Mid-range ($700-$1300)', 'Premium ($1300-$2300)']
colors_legend = ['green', 'orange', 'red']
for i, (range_label, color) in enumerate(zip(price_ranges, colors_legend)):
    ax.scatter([], [], [], c=color, s=100, alpha=0.7, label=range_label)

ax.legend(loc='upper left', bbox_to_anchor=(0.02, 0.98))

# Add starfield background effect
star_x = np.random.rand(100) * 10
star_y = np.random.rand(100) * 10
star_z = np.random.rand(100) * 5
ax.scatter(star_x, star_y, star_z, c='white', s=1, alpha=0.3)

# Print summary statistics
print("Washing Machine Price Explorer 2026")
print("=" * 40)
print(f"Average Price: ${np.mean(prices):.2f}")
print(f"Price Range: ${np.min(prices):.2f} - ${np.max(prices):.2f}")
print(f"Number of Models: {len(brands)}")
print("\nTop 3 Most Expensive Models:")
sorted_prices = sorted(zip(brands, prices), key=lambda x: x[1], reverse=True)
for brand, price in sorted_prices[:3]:
    print(f"  {brand}: ${price:.2f}")

plt.tight_layout()
plt.show()

# Create additional price comparison chart
fig2, ax2 = plt.subplots(figsize=(10, 6))
bars = ax2.bar(range(len(brands)), prices, color=plt.cm.viridis(np.linspace(0, 1, len(brands))))
ax2.set_xlabel('Washing Machine Models')
ax2.set_ylabel('Price ($)')
ax2.set_title('Price Comparison of Washing Machines 2026')
ax2.set_xticks(range(len(brands)))
ax2.set_xticklabels([f'{brand}\n${int(price)}' for brand, price in zip(brands, prices)],
                    rotation=45, ha='right')
ax2.grid(True, alpha=0.3)

# Add value labels on bars
for i, (bar, price) in enumerate(zip(bars, prices)):
    ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 10,
             f'${int(price)}', ha='center', va='bottom')

plt.tight_layout()
plt.show()