# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-21 20:49:07
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
import matplotlib.patheffects as pe

# -------------------------------------------------
#  SOLUTION STATES
# -------------------------------------------------
steps = [
    (0, 0, "Start\nBoth jugs empty"),
    (0, 5, "Fill the\n5L jug"),
    (3, 2, "Pour 5L->3L\n(3L fills, 2L left)"),
    (0, 2, "Empty\nthe 3L jug"),
    (2, 0, "Pour 5L->3L\n(2L moved)"),
    (2, 5, "Fill the\n5L jug again"),
    (3, 4, "Pour 5L->3L\n(3L fills, 4L left!) DONE"),
]

JUG_3_CAP = 3
JUG_5_CAP = 5

# -------------------------------------------------
#  COLOUR PALETTE
# -------------------------------------------------
BG_COLOR      = "#0d1117"
PANEL_COLOR   = "#161b22"
BORDER_COLOR  = "#30363d"
WATER_COLORS  = ["#1e90ff", "#00bfff", "#87cefa"]
EMPTY_COLOR   = "#21262d"
JUG_BORDER    = "#58a6ff"
TEXT_COLOR    = "#e6edf3"
ACCENT_COLOR  = "#f0883e"
SUCCESS_COLOR = "#3fb950"
STEP_COLORS   = [
    "#6e40c9", "#1f6feb", "#1f6feb",
    "#da3633", "#388bfd", "#388bfd", "#3fb950"
]

# -------------------------------------------------
#  HELPER: draw a single jug
# -------------------------------------------------
def draw_jug(ax, x, y, width, height, capacity, amount,
             label, water_color, is_goal=False):
    pad = 0.02

    # Outer border
    border_rect = FancyBboxPatch(
        (x - pad, y - pad),
        width + 2 * pad, height + 2 * pad,
        boxstyle="round,pad=0.01",
        linewidth=3.5 if is_goal else 2.5,
        edgecolor=SUCCESS_COLOR if is_goal else JUG_BORDER,
        facecolor="none",
        zorder=4
    )
    ax.add_patch(border_rect)

    # Empty interior
    interior = FancyBboxPatch(
        (x, y), width, height,
        boxstyle="square,pad=0",
        linewidth=0,
        facecolor=EMPTY_COLOR,
        zorder=2
    )
    ax.add_patch(interior)

    # Water fill with gradient bands
    if amount > 0:
        fill_h = height * (amount / capacity)
        n_bands = 40
        for i in range(n_bands):
            band_y = y + (fill_h / n_bands) * i
            band_h = fill_h / n_bands
            alpha  = 0.55 + 0.45 * (i / n_bands)
            band = plt.Rectangle(
                (x, band_y), width, band_h,
                facecolor=water_color,
                alpha=alpha,
                zorder=3
            )
            ax.add_patch(band)

        # Shimmer highlight
        shimmer = plt.Rectangle(
            (x + 0.01, y + fill_h * 0.3),
            width * 0.12, fill_h * 0.5,
            facecolor="white", alpha=0.12, zorder=4
        )
        ax.add_patch(shimmer)

    # Capacity tick marks
    for tick_val in range(1, capacity + 1):
        tick_y = y + height * (tick_val / capacity)
        ax.plot(
            [x + width, x + width + 0.03], [tick_y, tick_y],
            color=BORDER_COLOR, lw=1.2, zorder=5
        )
        ax.text(
            x + width + 0.05, tick_y,
            f"{tick_val}L",
            va="center", ha="left",
            fontsize=6.5, color="#8b949e",
            fontfamily="monospace", zorder=5
        )

    # Volume label inside jug
    vol_color = SUCCESS_COLOR if is_goal else (TEXT_COLOR if amount > 0 else "#484f58")
    ax.text(
        x + width / 2, y + height / 2,
        f"{amount}L",
        ha="center", va="center",
        fontsize=14, fontweight="bold",
        color=vol_color,
        fontfamily="monospace",
        zorder=6,
        path_effects=[pe.withStroke(linewidth=3, foreground=EMPTY_COLOR)]
    )

    # Jug label below
    ax.text(
        x + width / 2, y - 0.09,
        label,
        ha="center", va="top",
        fontsize=9, color=ACCENT_COLOR,
        fontweight="bold", fontfamily="monospace",
        zorder=5
    )

# -------------------------------------------------
#  HELPER: draw one step panel
# -------------------------------------------------
def draw_step(ax, step_idx, jug3, jug5, description, accent):
    ax.set_facecolor(PANEL_COLOR)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_aspect("auto")
    ax.axis("off")

    is_final = (step_idx == len(steps) - 1)

    # Panel border
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_edgecolor(SUCCESS_COLOR if is_final else accent)
        spine.set_linewidth(2.5 if is_final else 1.5)

    # Step badge
    badge_color = SUCCESS_COLOR if is_final else accent
    badge = FancyBboxPatch(
        (0.03, 0.88), 0.94, 0.10,
        boxstyle="round,pad=0.01",
        facecolor=badge_color, alpha=0.25,
        edgecolor=badge_color, linewidth=1,
        transform=ax.transAxes, zorder=3
    )
    ax.add_patch(badge)

    step_label = "** SOLVED! **" if is_final else f"Step {step_idx}"
    ax.text(
        0.5, 0.935, step_label,
        ha="center", va="center",
        fontsize=10, fontweight="bold",
        color=SUCCESS_COLOR if is_final else TEXT_COLOR,
        fontfamily="monospace",
        transform=ax.transAxes, zorder=4
    )

    # Description
    ax.text(
        0.5, 0.80, description,
        ha="center", va="top",
        fontsize=8.2, color="#8b949e",
        fontfamily="monospace",
        transform=ax.transAxes,
        multialignment="center",
        zorder=4
    )

    # Water colour
    w_color = SUCCESS_COLOR if is_final else WATER_COLORS[step_idx % len(WATER_COLORS)]

    # Jug dimensions
    jug_h  = 0.38
    jug3_w = 0.18
    jug5_w = 0.22
    jug_y  = 0.17
    x3 = 0.28 - jug3_w / 2
    x5 = 0.62 - jug5_w / 2

    draw_jug(ax, x3, jug_y, jug3_w, jug_h,
             JUG_3_CAP, jug3, "3L Jug", w_color, is_goal=False)
    draw_jug(ax, x5, jug_y, jug5_w, jug_h,
             JUG_5_CAP, jug5, "5L Jug", w_color,
             is_goal=(is_final and jug5 == 4))

    # State tuple
    ax.text(
        0.5, 0.08, f"({jug3}L, {jug5}L)",
        ha="center", va="center",
        fontsize=9, color=accent,
        fontfamily="monospace", fontweight="bold",
        transform=ax.transAxes, zorder=4
    )

# -------------------------------------------------
#  FIGURE & GRID SETUP
# -------------------------------------------------
COLS, ROWS = 4, 2
fig = plt.figure(figsize=(22, 12), facecolor=BG_COLOR)
fig.patch.set_facecolor(BG_COLOR)

fig.text(
    0.5, 0.97,
    "Water Jug Problem  --  Measuring Exactly 4 Litres",
    ha="center", va="top",
    fontsize=22, fontweight="bold",
    color=TEXT_COLOR, fontfamily="monospace",
    path_effects=[pe.withStroke(linewidth=4, foreground=BG_COLOR)]
)
fig.text(
    0.5, 0.925,
    "3-Litre Jug  .  5-Litre Jug  ->  Goal: 4L in the 5L jug",
    ha="center", va="top",
    fontsize=13, color="#8b949e", fontfamily="monospace"
)

grid = fig.add_gridspec(
    ROWS, COLS,
    left=0.03, right=0.97,
    top=0.88, bottom=0.04,
    hspace=0.38, wspace=0.22
)

positions = [(r, c) for r in range(ROWS) for c in range(COLS)]

for i, (jug3, jug5, desc) in enumerate(steps):
    row, col = positions[i]
    ax = fig.add_subplot(grid[row, col])
    draw_step(ax, i, jug3, jug5, desc, STEP_COLORS[i])

# -------------------------------------------------
#  SUMMARY PANEL (8th slot)
# -------------------------------------------------
ax_leg = fig.add_subplot(grid[1, 3])
ax_leg.set_facecolor("#0d1117")
ax_leg.axis("off")

for spine in ax_leg.spines.values():
    spine.set_visible(True)
    spine.set_edgecolor("#3fb950")
    spine.set_linewidth(2)

summary_lines = [
    ("HOW IT WORKS",             "#f0883e", 11,  "bold"),
    ("",                          TEXT_COLOR, 7,  "normal"),
    ("1. Fill 5L jug",            TEXT_COLOR, 8.5,"normal"),
    ("2. Pour into 3L jug",       TEXT_COLOR, 8.5,"normal"),
    ("   -> 2L remains in 5L",    "#8b949e",  7.5,"normal"),
    ("3. Empty the 3L jug",       TEXT_COLOR, 8.5,"normal"),
    ("4. Move 2L -> 3L jug",      TEXT_COLOR, 8.5,"normal"),
    ("5. Refill the 5L jug",      TEXT_COLOR, 8.5,"normal"),
    ("6. Pour into 3L jug",       TEXT_COLOR, 8.5,"normal"),
    ("   -> 3L fills, 4L left!",  "#3fb950",  8.5,"bold"),
    ("",                          TEXT_COLOR, 7,  "normal"),
    ("Result: 4L in 5L jug",      "#3fb950",  9,  "bold"),
    ("   in just 6 steps!",       "#3fb950",  8.5,"normal"),
]

y_pos = 0.97
for line, color, size, weight in summary_lines:
    ax_leg.text(
        0.08, y_pos, line,
        ha="left", va="top",
        fontsize=size, color=color,
        fontweight=weight, fontfamily="monospace",
        transform=ax_leg.transAxes
    )
    y_pos -= 0.075

# Footer
fig.text(
    0.5, 0.005,
    "State notation: (3L jug, 5L jug)  .  Each panel = one fill or pour action",
    ha="center", va="bottom",
    fontsize=9, color="#484f58", fontfamily="monospace"
)

plt.savefig(
    "water_jug_solution.png",
    dpi=180, bbox_inches="tight",
    facecolor=BG_COLOR, edgecolor="none"
)
plt.show()
print("Saved as water_jug_solution.png")
