# Generated by: qwen3-coder:30b (Ollama)
# Date: 2026-03-01 14:41:03
# AutoCoder System - Automated Code Generation

import tkinter as tk
from tkinter import ttk
import numpy as np
import sounddevice as sd
import threading
import time
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.pyplot as plt
from matplotlib.figure import Figure


class WaveformGenerator:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("Waveform Generator")
        self.root.geometry("800x600")
        self.root.configure(bg='#2c3e50')

        # Audio parameters
        self.sample_rate = 44100
        self.frequency = 440.0
        self.wave_type = "sine"
        self.is_playing = False
        self.audio_thread = None
        self.display_thread = None

        # Create GUI
        self.create_widgets()

        # Initialize matplotlib figure
        self.create_plot()

    def create_widgets(self):
        # Main frame
        main_frame = tk.Frame(self.root, bg='#2c3e50')
        main_frame.pack(fill=tk.BOTH, expand=True, padx=20, pady=20)

        # Title
        title_label = tk.Label(main_frame, text="Waveform Generator",
                               font=("Arial", 24, "bold"),
                               bg='#2c3e50', fg='white')
        title_label.pack(pady=10)

        # Frequency display
        self.freq_var = tk.StringVar()
        self.freq_var.set("440 Hz")
        freq_label = tk.Label(main_frame, textvariable=self.freq_var,
                              font=("Arial", 32, "bold"),
                              bg='#2c3e50', fg='#3498db')
        freq_label.pack(pady=10)

        # Wave type selector
        type_frame = tk.Frame(main_frame, bg='#2c3e50')
        type_frame.pack(pady=10)

        tk.Label(type_frame, text="Wave Type:", font=("Arial", 12),
                 bg='#2c3e50', fg='white').pack(side=tk.LEFT)

        self.wave_type_var = tk.StringVar(value="sine")
        wave_combo = ttk.Combobox(type_frame, textvariable=self.wave_type_var,
                                  values=["sine", "square", "triangle"],
                                  state="readonly", width=10)
        wave_combo.pack(side=tk.LEFT, padx=10)
        wave_combo.bind('<<ComboboxSelected>>', self.on_wave_type_change)

        # Frequency slider
        slider_frame = tk.Frame(main_frame, bg='#2c3e50')
        slider_frame.pack(pady=20, fill=tk.X)

        tk.Label(slider_frame, text="Frequency (Hz):", font=("Arial", 12),
                 bg='#2c3e50', fg='white').pack()

        self.freq_slider = ttk.Scale(slider_frame, from_=20, to=2000,
                                     orient=tk.HORIZONTAL, length=400,
                                     command=self.on_frequency_change)
        self.freq_slider.set(440)
        self.freq_slider.pack(pady=10)

        # Canvas for waveform display
        self.canvas_frame = tk.Frame(main_frame, bg='black')
        self.canvas_frame.pack(fill=tk.BOTH, expand=True, pady=20)

        # Start/stop button
        button_frame = tk.Frame(main_frame, bg='#2c3e50')
        button_frame.pack(pady=10)

        self.play_button = tk.Button(button_frame, text="Play",
                                     command=self.toggle_play,
                                     font=("Arial", 12, "bold"),
                                     bg='#3498db', fg='white',
                                     width=10)
        self.play_button.pack(side=tk.LEFT, padx=10)

    def create_plot(self):
        # Create matplotlib figure
        self.fig = Figure(figsize=(8, 3), dpi=100)
        self.fig.patch.set_facecolor('#2c3e50')
        self.ax = self.fig.add_subplot(111)
        self.ax.set_facecolor('#2c3e50')
        self.ax.set_title('Waveform Display', color='white')
        self.ax.set_xlabel('Time', color='white')
        self.ax.set_ylabel('Amplitude', color='white')
        self.ax.tick_params(colors='white')
        self.ax.grid(True, alpha=0.3)

        # Create canvas
        self.canvas = FigureCanvasTkAgg(self.fig, self.canvas_frame)
        self.canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True)

        # Initialize empty plot
        self.line, = self.ax.plot([], [], 'b-', linewidth=2)
        self.ax.set_xlim(0, 0.05)  # 50ms window
        self.ax.set_ylim(-1.1, 1.1)

    def generate_waveform(self, frequency, wave_type, duration=0.05):
        """Generate waveform data for display"""
        t = np.linspace(0, duration, int(self.sample_rate * duration), endpoint=False)

        if wave_type == "sine":
            wave = np.sin(2 * np.pi * frequency * t)
        elif wave_type == "square":
            wave = np.sign(np.sin(2 * np.pi * frequency * t))
        elif wave_type == "triangle":
            wave = 2 * np.abs(2 * (t * frequency - np.floor(0.5 + t * frequency))) - 1
        else:
            wave = np.sin(2 * np.pi * frequency * t)

        return t, wave

    def update_display(self):
        """Update waveform display in real-time"""
        while self.is_playing:
            try:
                t, wave = self.generate_waveform(self.frequency, self.wave_type)
                self.line.set_data(t, wave)
                self.canvas.draw()
                time.sleep(0.02)  # Update every 20ms
            except Exception as e:
                print(f"Display update error: {e}")
                break

    def generate_audio(self, duration=0.1):
        """Generate audio samples for playback"""
        t = np.linspace(0, duration, int(self.sample_rate * duration), endpoint=False)

        if self.wave_type == "sine":
            wave = np.sin(2 * np.pi * self.frequency * t)
        elif self.wave_type == "square":
            wave = np.sign(np.sin(2 * np.pi * self.frequency * t))
        elif self.wave_type == "triangle":
            wave = 2 * np.abs(2 * (t * self.frequency - np.floor(0.5 + t * self.frequency))) - 1
        else:
            wave = np.sin(2 * np.pi * self.frequency * t)

        return wave

    def audio_callback(self, outdata, frames, time, status):
        """Callback function for audio playback"""
        if self.is_playing:
            audio_data = self.generate_audio(duration=frames / self.sample_rate)
            outdata[:, 0] = audio_data  # Left channel
            outdata[:, 1] = audio_data  # Right channel
        else:
            outdata.fill(0)

    def toggle_play(self):
        """Toggle play/pause"""
        self.is_playing = not self.is_playing
        self.play_button.config(text="Stop" if self.is_playing else "Play")

        if self.is_playing:
            # Start audio playback
            self.stream = sd.OutputStream(callback=self.audio_callback,
                                          channels=2,
                                          samplerate=self.sample_rate)
            self.stream.start()

            # Start display update thread
            self.display_thread = threading.Thread(target=self.update_display)
            self.display_thread.daemon = True
            self.display_thread.start()

            print("Audio playback started")
        else:
            # Stop audio playback
            if hasattr(self, 'stream'):
                self.stream.stop()
                self.stream.close()
            print("Audio playback stopped")

    def on_frequency_change(self, value):
        """Handle frequency slider change"""
        self.frequency = float(value)
        self.freq_var.set(f"{int(self.frequency)} Hz")

    def on_wave_type_change(self, event):
        """Handle wave type change"""
        self.wave_type = self.wave_type_var.get()
        print(f"Wave type changed to: {self.wave_type}")

    def run(self):
        """Run the application"""
        self.root.protocol("WM_DELETE_WINDOW", self.on_closing)
        self.root.mainloop()

    def on_closing(self):
        """Handle application closing"""
        self.is_playing = False
        if hasattr(self, 'stream'):
            self.stream.stop()
            self.stream.close()
        self.root.destroy()


# Create and run the application
if __name__ == "__main__":
    app = WaveformGenerator()
    print("Starting waveform generator application...")
    app.run()