# Generated by: qwen/qwen3-coder (Ollama)
# Date: 2026-03-04 07:26:18
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime, timedelta
import math

print("Generating world clocks with improved layout and colors...")


# Function to draw an analog clock face with better aesthetics
def draw_clock_face(ax, time_hour, title):
    ax.set_xlim(-1.2, 1.2)
    ax.set_ylim(-1.2, 1.2)
    ax.set_aspect('equal')
    ax.axis('off')

    # Draw circle with better color
    circle = plt.Circle((0, 0), 1, color='#2E86AB', fill=False, linewidth=2)
    ax.add_patch(circle)

    # Draw hour marks
    for i in range(12):
        angle = math.radians(i * 30)
        x_outer = 0.9 * math.sin(angle)
        y_outer = 0.9 * math.cos(angle)
        x_inner = 0.8 * math.sin(angle)
        y_inner = 0.8 * math.cos(angle)
        ax.plot([x_inner, x_outer], [y_inner, y_outer], color='#2E86AB', linewidth=2)

        # Hour numbers with better positioning and color
        x_num = 0.65 * math.sin(angle)
        y_num = 0.65 * math.cos(angle)
        ax.text(x_num, y_num, str(i if i != 0 else 12), fontsize=12,
                ha='center', va='center', color='#1a5276', fontweight='bold')

    # Calculate hand angles
    hour_angle = math.radians((time_hour % 12) * 30 + (time_hour % 1) * 30)
    minute_angle = math.radians((time_hour % 1) * 60 * 6)

    # Hour hand
    hour_x = 0.4 * math.sin(hour_angle)
    hour_y = 0.4 * math.cos(hour_angle)
    ax.plot([0, hour_x], [0, hour_y], color='#A93226', linewidth=4, solid_capstyle='round')

    # Minute hand
    minute_x = 0.6 * math.sin(minute_angle)
    minute_y = 0.6 * math.cos(minute_angle)
    ax.plot([0, minute_x], [0, minute_y], color='#1E8449', linewidth=2, solid_capstyle='round')

    # Center dot
    ax.plot(0, 0, 'o', markersize=6, color='#7B7D7D')

    # Title (city name) with better styling
    ax.set_title(title, fontsize=14, pad=20, fontweight='bold', color='#1a5276')


# Timezone offsets from UTC (simplified - does not account for DST)
cities = {
    "Auckland": 12,
    "Sydney": 10,
    "London": 0,
    "LA": -8,
    "New York": -5,
    "Singapore": 8
}

# Get current UTC time
utc_now = datetime.utcnow()

# Create figure with subplots and better spacing
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
fig.suptitle("World Clocks", fontsize=20, y=0.95, fontweight='bold', color='#1a5276')
axes = axes.flatten()

# Plot each clock
for idx, (city, offset) in enumerate(cities.items()):
    # Calculate local time
    local_time = utc_now.hour + utc_now.minute / 60 + offset
    if local_time < 0:
        local_time += 24
    elif local_time >= 24:
        local_time -= 24

    # Draw clock
    draw_clock_face(axes[idx], local_time, city)

    # Add date and day of week with better positioning and styling
    local_date = utc_now + timedelta(hours=offset)
    weekday = local_date.strftime("%A")
    date_str = local_date.strftime("%Y-%m-%d")

    # Better text positioning to avoid overlap
    axes[idx].text(0, -0.9, f"{weekday}\n{date_str}",
                   fontsize=9, ha='center', va='top',
                   bbox=dict(boxstyle="round,pad=0.3", facecolor='#EBF5FB', alpha=0.8),
                   color='#2C3E50')

# Improve layout to prevent overlapping
plt.tight_layout(rect=[0, 0, 1, 0.93], pad=2.0, h_pad=3.0, w_pad=2.0)
print("Displaying world clocks matrix with improved layout...")
plt.show()