# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-09 07:47:01
# AutoCoder System - Automated Code Generation

import subprocess
import sys
import os


def install_package(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package],
                          stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# Install required packages
print("Installing required packages...")
try:
    import yt_dlp
except ImportError:
    print("Installing yt-dlp...")
    install_package("yt-dlp")
    import yt_dlp

# A short, publicly available YouTube video about AI
# Using a well-known short AI explainer video
VIDEO_URL = "https://www.youtube.com/watch?v=mJeNghZXtMo"  # Short AI video

# Output filename
OUTPUT_FILE = "ai_video.mp4"


def download_video(url, output_path):
    """Download a YouTube video using yt-dlp."""
    print(f"\nDownloading video from: {url}")
    print("Please wait...")

    ydl_opts = {
        'format': 'best[height<=480]/best',  # Download at most 480p for speed
        'outtmpl': output_path,
        'quiet': False,
        'no_warnings': False,
        'progress_hooks': [progress_hook],
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = info.get('title', 'Unknown Title')
            duration = info.get('duration', 0)
            print(f"\nVideo Title: {title}")
            print(f"Duration: {duration} seconds")
            return True
    except Exception as e:
        print(f"Error downloading video: {e}")
        return False


def progress_hook(d):
    """Show download progress."""
    if d['status'] == 'downloading':
        percent = d.get('_percent_str', 'N/A')
        speed = d.get('_speed_str', 'N/A')
        print(f"\rDownloading: {percent} at {speed}    ", end='', flush=True)
    elif d['status'] == 'finished':
        print(f"\nDownload complete! File saved as: {d['filename']}")


def play_video(filepath):
    """Play the downloaded video using the system's default player."""
    print(f"\nAttempting to play: {filepath}")

    if not os.path.exists(filepath):
        # Try to find the file with different extensions
        for ext in ['.mp4', '.mkv', '.webm', '.avi']:
            alt_path = os.path.splitext(filepath)[0] + ext
            if os.path.exists(alt_path):
                filepath = alt_path
                break

    if not os.path.exists(filepath):
        print(f"Video file not found: {filepath}")
        print("Files in current directory:")
        for f in os.listdir('.'):
            if f.startswith('ai_video'):
                print(f"  Found: {f}")
                filepath = f
                break

    print(f"Playing: {filepath}")

    # Try different players based on OS
    if sys.platform == 'win32':
        # Windows - use default media player
        os.startfile(os.path.abspath(filepath))
        print("Video opened with Windows default media player.")

    elif sys.platform == 'darwin':
        # macOS - use open command
        subprocess.Popen(['open', filepath])
        print("Video opened with macOS default media player.")

    else:
        # Linux - try multiple players
        players = ['vlc', 'mpv', 'mplayer', 'totem', 'xdg-open', 'ffplay']
        played = False
        for player in players:
            try:
                result = subprocess.run(['which', player],
                                        capture_output=True, text=True)
                if result.returncode == 0:
                    print(f"Playing with {player}...")
                    subprocess.Popen([player, filepath])
                    played = True
                    break
            except Exception:
                continue

        if not played:
            print("No media player found. Trying xdg-open...")
            try:
                subprocess.Popen(['xdg-open', filepath])
            except Exception as e:
                print(f"Could not open video: {e}")
                print(f"Please manually open the file: {os.path.abspath(filepath)}")


def main():
    print("=" * 60)
    print("YouTube AI Video Downloader and Player")
    print("=" * 60)
    print(f"Target URL: {VIDEO_URL}")
    print(f"Output file: {OUTPUT_FILE}")

    # Download the video
    success = download_video(VIDEO_URL, OUTPUT_FILE)

    if success:
        print("\nDownload successful!")

        # Check file size
        if os.path.exists(OUTPUT_FILE):
            size = os.path.getsize(OUTPUT_FILE)
            print(f"File size: {size / (1024 * 1024):.2f} MB")

        # Play the video
        play_video(OUTPUT_FILE)
        print("\nVideo playback initiated!")
        print("Close the media player when done watching.")
    else:
        print("\nDownload failed. Trying alternative video...")
        # Try an alternative short AI video
        alt_url = "https://www.youtube.com/watch?v=ad79nYk2keg"
        success2 = download_video(alt_url, OUTPUT_FILE)
        if success2:
            play_video(OUTPUT_FILE)
        else:
            print("Could not download video. Please check your internet connection.")
            print("You can manually visit: https://www.youtube.com/watch?v=mJeNghZXtMo")


if __name__ == "__main__":
    main()