# Generated: 2026-04-07 21:17:16
# ============================================================

# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-04-07 21:17:16
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.widgets import Slider
from scipy.linalg import solve_continuous_are

# -- System matrices ----------------------------------------------------------
A = np.array([[0., 1.],
              [0., 0.]])
B = np.array([[0.],
              [1.]])
C = np.array([[1., 0.]])

# -- LQR design ---------------------------------------------------------------
Q_lqr = np.diag([100., 1.])
R_lqr = np.array([[1.]])

P_lqr = solve_continuous_are(A, B, Q_lqr, R_lqr)
K = np.linalg.inv(R_lqr) @ B.T @ P_lqr          # shape (1,2)

# -- Kalman filter design -----------------------------------------------------
Qn = np.diag([0.01, 0.1])                         # process noise covariance
Rn = np.array([[1.]])                              # measurement noise covariance

P_kal = solve_continuous_are(A.T, C.T, Qn, Rn)
L = P_kal @ C.T @ np.linalg.inv(Rn)              # shape (2,1)

# -- Simulation parameters ----------------------------------------------------
dt = 0.01
t  = np.arange(0., 10. + dt, dt)
N  = len(t)

np.random.seed(42)
proc_noise = np.random.randn(N, 2) * np.sqrt([0.01, 0.1])
meas_noise = np.random.randn(N, 1) * np.sqrt(1.0)

# -- Run simulation -----------------------------------------------------------
def run_sim(r_pos):
    """Simulate LQG for a given position setpoint r_pos (velocity setpoint = 0)."""
    r = np.array([r_pos, 0.])          # reference state

    x     = np.zeros(2)               # true state  [pos, vel]
    x_hat = np.zeros(2)               # estimated state

    xs     = np.zeros((N, 2))
    x_hats = np.zeros((N, 2))
    us     = np.zeros(N)

    for i in range(N):
        # setpoint steps in at t = 1 s
        ref = r if t[i] >= 1.0 else np.zeros(2)

        # control law on estimated state
        e     = x_hat - ref
        u     = float(-K @ e)
        us[i] = u

        # true state (Euler integration + process noise)
        x_dot = A @ x + B.flatten() * u + proc_noise[i]
        x     = x + x_dot * dt

        # noisy measurement
        y = C @ x + meas_noise[i]

        # Kalman observer update
        x_hat_dot = (A @ x_hat
                     + B.flatten() * u
                     + L.flatten() * (y.flatten() - (C @ x_hat).flatten()))
        x_hat = x_hat + x_hat_dot * dt

        xs[i]     = x
        x_hats[i] = x_hat

    return xs, x_hats, us

# -- Initial plot -------------------------------------------------------------
init_r = 5.0
xs, x_hats, us = run_sim(init_r)

print("Simulation complete. Setting up plot...")

fig = plt.figure(figsize=(12, 9))
plt.suptitle("LQG Control: Second-Order Position-Velocity System", y=0.98)

gs  = gridspec.GridSpec(4, 1, figure=fig, hspace=0.65)
ax1 = fig.add_subplot(gs[0])
ax2 = fig.add_subplot(gs[1])
ax3 = fig.add_subplot(gs[2])
ax4 = fig.add_subplot(gs[3])

# Setpoint line values
sp_line_vals = np.where(t >= 1.0, init_r, 0.0)

# -- Position subplot ---------------------------------------------------------
l_pos_true, = ax1.plot(t, xs[:, 0],     'b',   lw=1.5, label='True position')
l_pos_est,  = ax1.plot(t, x_hats[:, 0], 'r--', lw=1.5, label='Kalman estimate')
l_pos_sp,   = ax1.plot(t, sp_line_vals,  'k:',  lw=1.2, label='Setpoint')
ax1.set_ylabel('Position (m)')
ax1.set_title('Position')
ax1.legend(loc='upper left', fontsize=8)
ax1.grid(True, alpha=0.3)

# -- Velocity subplot ---------------------------------------------------------
l_vel_true, = ax2.plot(t, xs[:, 1],     'b',   lw=1.5, label='True velocity')
l_vel_est,  = ax2.plot(t, x_hats[:, 1], 'r--', lw=1.5, label='Kalman estimate')
ax2.axhline(0, color='k', linestyle=':', lw=1.2, label='Setpoint (0 m/s)')
ax2.set_ylabel('Velocity (m/s)')
ax2.set_title('Velocity')
ax2.legend(loc='upper right', fontsize=8)
ax2.grid(True, alpha=0.3)

# -- Control input subplot ----------------------------------------------------
l_ctrl, = ax3.plot(t, us, 'g', lw=1.5, label='Control input u')
ax3.set_ylabel('Control (m/s^2)')
ax3.set_title('Control Input')
ax3.legend(loc='upper right', fontsize=8)
ax3.grid(True, alpha=0.3)

# -- Estimation error subplot -------------------------------------------------
l_err_pos, = ax4.plot(t, xs[:, 0] - x_hats[:, 0], 'm',   lw=1.2, label='Position error')
l_err_vel, = ax4.plot(t, xs[:, 1] - x_hats[:, 1], 'c--', lw=1.2, label='Velocity error')
ax4.axhline(0, color='k', lw=0.8)
ax4.set_xlabel('Time (s)')
ax4.set_ylabel('Error')
ax4.set_title('Kalman Estimation Error (True - Estimated)')
ax4.legend(loc='upper right', fontsize=8)
ax4.grid(True, alpha=0.3)

plt.tight_layout()

# -- Slider -------------------------------------------------------------------
fig.subplots_adjust(bottom=0.10)
ax_slider = fig.add_axes([0.15, 0.02, 0.70, 0.025])
slider    = Slider(ax_slider, 'Position Setpoint (m)', 0.0, 10.0,
                   valinit=init_r, valstep=0.1, color='steelblue')

def update(val):
    r_new  = slider.val
    xs_n, x_hats_n, us_n = run_sim(r_new)
    sp_new = np.where(t >= 1.0, r_new, 0.0)

    l_pos_true.set_ydata(xs_n[:, 0])
    l_pos_est.set_ydata(x_hats_n[:, 0])
    l_pos_sp.set_ydata(sp_new)

    l_vel_true.set_ydata(xs_n[:, 1])
    l_vel_est.set_ydata(x_hats_n[:, 1])

    l_ctrl.set_ydata(us_n)

    l_err_pos.set_ydata(xs_n[:, 0] - x_hats_n[:, 0])
    l_err_vel.set_ydata(xs_n[:, 1] - x_hats_n[:, 1])

    for ax in [ax1, ax2, ax3, ax4]:
        ax.relim()
        ax.autoscale_view()

    fig.canvas.draw_idle()
    print(f"Setpoint updated to {r_new:.1f} m")

slider.on_changed(update)

print("Plot ready. Use the slider to change the position setpoint.")
print(f"LQR gain K = {K}")
print(f"Kalman gain L = {L.flatten()}")

plt.show()